// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package conversation

import (
	"fmt"
	"github.com/kiosk404/airi-go/backend/api/model/base"
	"github.com/kiosk404/airi-go/backend/api/model/conversation/common"
)

type ClearConversationHistoryRequest struct {
	ConversationID int64         `thrift:"conversation_id,1,required" json:"conversation_id,string"`
	Scene          *common.Scene `thrift:"scene,2,optional,Scene" json:"scene,omitempty"`
	BotID          *int64        `thrift:"bot_id,3,optional" json:"bot_id,omitempty"`
}

func NewClearConversationHistoryRequest() *ClearConversationHistoryRequest {
	return &ClearConversationHistoryRequest{}
}

func (p *ClearConversationHistoryRequest) InitDefault() {
}

func (p *ClearConversationHistoryRequest) GetConversationID() (v int64) {
	return p.ConversationID
}

var ClearConversationHistoryRequest_Scene_DEFAULT common.Scene

func (p *ClearConversationHistoryRequest) GetScene() (v common.Scene) {
	if !p.IsSetScene() {
		return ClearConversationHistoryRequest_Scene_DEFAULT
	}
	return *p.Scene
}

var ClearConversationHistoryRequest_BotID_DEFAULT int64

func (p *ClearConversationHistoryRequest) GetBotID() (v int64) {
	if !p.IsSetBotID() {
		return ClearConversationHistoryRequest_BotID_DEFAULT
	}
	return *p.BotID
}
func (p *ClearConversationHistoryRequest) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *ClearConversationHistoryRequest) SetScene(val *common.Scene) {
	p.Scene = val
}
func (p *ClearConversationHistoryRequest) SetBotID(val *int64) {
	p.BotID = val
}

func (p *ClearConversationHistoryRequest) IsSetScene() bool {
	return p.Scene != nil
}

func (p *ClearConversationHistoryRequest) IsSetBotID() bool {
	return p.BotID != nil
}

func (p *ClearConversationHistoryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClearConversationHistoryRequest(%+v)", *p)
}

type ClearConversationHistoryResponse struct {
	Code         int64  `thrift:"code,1" json:"code"`
	Msg          string `thrift:"msg,2" json:"msg"`
	NewSectionID int64  `thrift:"new_section_id,3,required" json:"new_section_id"`
}

func NewClearConversationHistoryResponse() *ClearConversationHistoryResponse {
	return &ClearConversationHistoryResponse{}
}

func (p *ClearConversationHistoryResponse) InitDefault() {
}

func (p *ClearConversationHistoryResponse) GetCode() (v int64) {
	return p.Code
}

func (p *ClearConversationHistoryResponse) GetMsg() (v string) {
	return p.Msg
}

func (p *ClearConversationHistoryResponse) GetNewSectionID() (v int64) {
	return p.NewSectionID
}
func (p *ClearConversationHistoryResponse) SetCode(val int64) {
	p.Code = val
}
func (p *ClearConversationHistoryResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *ClearConversationHistoryResponse) SetNewSectionID(val int64) {
	p.NewSectionID = val
}

func (p *ClearConversationHistoryResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClearConversationHistoryResponse(%+v)", *p)
}

type ClearConversationCtxRequest struct {
	ConversationID           int64         `thrift:"conversation_id,1,required" json:"conversation_id,string"`
	Scene                    *common.Scene `thrift:"scene,2,optional,Scene" json:"scene,omitempty"`
	InsertHistoryMessageList []string      `thrift:"insert_history_message_list,3,optional,list<string>" json:"insert_history_message_list,omitempty"`
}

func NewClearConversationCtxRequest() *ClearConversationCtxRequest {
	return &ClearConversationCtxRequest{}
}

func (p *ClearConversationCtxRequest) InitDefault() {
}

func (p *ClearConversationCtxRequest) GetConversationID() (v int64) {
	return p.ConversationID
}

var ClearConversationCtxRequest_Scene_DEFAULT common.Scene

func (p *ClearConversationCtxRequest) GetScene() (v common.Scene) {
	if !p.IsSetScene() {
		return ClearConversationCtxRequest_Scene_DEFAULT
	}
	return *p.Scene
}

var ClearConversationCtxRequest_InsertHistoryMessageList_DEFAULT []string

func (p *ClearConversationCtxRequest) GetInsertHistoryMessageList() (v []string) {
	if !p.IsSetInsertHistoryMessageList() {
		return ClearConversationCtxRequest_InsertHistoryMessageList_DEFAULT
	}
	return p.InsertHistoryMessageList
}
func (p *ClearConversationCtxRequest) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *ClearConversationCtxRequest) SetScene(val *common.Scene) {
	p.Scene = val
}
func (p *ClearConversationCtxRequest) SetInsertHistoryMessageList(val []string) {
	p.InsertHistoryMessageList = val
}

func (p *ClearConversationCtxRequest) IsSetScene() bool {
	return p.Scene != nil
}

func (p *ClearConversationCtxRequest) IsSetInsertHistoryMessageList() bool {
	return p.InsertHistoryMessageList != nil
}

func (p *ClearConversationCtxRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClearConversationCtxRequest(%+v)", *p)
}

type ClearConversationCtxResponse struct {
	Code         int64  `thrift:"code,1" json:"code"`
	Msg          string `thrift:"msg,2" json:"msg"`
	NewSectionID int64  `thrift:"new_section_id,3,required" json:"new_section_id"`
}

func NewClearConversationCtxResponse() *ClearConversationCtxResponse {
	return &ClearConversationCtxResponse{}
}

func (p *ClearConversationCtxResponse) InitDefault() {
}

func (p *ClearConversationCtxResponse) GetCode() (v int64) {
	return p.Code
}

func (p *ClearConversationCtxResponse) GetMsg() (v string) {
	return p.Msg
}

func (p *ClearConversationCtxResponse) GetNewSectionID() (v int64) {
	return p.NewSectionID
}
func (p *ClearConversationCtxResponse) SetCode(val int64) {
	p.Code = val
}
func (p *ClearConversationCtxResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *ClearConversationCtxResponse) SetNewSectionID(val int64) {
	p.NewSectionID = val
}

func (p *ClearConversationCtxResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClearConversationCtxResponse(%+v)", *p)
}

type ConversationData struct {
	Id            int64             `thrift:"Id,1" json:"Id"`
	CreatedAt     int64             `thrift:"CreatedAt,2" json:"CreatedAt"`
	MetaData      map[string]string `thrift:"MetaData,3" json:"MetaData"`
	CreatorID     *int64            `thrift:"CreatorID,4,optional" json:"CreatorID,omitempty"`
	LastSectionID *int64            `thrift:"LastSectionID,5,optional" json:"LastSectionID,omitempty"`
	AccountID     *int64            `thrift:"AccountID,6,optional" json:"AccountID,omitempty"`
	Name          *string           `thrift:"Name,7,optional" json:"Name,omitempty"`
}

func NewConversationData() *ConversationData {
	return &ConversationData{}
}

func (p *ConversationData) InitDefault() {
}

func (p *ConversationData) GetId() (v int64) {
	return p.Id
}

func (p *ConversationData) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *ConversationData) GetMetaData() (v map[string]string) {
	return p.MetaData
}

var ConversationData_CreatorID_DEFAULT int64

func (p *ConversationData) GetCreatorID() (v int64) {
	if !p.IsSetCreatorID() {
		return ConversationData_CreatorID_DEFAULT
	}
	return *p.CreatorID
}

var ConversationData_LastSectionID_DEFAULT int64

func (p *ConversationData) GetLastSectionID() (v int64) {
	if !p.IsSetLastSectionID() {
		return ConversationData_LastSectionID_DEFAULT
	}
	return *p.LastSectionID
}

var ConversationData_AccountID_DEFAULT int64

func (p *ConversationData) GetAccountID() (v int64) {
	if !p.IsSetAccountID() {
		return ConversationData_AccountID_DEFAULT
	}
	return *p.AccountID
}

var ConversationData_Name_DEFAULT string

func (p *ConversationData) GetName() (v string) {
	if !p.IsSetName() {
		return ConversationData_Name_DEFAULT
	}
	return *p.Name
}
func (p *ConversationData) SetId(val int64) {
	p.Id = val
}
func (p *ConversationData) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *ConversationData) SetMetaData(val map[string]string) {
	p.MetaData = val
}
func (p *ConversationData) SetCreatorID(val *int64) {
	p.CreatorID = val
}
func (p *ConversationData) SetLastSectionID(val *int64) {
	p.LastSectionID = val
}
func (p *ConversationData) SetAccountID(val *int64) {
	p.AccountID = val
}
func (p *ConversationData) SetName(val *string) {
	p.Name = val
}

func (p *ConversationData) IsSetCreatorID() bool {
	return p.CreatorID != nil
}

func (p *ConversationData) IsSetLastSectionID() bool {
	return p.LastSectionID != nil
}

func (p *ConversationData) IsSetAccountID() bool {
	return p.AccountID != nil
}

func (p *ConversationData) IsSetName() bool {
	return p.Name != nil
}

func (p *ConversationData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConversationData(%+v)", *p)
}

type CreateConversationRequest struct {
	MetaData map[string]string `thrift:"MetaData,1,optional" json:"MetaData,omitempty"`
	BotId    *int64            `thrift:"BotId,3,optional" json:"BotId,omitempty"`
}

func NewCreateConversationRequest() *CreateConversationRequest {
	return &CreateConversationRequest{}
}

func (p *CreateConversationRequest) InitDefault() {
}

var CreateConversationRequest_MetaData_DEFAULT map[string]string

func (p *CreateConversationRequest) GetMetaData() (v map[string]string) {
	if !p.IsSetMetaData() {
		return CreateConversationRequest_MetaData_DEFAULT
	}
	return p.MetaData
}

var CreateConversationRequest_BotId_DEFAULT int64

func (p *CreateConversationRequest) GetBotId() (v int64) {
	if !p.IsSetBotId() {
		return CreateConversationRequest_BotId_DEFAULT
	}
	return *p.BotId
}
func (p *CreateConversationRequest) SetMetaData(val map[string]string) {
	p.MetaData = val
}
func (p *CreateConversationRequest) SetBotId(val *int64) {
	p.BotId = val
}

func (p *CreateConversationRequest) IsSetMetaData() bool {
	return p.MetaData != nil
}

func (p *CreateConversationRequest) IsSetBotId() bool {
	return p.BotId != nil
}

func (p *CreateConversationRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateConversationRequest(%+v)", *p)
}

type CreateConversationResponse struct {
	Code             int64             `thrift:"code,1" json:"code"`
	Msg              string            `thrift:"msg,2" json:"msg"`
	ConversationData *ConversationData `thrift:"ConversationData,3,optional" json:"ConversationData,omitempty"`
}

func NewCreateConversationResponse() *CreateConversationResponse {
	return &CreateConversationResponse{}
}

func (p *CreateConversationResponse) InitDefault() {
}

func (p *CreateConversationResponse) GetCode() (v int64) {
	return p.Code
}

func (p *CreateConversationResponse) GetMsg() (v string) {
	return p.Msg
}

var CreateConversationResponse_ConversationData_DEFAULT *ConversationData

func (p *CreateConversationResponse) GetConversationData() (v *ConversationData) {
	if !p.IsSetConversationData() {
		return CreateConversationResponse_ConversationData_DEFAULT
	}
	return p.ConversationData
}
func (p *CreateConversationResponse) SetCode(val int64) {
	p.Code = val
}
func (p *CreateConversationResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *CreateConversationResponse) SetConversationData(val *ConversationData) {
	p.ConversationData = val
}

func (p *CreateConversationResponse) IsSetConversationData() bool {
	return p.ConversationData != nil
}

func (p *CreateConversationResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateConversationResponse(%+v)", *p)
}

type ClearConversationApiRequest struct {
	ConversationID int64      `thrift:"ConversationID,1,required" json:"ConversationID"`
	Base           *base.Base `thrift:"Base,255" json:"Base"`
}

func NewClearConversationApiRequest() *ClearConversationApiRequest {
	return &ClearConversationApiRequest{}
}

func (p *ClearConversationApiRequest) InitDefault() {
}

func (p *ClearConversationApiRequest) GetConversationID() (v int64) {
	return p.ConversationID
}

var ClearConversationApiRequest_Base_DEFAULT *base.Base

func (p *ClearConversationApiRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ClearConversationApiRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *ClearConversationApiRequest) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *ClearConversationApiRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *ClearConversationApiRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ClearConversationApiRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClearConversationApiRequest(%+v)", *p)
}

type Section struct {
	ID             int64 `thrift:"id,1" json:"id"`
	ConversationID int64 `thrift:"conversation_id,2" json:"conversation_id"`
}

func NewSection() *Section {
	return &Section{}
}

func (p *Section) InitDefault() {
}

func (p *Section) GetID() (v int64) {
	return p.ID
}

func (p *Section) GetConversationID() (v int64) {
	return p.ConversationID
}
func (p *Section) SetID(val int64) {
	p.ID = val
}
func (p *Section) SetConversationID(val int64) {
	p.ConversationID = val
}

func (p *Section) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Section(%+v)", *p)
}

type ClearConversationApiResponse struct {
	Code     int64          `thrift:"code,1" json:"code"`
	Msg      string         `thrift:"msg,2" json:"msg"`
	Data     *Section       `thrift:"data,3" json:"data"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255" json:"BaseResp"`
}

func NewClearConversationApiResponse() *ClearConversationApiResponse {
	return &ClearConversationApiResponse{}
}

func (p *ClearConversationApiResponse) InitDefault() {
}

func (p *ClearConversationApiResponse) GetCode() (v int64) {
	return p.Code
}

func (p *ClearConversationApiResponse) GetMsg() (v string) {
	return p.Msg
}

var ClearConversationApiResponse_Data_DEFAULT *Section

func (p *ClearConversationApiResponse) GetData() (v *Section) {
	if !p.IsSetData() {
		return ClearConversationApiResponse_Data_DEFAULT
	}
	return p.Data
}

var ClearConversationApiResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ClearConversationApiResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ClearConversationApiResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ClearConversationApiResponse) SetCode(val int64) {
	p.Code = val
}
func (p *ClearConversationApiResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *ClearConversationApiResponse) SetData(val *Section) {
	p.Data = val
}
func (p *ClearConversationApiResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ClearConversationApiResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *ClearConversationApiResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ClearConversationApiResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClearConversationApiResponse(%+v)", *p)
}

type ListConversationsApiRequest struct {
	PageNum   int64      `thrift:"page_num,1" json:"page_num"`
	PageSize  int64      `thrift:"page_size,2" json:"page_size"`
	SortOrder string     `thrift:"sort_order,3" json:"sort_order"`
	SortField string     `thrift:"sort_field,4" json:"sort_field"`
	BotID     int64      `thrift:"bot_id,5,required" json:"bot_id"`
	Base      *base.Base `thrift:"Base,255" json:"Base"`
}

func NewListConversationsApiRequest() *ListConversationsApiRequest {
	return &ListConversationsApiRequest{}
}

func (p *ListConversationsApiRequest) InitDefault() {
}

func (p *ListConversationsApiRequest) GetPageNum() (v int64) {
	return p.PageNum
}

func (p *ListConversationsApiRequest) GetPageSize() (v int64) {
	return p.PageSize
}

func (p *ListConversationsApiRequest) GetSortOrder() (v string) {
	return p.SortOrder
}

func (p *ListConversationsApiRequest) GetSortField() (v string) {
	return p.SortField
}

func (p *ListConversationsApiRequest) GetBotID() (v int64) {
	return p.BotID
}

var ListConversationsApiRequest_Base_DEFAULT *base.Base

func (p *ListConversationsApiRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ListConversationsApiRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *ListConversationsApiRequest) SetPageNum(val int64) {
	p.PageNum = val
}
func (p *ListConversationsApiRequest) SetPageSize(val int64) {
	p.PageSize = val
}
func (p *ListConversationsApiRequest) SetSortOrder(val string) {
	p.SortOrder = val
}
func (p *ListConversationsApiRequest) SetSortField(val string) {
	p.SortField = val
}
func (p *ListConversationsApiRequest) SetBotID(val int64) {
	p.BotID = val
}
func (p *ListConversationsApiRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *ListConversationsApiRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListConversationsApiRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationsApiRequest(%+v)", *p)
}

type ListConversationsApiResponse struct {
	Code     int64                 `thrift:"code,1" json:"code"`
	Msg      string                `thrift:"msg,2" json:"msg"`
	Data     *ListConversationData `thrift:"data,3" json:"data"`
	BaseResp *base.BaseResp        `thrift:"BaseResp,255" json:"BaseResp"`
}

func NewListConversationsApiResponse() *ListConversationsApiResponse {
	return &ListConversationsApiResponse{}
}

func (p *ListConversationsApiResponse) InitDefault() {
}

func (p *ListConversationsApiResponse) GetCode() (v int64) {
	return p.Code
}

func (p *ListConversationsApiResponse) GetMsg() (v string) {
	return p.Msg
}

var ListConversationsApiResponse_Data_DEFAULT *ListConversationData

func (p *ListConversationsApiResponse) GetData() (v *ListConversationData) {
	if !p.IsSetData() {
		return ListConversationsApiResponse_Data_DEFAULT
	}
	return p.Data
}

var ListConversationsApiResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ListConversationsApiResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListConversationsApiResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListConversationsApiResponse) SetCode(val int64) {
	p.Code = val
}
func (p *ListConversationsApiResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *ListConversationsApiResponse) SetData(val *ListConversationData) {
	p.Data = val
}
func (p *ListConversationsApiResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListConversationsApiResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *ListConversationsApiResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListConversationsApiResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationsApiResponse(%+v)", *p)
}

type ListConversationData struct {
	Conversations []*ConversationData `thrift:"conversations,1,default,list<ConversationData>" json:"conversations"`
	HasMore       bool                `thrift:"has_more,2" json:"has_more"`
}

func NewListConversationData() *ListConversationData {
	return &ListConversationData{}
}

func (p *ListConversationData) InitDefault() {
}

func (p *ListConversationData) GetConversations() (v []*ConversationData) {
	return p.Conversations
}

func (p *ListConversationData) GetHasMore() (v bool) {
	return p.HasMore
}
func (p *ListConversationData) SetConversations(val []*ConversationData) {
	p.Conversations = val
}
func (p *ListConversationData) SetHasMore(val bool) {
	p.HasMore = val
}

func (p *ListConversationData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationData(%+v)", *p)
}

type UpdateConversationApiRequest struct {
	ConversationID *int64     `thrift:"ConversationID,1,optional" json:"ConversationID,omitempty"`
	Name           *string    `thrift:"Name,2,optional" json:"Name,omitempty"`
	Base           *base.Base `thrift:"Base,255" json:"Base"`
}

func NewUpdateConversationApiRequest() *UpdateConversationApiRequest {
	return &UpdateConversationApiRequest{}
}

func (p *UpdateConversationApiRequest) InitDefault() {
}

var UpdateConversationApiRequest_ConversationID_DEFAULT int64

func (p *UpdateConversationApiRequest) GetConversationID() (v int64) {
	if !p.IsSetConversationID() {
		return UpdateConversationApiRequest_ConversationID_DEFAULT
	}
	return *p.ConversationID
}

var UpdateConversationApiRequest_Name_DEFAULT string

func (p *UpdateConversationApiRequest) GetName() (v string) {
	if !p.IsSetName() {
		return UpdateConversationApiRequest_Name_DEFAULT
	}
	return *p.Name
}

var UpdateConversationApiRequest_Base_DEFAULT *base.Base

func (p *UpdateConversationApiRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return UpdateConversationApiRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateConversationApiRequest) SetConversationID(val *int64) {
	p.ConversationID = val
}
func (p *UpdateConversationApiRequest) SetName(val *string) {
	p.Name = val
}
func (p *UpdateConversationApiRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *UpdateConversationApiRequest) IsSetConversationID() bool {
	return p.ConversationID != nil
}

func (p *UpdateConversationApiRequest) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdateConversationApiRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateConversationApiRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateConversationApiRequest(%+v)", *p)
}

type UpdateConversationApiResponse struct {
	ConversationData *ConversationData `thrift:"ConversationData,1,optional" json:"ConversationData,omitempty"`
	Code             int32             `thrift:"Code,2" json:"Code"`
	Msg              string            `thrift:"Msg,3" json:"Msg"`
	BaseResp         *base.BaseResp    `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewUpdateConversationApiResponse() *UpdateConversationApiResponse {
	return &UpdateConversationApiResponse{}
}

func (p *UpdateConversationApiResponse) InitDefault() {
}

var UpdateConversationApiResponse_ConversationData_DEFAULT *ConversationData

func (p *UpdateConversationApiResponse) GetConversationData() (v *ConversationData) {
	if !p.IsSetConversationData() {
		return UpdateConversationApiResponse_ConversationData_DEFAULT
	}
	return p.ConversationData
}

func (p *UpdateConversationApiResponse) GetCode() (v int32) {
	return p.Code
}

func (p *UpdateConversationApiResponse) GetMsg() (v string) {
	return p.Msg
}

var UpdateConversationApiResponse_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateConversationApiResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateConversationApiResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateConversationApiResponse) SetConversationData(val *ConversationData) {
	p.ConversationData = val
}
func (p *UpdateConversationApiResponse) SetCode(val int32) {
	p.Code = val
}
func (p *UpdateConversationApiResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *UpdateConversationApiResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateConversationApiResponse) IsSetConversationData() bool {
	return p.ConversationData != nil
}

func (p *UpdateConversationApiResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateConversationApiResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateConversationApiResponse(%+v)", *p)
}

type DeleteConversationApiRequest struct {
	ConversationID *int64     `thrift:"ConversationID,1,optional" json:"ConversationID,omitempty"`
	Base           *base.Base `thrift:"Base,255" json:"Base"`
}

func NewDeleteConversationApiRequest() *DeleteConversationApiRequest {
	return &DeleteConversationApiRequest{}
}

func (p *DeleteConversationApiRequest) InitDefault() {
}

var DeleteConversationApiRequest_ConversationID_DEFAULT int64

func (p *DeleteConversationApiRequest) GetConversationID() (v int64) {
	if !p.IsSetConversationID() {
		return DeleteConversationApiRequest_ConversationID_DEFAULT
	}
	return *p.ConversationID
}

var DeleteConversationApiRequest_Base_DEFAULT *base.Base

func (p *DeleteConversationApiRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return DeleteConversationApiRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteConversationApiRequest) SetConversationID(val *int64) {
	p.ConversationID = val
}
func (p *DeleteConversationApiRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *DeleteConversationApiRequest) IsSetConversationID() bool {
	return p.ConversationID != nil
}

func (p *DeleteConversationApiRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteConversationApiRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteConversationApiRequest(%+v)", *p)
}

type DeleteConversationApiResponse struct {
	Code     int32          `thrift:"Code,1" json:"Code"`
	Msg      string         `thrift:"Msg,2" json:"Msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255" json:"BaseResp"`
}

func NewDeleteConversationApiResponse() *DeleteConversationApiResponse {
	return &DeleteConversationApiResponse{}
}

func (p *DeleteConversationApiResponse) InitDefault() {
}

func (p *DeleteConversationApiResponse) GetCode() (v int32) {
	return p.Code
}

func (p *DeleteConversationApiResponse) GetMsg() (v string) {
	return p.Msg
}

var DeleteConversationApiResponse_BaseResp_DEFAULT *base.BaseResp

func (p *DeleteConversationApiResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeleteConversationApiResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteConversationApiResponse) SetCode(val int32) {
	p.Code = val
}
func (p *DeleteConversationApiResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *DeleteConversationApiResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeleteConversationApiResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteConversationApiResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteConversationApiResponse(%+v)", *p)
}
