// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package playground

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/kiosk404/airi-go/backend/api/model/app/bot_common"
	"github.com/kiosk404/airi-go/backend/api/model/base"
)

type BotPopupType int64

const (
	BotPopupType_AutoGenBeforePublish BotPopupType = 1
)

func (p BotPopupType) String() string {
	switch p {
	case BotPopupType_AutoGenBeforePublish:
		return "AutoGenBeforePublish"
	}
	return "<UNSET>"
}

func BotPopupTypeFromString(s string) (BotPopupType, error) {
	switch s {
	case "AutoGenBeforePublish":
		return BotPopupType_AutoGenBeforePublish, nil
	}
	return BotPopupType(0), fmt.Errorf("not a valid BotPopupType string")
}

func BotPopupTypePtr(v BotPopupType) *BotPopupType { return &v }
func (p *BotPopupType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = BotPopupType(result.Int64)
	return
}

func (p *BotPopupType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ResourceType int64

const (
	ResourceType_DraftBot ResourceType = 1
	ResourceType_Project  ResourceType = 2
)

func (p ResourceType) String() string {
	switch p {
	case ResourceType_DraftBot:
		return "DraftBot"
	case ResourceType_Project:
		return "Project"
	}
	return "<UNSET>"
}

func ResourceTypeFromString(s string) (ResourceType, error) {
	switch s {
	case "DraftBot":
		return ResourceType_DraftBot, nil
	case "Project":
		return ResourceType_Project, nil
	}
	return ResourceType(0), fmt.Errorf("not a valid ResourceType string")
}

func ResourceTypePtr(v ResourceType) *ResourceType { return &v }
func (p *ResourceType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ResourceType(result.Int64)
	return
}

func (p *ResourceType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type BehaviorType int64

const (
	BehaviorType_Visit BehaviorType = 1
	BehaviorType_Edit  BehaviorType = 2
)

func (p BehaviorType) String() string {
	switch p {
	case BehaviorType_Visit:
		return "Visit"
	case BehaviorType_Edit:
		return "Edit"
	}
	return "<UNSET>"
}

func BehaviorTypeFromString(s string) (BehaviorType, error) {
	switch s {
	case "Visit":
		return BehaviorType_Visit, nil
	case "Edit":
		return BehaviorType_Edit, nil
	}
	return BehaviorType(0), fmt.Errorf("not a valid BehaviorType string")
}

func BehaviorTypePtr(v BehaviorType) *BehaviorType { return &v }
func (p *BehaviorType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = BehaviorType(result.Int64)
	return
}

func (p *BehaviorType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OnboardingContent struct {
	Prologue                   *string                                `thrift:"prologue,1,optional" json:"prologue,omitempty"`
	SuggestedQuestions         []string                               `thrift:"suggested_questions,2,optional,list<string>" json:"suggested_questions,omitempty"`
	SuggestedQuestionsShowMode *bot_common.SuggestedQuestionsShowMode `thrift:"suggested_questions_show_mode,3,optional,SuggestedQuestionsShowMode" json:"suggested_questions_show_mode,omitempty"`
}

func NewOnboardingContent() *OnboardingContent {
	return &OnboardingContent{}
}

func (p *OnboardingContent) InitDefault() {
}

var OnboardingContent_Prologue_DEFAULT string

func (p *OnboardingContent) GetPrologue() (v string) {
	if !p.IsSetPrologue() {
		return OnboardingContent_Prologue_DEFAULT
	}
	return *p.Prologue
}

var OnboardingContent_SuggestedQuestions_DEFAULT []string

func (p *OnboardingContent) GetSuggestedQuestions() (v []string) {
	if !p.IsSetSuggestedQuestions() {
		return OnboardingContent_SuggestedQuestions_DEFAULT
	}
	return p.SuggestedQuestions
}

var OnboardingContent_SuggestedQuestionsShowMode_DEFAULT bot_common.SuggestedQuestionsShowMode

func (p *OnboardingContent) GetSuggestedQuestionsShowMode() (v bot_common.SuggestedQuestionsShowMode) {
	if !p.IsSetSuggestedQuestionsShowMode() {
		return OnboardingContent_SuggestedQuestionsShowMode_DEFAULT
	}
	return *p.SuggestedQuestionsShowMode
}
func (p *OnboardingContent) SetPrologue(val *string) {
	p.Prologue = val
}
func (p *OnboardingContent) SetSuggestedQuestions(val []string) {
	p.SuggestedQuestions = val
}
func (p *OnboardingContent) SetSuggestedQuestionsShowMode(val *bot_common.SuggestedQuestionsShowMode) {
	p.SuggestedQuestionsShowMode = val
}

func (p *OnboardingContent) IsSetPrologue() bool {
	return p.Prologue != nil
}

func (p *OnboardingContent) IsSetSuggestedQuestions() bool {
	return p.SuggestedQuestions != nil
}

func (p *OnboardingContent) IsSetSuggestedQuestionsShowMode() bool {
	return p.SuggestedQuestionsShowMode != nil
}

func (p *OnboardingContent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OnboardingContent(%+v)", *p)
}

type GetBotPopupInfoRequest struct {
	BotPopupTypes []BotPopupType `thrift:"bot_popup_types,1,required,list<BotPopupType>" json:"bot_popup_types"`
	BotID         int64          `thrift:"bot_id,2,required" json:"bot_id"`
	Base          *base.Base     `thrift:"Base,255" json:"Base"`
}

func NewGetBotPopupInfoRequest() *GetBotPopupInfoRequest {
	return &GetBotPopupInfoRequest{}
}

func (p *GetBotPopupInfoRequest) InitDefault() {
}

func (p *GetBotPopupInfoRequest) GetBotPopupTypes() (v []BotPopupType) {
	return p.BotPopupTypes
}

func (p *GetBotPopupInfoRequest) GetBotID() (v int64) {
	return p.BotID
}

var GetBotPopupInfoRequest_Base_DEFAULT *base.Base

func (p *GetBotPopupInfoRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetBotPopupInfoRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *GetBotPopupInfoRequest) SetBotPopupTypes(val []BotPopupType) {
	p.BotPopupTypes = val
}
func (p *GetBotPopupInfoRequest) SetBotID(val int64) {
	p.BotID = val
}
func (p *GetBotPopupInfoRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetBotPopupInfoRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetBotPopupInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBotPopupInfoRequest(%+v)", *p)
}

type GetBotPopupInfoResponse struct {
	Data     *BotPopupInfoData `thrift:"data,1,required" json:"data"`
	Code     int64             `thrift:"code,253,required" json:"code"`
	Msg      string            `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp    `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewGetBotPopupInfoResponse() *GetBotPopupInfoResponse {
	return &GetBotPopupInfoResponse{}
}

func (p *GetBotPopupInfoResponse) InitDefault() {
}

var GetBotPopupInfoResponse_Data_DEFAULT *BotPopupInfoData

func (p *GetBotPopupInfoResponse) GetData() (v *BotPopupInfoData) {
	if !p.IsSetData() {
		return GetBotPopupInfoResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *GetBotPopupInfoResponse) GetCode() (v int64) {
	return p.Code
}

func (p *GetBotPopupInfoResponse) GetMsg() (v string) {
	return p.Msg
}

var GetBotPopupInfoResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetBotPopupInfoResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetBotPopupInfoResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetBotPopupInfoResponse) SetData(val *BotPopupInfoData) {
	p.Data = val
}
func (p *GetBotPopupInfoResponse) SetCode(val int64) {
	p.Code = val
}
func (p *GetBotPopupInfoResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *GetBotPopupInfoResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetBotPopupInfoResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetBotPopupInfoResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetBotPopupInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBotPopupInfoResponse(%+v)", *p)
}

type BotPopupInfoData struct {
	BotPopupCountInfo map[BotPopupType]int64 `thrift:"bot_popup_count_info,1,required,map<BotPopupType:i64>" json:"bot_popup_count_info"`
}

func NewBotPopupInfoData() *BotPopupInfoData {
	return &BotPopupInfoData{}
}

func (p *BotPopupInfoData) InitDefault() {
}

func (p *BotPopupInfoData) GetBotPopupCountInfo() (v map[BotPopupType]int64) {
	return p.BotPopupCountInfo
}
func (p *BotPopupInfoData) SetBotPopupCountInfo(val map[BotPopupType]int64) {
	p.BotPopupCountInfo = val
}

func (p *BotPopupInfoData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BotPopupInfoData(%+v)", *p)
}

type UpdateBotPopupInfoResponse struct {
	Code     int64          `thrift:"code,253,required" json:"code"`
	Msg      string         `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewUpdateBotPopupInfoResponse() *UpdateBotPopupInfoResponse {
	return &UpdateBotPopupInfoResponse{}
}

func (p *UpdateBotPopupInfoResponse) InitDefault() {
}

func (p *UpdateBotPopupInfoResponse) GetCode() (v int64) {
	return p.Code
}

func (p *UpdateBotPopupInfoResponse) GetMsg() (v string) {
	return p.Msg
}

var UpdateBotPopupInfoResponse_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateBotPopupInfoResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateBotPopupInfoResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateBotPopupInfoResponse) SetCode(val int64) {
	p.Code = val
}
func (p *UpdateBotPopupInfoResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *UpdateBotPopupInfoResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateBotPopupInfoResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateBotPopupInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateBotPopupInfoResponse(%+v)", *p)
}

type UpdateBotPopupInfoRequest struct {
	BotPopupType BotPopupType `thrift:"bot_popup_type,1,required,BotPopupType" json:"bot_popup_type"`
	BotID        int64        `thrift:"bot_id,2,required" json:"bot_id"`
	Base         *base.Base   `thrift:"Base,255" json:"Base"`
}

func NewUpdateBotPopupInfoRequest() *UpdateBotPopupInfoRequest {
	return &UpdateBotPopupInfoRequest{}
}

func (p *UpdateBotPopupInfoRequest) InitDefault() {
}

func (p *UpdateBotPopupInfoRequest) GetBotPopupType() (v BotPopupType) {
	return p.BotPopupType
}

func (p *UpdateBotPopupInfoRequest) GetBotID() (v int64) {
	return p.BotID
}

var UpdateBotPopupInfoRequest_Base_DEFAULT *base.Base

func (p *UpdateBotPopupInfoRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return UpdateBotPopupInfoRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateBotPopupInfoRequest) SetBotPopupType(val BotPopupType) {
	p.BotPopupType = val
}
func (p *UpdateBotPopupInfoRequest) SetBotID(val int64) {
	p.BotID = val
}
func (p *UpdateBotPopupInfoRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *UpdateBotPopupInfoRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateBotPopupInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateBotPopupInfoRequest(%+v)", *p)
}

type ReportUserBehaviorRequest struct {
	ResourceID   int64        `thrift:"ResourceID,1,required" json:"ResourceID"`
	ResourceType ResourceType `thrift:"ResourceType,2,required,ResourceType" json:"ResourceType"`
	BehaviorType BehaviorType `thrift:"BehaviorType,3,required,BehaviorType" json:"BehaviorType"`
	SpaceID      *int64       `thrift:"SpaceID,4,optional" json:"SpaceID,omitempty"`
	Base         *base.Base   `thrift:"Base,255" json:"Base"`
}

func NewReportUserBehaviorRequest() *ReportUserBehaviorRequest {
	return &ReportUserBehaviorRequest{}
}

func (p *ReportUserBehaviorRequest) InitDefault() {
}

func (p *ReportUserBehaviorRequest) GetResourceID() (v int64) {
	return p.ResourceID
}

func (p *ReportUserBehaviorRequest) GetResourceType() (v ResourceType) {
	return p.ResourceType
}

func (p *ReportUserBehaviorRequest) GetBehaviorType() (v BehaviorType) {
	return p.BehaviorType
}

var ReportUserBehaviorRequest_SpaceID_DEFAULT int64

func (p *ReportUserBehaviorRequest) GetSpaceID() (v int64) {
	if !p.IsSetSpaceID() {
		return ReportUserBehaviorRequest_SpaceID_DEFAULT
	}
	return *p.SpaceID
}

var ReportUserBehaviorRequest_Base_DEFAULT *base.Base

func (p *ReportUserBehaviorRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ReportUserBehaviorRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *ReportUserBehaviorRequest) SetResourceID(val int64) {
	p.ResourceID = val
}
func (p *ReportUserBehaviorRequest) SetResourceType(val ResourceType) {
	p.ResourceType = val
}
func (p *ReportUserBehaviorRequest) SetBehaviorType(val BehaviorType) {
	p.BehaviorType = val
}
func (p *ReportUserBehaviorRequest) SetSpaceID(val *int64) {
	p.SpaceID = val
}
func (p *ReportUserBehaviorRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *ReportUserBehaviorRequest) IsSetSpaceID() bool {
	return p.SpaceID != nil
}

func (p *ReportUserBehaviorRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ReportUserBehaviorRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReportUserBehaviorRequest(%+v)", *p)
}

type ReportUserBehaviorResponse struct {
	Code     int64          `thrift:"code,253,required" json:"code"`
	Msg      string         `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewReportUserBehaviorResponse() *ReportUserBehaviorResponse {
	return &ReportUserBehaviorResponse{}
}

func (p *ReportUserBehaviorResponse) InitDefault() {
}

func (p *ReportUserBehaviorResponse) GetCode() (v int64) {
	return p.Code
}

func (p *ReportUserBehaviorResponse) GetMsg() (v string) {
	return p.Msg
}

var ReportUserBehaviorResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ReportUserBehaviorResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ReportUserBehaviorResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ReportUserBehaviorResponse) SetCode(val int64) {
	p.Code = val
}
func (p *ReportUserBehaviorResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *ReportUserBehaviorResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ReportUserBehaviorResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ReportUserBehaviorResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReportUserBehaviorResponse(%+v)", *p)
}

type PlaygroundService interface {
	GetBotPopupInfo(ctx context.Context, request *GetBotPopupInfoRequest) (r *GetBotPopupInfoResponse, err error)

	UpdateBotPopupInfo(ctx context.Context, request *UpdateBotPopupInfoRequest) (r *UpdateBotPopupInfoResponse, err error)

	ReportUserBehavior(ctx context.Context, request *ReportUserBehaviorRequest) (r *ReportUserBehaviorResponse, err error)
}
