// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package playground

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/kiosk404/airi-go/backend/api/model/base"
)

type ActionKey int64

const (
	ActionKey_Copy         ActionKey = 1
	ActionKey_Delete       ActionKey = 2
	ActionKey_EnableSwitch ActionKey = 3
	ActionKey_Edit         ActionKey = 4
)

func (p ActionKey) String() string {
	switch p {
	case ActionKey_Copy:
		return "Copy"
	case ActionKey_Delete:
		return "Delete"
	case ActionKey_EnableSwitch:
		return "EnableSwitch"
	case ActionKey_Edit:
		return "Edit"
	}
	return "<UNSET>"
}

func ActionKeyFromString(s string) (ActionKey, error) {
	switch s {
	case "Copy":
		return ActionKey_Copy, nil
	case "Delete":
		return ActionKey_Delete, nil
	case "EnableSwitch":
		return ActionKey_EnableSwitch, nil
	case "Edit":
		return ActionKey_Edit, nil
	}
	return ActionKey(0), fmt.Errorf("not a valid ActionKey string")
}

func ActionKeyPtr(v ActionKey) *ActionKey { return &v }
func (p *ActionKey) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ActionKey(result.Int64)
	return
}

func (p *ActionKey) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ResourcePublishStatus int64

const (
	ResourcePublishStatus_UnPublished ResourcePublishStatus = 1
	ResourcePublishStatus_Published   ResourcePublishStatus = 2
)

func (p ResourcePublishStatus) String() string {
	switch p {
	case ResourcePublishStatus_UnPublished:
		return "UnPublished"
	case ResourcePublishStatus_Published:
		return "Published"
	}
	return "<UNSET>"
}

func ResourcePublishStatusFromString(s string) (ResourcePublishStatus, error) {
	switch s {
	case "UnPublished":
		return ResourcePublishStatus_UnPublished, nil
	case "Published":
		return ResourcePublishStatus_Published, nil
	}
	return ResourcePublishStatus(0), fmt.Errorf("not a valid ResourcePublishStatus string")
}

func ResourcePublishStatusPtr(v ResourcePublishStatus) *ResourcePublishStatus { return &v }
func (p *ResourcePublishStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ResourcePublishStatus(result.Int64)
	return
}

func (p *ResourcePublishStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type GetOfficialPromptResourceListRequest struct {
	Keyword *string    `thrift:"Keyword,1,optional" json:"Keyword,omitempty"`
	Base    *base.Base `thrift:"Base,255" json:"Base"`
}

func NewGetOfficialPromptResourceListRequest() *GetOfficialPromptResourceListRequest {
	return &GetOfficialPromptResourceListRequest{}
}

func (p *GetOfficialPromptResourceListRequest) InitDefault() {
}

var GetOfficialPromptResourceListRequest_Keyword_DEFAULT string

func (p *GetOfficialPromptResourceListRequest) GetKeyword() (v string) {
	if !p.IsSetKeyword() {
		return GetOfficialPromptResourceListRequest_Keyword_DEFAULT
	}
	return *p.Keyword
}

var GetOfficialPromptResourceListRequest_Base_DEFAULT *base.Base

func (p *GetOfficialPromptResourceListRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetOfficialPromptResourceListRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *GetOfficialPromptResourceListRequest) SetKeyword(val *string) {
	p.Keyword = val
}
func (p *GetOfficialPromptResourceListRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetOfficialPromptResourceListRequest) IsSetKeyword() bool {
	return p.Keyword != nil
}

func (p *GetOfficialPromptResourceListRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetOfficialPromptResourceListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOfficialPromptResourceListRequest(%+v)", *p)
}

type PromptResource struct {
	ID          *int64  `thrift:"ID,1,optional" json:"ID,omitempty"`
	Name        *string `thrift:"Name,2,optional" json:"Name,omitempty"`
	Description *string `thrift:"Description,3,optional" json:"Description,omitempty"`
	PromptText  *string `thrift:"PromptText,4,optional" json:"PromptText,omitempty"`
}

func NewPromptResource() *PromptResource {
	return &PromptResource{}
}

func (p *PromptResource) InitDefault() {
}

var PromptResource_ID_DEFAULT int64

func (p *PromptResource) GetID() (v int64) {
	if !p.IsSetID() {
		return PromptResource_ID_DEFAULT
	}
	return *p.ID
}

var PromptResource_Name_DEFAULT string

func (p *PromptResource) GetName() (v string) {
	if !p.IsSetName() {
		return PromptResource_Name_DEFAULT
	}
	return *p.Name
}

var PromptResource_Description_DEFAULT string

func (p *PromptResource) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return PromptResource_Description_DEFAULT
	}
	return *p.Description
}

var PromptResource_PromptText_DEFAULT string

func (p *PromptResource) GetPromptText() (v string) {
	if !p.IsSetPromptText() {
		return PromptResource_PromptText_DEFAULT
	}
	return *p.PromptText
}
func (p *PromptResource) SetID(val *int64) {
	p.ID = val
}
func (p *PromptResource) SetName(val *string) {
	p.Name = val
}
func (p *PromptResource) SetDescription(val *string) {
	p.Description = val
}
func (p *PromptResource) SetPromptText(val *string) {
	p.PromptText = val
}

func (p *PromptResource) IsSetID() bool {
	return p.ID != nil
}

func (p *PromptResource) IsSetName() bool {
	return p.Name != nil
}

func (p *PromptResource) IsSetDescription() bool {
	return p.Description != nil
}

func (p *PromptResource) IsSetPromptText() bool {
	return p.PromptText != nil
}

func (p *PromptResource) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PromptResource(%+v)", *p)
}

type GetOfficialPromptResourceListResponse struct {
	PromptResourceList []*PromptResource `thrift:"PromptResourceList,1,default,list<PromptResource>" json:"PromptResourceList"`
	Code               int64             `thrift:"code,253,required" json:"code"`
	Msg                string            `thrift:"msg,254,required" json:"msg"`
	BaseResp           *base.BaseResp    `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewGetOfficialPromptResourceListResponse() *GetOfficialPromptResourceListResponse {
	return &GetOfficialPromptResourceListResponse{}
}

func (p *GetOfficialPromptResourceListResponse) InitDefault() {
}

func (p *GetOfficialPromptResourceListResponse) GetPromptResourceList() (v []*PromptResource) {
	return p.PromptResourceList
}

func (p *GetOfficialPromptResourceListResponse) GetCode() (v int64) {
	return p.Code
}

func (p *GetOfficialPromptResourceListResponse) GetMsg() (v string) {
	return p.Msg
}

var GetOfficialPromptResourceListResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetOfficialPromptResourceListResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetOfficialPromptResourceListResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetOfficialPromptResourceListResponse) SetPromptResourceList(val []*PromptResource) {
	p.PromptResourceList = val
}
func (p *GetOfficialPromptResourceListResponse) SetCode(val int64) {
	p.Code = val
}
func (p *GetOfficialPromptResourceListResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *GetOfficialPromptResourceListResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetOfficialPromptResourceListResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetOfficialPromptResourceListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOfficialPromptResourceListResponse(%+v)", *p)
}

type GetPromptResourceInfoRequest struct {
	PromptResourceID int64      `thrift:"PromptResourceID,1,required" json:"PromptResourceID"`
	Base             *base.Base `thrift:"Base,255" json:"Base"`
}

func NewGetPromptResourceInfoRequest() *GetPromptResourceInfoRequest {
	return &GetPromptResourceInfoRequest{}
}

func (p *GetPromptResourceInfoRequest) InitDefault() {
}

func (p *GetPromptResourceInfoRequest) GetPromptResourceID() (v int64) {
	return p.PromptResourceID
}

var GetPromptResourceInfoRequest_Base_DEFAULT *base.Base

func (p *GetPromptResourceInfoRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetPromptResourceInfoRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *GetPromptResourceInfoRequest) SetPromptResourceID(val int64) {
	p.PromptResourceID = val
}
func (p *GetPromptResourceInfoRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetPromptResourceInfoRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPromptResourceInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPromptResourceInfoRequest(%+v)", *p)
}

type GetPromptResourceInfoResponse struct {
	Data     *PromptResource `thrift:"Data,1,optional" json:"Data,omitempty"`
	Code     int64           `thrift:"code,253,required" json:"code"`
	Msg      string          `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp  `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewGetPromptResourceInfoResponse() *GetPromptResourceInfoResponse {
	return &GetPromptResourceInfoResponse{}
}

func (p *GetPromptResourceInfoResponse) InitDefault() {
}

var GetPromptResourceInfoResponse_Data_DEFAULT *PromptResource

func (p *GetPromptResourceInfoResponse) GetData() (v *PromptResource) {
	if !p.IsSetData() {
		return GetPromptResourceInfoResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *GetPromptResourceInfoResponse) GetCode() (v int64) {
	return p.Code
}

func (p *GetPromptResourceInfoResponse) GetMsg() (v string) {
	return p.Msg
}

var GetPromptResourceInfoResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetPromptResourceInfoResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetPromptResourceInfoResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetPromptResourceInfoResponse) SetData(val *PromptResource) {
	p.Data = val
}
func (p *GetPromptResourceInfoResponse) SetCode(val int64) {
	p.Code = val
}
func (p *GetPromptResourceInfoResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *GetPromptResourceInfoResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetPromptResourceInfoResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetPromptResourceInfoResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetPromptResourceInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPromptResourceInfoResponse(%+v)", *p)
}

type UpsertPromptResourceRequest struct {
	Prompt *PromptResource `thrift:"Prompt,1,required" json:"Prompt"`
	Base   *base.Base      `thrift:"Base,255" json:"Base"`
}

func NewUpsertPromptResourceRequest() *UpsertPromptResourceRequest {
	return &UpsertPromptResourceRequest{}
}

func (p *UpsertPromptResourceRequest) InitDefault() {
}

var UpsertPromptResourceRequest_Prompt_DEFAULT *PromptResource

func (p *UpsertPromptResourceRequest) GetPrompt() (v *PromptResource) {
	if !p.IsSetPrompt() {
		return UpsertPromptResourceRequest_Prompt_DEFAULT
	}
	return p.Prompt
}

var UpsertPromptResourceRequest_Base_DEFAULT *base.Base

func (p *UpsertPromptResourceRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return UpsertPromptResourceRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *UpsertPromptResourceRequest) SetPrompt(val *PromptResource) {
	p.Prompt = val
}
func (p *UpsertPromptResourceRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *UpsertPromptResourceRequest) IsSetPrompt() bool {
	return p.Prompt != nil
}

func (p *UpsertPromptResourceRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpsertPromptResourceRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpsertPromptResourceRequest(%+v)", *p)
}

type UpsertPromptResourceResponse struct {
	Data     *ShowPromptResource `thrift:"data,1,optional" json:"data,omitempty"`
	Code     int64               `thrift:"code,253,required" json:"code"`
	Msg      string              `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp      `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewUpsertPromptResourceResponse() *UpsertPromptResourceResponse {
	return &UpsertPromptResourceResponse{}
}

func (p *UpsertPromptResourceResponse) InitDefault() {
}

var UpsertPromptResourceResponse_Data_DEFAULT *ShowPromptResource

func (p *UpsertPromptResourceResponse) GetData() (v *ShowPromptResource) {
	if !p.IsSetData() {
		return UpsertPromptResourceResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *UpsertPromptResourceResponse) GetCode() (v int64) {
	return p.Code
}

func (p *UpsertPromptResourceResponse) GetMsg() (v string) {
	return p.Msg
}

var UpsertPromptResourceResponse_BaseResp_DEFAULT *base.BaseResp

func (p *UpsertPromptResourceResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpsertPromptResourceResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpsertPromptResourceResponse) SetData(val *ShowPromptResource) {
	p.Data = val
}
func (p *UpsertPromptResourceResponse) SetCode(val int64) {
	p.Code = val
}
func (p *UpsertPromptResourceResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *UpsertPromptResourceResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpsertPromptResourceResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *UpsertPromptResourceResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpsertPromptResourceResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpsertPromptResourceResponse(%+v)", *p)
}

type ShowPromptResource struct {
	ID int64 `thrift:"ID,1" json:"ID"`
}

func NewShowPromptResource() *ShowPromptResource {
	return &ShowPromptResource{}
}

func (p *ShowPromptResource) InitDefault() {
}

func (p *ShowPromptResource) GetID() (v int64) {
	return p.ID
}
func (p *ShowPromptResource) SetID(val int64) {
	p.ID = val
}

func (p *ShowPromptResource) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShowPromptResource(%+v)", *p)
}

type DeletePromptResourceRequest struct {
	PromptResourceID int64      `thrift:"PromptResourceID,1,required" json:"PromptResourceID"`
	Base             *base.Base `thrift:"Base,255" json:"Base"`
}

func NewDeletePromptResourceRequest() *DeletePromptResourceRequest {
	return &DeletePromptResourceRequest{}
}

func (p *DeletePromptResourceRequest) InitDefault() {
}

func (p *DeletePromptResourceRequest) GetPromptResourceID() (v int64) {
	return p.PromptResourceID
}

var DeletePromptResourceRequest_Base_DEFAULT *base.Base

func (p *DeletePromptResourceRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return DeletePromptResourceRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *DeletePromptResourceRequest) SetPromptResourceID(val int64) {
	p.PromptResourceID = val
}
func (p *DeletePromptResourceRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *DeletePromptResourceRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeletePromptResourceRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeletePromptResourceRequest(%+v)", *p)
}

type DeletePromptResourceResponse struct {
	Code     int64          `thrift:"code,253,required" json:"code"`
	Msg      string         `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewDeletePromptResourceResponse() *DeletePromptResourceResponse {
	return &DeletePromptResourceResponse{}
}

func (p *DeletePromptResourceResponse) InitDefault() {
}

func (p *DeletePromptResourceResponse) GetCode() (v int64) {
	return p.Code
}

func (p *DeletePromptResourceResponse) GetMsg() (v string) {
	return p.Msg
}

var DeletePromptResourceResponse_BaseResp_DEFAULT *base.BaseResp

func (p *DeletePromptResourceResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeletePromptResourceResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeletePromptResourceResponse) SetCode(val int64) {
	p.Code = val
}
func (p *DeletePromptResourceResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *DeletePromptResourceResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeletePromptResourceResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeletePromptResourceResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeletePromptResourceResponse(%+v)", *p)
}

type SyncPromptResourceToEsRequest struct {
	SyncAll              *bool      `thrift:"SyncAll,1,optional" json:"SyncAll,omitempty"`
	PromptResourceIDList []int64    `thrift:"PromptResourceIDList,2,optional,list<i64>" json:"PromptResourceIDList,omitempty"`
	Base                 *base.Base `thrift:"Base,255" json:"Base"`
}

func NewSyncPromptResourceToEsRequest() *SyncPromptResourceToEsRequest {
	return &SyncPromptResourceToEsRequest{}
}

func (p *SyncPromptResourceToEsRequest) InitDefault() {
}

var SyncPromptResourceToEsRequest_SyncAll_DEFAULT bool

func (p *SyncPromptResourceToEsRequest) GetSyncAll() (v bool) {
	if !p.IsSetSyncAll() {
		return SyncPromptResourceToEsRequest_SyncAll_DEFAULT
	}
	return *p.SyncAll
}

var SyncPromptResourceToEsRequest_PromptResourceIDList_DEFAULT []int64

func (p *SyncPromptResourceToEsRequest) GetPromptResourceIDList() (v []int64) {
	if !p.IsSetPromptResourceIDList() {
		return SyncPromptResourceToEsRequest_PromptResourceIDList_DEFAULT
	}
	return p.PromptResourceIDList
}

var SyncPromptResourceToEsRequest_Base_DEFAULT *base.Base

func (p *SyncPromptResourceToEsRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return SyncPromptResourceToEsRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *SyncPromptResourceToEsRequest) SetSyncAll(val *bool) {
	p.SyncAll = val
}
func (p *SyncPromptResourceToEsRequest) SetPromptResourceIDList(val []int64) {
	p.PromptResourceIDList = val
}
func (p *SyncPromptResourceToEsRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *SyncPromptResourceToEsRequest) IsSetSyncAll() bool {
	return p.SyncAll != nil
}

func (p *SyncPromptResourceToEsRequest) IsSetPromptResourceIDList() bool {
	return p.PromptResourceIDList != nil
}

func (p *SyncPromptResourceToEsRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *SyncPromptResourceToEsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SyncPromptResourceToEsRequest(%+v)", *p)
}

type SyncPromptResourceToEsResponse struct {
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewSyncPromptResourceToEsResponse() *SyncPromptResourceToEsResponse {
	return &SyncPromptResourceToEsResponse{}
}

func (p *SyncPromptResourceToEsResponse) InitDefault() {
}

var SyncPromptResourceToEsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *SyncPromptResourceToEsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return SyncPromptResourceToEsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SyncPromptResourceToEsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *SyncPromptResourceToEsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SyncPromptResourceToEsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SyncPromptResourceToEsResponse(%+v)", *p)
}

type MGetDisplayResourceInfoRequest struct {
	ResIDs        []int64    `thrift:"ResIDs,1,default,list<i64>" json:"ResIDs"`
	CurrentUserID int64      `thrift:"CurrentUserID,2" json:"CurrentUserID"`
	Base          *base.Base `thrift:"Base,255" json:"Base"`
}

func NewMGetDisplayResourceInfoRequest() *MGetDisplayResourceInfoRequest {
	return &MGetDisplayResourceInfoRequest{}
}

func (p *MGetDisplayResourceInfoRequest) InitDefault() {
}

func (p *MGetDisplayResourceInfoRequest) GetResIDs() (v []int64) {
	return p.ResIDs
}

func (p *MGetDisplayResourceInfoRequest) GetCurrentUserID() (v int64) {
	return p.CurrentUserID
}

var MGetDisplayResourceInfoRequest_Base_DEFAULT *base.Base

func (p *MGetDisplayResourceInfoRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return MGetDisplayResourceInfoRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *MGetDisplayResourceInfoRequest) SetResIDs(val []int64) {
	p.ResIDs = val
}
func (p *MGetDisplayResourceInfoRequest) SetCurrentUserID(val int64) {
	p.CurrentUserID = val
}
func (p *MGetDisplayResourceInfoRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *MGetDisplayResourceInfoRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *MGetDisplayResourceInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MGetDisplayResourceInfoRequest(%+v)", *p)
}

type MGetDisplayResourceInfoResponse struct {
	ResourceList []*DisplayResourceInfo `thrift:"ResourceList,1,default,list<DisplayResourceInfo>" json:"ResourceList"`
	BaseResp     *base.BaseResp         `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewMGetDisplayResourceInfoResponse() *MGetDisplayResourceInfoResponse {
	return &MGetDisplayResourceInfoResponse{}
}

func (p *MGetDisplayResourceInfoResponse) InitDefault() {
}

func (p *MGetDisplayResourceInfoResponse) GetResourceList() (v []*DisplayResourceInfo) {
	return p.ResourceList
}

var MGetDisplayResourceInfoResponse_BaseResp_DEFAULT *base.BaseResp

func (p *MGetDisplayResourceInfoResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return MGetDisplayResourceInfoResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *MGetDisplayResourceInfoResponse) SetResourceList(val []*DisplayResourceInfo) {
	p.ResourceList = val
}
func (p *MGetDisplayResourceInfoResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *MGetDisplayResourceInfoResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *MGetDisplayResourceInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MGetDisplayResourceInfoResponse(%+v)", *p)
}

type ResourceAction struct {
	Key    ActionKey `thrift:"Key,1,required,ActionKey" json:"key"`
	Enable bool      `thrift:"Enable,2,required" json:"enable"`
}

func NewResourceAction() *ResourceAction {
	return &ResourceAction{}
}

func (p *ResourceAction) InitDefault() {
}

func (p *ResourceAction) GetKey() (v ActionKey) {
	return p.Key
}

func (p *ResourceAction) GetEnable() (v bool) {
	return p.Enable
}
func (p *ResourceAction) SetKey(val ActionKey) {
	p.Key = val
}
func (p *ResourceAction) SetEnable(val bool) {
	p.Enable = val
}

func (p *ResourceAction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResourceAction(%+v)", *p)
}

type DisplayResourceInfo struct {
	ResID               *int64                 `thrift:"ResID,1,optional" json:"ResID,omitempty"`
	Desc                *string                `thrift:"Desc,5,optional" json:"Desc,omitempty"`
	Icon                *string                `thrift:"Icon,6,optional" json:"Icon,omitempty"`
	BizResStatus        *int32                 `thrift:"BizResStatus,12,optional" json:"BizResStatus,omitempty"`
	CollaborationEnable *bool                  `thrift:"CollaborationEnable,13,optional" json:"CollaborationEnable,omitempty"`
	BizExtend           map[string]string      `thrift:"BizExtend,16,optional" json:"BizExtend,omitempty"`
	Actions             []*ResourceAction      `thrift:"Actions,17,optional,list<ResourceAction>" json:"Actions,omitempty"`
	DetailDisable       *bool                  `thrift:"DetailDisable,18,optional" json:"DetailDisable,omitempty"`
	Name                *string                `thrift:"Name,19,optional" json:"Name,omitempty"`
	PublishStatus       *ResourcePublishStatus `thrift:"PublishStatus,20,optional,ResourcePublishStatus" json:"PublishStatus,omitempty"`
	EditTime            *int64                 `thrift:"EditTime,21,optional" json:"EditTime,omitempty"`
}

func NewDisplayResourceInfo() *DisplayResourceInfo {
	return &DisplayResourceInfo{}
}

func (p *DisplayResourceInfo) InitDefault() {
}

var DisplayResourceInfo_ResID_DEFAULT int64

func (p *DisplayResourceInfo) GetResID() (v int64) {
	if !p.IsSetResID() {
		return DisplayResourceInfo_ResID_DEFAULT
	}
	return *p.ResID
}

var DisplayResourceInfo_Desc_DEFAULT string

func (p *DisplayResourceInfo) GetDesc() (v string) {
	if !p.IsSetDesc() {
		return DisplayResourceInfo_Desc_DEFAULT
	}
	return *p.Desc
}

var DisplayResourceInfo_Icon_DEFAULT string

func (p *DisplayResourceInfo) GetIcon() (v string) {
	if !p.IsSetIcon() {
		return DisplayResourceInfo_Icon_DEFAULT
	}
	return *p.Icon
}

var DisplayResourceInfo_BizResStatus_DEFAULT int32

func (p *DisplayResourceInfo) GetBizResStatus() (v int32) {
	if !p.IsSetBizResStatus() {
		return DisplayResourceInfo_BizResStatus_DEFAULT
	}
	return *p.BizResStatus
}

var DisplayResourceInfo_CollaborationEnable_DEFAULT bool

func (p *DisplayResourceInfo) GetCollaborationEnable() (v bool) {
	if !p.IsSetCollaborationEnable() {
		return DisplayResourceInfo_CollaborationEnable_DEFAULT
	}
	return *p.CollaborationEnable
}

var DisplayResourceInfo_BizExtend_DEFAULT map[string]string

func (p *DisplayResourceInfo) GetBizExtend() (v map[string]string) {
	if !p.IsSetBizExtend() {
		return DisplayResourceInfo_BizExtend_DEFAULT
	}
	return p.BizExtend
}

var DisplayResourceInfo_Actions_DEFAULT []*ResourceAction

func (p *DisplayResourceInfo) GetActions() (v []*ResourceAction) {
	if !p.IsSetActions() {
		return DisplayResourceInfo_Actions_DEFAULT
	}
	return p.Actions
}

var DisplayResourceInfo_DetailDisable_DEFAULT bool

func (p *DisplayResourceInfo) GetDetailDisable() (v bool) {
	if !p.IsSetDetailDisable() {
		return DisplayResourceInfo_DetailDisable_DEFAULT
	}
	return *p.DetailDisable
}

var DisplayResourceInfo_Name_DEFAULT string

func (p *DisplayResourceInfo) GetName() (v string) {
	if !p.IsSetName() {
		return DisplayResourceInfo_Name_DEFAULT
	}
	return *p.Name
}

var DisplayResourceInfo_PublishStatus_DEFAULT ResourcePublishStatus

func (p *DisplayResourceInfo) GetPublishStatus() (v ResourcePublishStatus) {
	if !p.IsSetPublishStatus() {
		return DisplayResourceInfo_PublishStatus_DEFAULT
	}
	return *p.PublishStatus
}

var DisplayResourceInfo_EditTime_DEFAULT int64

func (p *DisplayResourceInfo) GetEditTime() (v int64) {
	if !p.IsSetEditTime() {
		return DisplayResourceInfo_EditTime_DEFAULT
	}
	return *p.EditTime
}
func (p *DisplayResourceInfo) SetResID(val *int64) {
	p.ResID = val
}
func (p *DisplayResourceInfo) SetDesc(val *string) {
	p.Desc = val
}
func (p *DisplayResourceInfo) SetIcon(val *string) {
	p.Icon = val
}
func (p *DisplayResourceInfo) SetBizResStatus(val *int32) {
	p.BizResStatus = val
}
func (p *DisplayResourceInfo) SetCollaborationEnable(val *bool) {
	p.CollaborationEnable = val
}
func (p *DisplayResourceInfo) SetBizExtend(val map[string]string) {
	p.BizExtend = val
}
func (p *DisplayResourceInfo) SetActions(val []*ResourceAction) {
	p.Actions = val
}
func (p *DisplayResourceInfo) SetDetailDisable(val *bool) {
	p.DetailDisable = val
}
func (p *DisplayResourceInfo) SetName(val *string) {
	p.Name = val
}
func (p *DisplayResourceInfo) SetPublishStatus(val *ResourcePublishStatus) {
	p.PublishStatus = val
}
func (p *DisplayResourceInfo) SetEditTime(val *int64) {
	p.EditTime = val
}

func (p *DisplayResourceInfo) IsSetResID() bool {
	return p.ResID != nil
}

func (p *DisplayResourceInfo) IsSetDesc() bool {
	return p.Desc != nil
}

func (p *DisplayResourceInfo) IsSetIcon() bool {
	return p.Icon != nil
}

func (p *DisplayResourceInfo) IsSetBizResStatus() bool {
	return p.BizResStatus != nil
}

func (p *DisplayResourceInfo) IsSetCollaborationEnable() bool {
	return p.CollaborationEnable != nil
}

func (p *DisplayResourceInfo) IsSetBizExtend() bool {
	return p.BizExtend != nil
}

func (p *DisplayResourceInfo) IsSetActions() bool {
	return p.Actions != nil
}

func (p *DisplayResourceInfo) IsSetDetailDisable() bool {
	return p.DetailDisable != nil
}

func (p *DisplayResourceInfo) IsSetName() bool {
	return p.Name != nil
}

func (p *DisplayResourceInfo) IsSetPublishStatus() bool {
	return p.PublishStatus != nil
}

func (p *DisplayResourceInfo) IsSetEditTime() bool {
	return p.EditTime != nil
}

func (p *DisplayResourceInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DisplayResourceInfo(%+v)", *p)
}
