// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package permission

import (
	"context"
	"github.com/kiosk404/airi-go/backend/api/model/foundation/permission/openapiauth"
)

type OpenAPIAuthService interface {
	GetPersonalAccessTokenAndPermission(ctx context.Context, req *openapiauth.GetPersonalAccessTokenAndPermissionRequest) (r *openapiauth.GetPersonalAccessTokenAndPermissionResponse, err error)

	DeletePersonalAccessTokenAndPermission(ctx context.Context, req *openapiauth.DeletePersonalAccessTokenAndPermissionRequest) (r *openapiauth.DeletePersonalAccessTokenAndPermissionResponse, err error)

	ListPersonalAccessTokens(ctx context.Context, req *openapiauth.ListPersonalAccessTokensRequest) (r *openapiauth.ListPersonalAccessTokensResponse, err error)

	CreatePersonalAccessTokenAndPermission(ctx context.Context, req *openapiauth.CreatePersonalAccessTokenAndPermissionRequest) (r *openapiauth.CreatePersonalAccessTokenAndPermissionResponse, err error)

	UpdatePersonalAccessTokenAndPermission(ctx context.Context, req *openapiauth.UpdatePersonalAccessTokenAndPermissionRequest) (r *openapiauth.UpdatePersonalAccessTokenAndPermissionResponse, err error)
}
