package router

import (
	"os"
	"path"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/kiosk404/airi-go/backend/api/handle"
	"github.com/kiosk404/airi-go/backend/api/router/airi"
	"github.com/kiosk404/airi-go/backend/pkg/logs"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *gin.Engine) {
	// INSERT_POINT: DO NOT DELETE THIS LINE!
	airi.Register(r)
	staticFileRegister(r)
}

// staticFileRegister registers web page router.
func staticFileRegister(r *gin.Engine) {
	cwd, err := os.Getwd()
	if err != nil {
		logs.Warn("[staticFileRegister] Failed to get current working directory: %v", err)
		cwd = os.Getenv("PWD")
	}

	staticFile := path.Join(cwd, "resources/static/index.html")

	// 注册文件服务路由：/static/files/*filepath
	r.GET("/static/files/*filepath", handle.GetFile)
	
	r.StaticFile("/favicon.png", "./resources/static/favicon.png")
	r.StaticFile("/", staticFile)
	r.StaticFile("/sign", staticFile)

	type data struct {
		Code int32  `json:"code"`
		Msg  string `json:"msg"`
	}

	r.NoRoute(func(ctx *gin.Context) {
		requestPath := ctx.Request.URL.Path
		if strings.HasPrefix(requestPath, "/api/") ||
			strings.HasPrefix(requestPath, "/v1/") ||
			strings.HasPrefix(requestPath, "/v3/") {
			ctx.JSON(404, data{
				Code: 404,
				Msg:  "not found",
			})
			return
		}

		// index page will show 404 error
		ctx.File(staticFile)
	})
}
