// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kiosk404/airi-go/backend/modules/llm/domain/component/rpc (interfaces: IAuthProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/auth_provider.go -package=mocks . IAuthProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAuthProvider is a mock of IAuthProvider interface.
type MockIAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthProviderMockRecorder
	isgomock struct{}
}

// MockIAuthProviderMockRecorder is the mock recorder for MockIAuthProvider.
type MockIAuthProviderMockRecorder struct {
	mock *MockIAuthProvider
}

// NewMockIAuthProvider creates a new mock instance.
func NewMockIAuthProvider(ctrl *gomock.Controller) *MockIAuthProvider {
	mock := &MockIAuthProvider{ctrl: ctrl}
	mock.recorder = &MockIAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthProvider) EXPECT() *MockIAuthProviderMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockIAuthProvider) CheckPermission(ctx context.Context, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockIAuthProviderMockRecorder) CheckPermission(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockIAuthProvider)(nil).CheckPermission), ctx, action)
}
