// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package openapiauth

import (
	"fmt"
)

const (
	All = "all"

	Others = "others"

	Owned = "owned"

	Active = "active"

	Deactivated = "deactivated"

	Offboarded = "offboarded"
)

type PatSearchOption = string

type UserStatus = string

type CreatePersonalAccessTokenAndPermissionRequest struct {
	Name           string `thrift:"name,1,required" json:"name"`
	ExpireAt       int64  `thrift:"expire_at,2" json:"expire_at"`
	DurationDay    string `thrift:"duration_day,3" json:"duration_day"`
	OrganizationID string `thrift:"organization_id,4" json:"organization_id"`
}

func NewCreatePersonalAccessTokenAndPermissionRequest() *CreatePersonalAccessTokenAndPermissionRequest {
	return &CreatePersonalAccessTokenAndPermissionRequest{}
}

func (p *CreatePersonalAccessTokenAndPermissionRequest) InitDefault() {
}

func (p *CreatePersonalAccessTokenAndPermissionRequest) GetName() (v string) {
	return p.Name
}

func (p *CreatePersonalAccessTokenAndPermissionRequest) GetExpireAt() (v int64) {
	return p.ExpireAt
}

func (p *CreatePersonalAccessTokenAndPermissionRequest) GetDurationDay() (v string) {
	return p.DurationDay
}

func (p *CreatePersonalAccessTokenAndPermissionRequest) GetOrganizationID() (v string) {
	return p.OrganizationID
}
func (p *CreatePersonalAccessTokenAndPermissionRequest) SetName(val string) {
	p.Name = val
}
func (p *CreatePersonalAccessTokenAndPermissionRequest) SetExpireAt(val int64) {
	p.ExpireAt = val
}
func (p *CreatePersonalAccessTokenAndPermissionRequest) SetDurationDay(val string) {
	p.DurationDay = val
}
func (p *CreatePersonalAccessTokenAndPermissionRequest) SetOrganizationID(val string) {
	p.OrganizationID = val
}

func (p *CreatePersonalAccessTokenAndPermissionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePersonalAccessTokenAndPermissionRequest(%+v)", *p)
}

type PersonalAccessToken struct {
	ID         int64  `thrift:"id,1,required" json:"id"`
	Name       string `thrift:"name,2,required" json:"name"`
	CreatedAt  int64  `thrift:"created_at,3,required" json:"created_at"`
	UpdatedAt  int64  `thrift:"updated_at,4,required" json:"updated_at"`
	LastUsedAt int64  `thrift:"last_used_at,5,required" json:"last_used_at"`
	ExpireAt   int64  `thrift:"expire_at,6,required" json:"expire_at"`
}

func NewPersonalAccessToken() *PersonalAccessToken {
	return &PersonalAccessToken{}
}

func (p *PersonalAccessToken) InitDefault() {
}

func (p *PersonalAccessToken) GetID() (v int64) {
	return p.ID
}

func (p *PersonalAccessToken) GetName() (v string) {
	return p.Name
}

func (p *PersonalAccessToken) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *PersonalAccessToken) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

func (p *PersonalAccessToken) GetLastUsedAt() (v int64) {
	return p.LastUsedAt
}

func (p *PersonalAccessToken) GetExpireAt() (v int64) {
	return p.ExpireAt
}
func (p *PersonalAccessToken) SetID(val int64) {
	p.ID = val
}
func (p *PersonalAccessToken) SetName(val string) {
	p.Name = val
}
func (p *PersonalAccessToken) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *PersonalAccessToken) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *PersonalAccessToken) SetLastUsedAt(val int64) {
	p.LastUsedAt = val
}
func (p *PersonalAccessToken) SetExpireAt(val int64) {
	p.ExpireAt = val
}

func (p *PersonalAccessToken) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PersonalAccessToken(%+v)", *p)
}

type CreatePersonalAccessTokenAndPermissionResponseData struct {
	PersonalAccessToken *PersonalAccessToken `thrift:"personal_access_token,1,required" json:"personal_access_token"`
	Token               string               `thrift:"token,2,required" json:"token"`
}

func NewCreatePersonalAccessTokenAndPermissionResponseData() *CreatePersonalAccessTokenAndPermissionResponseData {
	return &CreatePersonalAccessTokenAndPermissionResponseData{}
}

func (p *CreatePersonalAccessTokenAndPermissionResponseData) InitDefault() {
}

var CreatePersonalAccessTokenAndPermissionResponseData_PersonalAccessToken_DEFAULT *PersonalAccessToken

func (p *CreatePersonalAccessTokenAndPermissionResponseData) GetPersonalAccessToken() (v *PersonalAccessToken) {
	if !p.IsSetPersonalAccessToken() {
		return CreatePersonalAccessTokenAndPermissionResponseData_PersonalAccessToken_DEFAULT
	}
	return p.PersonalAccessToken
}

func (p *CreatePersonalAccessTokenAndPermissionResponseData) GetToken() (v string) {
	return p.Token
}
func (p *CreatePersonalAccessTokenAndPermissionResponseData) SetPersonalAccessToken(val *PersonalAccessToken) {
	p.PersonalAccessToken = val
}
func (p *CreatePersonalAccessTokenAndPermissionResponseData) SetToken(val string) {
	p.Token = val
}

func (p *CreatePersonalAccessTokenAndPermissionResponseData) IsSetPersonalAccessToken() bool {
	return p.PersonalAccessToken != nil
}

func (p *CreatePersonalAccessTokenAndPermissionResponseData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePersonalAccessTokenAndPermissionResponseData(%+v)", *p)
}

type CreatePersonalAccessTokenAndPermissionResponse struct {
	Data *CreatePersonalAccessTokenAndPermissionResponseData `thrift:"data,1,required" json:"data"`
	Code int32                                               `thrift:"code,2,required" json:"code"`
	Msg  string                                              `thrift:"msg,3,required" json:"msg"`
}

func NewCreatePersonalAccessTokenAndPermissionResponse() *CreatePersonalAccessTokenAndPermissionResponse {
	return &CreatePersonalAccessTokenAndPermissionResponse{}
}

func (p *CreatePersonalAccessTokenAndPermissionResponse) InitDefault() {
}

var CreatePersonalAccessTokenAndPermissionResponse_Data_DEFAULT *CreatePersonalAccessTokenAndPermissionResponseData

func (p *CreatePersonalAccessTokenAndPermissionResponse) GetData() (v *CreatePersonalAccessTokenAndPermissionResponseData) {
	if !p.IsSetData() {
		return CreatePersonalAccessTokenAndPermissionResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *CreatePersonalAccessTokenAndPermissionResponse) GetCode() (v int32) {
	return p.Code
}

func (p *CreatePersonalAccessTokenAndPermissionResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *CreatePersonalAccessTokenAndPermissionResponse) SetData(val *CreatePersonalAccessTokenAndPermissionResponseData) {
	p.Data = val
}
func (p *CreatePersonalAccessTokenAndPermissionResponse) SetCode(val int32) {
	p.Code = val
}
func (p *CreatePersonalAccessTokenAndPermissionResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *CreatePersonalAccessTokenAndPermissionResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *CreatePersonalAccessTokenAndPermissionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePersonalAccessTokenAndPermissionResponse(%+v)", *p)
}

type ListPersonalAccessTokensRequest struct {
	OrganizationID *string          `thrift:"organization_id,1,optional" json:"organization_id,omitempty"`
	Page           *int64           `thrift:"page,2,optional" json:"page,omitempty"`
	Size           *int64           `thrift:"size,3,optional" json:"size,omitempty"`
	SearchOption   *PatSearchOption `thrift:"search_option,4,optional" json:"search_option,omitempty"`
}

func NewListPersonalAccessTokensRequest() *ListPersonalAccessTokensRequest {
	return &ListPersonalAccessTokensRequest{}
}

func (p *ListPersonalAccessTokensRequest) InitDefault() {
}

var ListPersonalAccessTokensRequest_OrganizationID_DEFAULT string

func (p *ListPersonalAccessTokensRequest) GetOrganizationID() (v string) {
	if !p.IsSetOrganizationID() {
		return ListPersonalAccessTokensRequest_OrganizationID_DEFAULT
	}
	return *p.OrganizationID
}

var ListPersonalAccessTokensRequest_Page_DEFAULT int64

func (p *ListPersonalAccessTokensRequest) GetPage() (v int64) {
	if !p.IsSetPage() {
		return ListPersonalAccessTokensRequest_Page_DEFAULT
	}
	return *p.Page
}

var ListPersonalAccessTokensRequest_Size_DEFAULT int64

func (p *ListPersonalAccessTokensRequest) GetSize() (v int64) {
	if !p.IsSetSize() {
		return ListPersonalAccessTokensRequest_Size_DEFAULT
	}
	return *p.Size
}

var ListPersonalAccessTokensRequest_SearchOption_DEFAULT PatSearchOption

func (p *ListPersonalAccessTokensRequest) GetSearchOption() (v PatSearchOption) {
	if !p.IsSetSearchOption() {
		return ListPersonalAccessTokensRequest_SearchOption_DEFAULT
	}
	return *p.SearchOption
}
func (p *ListPersonalAccessTokensRequest) SetOrganizationID(val *string) {
	p.OrganizationID = val
}
func (p *ListPersonalAccessTokensRequest) SetPage(val *int64) {
	p.Page = val
}
func (p *ListPersonalAccessTokensRequest) SetSize(val *int64) {
	p.Size = val
}
func (p *ListPersonalAccessTokensRequest) SetSearchOption(val *PatSearchOption) {
	p.SearchOption = val
}

func (p *ListPersonalAccessTokensRequest) IsSetOrganizationID() bool {
	return p.OrganizationID != nil
}

func (p *ListPersonalAccessTokensRequest) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListPersonalAccessTokensRequest) IsSetSize() bool {
	return p.Size != nil
}

func (p *ListPersonalAccessTokensRequest) IsSetSearchOption() bool {
	return p.SearchOption != nil
}

func (p *ListPersonalAccessTokensRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPersonalAccessTokensRequest(%+v)", *p)
}

type PersonalAccessTokenWithCreatorInfo struct {
	ID                int64      `thrift:"id,1,required" json:"id"`
	Name              string     `thrift:"name,2,required" json:"name"`
	CreatedAt         int64      `thrift:"created_at,3,required" json:"created_at"`
	UpdatedAt         int64      `thrift:"updated_at,4,required" json:"updated_at"`
	LastUsedAt        int64      `thrift:"last_used_at,5,required" json:"last_used_at"`
	ExpireAt          int64      `thrift:"expire_at,6,required" json:"expire_at"`
	CreatorName       string     `thrift:"creator_name,7" json:"creator_name"`
	CreatorUniqueName string     `thrift:"creator_unique_name,8" json:"creator_unique_name"`
	CreatorAvatarURL  string     `thrift:"creator_avatar_url,9" json:"creator_avatar_url"`
	CreatorIconURL    string     `thrift:"creator_icon_url,10" json:"creator_icon_url"`
	Locked            bool       `thrift:"locked,11" json:"locked"`
	CreatorStatus     UserStatus `thrift:"creator_status,12" json:"creator_status"`
}

func NewPersonalAccessTokenWithCreatorInfo() *PersonalAccessTokenWithCreatorInfo {
	return &PersonalAccessTokenWithCreatorInfo{}
}

func (p *PersonalAccessTokenWithCreatorInfo) InitDefault() {
}

func (p *PersonalAccessTokenWithCreatorInfo) GetID() (v int64) {
	return p.ID
}

func (p *PersonalAccessTokenWithCreatorInfo) GetName() (v string) {
	return p.Name
}

func (p *PersonalAccessTokenWithCreatorInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *PersonalAccessTokenWithCreatorInfo) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

func (p *PersonalAccessTokenWithCreatorInfo) GetLastUsedAt() (v int64) {
	return p.LastUsedAt
}

func (p *PersonalAccessTokenWithCreatorInfo) GetExpireAt() (v int64) {
	return p.ExpireAt
}

func (p *PersonalAccessTokenWithCreatorInfo) GetCreatorName() (v string) {
	return p.CreatorName
}

func (p *PersonalAccessTokenWithCreatorInfo) GetCreatorUniqueName() (v string) {
	return p.CreatorUniqueName
}

func (p *PersonalAccessTokenWithCreatorInfo) GetCreatorAvatarURL() (v string) {
	return p.CreatorAvatarURL
}

func (p *PersonalAccessTokenWithCreatorInfo) GetCreatorIconURL() (v string) {
	return p.CreatorIconURL
}

func (p *PersonalAccessTokenWithCreatorInfo) GetLocked() (v bool) {
	return p.Locked
}

func (p *PersonalAccessTokenWithCreatorInfo) GetCreatorStatus() (v UserStatus) {
	return p.CreatorStatus
}
func (p *PersonalAccessTokenWithCreatorInfo) SetID(val int64) {
	p.ID = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetName(val string) {
	p.Name = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetLastUsedAt(val int64) {
	p.LastUsedAt = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetExpireAt(val int64) {
	p.ExpireAt = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetCreatorName(val string) {
	p.CreatorName = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetCreatorUniqueName(val string) {
	p.CreatorUniqueName = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetCreatorAvatarURL(val string) {
	p.CreatorAvatarURL = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetCreatorIconURL(val string) {
	p.CreatorIconURL = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetLocked(val bool) {
	p.Locked = val
}
func (p *PersonalAccessTokenWithCreatorInfo) SetCreatorStatus(val UserStatus) {
	p.CreatorStatus = val
}

func (p *PersonalAccessTokenWithCreatorInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PersonalAccessTokenWithCreatorInfo(%+v)", *p)
}

type ListPersonalAccessTokensResponse struct {
	Data *ListPersonalAccessTokensResponseData `thrift:"data,1,required" json:"data"`
	Code int32                                 `thrift:"code,2,required" json:"code"`
	Msg  string                                `thrift:"msg,3,required" json:"msg"`
}

func NewListPersonalAccessTokensResponse() *ListPersonalAccessTokensResponse {
	return &ListPersonalAccessTokensResponse{}
}

func (p *ListPersonalAccessTokensResponse) InitDefault() {
}

var ListPersonalAccessTokensResponse_Data_DEFAULT *ListPersonalAccessTokensResponseData

func (p *ListPersonalAccessTokensResponse) GetData() (v *ListPersonalAccessTokensResponseData) {
	if !p.IsSetData() {
		return ListPersonalAccessTokensResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *ListPersonalAccessTokensResponse) GetCode() (v int32) {
	return p.Code
}

func (p *ListPersonalAccessTokensResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *ListPersonalAccessTokensResponse) SetData(val *ListPersonalAccessTokensResponseData) {
	p.Data = val
}
func (p *ListPersonalAccessTokensResponse) SetCode(val int32) {
	p.Code = val
}
func (p *ListPersonalAccessTokensResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *ListPersonalAccessTokensResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *ListPersonalAccessTokensResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPersonalAccessTokensResponse(%+v)", *p)
}

type ListPersonalAccessTokensResponseData struct {
	PersonalAccessTokens []*PersonalAccessTokenWithCreatorInfo `thrift:"personal_access_tokens,1,required" json:"personal_access_tokens"`
	HasMore              bool                                  `thrift:"has_more,2" json:"has_more"`
}

func NewListPersonalAccessTokensResponseData() *ListPersonalAccessTokensResponseData {
	return &ListPersonalAccessTokensResponseData{}
}

func (p *ListPersonalAccessTokensResponseData) InitDefault() {
}

func (p *ListPersonalAccessTokensResponseData) GetPersonalAccessTokens() (v []*PersonalAccessTokenWithCreatorInfo) {
	return p.PersonalAccessTokens
}

func (p *ListPersonalAccessTokensResponseData) GetHasMore() (v bool) {
	return p.HasMore
}
func (p *ListPersonalAccessTokensResponseData) SetPersonalAccessTokens(val []*PersonalAccessTokenWithCreatorInfo) {
	p.PersonalAccessTokens = val
}
func (p *ListPersonalAccessTokensResponseData) SetHasMore(val bool) {
	p.HasMore = val
}

func (p *ListPersonalAccessTokensResponseData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPersonalAccessTokensResponseData(%+v)", *p)
}

type DeletePersonalAccessTokenAndPermissionRequest struct {
	ID int64 `thrift:"id,1,required" json:"id"`
}

func NewDeletePersonalAccessTokenAndPermissionRequest() *DeletePersonalAccessTokenAndPermissionRequest {
	return &DeletePersonalAccessTokenAndPermissionRequest{}
}

func (p *DeletePersonalAccessTokenAndPermissionRequest) InitDefault() {
}

func (p *DeletePersonalAccessTokenAndPermissionRequest) GetID() (v int64) {
	return p.ID
}
func (p *DeletePersonalAccessTokenAndPermissionRequest) SetID(val int64) {
	p.ID = val
}

func (p *DeletePersonalAccessTokenAndPermissionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeletePersonalAccessTokenAndPermissionRequest(%+v)", *p)
}

type DeletePersonalAccessTokenAndPermissionResponse struct {
	Code int32  `thrift:"code,1,required" json:"code"`
	Msg  string `thrift:"msg,2,required" json:"msg"`
}

func NewDeletePersonalAccessTokenAndPermissionResponse() *DeletePersonalAccessTokenAndPermissionResponse {
	return &DeletePersonalAccessTokenAndPermissionResponse{}
}

func (p *DeletePersonalAccessTokenAndPermissionResponse) InitDefault() {
}

func (p *DeletePersonalAccessTokenAndPermissionResponse) GetCode() (v int32) {
	return p.Code
}

func (p *DeletePersonalAccessTokenAndPermissionResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *DeletePersonalAccessTokenAndPermissionResponse) SetCode(val int32) {
	p.Code = val
}
func (p *DeletePersonalAccessTokenAndPermissionResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *DeletePersonalAccessTokenAndPermissionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeletePersonalAccessTokenAndPermissionResponse(%+v)", *p)
}

type GetPersonalAccessTokenAndPermissionRequest struct {
	ID int64 `thrift:"id,1,required" json:"id"`
}

func NewGetPersonalAccessTokenAndPermissionRequest() *GetPersonalAccessTokenAndPermissionRequest {
	return &GetPersonalAccessTokenAndPermissionRequest{}
}

func (p *GetPersonalAccessTokenAndPermissionRequest) InitDefault() {
}

func (p *GetPersonalAccessTokenAndPermissionRequest) GetID() (v int64) {
	return p.ID
}
func (p *GetPersonalAccessTokenAndPermissionRequest) SetID(val int64) {
	p.ID = val
}

func (p *GetPersonalAccessTokenAndPermissionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPersonalAccessTokenAndPermissionRequest(%+v)", *p)
}

type GetPersonalAccessTokenAndPermissionResponseData struct {
	PersonalAccessToken *PersonalAccessToken `thrift:"personal_access_token,1,required" json:"personal_access_token"`
}

func NewGetPersonalAccessTokenAndPermissionResponseData() *GetPersonalAccessTokenAndPermissionResponseData {
	return &GetPersonalAccessTokenAndPermissionResponseData{}
}

func (p *GetPersonalAccessTokenAndPermissionResponseData) InitDefault() {
}

var GetPersonalAccessTokenAndPermissionResponseData_PersonalAccessToken_DEFAULT *PersonalAccessToken

func (p *GetPersonalAccessTokenAndPermissionResponseData) GetPersonalAccessToken() (v *PersonalAccessToken) {
	if !p.IsSetPersonalAccessToken() {
		return GetPersonalAccessTokenAndPermissionResponseData_PersonalAccessToken_DEFAULT
	}
	return p.PersonalAccessToken
}
func (p *GetPersonalAccessTokenAndPermissionResponseData) SetPersonalAccessToken(val *PersonalAccessToken) {
	p.PersonalAccessToken = val
}

func (p *GetPersonalAccessTokenAndPermissionResponseData) IsSetPersonalAccessToken() bool {
	return p.PersonalAccessToken != nil
}

func (p *GetPersonalAccessTokenAndPermissionResponseData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPersonalAccessTokenAndPermissionResponseData(%+v)", *p)
}

type GetPersonalAccessTokenAndPermissionResponse struct {
	Data *GetPersonalAccessTokenAndPermissionResponseData `thrift:"data,1,required" json:"data"`
	Code int32                                            `thrift:"code,2,required" json:"code"`
	Msg  string                                           `thrift:"msg,3,required" json:"msg"`
}

func NewGetPersonalAccessTokenAndPermissionResponse() *GetPersonalAccessTokenAndPermissionResponse {
	return &GetPersonalAccessTokenAndPermissionResponse{}
}

func (p *GetPersonalAccessTokenAndPermissionResponse) InitDefault() {
}

var GetPersonalAccessTokenAndPermissionResponse_Data_DEFAULT *GetPersonalAccessTokenAndPermissionResponseData

func (p *GetPersonalAccessTokenAndPermissionResponse) GetData() (v *GetPersonalAccessTokenAndPermissionResponseData) {
	if !p.IsSetData() {
		return GetPersonalAccessTokenAndPermissionResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *GetPersonalAccessTokenAndPermissionResponse) GetCode() (v int32) {
	return p.Code
}

func (p *GetPersonalAccessTokenAndPermissionResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *GetPersonalAccessTokenAndPermissionResponse) SetData(val *GetPersonalAccessTokenAndPermissionResponseData) {
	p.Data = val
}
func (p *GetPersonalAccessTokenAndPermissionResponse) SetCode(val int32) {
	p.Code = val
}
func (p *GetPersonalAccessTokenAndPermissionResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *GetPersonalAccessTokenAndPermissionResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetPersonalAccessTokenAndPermissionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPersonalAccessTokenAndPermissionResponse(%+v)", *p)
}

type UpdatePersonalAccessTokenAndPermissionRequest struct {
	ID   int64  `thrift:"id,1,required" json:"id"`
	Name string `thrift:"name,2" json:"name"`
}

func NewUpdatePersonalAccessTokenAndPermissionRequest() *UpdatePersonalAccessTokenAndPermissionRequest {
	return &UpdatePersonalAccessTokenAndPermissionRequest{}
}

func (p *UpdatePersonalAccessTokenAndPermissionRequest) InitDefault() {
}

func (p *UpdatePersonalAccessTokenAndPermissionRequest) GetID() (v int64) {
	return p.ID
}

func (p *UpdatePersonalAccessTokenAndPermissionRequest) GetName() (v string) {
	return p.Name
}
func (p *UpdatePersonalAccessTokenAndPermissionRequest) SetID(val int64) {
	p.ID = val
}
func (p *UpdatePersonalAccessTokenAndPermissionRequest) SetName(val string) {
	p.Name = val
}

func (p *UpdatePersonalAccessTokenAndPermissionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdatePersonalAccessTokenAndPermissionRequest(%+v)", *p)
}

type UpdatePersonalAccessTokenAndPermissionResponse struct {
	Code int32  `thrift:"code,1,required" json:"code"`
	Msg  string `thrift:"msg,2,required" json:"msg"`
}

func NewUpdatePersonalAccessTokenAndPermissionResponse() *UpdatePersonalAccessTokenAndPermissionResponse {
	return &UpdatePersonalAccessTokenAndPermissionResponse{}
}

func (p *UpdatePersonalAccessTokenAndPermissionResponse) InitDefault() {
}

func (p *UpdatePersonalAccessTokenAndPermissionResponse) GetCode() (v int32) {
	return p.Code
}

func (p *UpdatePersonalAccessTokenAndPermissionResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *UpdatePersonalAccessTokenAndPermissionResponse) SetCode(val int32) {
	p.Code = val
}
func (p *UpdatePersonalAccessTokenAndPermissionResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *UpdatePersonalAccessTokenAndPermissionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdatePersonalAccessTokenAndPermissionResponse(%+v)", *p)
}
