// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package openapiauth

import (
	"context"
)

type OpenAPIAuthService interface {
	GetPersonalAccessTokenAndPermission(ctx context.Context, req *GetPersonalAccessTokenAndPermissionRequest) (r *GetPersonalAccessTokenAndPermissionResponse, err error)

	DeletePersonalAccessTokenAndPermission(ctx context.Context, req *DeletePersonalAccessTokenAndPermissionRequest) (r *DeletePersonalAccessTokenAndPermissionResponse, err error)

	ListPersonalAccessTokens(ctx context.Context, req *ListPersonalAccessTokensRequest) (r *ListPersonalAccessTokensResponse, err error)

	CreatePersonalAccessTokenAndPermission(ctx context.Context, req *CreatePersonalAccessTokenAndPermissionRequest) (r *CreatePersonalAccessTokenAndPermissionResponse, err error)

	UpdatePersonalAccessTokenAndPermission(ctx context.Context, req *UpdatePersonalAccessTokenAndPermissionRequest) (r *UpdatePersonalAccessTokenAndPermissionResponse, err error)
}
