// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "message"

// Message 消息表
type Message struct {
	ID               int64   `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                             // 主键ID
	RunID            int64   `gorm:"column:run_id;type:bigint(20) unsigned;not null;index:idx_run_id,priority:1;comment:对应的run_id" json:"run_id"`                                         // 对应的run_id
	ConversationID   int64   `gorm:"column:conversation_id;type:bigint(20) unsigned;not null;index:idx_conversation_id,priority:1;comment:conversation id" json:"conversation_id"`        // conversation id
	UserID           string  `gorm:"column:user_id;type:varchar(60);not null;comment:user id" json:"user_id"`                                                                             // user id
	AgentID          int64   `gorm:"column:agent_id;type:bigint(20) unsigned;not null;comment:agent_id" json:"agent_id"`                                                                  // agent_id
	Role             string  `gorm:"column:role;type:varchar(100);not null;comment:角色: user、assistant、system" json:"role"`                                                                // 角色: user、assistant、system
	ContentType      string  `gorm:"column:content_type;type:varchar(100);not null;comment:内容类型 1 text" json:"content_type"`                                                              // 内容类型 1 text
	Content          *string `gorm:"column:content;type:mediumtext;comment:内容" json:"content"`                                                                                            // 内容
	MessageType      string  `gorm:"column:message_type;type:varchar(100);not null;comment:消息类型：" json:"message_type"`                                                                    // 消息类型：
	DisplayContent   *string `gorm:"column:display_content;type:text;comment:展示内容" json:"display_content"`                                                                                // 展示内容
	Ext              *string `gorm:"column:ext;type:text;comment:message 扩展字段" json:"ext"`                                                                                                // message 扩展字段
	SectionID        *int64  `gorm:"column:section_id;type:bigint(20) unsigned;comment:段落id" json:"section_id"`                                                                           // 段落id
	BrokenPosition   *int32  `gorm:"column:broken_position;type:int(11);comment:打断位置" json:"broken_position"`                                                                             // 打断位置
	Status           int32   `gorm:"column:status;type:tinyint(4) unsigned;not null;comment:消息状态 1 Available 2 Deleted 3 Replaced 4 Broken 5 Failed 6 Streaming 7 Pending" json:"status"` // 消息状态 1 Available 2 Deleted 3 Replaced 4 Broken 5 Failed 6 Streaming 7 Pending
	ModelContent     *string `gorm:"column:model_content;type:mediumtext;comment:模型输入内容" json:"model_content"`                                                                            // 模型输入内容
	MetaInfo         *string `gorm:"column:meta_info;type:text;comment:引用、高亮等文本标记信息" json:"meta_info"`                                                                                    // 引用、高亮等文本标记信息
	ReasoningContent *string `gorm:"column:reasoning_content;type:text;comment:思考内容" json:"reasoning_content"`                                                                            // 思考内容
	CreatedAt        int64   `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:创建时间" json:"created_at"`                                                                  // 创建时间
	UpdatedAt        int64   `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:更新时间" json:"updated_at"`                                                                  // 更新时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
