// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package common

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ResType int64

const (
	ResType_Plugin    ResType = 1
	ResType_Workflow  ResType = 2
	ResType_Imageflow ResType = 3
	ResType_Knowledge ResType = 4
	ResType_UI        ResType = 5
	ResType_Prompt    ResType = 6
	ResType_Database  ResType = 7
	ResType_Variable  ResType = 8
	ResType_Voice     ResType = 9
)

func (p ResType) String() string {
	switch p {
	case ResType_Plugin:
		return "Plugin"
	case ResType_Workflow:
		return "Workflow"
	case ResType_Imageflow:
		return "Imageflow"
	case ResType_Knowledge:
		return "Knowledge"
	case ResType_UI:
		return "UI"
	case ResType_Prompt:
		return "Prompt"
	case ResType_Database:
		return "Database"
	case ResType_Variable:
		return "Variable"
	case ResType_Voice:
		return "Voice"
	}
	return "<UNSET>"
}

func ResTypeFromString(s string) (ResType, error) {
	switch s {
	case "Plugin":
		return ResType_Plugin, nil
	case "Workflow":
		return ResType_Workflow, nil
	case "Imageflow":
		return ResType_Imageflow, nil
	case "Knowledge":
		return ResType_Knowledge, nil
	case "UI":
		return ResType_UI, nil
	case "Prompt":
		return ResType_Prompt, nil
	case "Database":
		return ResType_Database, nil
	case "Variable":
		return ResType_Variable, nil
	case "Voice":
		return ResType_Voice, nil
	}
	return ResType(0), fmt.Errorf("not a valid ResType string")
}

func ResTypePtr(v ResType) *ResType { return &v }
func (p *ResType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ResType(result.Int64)
	return
}

func (p *ResType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type PublishStatus int64

const (
	PublishStatus_UnPublished PublishStatus = 1
	PublishStatus_Published   PublishStatus = 2
)

func (p PublishStatus) String() string {
	switch p {
	case PublishStatus_UnPublished:
		return "UnPublished"
	case PublishStatus_Published:
		return "Published"
	}
	return "<UNSET>"
}

func PublishStatusFromString(s string) (PublishStatus, error) {
	switch s {
	case "UnPublished":
		return PublishStatus_UnPublished, nil
	case "Published":
		return PublishStatus_Published, nil
	}
	return PublishStatus(0), fmt.Errorf("not a valid PublishStatus string")
}

func PublishStatusPtr(v PublishStatus) *PublishStatus { return &v }
func (p *PublishStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = PublishStatus(result.Int64)
	return
}

func (p *PublishStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ActionKey int64

const (
	ActionKey_Copy             ActionKey = 1
	ActionKey_Delete           ActionKey = 2
	ActionKey_EnableSwitch     ActionKey = 3
	ActionKey_Edit             ActionKey = 4
	ActionKey_SwitchToFuncflow ActionKey = 8
	ActionKey_SwitchToChatflow ActionKey = 9
)

func (p ActionKey) String() string {
	switch p {
	case ActionKey_Copy:
		return "Copy"
	case ActionKey_Delete:
		return "Delete"
	case ActionKey_EnableSwitch:
		return "EnableSwitch"
	case ActionKey_Edit:
		return "Edit"
	case ActionKey_SwitchToFuncflow:
		return "SwitchToFuncflow"
	case ActionKey_SwitchToChatflow:
		return "SwitchToChatflow"
	}
	return "<UNSET>"
}

func ActionKeyFromString(s string) (ActionKey, error) {
	switch s {
	case "Copy":
		return ActionKey_Copy, nil
	case "Delete":
		return ActionKey_Delete, nil
	case "EnableSwitch":
		return ActionKey_EnableSwitch, nil
	case "Edit":
		return ActionKey_Edit, nil
	case "SwitchToFuncflow":
		return ActionKey_SwitchToFuncflow, nil
	case "SwitchToChatflow":
		return ActionKey_SwitchToChatflow, nil
	}
	return ActionKey(0), fmt.Errorf("not a valid ActionKey string")
}

func ActionKeyPtr(v ActionKey) *ActionKey { return &v }
func (p *ActionKey) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ActionKey(result.Int64)
	return
}

func (p *ActionKey) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ProjectResourceActionKey int64

const (
	ProjectResourceActionKey_Rename           ProjectResourceActionKey = 1
	ProjectResourceActionKey_Copy             ProjectResourceActionKey = 2
	ProjectResourceActionKey_CopyToLibrary    ProjectResourceActionKey = 3
	ProjectResourceActionKey_MoveToLibrary    ProjectResourceActionKey = 4
	ProjectResourceActionKey_Delete           ProjectResourceActionKey = 5
	ProjectResourceActionKey_Enable           ProjectResourceActionKey = 6
	ProjectResourceActionKey_Disable          ProjectResourceActionKey = 7
	ProjectResourceActionKey_SwitchToFuncflow ProjectResourceActionKey = 8
	ProjectResourceActionKey_SwitchToChatflow ProjectResourceActionKey = 9
	ProjectResourceActionKey_UpdateDesc       ProjectResourceActionKey = 10
)

func (p ProjectResourceActionKey) String() string {
	switch p {
	case ProjectResourceActionKey_Rename:
		return "Rename"
	case ProjectResourceActionKey_Copy:
		return "Copy"
	case ProjectResourceActionKey_CopyToLibrary:
		return "CopyToLibrary"
	case ProjectResourceActionKey_MoveToLibrary:
		return "MoveToLibrary"
	case ProjectResourceActionKey_Delete:
		return "Delete"
	case ProjectResourceActionKey_Enable:
		return "Enable"
	case ProjectResourceActionKey_Disable:
		return "Disable"
	case ProjectResourceActionKey_SwitchToFuncflow:
		return "SwitchToFuncflow"
	case ProjectResourceActionKey_SwitchToChatflow:
		return "SwitchToChatflow"
	case ProjectResourceActionKey_UpdateDesc:
		return "UpdateDesc"
	}
	return "<UNSET>"
}

func ProjectResourceActionKeyFromString(s string) (ProjectResourceActionKey, error) {
	switch s {
	case "Rename":
		return ProjectResourceActionKey_Rename, nil
	case "Copy":
		return ProjectResourceActionKey_Copy, nil
	case "CopyToLibrary":
		return ProjectResourceActionKey_CopyToLibrary, nil
	case "MoveToLibrary":
		return ProjectResourceActionKey_MoveToLibrary, nil
	case "Delete":
		return ProjectResourceActionKey_Delete, nil
	case "Enable":
		return ProjectResourceActionKey_Enable, nil
	case "Disable":
		return ProjectResourceActionKey_Disable, nil
	case "SwitchToFuncflow":
		return ProjectResourceActionKey_SwitchToFuncflow, nil
	case "SwitchToChatflow":
		return ProjectResourceActionKey_SwitchToChatflow, nil
	case "UpdateDesc":
		return ProjectResourceActionKey_UpdateDesc, nil
	}
	return ProjectResourceActionKey(0), fmt.Errorf("not a valid ProjectResourceActionKey string")
}

func ProjectResourceActionKeyPtr(v ProjectResourceActionKey) *ProjectResourceActionKey { return &v }
func (p *ProjectResourceActionKey) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ProjectResourceActionKey(result.Int64)
	return
}

func (p *ProjectResourceActionKey) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ProjectResourceGroupType int64

const (
	ProjectResourceGroupType_Workflow ProjectResourceGroupType = 1
	ProjectResourceGroupType_Plugin   ProjectResourceGroupType = 2
	ProjectResourceGroupType_Data     ProjectResourceGroupType = 3
)

func (p ProjectResourceGroupType) String() string {
	switch p {
	case ProjectResourceGroupType_Workflow:
		return "Workflow"
	case ProjectResourceGroupType_Plugin:
		return "Plugin"
	case ProjectResourceGroupType_Data:
		return "Data"
	}
	return "<UNSET>"
}

func ProjectResourceGroupTypeFromString(s string) (ProjectResourceGroupType, error) {
	switch s {
	case "Workflow":
		return ProjectResourceGroupType_Workflow, nil
	case "Plugin":
		return ProjectResourceGroupType_Plugin, nil
	case "Data":
		return ProjectResourceGroupType_Data, nil
	}
	return ProjectResourceGroupType(0), fmt.Errorf("not a valid ProjectResourceGroupType string")
}

func ProjectResourceGroupTypePtr(v ProjectResourceGroupType) *ProjectResourceGroupType { return &v }
func (p *ProjectResourceGroupType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ProjectResourceGroupType(result.Int64)
	return
}

func (p *ProjectResourceGroupType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ResourceCopyScene int64

const (
	ResourceCopyScene_CopyProjectResource     ResourceCopyScene = 1
	ResourceCopyScene_CopyResourceToLibrary   ResourceCopyScene = 2
	ResourceCopyScene_MoveResourceToLibrary   ResourceCopyScene = 3
	ResourceCopyScene_CopyResourceFromLibrary ResourceCopyScene = 4
	ResourceCopyScene_CopyProject             ResourceCopyScene = 5
	ResourceCopyScene_PublishProject          ResourceCopyScene = 6
	ResourceCopyScene_CopyProjectTemplate     ResourceCopyScene = 7
	ResourceCopyScene_PublishProjectTemplate  ResourceCopyScene = 8
	ResourceCopyScene_LaunchTemplate          ResourceCopyScene = 9
	ResourceCopyScene_ArchiveProject          ResourceCopyScene = 10
	ResourceCopyScene_RollbackProject         ResourceCopyScene = 11
)

func (p ResourceCopyScene) String() string {
	switch p {
	case ResourceCopyScene_CopyProjectResource:
		return "CopyProjectResource"
	case ResourceCopyScene_CopyResourceToLibrary:
		return "CopyResourceToLibrary"
	case ResourceCopyScene_MoveResourceToLibrary:
		return "MoveResourceToLibrary"
	case ResourceCopyScene_CopyResourceFromLibrary:
		return "CopyResourceFromLibrary"
	case ResourceCopyScene_CopyProject:
		return "CopyProject"
	case ResourceCopyScene_PublishProject:
		return "PublishProject"
	case ResourceCopyScene_CopyProjectTemplate:
		return "CopyProjectTemplate"
	case ResourceCopyScene_PublishProjectTemplate:
		return "PublishProjectTemplate"
	case ResourceCopyScene_LaunchTemplate:
		return "LaunchTemplate"
	case ResourceCopyScene_ArchiveProject:
		return "ArchiveProject"
	case ResourceCopyScene_RollbackProject:
		return "RollbackProject"
	}
	return "<UNSET>"
}

func ResourceCopySceneFromString(s string) (ResourceCopyScene, error) {
	switch s {
	case "CopyProjectResource":
		return ResourceCopyScene_CopyProjectResource, nil
	case "CopyResourceToLibrary":
		return ResourceCopyScene_CopyResourceToLibrary, nil
	case "MoveResourceToLibrary":
		return ResourceCopyScene_MoveResourceToLibrary, nil
	case "CopyResourceFromLibrary":
		return ResourceCopyScene_CopyResourceFromLibrary, nil
	case "CopyProject":
		return ResourceCopyScene_CopyProject, nil
	case "PublishProject":
		return ResourceCopyScene_PublishProject, nil
	case "CopyProjectTemplate":
		return ResourceCopyScene_CopyProjectTemplate, nil
	case "PublishProjectTemplate":
		return ResourceCopyScene_PublishProjectTemplate, nil
	case "LaunchTemplate":
		return ResourceCopyScene_LaunchTemplate, nil
	case "ArchiveProject":
		return ResourceCopyScene_ArchiveProject, nil
	case "RollbackProject":
		return ResourceCopyScene_RollbackProject, nil
	}
	return ResourceCopyScene(0), fmt.Errorf("not a valid ResourceCopyScene string")
}

func ResourceCopyScenePtr(v ResourceCopyScene) *ResourceCopyScene { return &v }
func (p *ResourceCopyScene) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ResourceCopyScene(result.Int64)
	return
}

func (p *ResourceCopyScene) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TaskStatus int64

const (
	TaskStatus_Successed  TaskStatus = 1
	TaskStatus_Processing TaskStatus = 2
	TaskStatus_Failed     TaskStatus = 3
	TaskStatus_Canceled   TaskStatus = 4
)

func (p TaskStatus) String() string {
	switch p {
	case TaskStatus_Successed:
		return "Successed"
	case TaskStatus_Processing:
		return "Processing"
	case TaskStatus_Failed:
		return "Failed"
	case TaskStatus_Canceled:
		return "Canceled"
	}
	return "<UNSET>"
}

func TaskStatusFromString(s string) (TaskStatus, error) {
	switch s {
	case "Successed":
		return TaskStatus_Successed, nil
	case "Processing":
		return TaskStatus_Processing, nil
	case "Failed":
		return TaskStatus_Failed, nil
	case "Canceled":
		return TaskStatus_Canceled, nil
	}
	return TaskStatus(0), fmt.Errorf("not a valid TaskStatus string")
}

func TaskStatusPtr(v TaskStatus) *TaskStatus { return &v }
func (p *TaskStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TaskStatus(result.Int64)
	return
}

func (p *TaskStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ResourceAction struct {
	Key    ActionKey `thrift:"Key,1,required,ActionKey" json:"key"`
	Enable bool      `thrift:"Enable,2,required" json:"enable"`
}

func NewResourceAction() *ResourceAction {
	return &ResourceAction{}
}

func (p *ResourceAction) InitDefault() {
}

func (p *ResourceAction) GetKey() (v ActionKey) {
	return p.Key
}

func (p *ResourceAction) GetEnable() (v bool) {
	return p.Enable
}
func (p *ResourceAction) SetKey(val ActionKey) {
	p.Key = val
}
func (p *ResourceAction) SetEnable(val bool) {
	p.Enable = val
}

func (p *ResourceAction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResourceAction(%+v)", *p)
}

type ResourceInfo struct {
	ResID               *int64            `thrift:"ResID,1,optional" json:"ResID,omitempty"`
	ResType             *ResType          `thrift:"ResType,2,optional,ResType" json:"res_type"`
	ResSubType          *int32            `thrift:"ResSubType,3,optional" json:"res_sub_type"`
	Name                *string           `thrift:"Name,4,optional" json:"name"`
	Desc                *string           `thrift:"Desc,5,optional" json:"desc"`
	Icon                *string           `thrift:"Icon,6,optional" json:"icon"`
	CreatorID           *int64            `thrift:"CreatorID,7,optional" json:"CreatorID,omitempty"`
	CreatorAvatar       *string           `thrift:"CreatorAvatar,8,optional" json:"creator_avatar"`
	CreatorName         *string           `thrift:"CreatorName,9,optional" json:"creator_name"`
	UserName            *string           `thrift:"UserName,10,optional" json:"user_name"`
	PublishStatus       *PublishStatus    `thrift:"PublishStatus,11,optional,PublishStatus" json:"publish_status"`
	BizResStatus        *int32            `thrift:"BizResStatus,12,optional" json:"biz_res_status"`
	CollaborationEnable *bool             `thrift:"CollaborationEnable,13,optional" json:"collaboration_enable"`
	EditTime            *int64            `thrift:"EditTime,14,optional" json:"EditTime,omitempty"`
	SpaceID             *int64            `thrift:"SpaceID,15,optional" json:"SpaceID,omitempty"`
	BizExtend           map[string]string `thrift:"BizExtend,16,optional" json:"biz_extend"`
	Actions             []*ResourceAction `thrift:"Actions,17,optional,list<ResourceAction>" json:"actions"`
	DetailDisable       *bool             `thrift:"DetailDisable,18,optional" json:"detail_disable"`
	DelFlag             *bool             `thrift:"DelFlag,19,optional" json:"del_flag"`
}

func NewResourceInfo() *ResourceInfo {
	return &ResourceInfo{}
}

func (p *ResourceInfo) InitDefault() {
}

var ResourceInfo_ResID_DEFAULT int64

func (p *ResourceInfo) GetResID() (v int64) {
	if !p.IsSetResID() {
		return ResourceInfo_ResID_DEFAULT
	}
	return *p.ResID
}

var ResourceInfo_ResType_DEFAULT ResType

func (p *ResourceInfo) GetResType() (v ResType) {
	if !p.IsSetResType() {
		return ResourceInfo_ResType_DEFAULT
	}
	return *p.ResType
}

var ResourceInfo_ResSubType_DEFAULT int32

func (p *ResourceInfo) GetResSubType() (v int32) {
	if !p.IsSetResSubType() {
		return ResourceInfo_ResSubType_DEFAULT
	}
	return *p.ResSubType
}

var ResourceInfo_Name_DEFAULT string

func (p *ResourceInfo) GetName() (v string) {
	if !p.IsSetName() {
		return ResourceInfo_Name_DEFAULT
	}
	return *p.Name
}

var ResourceInfo_Desc_DEFAULT string

func (p *ResourceInfo) GetDesc() (v string) {
	if !p.IsSetDesc() {
		return ResourceInfo_Desc_DEFAULT
	}
	return *p.Desc
}

var ResourceInfo_Icon_DEFAULT string

func (p *ResourceInfo) GetIcon() (v string) {
	if !p.IsSetIcon() {
		return ResourceInfo_Icon_DEFAULT
	}
	return *p.Icon
}

var ResourceInfo_CreatorID_DEFAULT int64

func (p *ResourceInfo) GetCreatorID() (v int64) {
	if !p.IsSetCreatorID() {
		return ResourceInfo_CreatorID_DEFAULT
	}
	return *p.CreatorID
}

var ResourceInfo_CreatorAvatar_DEFAULT string

func (p *ResourceInfo) GetCreatorAvatar() (v string) {
	if !p.IsSetCreatorAvatar() {
		return ResourceInfo_CreatorAvatar_DEFAULT
	}
	return *p.CreatorAvatar
}

var ResourceInfo_CreatorName_DEFAULT string

func (p *ResourceInfo) GetCreatorName() (v string) {
	if !p.IsSetCreatorName() {
		return ResourceInfo_CreatorName_DEFAULT
	}
	return *p.CreatorName
}

var ResourceInfo_UserName_DEFAULT string

func (p *ResourceInfo) GetUserName() (v string) {
	if !p.IsSetUserName() {
		return ResourceInfo_UserName_DEFAULT
	}
	return *p.UserName
}

var ResourceInfo_PublishStatus_DEFAULT PublishStatus

func (p *ResourceInfo) GetPublishStatus() (v PublishStatus) {
	if !p.IsSetPublishStatus() {
		return ResourceInfo_PublishStatus_DEFAULT
	}
	return *p.PublishStatus
}

var ResourceInfo_BizResStatus_DEFAULT int32

func (p *ResourceInfo) GetBizResStatus() (v int32) {
	if !p.IsSetBizResStatus() {
		return ResourceInfo_BizResStatus_DEFAULT
	}
	return *p.BizResStatus
}

var ResourceInfo_CollaborationEnable_DEFAULT bool

func (p *ResourceInfo) GetCollaborationEnable() (v bool) {
	if !p.IsSetCollaborationEnable() {
		return ResourceInfo_CollaborationEnable_DEFAULT
	}
	return *p.CollaborationEnable
}

var ResourceInfo_EditTime_DEFAULT int64

func (p *ResourceInfo) GetEditTime() (v int64) {
	if !p.IsSetEditTime() {
		return ResourceInfo_EditTime_DEFAULT
	}
	return *p.EditTime
}

var ResourceInfo_SpaceID_DEFAULT int64

func (p *ResourceInfo) GetSpaceID() (v int64) {
	if !p.IsSetSpaceID() {
		return ResourceInfo_SpaceID_DEFAULT
	}
	return *p.SpaceID
}

var ResourceInfo_BizExtend_DEFAULT map[string]string

func (p *ResourceInfo) GetBizExtend() (v map[string]string) {
	if !p.IsSetBizExtend() {
		return ResourceInfo_BizExtend_DEFAULT
	}
	return p.BizExtend
}

var ResourceInfo_Actions_DEFAULT []*ResourceAction

func (p *ResourceInfo) GetActions() (v []*ResourceAction) {
	if !p.IsSetActions() {
		return ResourceInfo_Actions_DEFAULT
	}
	return p.Actions
}

var ResourceInfo_DetailDisable_DEFAULT bool

func (p *ResourceInfo) GetDetailDisable() (v bool) {
	if !p.IsSetDetailDisable() {
		return ResourceInfo_DetailDisable_DEFAULT
	}
	return *p.DetailDisable
}

var ResourceInfo_DelFlag_DEFAULT bool

func (p *ResourceInfo) GetDelFlag() (v bool) {
	if !p.IsSetDelFlag() {
		return ResourceInfo_DelFlag_DEFAULT
	}
	return *p.DelFlag
}
func (p *ResourceInfo) SetResID(val *int64) {
	p.ResID = val
}
func (p *ResourceInfo) SetResType(val *ResType) {
	p.ResType = val
}
func (p *ResourceInfo) SetResSubType(val *int32) {
	p.ResSubType = val
}
func (p *ResourceInfo) SetName(val *string) {
	p.Name = val
}
func (p *ResourceInfo) SetDesc(val *string) {
	p.Desc = val
}
func (p *ResourceInfo) SetIcon(val *string) {
	p.Icon = val
}
func (p *ResourceInfo) SetCreatorID(val *int64) {
	p.CreatorID = val
}
func (p *ResourceInfo) SetCreatorAvatar(val *string) {
	p.CreatorAvatar = val
}
func (p *ResourceInfo) SetCreatorName(val *string) {
	p.CreatorName = val
}
func (p *ResourceInfo) SetUserName(val *string) {
	p.UserName = val
}
func (p *ResourceInfo) SetPublishStatus(val *PublishStatus) {
	p.PublishStatus = val
}
func (p *ResourceInfo) SetBizResStatus(val *int32) {
	p.BizResStatus = val
}
func (p *ResourceInfo) SetCollaborationEnable(val *bool) {
	p.CollaborationEnable = val
}
func (p *ResourceInfo) SetEditTime(val *int64) {
	p.EditTime = val
}
func (p *ResourceInfo) SetSpaceID(val *int64) {
	p.SpaceID = val
}
func (p *ResourceInfo) SetBizExtend(val map[string]string) {
	p.BizExtend = val
}
func (p *ResourceInfo) SetActions(val []*ResourceAction) {
	p.Actions = val
}
func (p *ResourceInfo) SetDetailDisable(val *bool) {
	p.DetailDisable = val
}
func (p *ResourceInfo) SetDelFlag(val *bool) {
	p.DelFlag = val
}

func (p *ResourceInfo) IsSetResID() bool {
	return p.ResID != nil
}

func (p *ResourceInfo) IsSetResType() bool {
	return p.ResType != nil
}

func (p *ResourceInfo) IsSetResSubType() bool {
	return p.ResSubType != nil
}

func (p *ResourceInfo) IsSetName() bool {
	return p.Name != nil
}

func (p *ResourceInfo) IsSetDesc() bool {
	return p.Desc != nil
}

func (p *ResourceInfo) IsSetIcon() bool {
	return p.Icon != nil
}

func (p *ResourceInfo) IsSetCreatorID() bool {
	return p.CreatorID != nil
}

func (p *ResourceInfo) IsSetCreatorAvatar() bool {
	return p.CreatorAvatar != nil
}

func (p *ResourceInfo) IsSetCreatorName() bool {
	return p.CreatorName != nil
}

func (p *ResourceInfo) IsSetUserName() bool {
	return p.UserName != nil
}

func (p *ResourceInfo) IsSetPublishStatus() bool {
	return p.PublishStatus != nil
}

func (p *ResourceInfo) IsSetBizResStatus() bool {
	return p.BizResStatus != nil
}

func (p *ResourceInfo) IsSetCollaborationEnable() bool {
	return p.CollaborationEnable != nil
}

func (p *ResourceInfo) IsSetEditTime() bool {
	return p.EditTime != nil
}

func (p *ResourceInfo) IsSetSpaceID() bool {
	return p.SpaceID != nil
}

func (p *ResourceInfo) IsSetBizExtend() bool {
	return p.BizExtend != nil
}

func (p *ResourceInfo) IsSetActions() bool {
	return p.Actions != nil
}

func (p *ResourceInfo) IsSetDetailDisable() bool {
	return p.DetailDisable != nil
}

func (p *ResourceInfo) IsSetDelFlag() bool {
	return p.DelFlag != nil
}

func (p *ResourceInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResourceInfo(%+v)", *p)
}

type ProjectResourceAction struct {
	Key    ProjectResourceActionKey `thrift:"Key,1,required,ProjectResourceActionKey" json:"key"`
	Enable bool                     `thrift:"Enable,2,required" json:"enable"`
	Hint   *string                  `thrift:"Hint,3,optional" json:"hint"`
}

func NewProjectResourceAction() *ProjectResourceAction {
	return &ProjectResourceAction{}
}

func (p *ProjectResourceAction) InitDefault() {
}

func (p *ProjectResourceAction) GetKey() (v ProjectResourceActionKey) {
	return p.Key
}

func (p *ProjectResourceAction) GetEnable() (v bool) {
	return p.Enable
}

var ProjectResourceAction_Hint_DEFAULT string

func (p *ProjectResourceAction) GetHint() (v string) {
	if !p.IsSetHint() {
		return ProjectResourceAction_Hint_DEFAULT
	}
	return *p.Hint
}
func (p *ProjectResourceAction) SetKey(val ProjectResourceActionKey) {
	p.Key = val
}
func (p *ProjectResourceAction) SetEnable(val bool) {
	p.Enable = val
}
func (p *ProjectResourceAction) SetHint(val *string) {
	p.Hint = val
}

func (p *ProjectResourceAction) IsSetHint() bool {
	return p.Hint != nil
}

func (p *ProjectResourceAction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProjectResourceAction(%+v)", *p)
}

type ProjectResourceInfo struct {
	ResID        int64                    `thrift:"ResID,1" json:"ResID"`
	Name         string                   `thrift:"Name,2" json:"name"`
	Actions      []*ProjectResourceAction `thrift:"Actions,3,default,list<ProjectResourceAction>" json:"actions"`
	ResType      ResType                  `thrift:"ResType,5,default,ResType" json:"res_type"`
	ResSubType   *int32                   `thrift:"ResSubType,6,optional" json:"res_sub_type"`
	BizExtend    map[string]string        `thrift:"BizExtend,7,optional" json:"biz_extend"`
	BizResStatus *int32                   `thrift:"BizResStatus,8,optional" json:"biz_res_status"`
	VersionStr   *string                  `thrift:"VersionStr,9,optional" json:"version_str"`
}

func NewProjectResourceInfo() *ProjectResourceInfo {
	return &ProjectResourceInfo{}
}

func (p *ProjectResourceInfo) InitDefault() {
}

func (p *ProjectResourceInfo) GetResID() (v int64) {
	return p.ResID
}

func (p *ProjectResourceInfo) GetName() (v string) {
	return p.Name
}

func (p *ProjectResourceInfo) GetActions() (v []*ProjectResourceAction) {
	return p.Actions
}

func (p *ProjectResourceInfo) GetResType() (v ResType) {
	return p.ResType
}

var ProjectResourceInfo_ResSubType_DEFAULT int32

func (p *ProjectResourceInfo) GetResSubType() (v int32) {
	if !p.IsSetResSubType() {
		return ProjectResourceInfo_ResSubType_DEFAULT
	}
	return *p.ResSubType
}

var ProjectResourceInfo_BizExtend_DEFAULT map[string]string

func (p *ProjectResourceInfo) GetBizExtend() (v map[string]string) {
	if !p.IsSetBizExtend() {
		return ProjectResourceInfo_BizExtend_DEFAULT
	}
	return p.BizExtend
}

var ProjectResourceInfo_BizResStatus_DEFAULT int32

func (p *ProjectResourceInfo) GetBizResStatus() (v int32) {
	if !p.IsSetBizResStatus() {
		return ProjectResourceInfo_BizResStatus_DEFAULT
	}
	return *p.BizResStatus
}

var ProjectResourceInfo_VersionStr_DEFAULT string

func (p *ProjectResourceInfo) GetVersionStr() (v string) {
	if !p.IsSetVersionStr() {
		return ProjectResourceInfo_VersionStr_DEFAULT
	}
	return *p.VersionStr
}
func (p *ProjectResourceInfo) SetResID(val int64) {
	p.ResID = val
}
func (p *ProjectResourceInfo) SetName(val string) {
	p.Name = val
}
func (p *ProjectResourceInfo) SetActions(val []*ProjectResourceAction) {
	p.Actions = val
}
func (p *ProjectResourceInfo) SetResType(val ResType) {
	p.ResType = val
}
func (p *ProjectResourceInfo) SetResSubType(val *int32) {
	p.ResSubType = val
}
func (p *ProjectResourceInfo) SetBizExtend(val map[string]string) {
	p.BizExtend = val
}
func (p *ProjectResourceInfo) SetBizResStatus(val *int32) {
	p.BizResStatus = val
}
func (p *ProjectResourceInfo) SetVersionStr(val *string) {
	p.VersionStr = val
}

func (p *ProjectResourceInfo) IsSetResSubType() bool {
	return p.ResSubType != nil
}

func (p *ProjectResourceInfo) IsSetBizExtend() bool {
	return p.BizExtend != nil
}

func (p *ProjectResourceInfo) IsSetBizResStatus() bool {
	return p.BizResStatus != nil
}

func (p *ProjectResourceInfo) IsSetVersionStr() bool {
	return p.VersionStr != nil
}

func (p *ProjectResourceInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProjectResourceInfo(%+v)", *p)
}

type ProjectResourceGroup struct {
	GroupType    ProjectResourceGroupType `thrift:"GroupType,1,default,ProjectResourceGroupType" json:"group_type"`
	ResourceList []*ProjectResourceInfo   `thrift:"ResourceList,2,optional,list<ProjectResourceInfo>" json:"resource_list"`
}

func NewProjectResourceGroup() *ProjectResourceGroup {
	return &ProjectResourceGroup{}
}

func (p *ProjectResourceGroup) InitDefault() {
}

func (p *ProjectResourceGroup) GetGroupType() (v ProjectResourceGroupType) {
	return p.GroupType
}

var ProjectResourceGroup_ResourceList_DEFAULT []*ProjectResourceInfo

func (p *ProjectResourceGroup) GetResourceList() (v []*ProjectResourceInfo) {
	if !p.IsSetResourceList() {
		return ProjectResourceGroup_ResourceList_DEFAULT
	}
	return p.ResourceList
}
func (p *ProjectResourceGroup) SetGroupType(val ProjectResourceGroupType) {
	p.GroupType = val
}
func (p *ProjectResourceGroup) SetResourceList(val []*ProjectResourceInfo) {
	p.ResourceList = val
}

func (p *ProjectResourceGroup) IsSetResourceList() bool {
	return p.ResourceList != nil
}

func (p *ProjectResourceGroup) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProjectResourceGroup(%+v)", *p)
}

type ResourceCopyFailedReason struct {
	ResID             int64   `thrift:"ResID,1" json:"ResID"`
	ResType           ResType `thrift:"ResType,2,default,ResType" json:"res_type"`
	ResName           string  `thrift:"ResName,3" json:"res_name"`
	Reason            string  `thrift:"Reason,4" json:"reason"`
	PublishVersion    *int64  `thrift:"PublishVersion,5,optional" json:"publish_version"`
	PublishVersionStr *string `thrift:"PublishVersionStr,6,optional" json:"publish_version_str"`
}

func NewResourceCopyFailedReason() *ResourceCopyFailedReason {
	return &ResourceCopyFailedReason{}
}

func (p *ResourceCopyFailedReason) InitDefault() {
}

func (p *ResourceCopyFailedReason) GetResID() (v int64) {
	return p.ResID
}

func (p *ResourceCopyFailedReason) GetResType() (v ResType) {
	return p.ResType
}

func (p *ResourceCopyFailedReason) GetResName() (v string) {
	return p.ResName
}

func (p *ResourceCopyFailedReason) GetReason() (v string) {
	return p.Reason
}

var ResourceCopyFailedReason_PublishVersion_DEFAULT int64

func (p *ResourceCopyFailedReason) GetPublishVersion() (v int64) {
	if !p.IsSetPublishVersion() {
		return ResourceCopyFailedReason_PublishVersion_DEFAULT
	}
	return *p.PublishVersion
}

var ResourceCopyFailedReason_PublishVersionStr_DEFAULT string

func (p *ResourceCopyFailedReason) GetPublishVersionStr() (v string) {
	if !p.IsSetPublishVersionStr() {
		return ResourceCopyFailedReason_PublishVersionStr_DEFAULT
	}
	return *p.PublishVersionStr
}
func (p *ResourceCopyFailedReason) SetResID(val int64) {
	p.ResID = val
}
func (p *ResourceCopyFailedReason) SetResType(val ResType) {
	p.ResType = val
}
func (p *ResourceCopyFailedReason) SetResName(val string) {
	p.ResName = val
}
func (p *ResourceCopyFailedReason) SetReason(val string) {
	p.Reason = val
}
func (p *ResourceCopyFailedReason) SetPublishVersion(val *int64) {
	p.PublishVersion = val
}
func (p *ResourceCopyFailedReason) SetPublishVersionStr(val *string) {
	p.PublishVersionStr = val
}

func (p *ResourceCopyFailedReason) IsSetPublishVersion() bool {
	return p.PublishVersion != nil
}

func (p *ResourceCopyFailedReason) IsSetPublishVersionStr() bool {
	return p.PublishVersionStr != nil
}

func (p *ResourceCopyFailedReason) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResourceCopyFailedReason(%+v)", *p)
}

type ResourceCopyTaskDetail struct {
	TaskID  string            `thrift:"task_id,1" json:"task_id"`
	Status  TaskStatus        `thrift:"status,2,default,TaskStatus" json:"status"`
	ResID   int64             `thrift:"res_id,3" json:"res_id"`
	ResType ResType           `thrift:"res_type,4,default,ResType" json:"res_type"`
	Scene   ResourceCopyScene `thrift:"scene,5,default,ResourceCopyScene" json:"scene"`
	ResName *string           `thrift:"res_name,6,optional" json:"res_name,omitempty"`
}

func NewResourceCopyTaskDetail() *ResourceCopyTaskDetail {
	return &ResourceCopyTaskDetail{}
}

func (p *ResourceCopyTaskDetail) InitDefault() {
}

func (p *ResourceCopyTaskDetail) GetTaskID() (v string) {
	return p.TaskID
}

func (p *ResourceCopyTaskDetail) GetStatus() (v TaskStatus) {
	return p.Status
}

func (p *ResourceCopyTaskDetail) GetResID() (v int64) {
	return p.ResID
}

func (p *ResourceCopyTaskDetail) GetResType() (v ResType) {
	return p.ResType
}

func (p *ResourceCopyTaskDetail) GetScene() (v ResourceCopyScene) {
	return p.Scene
}

var ResourceCopyTaskDetail_ResName_DEFAULT string

func (p *ResourceCopyTaskDetail) GetResName() (v string) {
	if !p.IsSetResName() {
		return ResourceCopyTaskDetail_ResName_DEFAULT
	}
	return *p.ResName
}
func (p *ResourceCopyTaskDetail) SetTaskID(val string) {
	p.TaskID = val
}
func (p *ResourceCopyTaskDetail) SetStatus(val TaskStatus) {
	p.Status = val
}
func (p *ResourceCopyTaskDetail) SetResID(val int64) {
	p.ResID = val
}
func (p *ResourceCopyTaskDetail) SetResType(val ResType) {
	p.ResType = val
}
func (p *ResourceCopyTaskDetail) SetScene(val ResourceCopyScene) {
	p.Scene = val
}
func (p *ResourceCopyTaskDetail) SetResName(val *string) {
	p.ResName = val
}

func (p *ResourceCopyTaskDetail) IsSetResName() bool {
	return p.ResName != nil
}

func (p *ResourceCopyTaskDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResourceCopyTaskDetail(%+v)", *p)
}
