// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package message

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/kiosk404/airi-go/backend/api/model/base"
	"github.com/kiosk404/airi-go/backend/api/model/conversation/common"
)

const (
	OrderByDesc = "DESC"

	OrderByAsc = "ASC"
)

type LoadDirection int64

const (
	LoadDirection_Unknown LoadDirection = 0
	LoadDirection_Prev    LoadDirection = 1
	LoadDirection_Next    LoadDirection = 2
)

func (p LoadDirection) String() string {
	switch p {
	case LoadDirection_Unknown:
		return "Unknown"
	case LoadDirection_Prev:
		return "Prev"
	case LoadDirection_Next:
		return "Next"
	}
	return "<UNSET>"
}

func LoadDirectionFromString(s string) (LoadDirection, error) {
	switch s {
	case "Unknown":
		return LoadDirection_Unknown, nil
	case "Prev":
		return LoadDirection_Prev, nil
	case "Next":
		return LoadDirection_Next, nil
	}
	return LoadDirection(0), fmt.Errorf("not a valid LoadDirection string")
}

func LoadDirectionPtr(v LoadDirection) *LoadDirection { return &v }
func (p *LoadDirection) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = LoadDirection(result.Int64)
	return
}

func (p *LoadDirection) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type MsgParticipantType int64

const (
	MsgParticipantType_Bot  MsgParticipantType = 1
	MsgParticipantType_User MsgParticipantType = 2
)

func (p MsgParticipantType) String() string {
	switch p {
	case MsgParticipantType_Bot:
		return "Bot"
	case MsgParticipantType_User:
		return "User"
	}
	return "<UNSET>"
}

func MsgParticipantTypeFromString(s string) (MsgParticipantType, error) {
	switch s {
	case "Bot":
		return MsgParticipantType_Bot, nil
	case "User":
		return MsgParticipantType_User, nil
	}
	return MsgParticipantType(0), fmt.Errorf("not a valid MsgParticipantType string")
}

func MsgParticipantTypePtr(v MsgParticipantType) *MsgParticipantType { return &v }
func (p *MsgParticipantType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = MsgParticipantType(result.Int64)
	return
}

func (p *MsgParticipantType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ChatMessageMetaType int64

const (
	ChatMessageMetaType_Default_0          ChatMessageMetaType = 0
	ChatMessageMetaType_Replaceable        ChatMessageMetaType = 1
	ChatMessageMetaType_Insertable         ChatMessageMetaType = 2
	ChatMessageMetaType_DocumentRef        ChatMessageMetaType = 3
	ChatMessageMetaType_KnowledgeCard      ChatMessageMetaType = 4
	ChatMessageMetaType_EmbeddedMultimedia ChatMessageMetaType = 100
)

func (p ChatMessageMetaType) String() string {
	switch p {
	case ChatMessageMetaType_Default_0:
		return "Default_0"
	case ChatMessageMetaType_Replaceable:
		return "Replaceable"
	case ChatMessageMetaType_Insertable:
		return "Insertable"
	case ChatMessageMetaType_DocumentRef:
		return "DocumentRef"
	case ChatMessageMetaType_KnowledgeCard:
		return "KnowledgeCard"
	case ChatMessageMetaType_EmbeddedMultimedia:
		return "EmbeddedMultimedia"
	}
	return "<UNSET>"
}

func ChatMessageMetaTypeFromString(s string) (ChatMessageMetaType, error) {
	switch s {
	case "Default_0":
		return ChatMessageMetaType_Default_0, nil
	case "Replaceable":
		return ChatMessageMetaType_Replaceable, nil
	case "Insertable":
		return ChatMessageMetaType_Insertable, nil
	case "DocumentRef":
		return ChatMessageMetaType_DocumentRef, nil
	case "KnowledgeCard":
		return ChatMessageMetaType_KnowledgeCard, nil
	case "EmbeddedMultimedia":
		return ChatMessageMetaType_EmbeddedMultimedia, nil
	}
	return ChatMessageMetaType(0), fmt.Errorf("not a valid ChatMessageMetaType string")
}

func ChatMessageMetaTypePtr(v ChatMessageMetaType) *ChatMessageMetaType { return &v }
func (p *ChatMessageMetaType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ChatMessageMetaType(result.Int64)
	return
}

func (p *ChatMessageMetaType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ExtraInfo struct {
	LocalMessageID      string `thrift:"local_message_id,1" json:"local_message_id"`
	InputTokens         string `thrift:"input_tokens,2" json:"input_tokens"`
	OutputTokens        string `thrift:"output_tokens,3" json:"output_tokens"`
	Token               string `thrift:"token,4" json:"token"`
	PluginStatus        string `thrift:"plugin_status,5" json:"plugin_status"`
	TimeCost            string `thrift:"time_cost,6" json:"time_cost"`
	WorkflowTokens      string `thrift:"workflow_tokens,7" json:"workflow_tokens"`
	BotState            string `thrift:"bot_state,8" json:"bot_state"`
	PluginRequest       string `thrift:"plugin_request,9" json:"plugin_request"`
	ToolName            string `thrift:"tool_name,10" json:"tool_name"`
	Plugin              string `thrift:"plugin,11" json:"plugin"`
	MockHitInfo         string `thrift:"mock_hit_info,12" json:"mock_hit_info"`
	LogID               string `thrift:"log_id,13" json:"log_id"`
	StreamID            string `thrift:"stream_id,14" json:"stream_id"`
	MessageTitle        string `thrift:"message_title,15" json:"message_title"`
	StreamPluginRunning string `thrift:"stream_plugin_running,16" json:"stream_plugin_running"`
	NewSectionID        string `thrift:"new_section_id,17" json:"new_section_id"`
	RemoveQueryID       string `thrift:"remove_query_id,18" json:"remove_query_id"`
	ExecuteDisplayName  string `thrift:"execute_display_name,19" json:"execute_display_name"`
	TaskType            string `thrift:"task_type,20" json:"task_type"`
	ReferFormat         string `thrift:"refer_format,21" json:"refer_format"`
	CallID              string `thrift:"call_id,22" json:"call_id"`
}

func NewExtraInfo() *ExtraInfo {
	return &ExtraInfo{}
}

func (p *ExtraInfo) InitDefault() {
}

func (p *ExtraInfo) GetLocalMessageID() (v string) {
	return p.LocalMessageID
}

func (p *ExtraInfo) GetInputTokens() (v string) {
	return p.InputTokens
}

func (p *ExtraInfo) GetOutputTokens() (v string) {
	return p.OutputTokens
}

func (p *ExtraInfo) GetToken() (v string) {
	return p.Token
}

func (p *ExtraInfo) GetPluginStatus() (v string) {
	return p.PluginStatus
}

func (p *ExtraInfo) GetTimeCost() (v string) {
	return p.TimeCost
}

func (p *ExtraInfo) GetWorkflowTokens() (v string) {
	return p.WorkflowTokens
}

func (p *ExtraInfo) GetBotState() (v string) {
	return p.BotState
}

func (p *ExtraInfo) GetPluginRequest() (v string) {
	return p.PluginRequest
}

func (p *ExtraInfo) GetToolName() (v string) {
	return p.ToolName
}

func (p *ExtraInfo) GetPlugin() (v string) {
	return p.Plugin
}

func (p *ExtraInfo) GetMockHitInfo() (v string) {
	return p.MockHitInfo
}

func (p *ExtraInfo) GetLogID() (v string) {
	return p.LogID
}

func (p *ExtraInfo) GetStreamID() (v string) {
	return p.StreamID
}

func (p *ExtraInfo) GetMessageTitle() (v string) {
	return p.MessageTitle
}

func (p *ExtraInfo) GetStreamPluginRunning() (v string) {
	return p.StreamPluginRunning
}

func (p *ExtraInfo) GetNewSectionID() (v string) {
	return p.NewSectionID
}

func (p *ExtraInfo) GetRemoveQueryID() (v string) {
	return p.RemoveQueryID
}

func (p *ExtraInfo) GetExecuteDisplayName() (v string) {
	return p.ExecuteDisplayName
}

func (p *ExtraInfo) GetTaskType() (v string) {
	return p.TaskType
}

func (p *ExtraInfo) GetReferFormat() (v string) {
	return p.ReferFormat
}

func (p *ExtraInfo) GetCallID() (v string) {
	return p.CallID
}
func (p *ExtraInfo) SetLocalMessageID(val string) {
	p.LocalMessageID = val
}
func (p *ExtraInfo) SetInputTokens(val string) {
	p.InputTokens = val
}
func (p *ExtraInfo) SetOutputTokens(val string) {
	p.OutputTokens = val
}
func (p *ExtraInfo) SetToken(val string) {
	p.Token = val
}
func (p *ExtraInfo) SetPluginStatus(val string) {
	p.PluginStatus = val
}
func (p *ExtraInfo) SetTimeCost(val string) {
	p.TimeCost = val
}
func (p *ExtraInfo) SetWorkflowTokens(val string) {
	p.WorkflowTokens = val
}
func (p *ExtraInfo) SetBotState(val string) {
	p.BotState = val
}
func (p *ExtraInfo) SetPluginRequest(val string) {
	p.PluginRequest = val
}
func (p *ExtraInfo) SetToolName(val string) {
	p.ToolName = val
}
func (p *ExtraInfo) SetPlugin(val string) {
	p.Plugin = val
}
func (p *ExtraInfo) SetMockHitInfo(val string) {
	p.MockHitInfo = val
}
func (p *ExtraInfo) SetLogID(val string) {
	p.LogID = val
}
func (p *ExtraInfo) SetStreamID(val string) {
	p.StreamID = val
}
func (p *ExtraInfo) SetMessageTitle(val string) {
	p.MessageTitle = val
}
func (p *ExtraInfo) SetStreamPluginRunning(val string) {
	p.StreamPluginRunning = val
}
func (p *ExtraInfo) SetNewSectionID(val string) {
	p.NewSectionID = val
}
func (p *ExtraInfo) SetRemoveQueryID(val string) {
	p.RemoveQueryID = val
}
func (p *ExtraInfo) SetExecuteDisplayName(val string) {
	p.ExecuteDisplayName = val
}
func (p *ExtraInfo) SetTaskType(val string) {
	p.TaskType = val
}
func (p *ExtraInfo) SetReferFormat(val string) {
	p.ReferFormat = val
}
func (p *ExtraInfo) SetCallID(val string) {
	p.CallID = val
}

func (p *ExtraInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExtraInfo(%+v)", *p)
}

type MsgParticipantInfo struct {
	ID           string             `thrift:"id,1" json:"id"`
	Type         MsgParticipantType `thrift:"type,2,default,MsgParticipantType" json:"type"`
	Name         string             `thrift:"name,3" json:"name"`
	Desc         string             `thrift:"desc,4" json:"desc"`
	AvatarURL    string             `thrift:"avatar_url,5" json:"avatar_url"`
	UserID       string             `thrift:"user_id,6" json:"user_id"`
	UserName     string             `thrift:"user_name,7" json:"user_name"`
	AllowMention bool               `thrift:"allow_mention,8" json:"allow_mention"`
	AccessPath   string             `thrift:"access_path,9" json:"access_path"`
	IsFav        bool               `thrift:"is_fav,12" json:"is_fav"`
	AllowShare   bool               `thrift:"allow_share,13" json:"allow_share"`
}

func NewMsgParticipantInfo() *MsgParticipantInfo {
	return &MsgParticipantInfo{}
}

func (p *MsgParticipantInfo) InitDefault() {
}

func (p *MsgParticipantInfo) GetID() (v string) {
	return p.ID
}

func (p *MsgParticipantInfo) GetType() (v MsgParticipantType) {
	return p.Type
}

func (p *MsgParticipantInfo) GetName() (v string) {
	return p.Name
}

func (p *MsgParticipantInfo) GetDesc() (v string) {
	return p.Desc
}

func (p *MsgParticipantInfo) GetAvatarURL() (v string) {
	return p.AvatarURL
}

func (p *MsgParticipantInfo) GetUserID() (v string) {
	return p.UserID
}

func (p *MsgParticipantInfo) GetUserName() (v string) {
	return p.UserName
}

func (p *MsgParticipantInfo) GetAllowMention() (v bool) {
	return p.AllowMention
}

func (p *MsgParticipantInfo) GetAccessPath() (v string) {
	return p.AccessPath
}

func (p *MsgParticipantInfo) GetIsFav() (v bool) {
	return p.IsFav
}

func (p *MsgParticipantInfo) GetAllowShare() (v bool) {
	return p.AllowShare
}
func (p *MsgParticipantInfo) SetID(val string) {
	p.ID = val
}
func (p *MsgParticipantInfo) SetType(val MsgParticipantType) {
	p.Type = val
}
func (p *MsgParticipantInfo) SetName(val string) {
	p.Name = val
}
func (p *MsgParticipantInfo) SetDesc(val string) {
	p.Desc = val
}
func (p *MsgParticipantInfo) SetAvatarURL(val string) {
	p.AvatarURL = val
}
func (p *MsgParticipantInfo) SetUserID(val string) {
	p.UserID = val
}
func (p *MsgParticipantInfo) SetUserName(val string) {
	p.UserName = val
}
func (p *MsgParticipantInfo) SetAllowMention(val bool) {
	p.AllowMention = val
}
func (p *MsgParticipantInfo) SetAccessPath(val string) {
	p.AccessPath = val
}
func (p *MsgParticipantInfo) SetIsFav(val bool) {
	p.IsFav = val
}
func (p *MsgParticipantInfo) SetAllowShare(val bool) {
	p.AllowShare = val
}

func (p *MsgParticipantInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgParticipantInfo(%+v)", *p)
}

type InterruptPlugin struct {
	ID   string `thrift:"id,1" json:"id"`
	Type string `thrift:"type,2" json:"type"`
}

func NewInterruptPlugin() *InterruptPlugin {
	return &InterruptPlugin{}
}

func (p *InterruptPlugin) InitDefault() {
}

func (p *InterruptPlugin) GetID() (v string) {
	return p.ID
}

func (p *InterruptPlugin) GetType() (v string) {
	return p.Type
}
func (p *InterruptPlugin) SetID(val string) {
	p.ID = val
}
func (p *InterruptPlugin) SetType(val string) {
	p.Type = val
}

func (p *InterruptPlugin) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterruptPlugin(%+v)", *p)
}

type SubmitToolOutputs struct {
	ToolCalls []*InterruptPlugin `thrift:"tool_calls,1,default,list<InterruptPlugin>" json:"tool_calls"`
}

func NewSubmitToolOutputs() *SubmitToolOutputs {
	return &SubmitToolOutputs{}
}

func (p *SubmitToolOutputs) InitDefault() {
}

func (p *SubmitToolOutputs) GetToolCalls() (v []*InterruptPlugin) {
	return p.ToolCalls
}
func (p *SubmitToolOutputs) SetToolCalls(val []*InterruptPlugin) {
	p.ToolCalls = val
}

func (p *SubmitToolOutputs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubmitToolOutputs(%+v)", *p)
}

type RequiredAction struct {
	Type              string             `thrift:"type,1" json:"type"`
	SubmitToolOutputs *SubmitToolOutputs `thrift:"submit_tool_outputs,2" json:"submit_tool_outputs"`
}

func NewRequiredAction() *RequiredAction {
	return &RequiredAction{}
}

func (p *RequiredAction) InitDefault() {
}

func (p *RequiredAction) GetType() (v string) {
	return p.Type
}

var RequiredAction_SubmitToolOutputs_DEFAULT *SubmitToolOutputs

func (p *RequiredAction) GetSubmitToolOutputs() (v *SubmitToolOutputs) {
	if !p.IsSetSubmitToolOutputs() {
		return RequiredAction_SubmitToolOutputs_DEFAULT
	}
	return p.SubmitToolOutputs
}
func (p *RequiredAction) SetType(val string) {
	p.Type = val
}
func (p *RequiredAction) SetSubmitToolOutputs(val *SubmitToolOutputs) {
	p.SubmitToolOutputs = val
}

func (p *RequiredAction) IsSetSubmitToolOutputs() bool {
	return p.SubmitToolOutputs != nil
}

func (p *RequiredAction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequiredAction(%+v)", *p)
}

type ChatMessageMetaInfo struct {
	Type ChatMessageMetaType `thrift:"type,1,default,ChatMessageMetaType" json:"type"`
	Info string              `thrift:"info,2" json:"info"`
}

func NewChatMessageMetaInfo() *ChatMessageMetaInfo {
	return &ChatMessageMetaInfo{}
}

func (p *ChatMessageMetaInfo) InitDefault() {
}

func (p *ChatMessageMetaInfo) GetType() (v ChatMessageMetaType) {
	return p.Type
}

func (p *ChatMessageMetaInfo) GetInfo() (v string) {
	return p.Info
}
func (p *ChatMessageMetaInfo) SetType(val ChatMessageMetaType) {
	p.Type = val
}
func (p *ChatMessageMetaInfo) SetInfo(val string) {
	p.Info = val
}

func (p *ChatMessageMetaInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatMessageMetaInfo(%+v)", *p)
}

type ChatMessage struct {
	Role             string                 `thrift:"role,1" json:"role"`
	Type             string                 `thrift:"type,2" json:"type"`
	Content          string                 `thrift:"content,3" json:"content"`
	ContentType      string                 `thrift:"content_type,4" json:"content_type"`
	MessageID        string                 `thrift:"message_id,5" json:"message_id"`
	ReplyID          string                 `thrift:"reply_id,6" json:"reply_id"`
	SectionID        string                 `thrift:"section_id,7" json:"section_id"`
	ExtraInfo        *ExtraInfo             `thrift:"extra_info,8" json:"extra_info"`
	Status           string                 `thrift:"status,9" json:"status"`
	BrokenPos        *int32                 `thrift:"broken_pos,10,optional" json:"broken_pos,omitempty"`
	SenderID         *string                `thrift:"sender_id,11,optional" json:"sender_id,omitempty"`
	MentionList      []*MsgParticipantInfo  `thrift:"mention_list,12,optional,list<MsgParticipantInfo>" json:"mention_list,omitempty"`
	ContentTime      int64                  `thrift:"content_time,13" json:"content_time"`
	MessageIndex     int64                  `thrift:"message_index,14" json:"message_index,string"`
	Source           int32                  `thrift:"source,15" json:"source"`
	ReplyMessage     *ChatMessage           `thrift:"reply_message,16,optional" json:"reply_message,omitempty"`
	RequiredAction   *RequiredAction        `thrift:"required_action,17,optional" json:"required_action,omitempty"`
	MetaInfos        []*ChatMessageMetaInfo `thrift:"meta_infos,18,optional,list<ChatMessageMetaInfo>" json:"meta_infos,omitempty"`
	CardStatus       map[string]string      `thrift:"card_status,19,optional" json:"card_status,omitempty"`
	ReasoningContent *string                `thrift:"reasoning_content,20,optional" json:"reasoning_content,omitempty"`
}

func NewChatMessage() *ChatMessage {
	return &ChatMessage{}
}

func (p *ChatMessage) InitDefault() {
}

func (p *ChatMessage) GetRole() (v string) {
	return p.Role
}

func (p *ChatMessage) GetType() (v string) {
	return p.Type
}

func (p *ChatMessage) GetContent() (v string) {
	return p.Content
}

func (p *ChatMessage) GetContentType() (v string) {
	return p.ContentType
}

func (p *ChatMessage) GetMessageID() (v string) {
	return p.MessageID
}

func (p *ChatMessage) GetReplyID() (v string) {
	return p.ReplyID
}

func (p *ChatMessage) GetSectionID() (v string) {
	return p.SectionID
}

var ChatMessage_ExtraInfo_DEFAULT *ExtraInfo

func (p *ChatMessage) GetExtraInfo() (v *ExtraInfo) {
	if !p.IsSetExtraInfo() {
		return ChatMessage_ExtraInfo_DEFAULT
	}
	return p.ExtraInfo
}

func (p *ChatMessage) GetStatus() (v string) {
	return p.Status
}

var ChatMessage_BrokenPos_DEFAULT int32

func (p *ChatMessage) GetBrokenPos() (v int32) {
	if !p.IsSetBrokenPos() {
		return ChatMessage_BrokenPos_DEFAULT
	}
	return *p.BrokenPos
}

var ChatMessage_SenderID_DEFAULT string

func (p *ChatMessage) GetSenderID() (v string) {
	if !p.IsSetSenderID() {
		return ChatMessage_SenderID_DEFAULT
	}
	return *p.SenderID
}

var ChatMessage_MentionList_DEFAULT []*MsgParticipantInfo

func (p *ChatMessage) GetMentionList() (v []*MsgParticipantInfo) {
	if !p.IsSetMentionList() {
		return ChatMessage_MentionList_DEFAULT
	}
	return p.MentionList
}

func (p *ChatMessage) GetContentTime() (v int64) {
	return p.ContentTime
}

func (p *ChatMessage) GetMessageIndex() (v int64) {
	return p.MessageIndex
}

func (p *ChatMessage) GetSource() (v int32) {
	return p.Source
}

var ChatMessage_ReplyMessage_DEFAULT *ChatMessage

func (p *ChatMessage) GetReplyMessage() (v *ChatMessage) {
	if !p.IsSetReplyMessage() {
		return ChatMessage_ReplyMessage_DEFAULT
	}
	return p.ReplyMessage
}

var ChatMessage_RequiredAction_DEFAULT *RequiredAction

func (p *ChatMessage) GetRequiredAction() (v *RequiredAction) {
	if !p.IsSetRequiredAction() {
		return ChatMessage_RequiredAction_DEFAULT
	}
	return p.RequiredAction
}

var ChatMessage_MetaInfos_DEFAULT []*ChatMessageMetaInfo

func (p *ChatMessage) GetMetaInfos() (v []*ChatMessageMetaInfo) {
	if !p.IsSetMetaInfos() {
		return ChatMessage_MetaInfos_DEFAULT
	}
	return p.MetaInfos
}

var ChatMessage_CardStatus_DEFAULT map[string]string

func (p *ChatMessage) GetCardStatus() (v map[string]string) {
	if !p.IsSetCardStatus() {
		return ChatMessage_CardStatus_DEFAULT
	}
	return p.CardStatus
}

var ChatMessage_ReasoningContent_DEFAULT string

func (p *ChatMessage) GetReasoningContent() (v string) {
	if !p.IsSetReasoningContent() {
		return ChatMessage_ReasoningContent_DEFAULT
	}
	return *p.ReasoningContent
}
func (p *ChatMessage) SetRole(val string) {
	p.Role = val
}
func (p *ChatMessage) SetType(val string) {
	p.Type = val
}
func (p *ChatMessage) SetContent(val string) {
	p.Content = val
}
func (p *ChatMessage) SetContentType(val string) {
	p.ContentType = val
}
func (p *ChatMessage) SetMessageID(val string) {
	p.MessageID = val
}
func (p *ChatMessage) SetReplyID(val string) {
	p.ReplyID = val
}
func (p *ChatMessage) SetSectionID(val string) {
	p.SectionID = val
}
func (p *ChatMessage) SetExtraInfo(val *ExtraInfo) {
	p.ExtraInfo = val
}
func (p *ChatMessage) SetStatus(val string) {
	p.Status = val
}
func (p *ChatMessage) SetBrokenPos(val *int32) {
	p.BrokenPos = val
}
func (p *ChatMessage) SetSenderID(val *string) {
	p.SenderID = val
}
func (p *ChatMessage) SetMentionList(val []*MsgParticipantInfo) {
	p.MentionList = val
}
func (p *ChatMessage) SetContentTime(val int64) {
	p.ContentTime = val
}
func (p *ChatMessage) SetMessageIndex(val int64) {
	p.MessageIndex = val
}
func (p *ChatMessage) SetSource(val int32) {
	p.Source = val
}
func (p *ChatMessage) SetReplyMessage(val *ChatMessage) {
	p.ReplyMessage = val
}
func (p *ChatMessage) SetRequiredAction(val *RequiredAction) {
	p.RequiredAction = val
}
func (p *ChatMessage) SetMetaInfos(val []*ChatMessageMetaInfo) {
	p.MetaInfos = val
}
func (p *ChatMessage) SetCardStatus(val map[string]string) {
	p.CardStatus = val
}
func (p *ChatMessage) SetReasoningContent(val *string) {
	p.ReasoningContent = val
}

func (p *ChatMessage) IsSetExtraInfo() bool {
	return p.ExtraInfo != nil
}

func (p *ChatMessage) IsSetBrokenPos() bool {
	return p.BrokenPos != nil
}

func (p *ChatMessage) IsSetSenderID() bool {
	return p.SenderID != nil
}

func (p *ChatMessage) IsSetMentionList() bool {
	return p.MentionList != nil
}

func (p *ChatMessage) IsSetReplyMessage() bool {
	return p.ReplyMessage != nil
}

func (p *ChatMessage) IsSetRequiredAction() bool {
	return p.RequiredAction != nil
}

func (p *ChatMessage) IsSetMetaInfos() bool {
	return p.MetaInfos != nil
}

func (p *ChatMessage) IsSetCardStatus() bool {
	return p.CardStatus != nil
}

func (p *ChatMessage) IsSetReasoningContent() bool {
	return p.ReasoningContent != nil
}

func (p *ChatMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatMessage(%+v)", *p)
}

type GetMessageListRequest struct {
	ConversationID           string         `thrift:"conversation_id,1" json:"conversation_id"`
	Cursor                   string         `thrift:"cursor,2,required" json:"cursor"`
	Count                    int32          `thrift:"count,3,required" json:"count"`
	BotID                    string         `thrift:"bot_id,4" json:"bot_id"`
	DraftMode                *bool          `thrift:"draft_mode,5,optional" json:"draft_mode,omitempty"`
	PresetBot                *string        `thrift:"preset_bot,6,optional" json:"preset_bot,omitempty"`
	Scene                    *common.Scene  `thrift:"scene,7,optional,Scene" json:"scene,omitempty"`
	BizKind                  *string        `thrift:"biz_kind,8,optional" json:"biz_kind,omitempty"`
	InsertHistoryMessageList []string       `thrift:"insert_history_message_list,9,optional,list<string>" json:"insert_history_message_list,omitempty"`
	LoadDirection            *LoadDirection `thrift:"load_direction,10,optional,LoadDirection" json:"load_direction,omitempty"`
	MustAppend               *bool          `thrift:"must_append,11,optional" json:"must_append,omitempty"`
	ShareID                  *int64         `thrift:"share_id,12,optional" json:"share_id,string"`
}

func NewGetMessageListRequest() *GetMessageListRequest {
	return &GetMessageListRequest{}
}

func (p *GetMessageListRequest) InitDefault() {
}

func (p *GetMessageListRequest) GetConversationID() (v string) {
	return p.ConversationID
}

func (p *GetMessageListRequest) GetCursor() (v string) {
	return p.Cursor
}

func (p *GetMessageListRequest) GetCount() (v int32) {
	return p.Count
}

func (p *GetMessageListRequest) GetBotID() (v string) {
	return p.BotID
}

var GetMessageListRequest_DraftMode_DEFAULT bool

func (p *GetMessageListRequest) GetDraftMode() (v bool) {
	if !p.IsSetDraftMode() {
		return GetMessageListRequest_DraftMode_DEFAULT
	}
	return *p.DraftMode
}

var GetMessageListRequest_PresetBot_DEFAULT string

func (p *GetMessageListRequest) GetPresetBot() (v string) {
	if !p.IsSetPresetBot() {
		return GetMessageListRequest_PresetBot_DEFAULT
	}
	return *p.PresetBot
}

var GetMessageListRequest_Scene_DEFAULT common.Scene

func (p *GetMessageListRequest) GetScene() (v common.Scene) {
	if !p.IsSetScene() {
		return GetMessageListRequest_Scene_DEFAULT
	}
	return *p.Scene
}

var GetMessageListRequest_BizKind_DEFAULT string

func (p *GetMessageListRequest) GetBizKind() (v string) {
	if !p.IsSetBizKind() {
		return GetMessageListRequest_BizKind_DEFAULT
	}
	return *p.BizKind
}

var GetMessageListRequest_InsertHistoryMessageList_DEFAULT []string

func (p *GetMessageListRequest) GetInsertHistoryMessageList() (v []string) {
	if !p.IsSetInsertHistoryMessageList() {
		return GetMessageListRequest_InsertHistoryMessageList_DEFAULT
	}
	return p.InsertHistoryMessageList
}

var GetMessageListRequest_LoadDirection_DEFAULT LoadDirection

func (p *GetMessageListRequest) GetLoadDirection() (v LoadDirection) {
	if !p.IsSetLoadDirection() {
		return GetMessageListRequest_LoadDirection_DEFAULT
	}
	return *p.LoadDirection
}

var GetMessageListRequest_MustAppend_DEFAULT bool

func (p *GetMessageListRequest) GetMustAppend() (v bool) {
	if !p.IsSetMustAppend() {
		return GetMessageListRequest_MustAppend_DEFAULT
	}
	return *p.MustAppend
}

var GetMessageListRequest_ShareID_DEFAULT int64

func (p *GetMessageListRequest) GetShareID() (v int64) {
	if !p.IsSetShareID() {
		return GetMessageListRequest_ShareID_DEFAULT
	}
	return *p.ShareID
}
func (p *GetMessageListRequest) SetConversationID(val string) {
	p.ConversationID = val
}
func (p *GetMessageListRequest) SetCursor(val string) {
	p.Cursor = val
}
func (p *GetMessageListRequest) SetCount(val int32) {
	p.Count = val
}
func (p *GetMessageListRequest) SetBotID(val string) {
	p.BotID = val
}
func (p *GetMessageListRequest) SetDraftMode(val *bool) {
	p.DraftMode = val
}
func (p *GetMessageListRequest) SetPresetBot(val *string) {
	p.PresetBot = val
}
func (p *GetMessageListRequest) SetScene(val *common.Scene) {
	p.Scene = val
}
func (p *GetMessageListRequest) SetBizKind(val *string) {
	p.BizKind = val
}
func (p *GetMessageListRequest) SetInsertHistoryMessageList(val []string) {
	p.InsertHistoryMessageList = val
}
func (p *GetMessageListRequest) SetLoadDirection(val *LoadDirection) {
	p.LoadDirection = val
}
func (p *GetMessageListRequest) SetMustAppend(val *bool) {
	p.MustAppend = val
}
func (p *GetMessageListRequest) SetShareID(val *int64) {
	p.ShareID = val
}

func (p *GetMessageListRequest) IsSetDraftMode() bool {
	return p.DraftMode != nil
}

func (p *GetMessageListRequest) IsSetPresetBot() bool {
	return p.PresetBot != nil
}

func (p *GetMessageListRequest) IsSetScene() bool {
	return p.Scene != nil
}

func (p *GetMessageListRequest) IsSetBizKind() bool {
	return p.BizKind != nil
}

func (p *GetMessageListRequest) IsSetInsertHistoryMessageList() bool {
	return p.InsertHistoryMessageList != nil
}

func (p *GetMessageListRequest) IsSetLoadDirection() bool {
	return p.LoadDirection != nil
}

func (p *GetMessageListRequest) IsSetMustAppend() bool {
	return p.MustAppend != nil
}

func (p *GetMessageListRequest) IsSetShareID() bool {
	return p.ShareID != nil
}

func (p *GetMessageListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMessageListRequest(%+v)", *p)
}

type GetMessageListResponse struct {
	MessageList             []*ChatMessage                 `thrift:"message_list,1,required,list<ChatMessage>" json:"message_list"`
	Cursor                  string                         `thrift:"cursor,2,required" json:"cursor"`
	Hasmore                 bool                           `thrift:"hasmore,3,required" json:"hasmore"`
	ConversationID          string                         `thrift:"conversation_id,4,required" json:"conversation_id"`
	LastSectionID           *string                        `thrift:"last_section_id,5,optional" json:"last_section_id,omitempty"`
	Code                    int64                          `thrift:"code,6" json:"code"`
	Msg                     string                         `thrift:"msg,7" json:"msg"`
	ParticipantInfoMap      map[string]*MsgParticipantInfo `thrift:"participant_info_map,8,optional" json:"participant_info_map,omitempty"`
	NextCursor              string                         `thrift:"next_cursor,9" json:"next_cursor"`
	NextHasMore             bool                           `thrift:"next_has_more,10" json:"next_has_more"`
	ReadMessageIndex        int64                          `thrift:"read_message_index,11" json:"read_message_index,string"`
	ConnectorConversationID string                         `thrift:"connector_conversation_id,12" json:"connector_conversation_id"`
}

func NewGetMessageListResponse() *GetMessageListResponse {
	return &GetMessageListResponse{}
}

func (p *GetMessageListResponse) InitDefault() {
}

func (p *GetMessageListResponse) GetMessageList() (v []*ChatMessage) {
	return p.MessageList
}

func (p *GetMessageListResponse) GetCursor() (v string) {
	return p.Cursor
}

func (p *GetMessageListResponse) GetHasmore() (v bool) {
	return p.Hasmore
}

func (p *GetMessageListResponse) GetConversationID() (v string) {
	return p.ConversationID
}

var GetMessageListResponse_LastSectionID_DEFAULT string

func (p *GetMessageListResponse) GetLastSectionID() (v string) {
	if !p.IsSetLastSectionID() {
		return GetMessageListResponse_LastSectionID_DEFAULT
	}
	return *p.LastSectionID
}

func (p *GetMessageListResponse) GetCode() (v int64) {
	return p.Code
}

func (p *GetMessageListResponse) GetMsg() (v string) {
	return p.Msg
}

var GetMessageListResponse_ParticipantInfoMap_DEFAULT map[string]*MsgParticipantInfo

func (p *GetMessageListResponse) GetParticipantInfoMap() (v map[string]*MsgParticipantInfo) {
	if !p.IsSetParticipantInfoMap() {
		return GetMessageListResponse_ParticipantInfoMap_DEFAULT
	}
	return p.ParticipantInfoMap
}

func (p *GetMessageListResponse) GetNextCursor() (v string) {
	return p.NextCursor
}

func (p *GetMessageListResponse) GetNextHasMore() (v bool) {
	return p.NextHasMore
}

func (p *GetMessageListResponse) GetReadMessageIndex() (v int64) {
	return p.ReadMessageIndex
}

func (p *GetMessageListResponse) GetConnectorConversationID() (v string) {
	return p.ConnectorConversationID
}
func (p *GetMessageListResponse) SetMessageList(val []*ChatMessage) {
	p.MessageList = val
}
func (p *GetMessageListResponse) SetCursor(val string) {
	p.Cursor = val
}
func (p *GetMessageListResponse) SetHasmore(val bool) {
	p.Hasmore = val
}
func (p *GetMessageListResponse) SetConversationID(val string) {
	p.ConversationID = val
}
func (p *GetMessageListResponse) SetLastSectionID(val *string) {
	p.LastSectionID = val
}
func (p *GetMessageListResponse) SetCode(val int64) {
	p.Code = val
}
func (p *GetMessageListResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *GetMessageListResponse) SetParticipantInfoMap(val map[string]*MsgParticipantInfo) {
	p.ParticipantInfoMap = val
}
func (p *GetMessageListResponse) SetNextCursor(val string) {
	p.NextCursor = val
}
func (p *GetMessageListResponse) SetNextHasMore(val bool) {
	p.NextHasMore = val
}
func (p *GetMessageListResponse) SetReadMessageIndex(val int64) {
	p.ReadMessageIndex = val
}
func (p *GetMessageListResponse) SetConnectorConversationID(val string) {
	p.ConnectorConversationID = val
}

func (p *GetMessageListResponse) IsSetLastSectionID() bool {
	return p.LastSectionID != nil
}

func (p *GetMessageListResponse) IsSetParticipantInfoMap() bool {
	return p.ParticipantInfoMap != nil
}

func (p *GetMessageListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMessageListResponse(%+v)", *p)
}

type DeleteMessageRequest struct {
	ConversationID int64         `thrift:"conversation_id,1,required" json:"conversation_id"`
	MessageID      int64         `thrift:"message_id,2,required" json:"message_id"`
	Scene          *common.Scene `thrift:"scene,3,optional,Scene" json:"scene,omitempty"`
	BotID          *int64        `thrift:"bot_id,4,optional" json:"bot_id,omitempty"`
}

func NewDeleteMessageRequest() *DeleteMessageRequest {
	return &DeleteMessageRequest{}
}

func (p *DeleteMessageRequest) InitDefault() {
}

func (p *DeleteMessageRequest) GetConversationID() (v int64) {
	return p.ConversationID
}

func (p *DeleteMessageRequest) GetMessageID() (v int64) {
	return p.MessageID
}

var DeleteMessageRequest_Scene_DEFAULT common.Scene

func (p *DeleteMessageRequest) GetScene() (v common.Scene) {
	if !p.IsSetScene() {
		return DeleteMessageRequest_Scene_DEFAULT
	}
	return *p.Scene
}

var DeleteMessageRequest_BotID_DEFAULT int64

func (p *DeleteMessageRequest) GetBotID() (v int64) {
	if !p.IsSetBotID() {
		return DeleteMessageRequest_BotID_DEFAULT
	}
	return *p.BotID
}
func (p *DeleteMessageRequest) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *DeleteMessageRequest) SetMessageID(val int64) {
	p.MessageID = val
}
func (p *DeleteMessageRequest) SetScene(val *common.Scene) {
	p.Scene = val
}
func (p *DeleteMessageRequest) SetBotID(val *int64) {
	p.BotID = val
}

func (p *DeleteMessageRequest) IsSetScene() bool {
	return p.Scene != nil
}

func (p *DeleteMessageRequest) IsSetBotID() bool {
	return p.BotID != nil
}

func (p *DeleteMessageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteMessageRequest(%+v)", *p)
}

type DeleteMessageResponse struct {
	Code int64  `thrift:"code,1" json:"code"`
	Msg  string `thrift:"msg,2" json:"msg"`
}

func NewDeleteMessageResponse() *DeleteMessageResponse {
	return &DeleteMessageResponse{}
}

func (p *DeleteMessageResponse) InitDefault() {
}

func (p *DeleteMessageResponse) GetCode() (v int64) {
	return p.Code
}

func (p *DeleteMessageResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *DeleteMessageResponse) SetCode(val int64) {
	p.Code = val
}
func (p *DeleteMessageResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *DeleteMessageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteMessageResponse(%+v)", *p)
}

type BreakMessageRequest struct {
	ConversationID  int64         `thrift:"conversation_id,1,required" json:"conversation_id"`
	QueryMessageID  int64         `thrift:"query_message_id,2,required" json:"query_message_id"`
	AnswerMessageID *int64        `thrift:"answer_message_id,3,optional" json:"answer_message_id,omitempty"`
	BrokenPos       *int32        `thrift:"broken_pos,4,optional" json:"broken_pos,omitempty"`
	Scene           *common.Scene `thrift:"scene,5,optional,Scene" json:"scene,omitempty"`
}

func NewBreakMessageRequest() *BreakMessageRequest {
	return &BreakMessageRequest{}
}

func (p *BreakMessageRequest) InitDefault() {
}

func (p *BreakMessageRequest) GetConversationID() (v int64) {
	return p.ConversationID
}

func (p *BreakMessageRequest) GetQueryMessageID() (v int64) {
	return p.QueryMessageID
}

var BreakMessageRequest_AnswerMessageID_DEFAULT int64

func (p *BreakMessageRequest) GetAnswerMessageID() (v int64) {
	if !p.IsSetAnswerMessageID() {
		return BreakMessageRequest_AnswerMessageID_DEFAULT
	}
	return *p.AnswerMessageID
}

var BreakMessageRequest_BrokenPos_DEFAULT int32

func (p *BreakMessageRequest) GetBrokenPos() (v int32) {
	if !p.IsSetBrokenPos() {
		return BreakMessageRequest_BrokenPos_DEFAULT
	}
	return *p.BrokenPos
}

var BreakMessageRequest_Scene_DEFAULT common.Scene

func (p *BreakMessageRequest) GetScene() (v common.Scene) {
	if !p.IsSetScene() {
		return BreakMessageRequest_Scene_DEFAULT
	}
	return *p.Scene
}
func (p *BreakMessageRequest) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *BreakMessageRequest) SetQueryMessageID(val int64) {
	p.QueryMessageID = val
}
func (p *BreakMessageRequest) SetAnswerMessageID(val *int64) {
	p.AnswerMessageID = val
}
func (p *BreakMessageRequest) SetBrokenPos(val *int32) {
	p.BrokenPos = val
}
func (p *BreakMessageRequest) SetScene(val *common.Scene) {
	p.Scene = val
}

func (p *BreakMessageRequest) IsSetAnswerMessageID() bool {
	return p.AnswerMessageID != nil
}

func (p *BreakMessageRequest) IsSetBrokenPos() bool {
	return p.BrokenPos != nil
}

func (p *BreakMessageRequest) IsSetScene() bool {
	return p.Scene != nil
}

func (p *BreakMessageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BreakMessageRequest(%+v)", *p)
}

type BreakMessageResponse struct {
	Code int64  `thrift:"code,1" json:"code"`
	Msg  string `thrift:"msg,2" json:"msg"`
}

func NewBreakMessageResponse() *BreakMessageResponse {
	return &BreakMessageResponse{}
}

func (p *BreakMessageResponse) InitDefault() {
}

func (p *BreakMessageResponse) GetCode() (v int64) {
	return p.Code
}

func (p *BreakMessageResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *BreakMessageResponse) SetCode(val int64) {
	p.Code = val
}
func (p *BreakMessageResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *BreakMessageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BreakMessageResponse(%+v)", *p)
}

type ListMessageApiRequest struct {
	ConversationID int64      `thrift:"conversation_id,1,required" json:"conversation_id"`
	Limit          *int64     `thrift:"limit,2,optional" json:"limit,omitempty"`
	Order          *string    `thrift:"order,3,optional" json:"order,omitempty"`
	ChatID         *int64     `thrift:"chat_id,4,optional" json:"chat_id,omitempty"`
	BeforeID       *int64     `thrift:"before_id,5,optional" json:"before_id,omitempty"`
	AfterID        *int64     `thrift:"after_id,6,optional" json:"after_id,omitempty"`
	Base           *base.Base `thrift:"Base,255" json:"Base"`
}

func NewListMessageApiRequest() *ListMessageApiRequest {
	return &ListMessageApiRequest{}
}

func (p *ListMessageApiRequest) InitDefault() {
}

func (p *ListMessageApiRequest) GetConversationID() (v int64) {
	return p.ConversationID
}

var ListMessageApiRequest_Limit_DEFAULT int64

func (p *ListMessageApiRequest) GetLimit() (v int64) {
	if !p.IsSetLimit() {
		return ListMessageApiRequest_Limit_DEFAULT
	}
	return *p.Limit
}

var ListMessageApiRequest_Order_DEFAULT string

func (p *ListMessageApiRequest) GetOrder() (v string) {
	if !p.IsSetOrder() {
		return ListMessageApiRequest_Order_DEFAULT
	}
	return *p.Order
}

var ListMessageApiRequest_ChatID_DEFAULT int64

func (p *ListMessageApiRequest) GetChatID() (v int64) {
	if !p.IsSetChatID() {
		return ListMessageApiRequest_ChatID_DEFAULT
	}
	return *p.ChatID
}

var ListMessageApiRequest_BeforeID_DEFAULT int64

func (p *ListMessageApiRequest) GetBeforeID() (v int64) {
	if !p.IsSetBeforeID() {
		return ListMessageApiRequest_BeforeID_DEFAULT
	}
	return *p.BeforeID
}

var ListMessageApiRequest_AfterID_DEFAULT int64

func (p *ListMessageApiRequest) GetAfterID() (v int64) {
	if !p.IsSetAfterID() {
		return ListMessageApiRequest_AfterID_DEFAULT
	}
	return *p.AfterID
}

var ListMessageApiRequest_Base_DEFAULT *base.Base

func (p *ListMessageApiRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ListMessageApiRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *ListMessageApiRequest) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *ListMessageApiRequest) SetLimit(val *int64) {
	p.Limit = val
}
func (p *ListMessageApiRequest) SetOrder(val *string) {
	p.Order = val
}
func (p *ListMessageApiRequest) SetChatID(val *int64) {
	p.ChatID = val
}
func (p *ListMessageApiRequest) SetBeforeID(val *int64) {
	p.BeforeID = val
}
func (p *ListMessageApiRequest) SetAfterID(val *int64) {
	p.AfterID = val
}
func (p *ListMessageApiRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *ListMessageApiRequest) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListMessageApiRequest) IsSetOrder() bool {
	return p.Order != nil
}

func (p *ListMessageApiRequest) IsSetChatID() bool {
	return p.ChatID != nil
}

func (p *ListMessageApiRequest) IsSetBeforeID() bool {
	return p.BeforeID != nil
}

func (p *ListMessageApiRequest) IsSetAfterID() bool {
	return p.AfterID != nil
}

func (p *ListMessageApiRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListMessageApiRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListMessageApiRequest(%+v)", *p)
}

type OpenMessageApi struct {
	ID               int64             `thrift:"id,1" json:"id"`
	BotID            int64             `thrift:"bot_id,2" json:"bot_id"`
	Role             string            `thrift:"role,3" json:"role"`
	Content          string            `thrift:"content,4" json:"content"`
	ConversationID   int64             `thrift:"conversation_id,5" json:"conversation_id"`
	MetaData         map[string]string `thrift:"meta_data,6" json:"meta_data"`
	CreatedAt        int64             `thrift:"created_at,7" json:"created_at"`
	UpdatedAt        int64             `thrift:"updated_at,8" json:"updated_at"`
	ChatID           int64             `thrift:"chat_id,9" json:"chat_id"`
	ContentType      string            `thrift:"content_type,10" json:"content_type"`
	Type             string            `thrift:"type,11" json:"type"`
	SectionID        string            `thrift:"section_id,12" json:"section_id"`
	ReasoningContent *string           `thrift:"reasoning_content,13,optional" json:"reasoning_content,omitempty"`
}

func NewOpenMessageApi() *OpenMessageApi {
	return &OpenMessageApi{}
}

func (p *OpenMessageApi) InitDefault() {
}

func (p *OpenMessageApi) GetID() (v int64) {
	return p.ID
}

func (p *OpenMessageApi) GetBotID() (v int64) {
	return p.BotID
}

func (p *OpenMessageApi) GetRole() (v string) {
	return p.Role
}

func (p *OpenMessageApi) GetContent() (v string) {
	return p.Content
}

func (p *OpenMessageApi) GetConversationID() (v int64) {
	return p.ConversationID
}

func (p *OpenMessageApi) GetMetaData() (v map[string]string) {
	return p.MetaData
}

func (p *OpenMessageApi) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *OpenMessageApi) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

func (p *OpenMessageApi) GetChatID() (v int64) {
	return p.ChatID
}

func (p *OpenMessageApi) GetContentType() (v string) {
	return p.ContentType
}

func (p *OpenMessageApi) GetType() (v string) {
	return p.Type
}

func (p *OpenMessageApi) GetSectionID() (v string) {
	return p.SectionID
}

var OpenMessageApi_ReasoningContent_DEFAULT string

func (p *OpenMessageApi) GetReasoningContent() (v string) {
	if !p.IsSetReasoningContent() {
		return OpenMessageApi_ReasoningContent_DEFAULT
	}
	return *p.ReasoningContent
}
func (p *OpenMessageApi) SetID(val int64) {
	p.ID = val
}
func (p *OpenMessageApi) SetBotID(val int64) {
	p.BotID = val
}
func (p *OpenMessageApi) SetRole(val string) {
	p.Role = val
}
func (p *OpenMessageApi) SetContent(val string) {
	p.Content = val
}
func (p *OpenMessageApi) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *OpenMessageApi) SetMetaData(val map[string]string) {
	p.MetaData = val
}
func (p *OpenMessageApi) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *OpenMessageApi) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *OpenMessageApi) SetChatID(val int64) {
	p.ChatID = val
}
func (p *OpenMessageApi) SetContentType(val string) {
	p.ContentType = val
}
func (p *OpenMessageApi) SetType(val string) {
	p.Type = val
}
func (p *OpenMessageApi) SetSectionID(val string) {
	p.SectionID = val
}
func (p *OpenMessageApi) SetReasoningContent(val *string) {
	p.ReasoningContent = val
}

func (p *OpenMessageApi) IsSetReasoningContent() bool {
	return p.ReasoningContent != nil
}

func (p *OpenMessageApi) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OpenMessageApi(%+v)", *p)
}

type ListMessageApiResponse struct {
	Messages []*OpenMessageApi `thrift:"messages,1,optional,list<OpenMessageApi>" json:"messages,omitempty"`
	HasMore  *bool             `thrift:"has_more,2,optional" json:"has_more,omitempty"`
	FirstID  *int64            `thrift:"first_id,3,optional" json:"first_id,omitempty"`
	LastID   *int64            `thrift:"last_id,4,optional" json:"last_id,omitempty"`
	Code     int64             `thrift:"code,253" json:"code"`
	Msg      string            `thrift:"msg,254" json:"msg"`
}

func NewListMessageApiResponse() *ListMessageApiResponse {
	return &ListMessageApiResponse{}
}

func (p *ListMessageApiResponse) InitDefault() {
}

var ListMessageApiResponse_Messages_DEFAULT []*OpenMessageApi

func (p *ListMessageApiResponse) GetMessages() (v []*OpenMessageApi) {
	if !p.IsSetMessages() {
		return ListMessageApiResponse_Messages_DEFAULT
	}
	return p.Messages
}

var ListMessageApiResponse_HasMore_DEFAULT bool

func (p *ListMessageApiResponse) GetHasMore() (v bool) {
	if !p.IsSetHasMore() {
		return ListMessageApiResponse_HasMore_DEFAULT
	}
	return *p.HasMore
}

var ListMessageApiResponse_FirstID_DEFAULT int64

func (p *ListMessageApiResponse) GetFirstID() (v int64) {
	if !p.IsSetFirstID() {
		return ListMessageApiResponse_FirstID_DEFAULT
	}
	return *p.FirstID
}

var ListMessageApiResponse_LastID_DEFAULT int64

func (p *ListMessageApiResponse) GetLastID() (v int64) {
	if !p.IsSetLastID() {
		return ListMessageApiResponse_LastID_DEFAULT
	}
	return *p.LastID
}

func (p *ListMessageApiResponse) GetCode() (v int64) {
	return p.Code
}

func (p *ListMessageApiResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *ListMessageApiResponse) SetMessages(val []*OpenMessageApi) {
	p.Messages = val
}
func (p *ListMessageApiResponse) SetHasMore(val *bool) {
	p.HasMore = val
}
func (p *ListMessageApiResponse) SetFirstID(val *int64) {
	p.FirstID = val
}
func (p *ListMessageApiResponse) SetLastID(val *int64) {
	p.LastID = val
}
func (p *ListMessageApiResponse) SetCode(val int64) {
	p.Code = val
}
func (p *ListMessageApiResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *ListMessageApiResponse) IsSetMessages() bool {
	return p.Messages != nil
}

func (p *ListMessageApiResponse) IsSetHasMore() bool {
	return p.HasMore != nil
}

func (p *ListMessageApiResponse) IsSetFirstID() bool {
	return p.FirstID != nil
}

func (p *ListMessageApiResponse) IsSetLastID() bool {
	return p.LastID != nil
}

func (p *ListMessageApiResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListMessageApiResponse(%+v)", *p)
}
