// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameModelEntity = "model_entity"

// ModelEntity 模型信息
type ModelEntity struct {
	ID            int64   `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                        // 主键ID
	MetaID        int64   `gorm:"column:meta_id;type:bigint(20) unsigned;not null;comment:模型元信息 id" json:"meta_id"`                               // 模型元信息 id
	Name          string  `gorm:"column:name;type:varchar(128);not null;comment:名称" json:"name"`                                                  // 名称
	Description   *string `gorm:"column:description;type:text;comment:描述" json:"description"`                                                     // 描述
	DefaultParams string  `gorm:"column:default_params;type:json;not null;comment:默认参数" json:"default_params"`                                    // 默认参数
	Scenario      int64   `gorm:"column:scenario;type:bigint(20) unsigned;not null;index:idx_scenario,priority:1;comment:模型应用场景" json:"scenario"` // 模型应用场景
	Status        int32   `gorm:"column:status;type:int(11);not null;index:idx_status,priority:1;default:1;comment:模型状态" json:"status"`           // 模型状态
	CreatedAt     int64   `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:Create Time in Milliseconds" json:"created_at"`      // Create Time in Milliseconds
	UpdatedAt     int64   `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:Update Time in Milliseconds" json:"updated_at"`      // Update Time in Milliseconds
	DeletedAt     *int64  `gorm:"column:deleted_at;type:bigint(20) unsigned;comment:Delete Time in Milliseconds" json:"deleted_at"`               // Delete Time in Milliseconds
}

// TableName ModelEntity's table name
func (*ModelEntity) TableName() string {
	return TableNameModelEntity
}
