// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kiosk404/airi-go/backend/modules/llm/crossdomain/llmmgr/model"
	"gorm.io/gorm"
)

const TableNameModelInstance = "model_instance"

// ModelInstance Model Instance Management Table
type ModelInstance struct {
	ID          int64                  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                                          // id
	Type        int32                  `gorm:"column:type;type:tinyint(4);not null;comment:Model Type 0-LLM 1-TextEmbedding 2-Rerank" json:"type"`                             // Model Type 0-LLM 1-TextEmbedding 2-Rerank
	Provider    *model.ModelProvider   `gorm:"column:provider;type:json;not null;comment:Provider Information;serializer:json" json:"provider"`                                // Provider Information
	DisplayInfo *model.DisplayInfo     `gorm:"column:display_info;type:json;not null;comment:Display Information;serializer:json" json:"display_info"`                         // Display Information
	Connection  *model.Connection      `gorm:"column:connection;type:json;not null;comment:Connection Information;serializer:json" json:"connection"`                          // Connection Information
	Capability  *model.ModelAbility    `gorm:"column:capability;type:json;not null;comment:Model Capability;serializer:json" json:"capability"`                                // Model Capability
	Parameters  []model.ModelParameter `gorm:"column:parameters;type:json;not null;comment:Model Parameters;serializer:json" json:"parameters"`                                // Model Parameters
	Extra       *string                `gorm:"column:extra;type:json;comment:Extra Information" json:"extra"`                                                                  // Extra Information
	CreatedAt   int64                  `gorm:"column:created_at;type:bigint(20) unsigned;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt   int64                  `gorm:"column:updated_at;type:bigint(20) unsigned;not null;autoUpdateTime:milli;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt   gorm.DeletedAt         `gorm:"column:deleted_at;type:datetime(3);comment:Delete Time" json:"deleted_at"`                                                       // Delete Time
}

// TableName ModelInstance's table name
func (*ModelInstance) TableName() string {
	return TableNameModelInstance
}
