// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameModelMetum = "model_meta"

// ModelMetum 模型元信息
type ModelMetum struct {
	ID          int64   `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                   // 主键ID
	ModelName   string  `gorm:"column:model_name;type:varchar(128);not null;comment:模型名称" json:"model_name"`                               // 模型名称
	Protocol    string  `gorm:"column:protocol;type:varchar(128);not null;comment:模型协议" json:"protocol"`                                   // 模型协议
	IconURI     string  `gorm:"column:icon_uri;type:varchar(255);not null;comment:Icon URI" json:"icon_uri"`                               // Icon URI
	IconURL     string  `gorm:"column:icon_url;type:varchar(255);not null;comment:Icon URL" json:"icon_url"`                               // Icon URL
	Capability  *string `gorm:"column:capability;type:json;comment:模型能力" json:"capability"`                                                // 模型能力
	ConnConfig  *string `gorm:"column:conn_config;type:json;comment:模型连接配置" json:"conn_config"`                                            // 模型连接配置
	Status      int32   `gorm:"column:status;type:int(11);not null;index:idx_status,priority:1;default:1;comment:模型状态" json:"status"`      // 模型状态
	Description string  `gorm:"column:description;type:varchar(2048);not null;comment:模型描述" json:"description"`                            // 模型描述
	CreatedAt   int64   `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt   int64   `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt   *int64  `gorm:"column:deleted_at;type:bigint(20) unsigned;comment:Delete Time in Milliseconds" json:"deleted_at"`          // Delete Time in Milliseconds
}

// TableName ModelMetum's table name
func (*ModelMetum) TableName() string {
	return TableNameModelMetum
}
