// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package user

import (
	"fmt"
)

const (
	Active = "active"

	Deactivated = "deactivated"

	Offboarded = "offboarded"
)

type UserStatus = string

type AppUserInfo struct {
	UserUniqueName string `thrift:"user_unique_name,1,required" json:"user_unique_name"`
}

func NewAppUserInfo() *AppUserInfo {
	return &AppUserInfo{}
}

func (p *AppUserInfo) InitDefault() {
}

func (p *AppUserInfo) GetUserUniqueName() (v string) {
	return p.UserUniqueName
}
func (p *AppUserInfo) SetUserUniqueName(val string) {
	p.UserUniqueName = val
}

func (p *AppUserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppUserInfo(%+v)", *p)
}

type UserInfoDetail struct {
	Name           string       `thrift:"name,1,required" json:"name"`
	NickName       string       `thrift:"nick_name,2,required" json:"nick_name"`
	AvatarURL      string       `thrift:"avatar_url,3,required" json:"avatar_url"`
	Account        string       `thrift:"account,4,required" json:"account"`
	Mobile         *string      `thrift:"mobile,5,optional" json:"mobile,omitempty"`
	Description    *string      `thrift:"description,6,optional" json:"description,omitempty"`
	UserID         *string      `thrift:"user_id,7,optional" json:"user_id,omitempty"`
	AppUserInfo    *AppUserInfo `thrift:"app_user_info,8,optional" json:"app_user_info,omitempty"`
	UserCreateTime int64        `thrift:"user_create_time,10" json:"user_create_time"`
}

func NewUserInfoDetail() *UserInfoDetail {
	return &UserInfoDetail{}
}

func (p *UserInfoDetail) InitDefault() {
}

func (p *UserInfoDetail) GetName() (v string) {
	return p.Name
}

func (p *UserInfoDetail) GetNickName() (v string) {
	return p.NickName
}

func (p *UserInfoDetail) GetAvatarURL() (v string) {
	return p.AvatarURL
}

func (p *UserInfoDetail) GetAccount() (v string) {
	return p.Account
}

var UserInfoDetail_Mobile_DEFAULT string

func (p *UserInfoDetail) GetMobile() (v string) {
	if !p.IsSetMobile() {
		return UserInfoDetail_Mobile_DEFAULT
	}
	return *p.Mobile
}

var UserInfoDetail_Description_DEFAULT string

func (p *UserInfoDetail) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UserInfoDetail_Description_DEFAULT
	}
	return *p.Description
}

var UserInfoDetail_UserID_DEFAULT string

func (p *UserInfoDetail) GetUserID() (v string) {
	if !p.IsSetUserID() {
		return UserInfoDetail_UserID_DEFAULT
	}
	return *p.UserID
}

var UserInfoDetail_AppUserInfo_DEFAULT *AppUserInfo

func (p *UserInfoDetail) GetAppUserInfo() (v *AppUserInfo) {
	if !p.IsSetAppUserInfo() {
		return UserInfoDetail_AppUserInfo_DEFAULT
	}
	return p.AppUserInfo
}

func (p *UserInfoDetail) GetUserCreateTime() (v int64) {
	return p.UserCreateTime
}
func (p *UserInfoDetail) SetName(val string) {
	p.Name = val
}
func (p *UserInfoDetail) SetNickName(val string) {
	p.NickName = val
}
func (p *UserInfoDetail) SetAvatarURL(val string) {
	p.AvatarURL = val
}
func (p *UserInfoDetail) SetAccount(val string) {
	p.Account = val
}
func (p *UserInfoDetail) SetMobile(val *string) {
	p.Mobile = val
}
func (p *UserInfoDetail) SetDescription(val *string) {
	p.Description = val
}
func (p *UserInfoDetail) SetUserID(val *string) {
	p.UserID = val
}
func (p *UserInfoDetail) SetAppUserInfo(val *AppUserInfo) {
	p.AppUserInfo = val
}
func (p *UserInfoDetail) SetUserCreateTime(val int64) {
	p.UserCreateTime = val
}

func (p *UserInfoDetail) IsSetMobile() bool {
	return p.Mobile != nil
}

func (p *UserInfoDetail) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UserInfoDetail) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *UserInfoDetail) IsSetAppUserInfo() bool {
	return p.AppUserInfo != nil
}

func (p *UserInfoDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoDetail(%+v)", *p)
}
