// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package run

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/kiosk404/airi-go/backend/api/model/base"
	"github.com/kiosk404/airi-go/backend/api/model/conversation/common"
	"github.com/kiosk404/airi-go/backend/api/model/conversation/message"
)

const (
	ContentTypeText = "text"

	ContentTypeImage = "image"

	ContentTypeAudio = "audio"

	ContentTypeVideo = "video"

	ContentTypeLink = "link"

	ContentTypeMusic = "music"

	ContentTypeCard = "card"

	ContentTypeAPP = "app"

	ContentTypeFile = "file"

	ContentTypeMix = "mix"

	ContentTypeMixApi = "object_string"

	RunEventMessage = "message"

	RunEventDone = "done"

	RunEventError = "error"
)

type DiffModeIdentifier int64

const (
	DiffModeIdentifier_ChatWithA DiffModeIdentifier = 1
	DiffModeIdentifier_ChatWithB DiffModeIdentifier = 2
)

func (p DiffModeIdentifier) String() string {
	switch p {
	case DiffModeIdentifier_ChatWithA:
		return "ChatWithA"
	case DiffModeIdentifier_ChatWithB:
		return "ChatWithB"
	}
	return "<UNSET>"
}

func DiffModeIdentifierFromString(s string) (DiffModeIdentifier, error) {
	switch s {
	case "ChatWithA":
		return DiffModeIdentifier_ChatWithA, nil
	case "ChatWithB":
		return DiffModeIdentifier_ChatWithB, nil
	}
	return DiffModeIdentifier(0), fmt.Errorf("not a valid DiffModeIdentifier string")
}

func DiffModeIdentifierPtr(v DiffModeIdentifier) *DiffModeIdentifier { return &v }
func (p *DiffModeIdentifier) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = DiffModeIdentifier(result.Int64)
	return
}

func (p *DiffModeIdentifier) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ParametersStruct struct {
	Value        string `thrift:"value,1" json:"value"`
	ResourceType string `thrift:"resource_type,2" json:"resource_type"`
}

func NewParametersStruct() *ParametersStruct {
	return &ParametersStruct{}
}

func (p *ParametersStruct) InitDefault() {
}

func (p *ParametersStruct) GetValue() (v string) {
	return p.Value
}

func (p *ParametersStruct) GetResourceType() (v string) {
	return p.ResourceType
}
func (p *ParametersStruct) SetValue(val string) {
	p.Value = val
}
func (p *ParametersStruct) SetResourceType(val string) {
	p.ResourceType = val
}

func (p *ParametersStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ParametersStruct(%+v)", *p)
}

type MixContentModel struct {
	ItemList   []*Item `thrift:"item_list,1,default,list<Item>" json:"item_list"`
	ReferItems []*Item `thrift:"refer_items,2,default,list<Item>" json:"refer_items"`
}

func NewMixContentModel() *MixContentModel {
	return &MixContentModel{}
}

func (p *MixContentModel) InitDefault() {
}

func (p *MixContentModel) GetItemList() (v []*Item) {
	return p.ItemList
}

func (p *MixContentModel) GetReferItems() (v []*Item) {
	return p.ReferItems
}
func (p *MixContentModel) SetItemList(val []*Item) {
	p.ItemList = val
}
func (p *MixContentModel) SetReferItems(val []*Item) {
	p.ReferItems = val
}

func (p *MixContentModel) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MixContentModel(%+v)", *p)
}

type Item struct {
	Type  string `thrift:"type,1" json:"type"`
	Text  string `thrift:"text,2" json:"text"`
	Image *Image `thrift:"image,3" json:"image"`
	File  *File  `thrift:"file,4" json:"file"`
}

func NewItem() *Item {
	return &Item{}
}

func (p *Item) InitDefault() {
}

func (p *Item) GetType() (v string) {
	return p.Type
}

func (p *Item) GetText() (v string) {
	return p.Text
}

var Item_Image_DEFAULT *Image

func (p *Item) GetImage() (v *Image) {
	if !p.IsSetImage() {
		return Item_Image_DEFAULT
	}
	return p.Image
}

var Item_File_DEFAULT *File

func (p *Item) GetFile() (v *File) {
	if !p.IsSetFile() {
		return Item_File_DEFAULT
	}
	return p.File
}
func (p *Item) SetType(val string) {
	p.Type = val
}
func (p *Item) SetText(val string) {
	p.Text = val
}
func (p *Item) SetImage(val *Image) {
	p.Image = val
}
func (p *Item) SetFile(val *File) {
	p.File = val
}

func (p *Item) IsSetImage() bool {
	return p.Image != nil
}

func (p *Item) IsSetFile() bool {
	return p.File != nil
}

func (p *Item) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Item(%+v)", *p)
}

type ImageDetail struct {
	URL    string `thrift:"url,1" json:"url"`
	Width  int32  `thrift:"width,2" json:"width"`
	Height int32  `thrift:"height,3" json:"height"`
}

func NewImageDetail() *ImageDetail {
	return &ImageDetail{}
}

func (p *ImageDetail) InitDefault() {
}

func (p *ImageDetail) GetURL() (v string) {
	return p.URL
}

func (p *ImageDetail) GetWidth() (v int32) {
	return p.Width
}

func (p *ImageDetail) GetHeight() (v int32) {
	return p.Height
}
func (p *ImageDetail) SetURL(val string) {
	p.URL = val
}
func (p *ImageDetail) SetWidth(val int32) {
	p.Width = val
}
func (p *ImageDetail) SetHeight(val int32) {
	p.Height = val
}

func (p *ImageDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageDetail(%+v)", *p)
}

type File struct {
	FileKey  string `thrift:"file_key,1" json:"file_key"`
	FileName string `thrift:"file_name,2" json:"file_name"`
	FileType string `thrift:"file_type,3" json:"file_type"`
	FileSize int64  `thrift:"file_size,4" json:"file_size"`
	FileURL  string `thrift:"file_url,6" json:"file_url"`
}

func NewFile() *File {
	return &File{}
}

func (p *File) InitDefault() {
}

func (p *File) GetFileKey() (v string) {
	return p.FileKey
}

func (p *File) GetFileName() (v string) {
	return p.FileName
}

func (p *File) GetFileType() (v string) {
	return p.FileType
}

func (p *File) GetFileSize() (v int64) {
	return p.FileSize
}

func (p *File) GetFileURL() (v string) {
	return p.FileURL
}
func (p *File) SetFileKey(val string) {
	p.FileKey = val
}
func (p *File) SetFileName(val string) {
	p.FileName = val
}
func (p *File) SetFileType(val string) {
	p.FileType = val
}
func (p *File) SetFileSize(val int64) {
	p.FileSize = val
}
func (p *File) SetFileURL(val string) {
	p.FileURL = val
}

func (p *File) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("File(%+v)", *p)
}

type Image struct {
	Key        string       `thrift:"key,1" json:"key"`
	ImageThumb *ImageDetail `thrift:"image_thumb,2" json:"image_thumb"`
	ImageOri   *ImageDetail `thrift:"image_ori,3" json:"image_ori"`
}

func NewImage() *Image {
	return &Image{}
}

func (p *Image) InitDefault() {
}

func (p *Image) GetKey() (v string) {
	return p.Key
}

var Image_ImageThumb_DEFAULT *ImageDetail

func (p *Image) GetImageThumb() (v *ImageDetail) {
	if !p.IsSetImageThumb() {
		return Image_ImageThumb_DEFAULT
	}
	return p.ImageThumb
}

var Image_ImageOri_DEFAULT *ImageDetail

func (p *Image) GetImageOri() (v *ImageDetail) {
	if !p.IsSetImageOri() {
		return Image_ImageOri_DEFAULT
	}
	return p.ImageOri
}
func (p *Image) SetKey(val string) {
	p.Key = val
}
func (p *Image) SetImageThumb(val *ImageDetail) {
	p.ImageThumb = val
}
func (p *Image) SetImageOri(val *ImageDetail) {
	p.ImageOri = val
}

func (p *Image) IsSetImageThumb() bool {
	return p.ImageThumb != nil
}

func (p *Image) IsSetImageOri() bool {
	return p.ImageOri != nil
}

func (p *Image) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Image(%+v)", *p)
}

type Tool struct {
	PluginID   int64                        `thrift:"plugin_id,1" json:"plugin_id"`
	Parameters map[string]*ParametersStruct `thrift:"parameters,2" json:"parameters"`
	APIName    string                       `thrift:"api_name,3" json:"api_name"`
	ToolID     int64                        `thrift:"tool_id,4" json:"tool_id"`
}

func NewTool() *Tool {
	return &Tool{}
}

func (p *Tool) InitDefault() {
}

func (p *Tool) GetPluginID() (v int64) {
	return p.PluginID
}

func (p *Tool) GetParameters() (v map[string]*ParametersStruct) {
	return p.Parameters
}

func (p *Tool) GetAPIName() (v string) {
	return p.APIName
}

func (p *Tool) GetToolID() (v int64) {
	return p.ToolID
}
func (p *Tool) SetPluginID(val int64) {
	p.PluginID = val
}
func (p *Tool) SetParameters(val map[string]*ParametersStruct) {
	p.Parameters = val
}
func (p *Tool) SetAPIName(val string) {
	p.APIName = val
}
func (p *Tool) SetToolID(val int64) {
	p.ToolID = val
}

func (p *Tool) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Tool(%+v)", *p)
}

type AdditionalContent struct {
	Type    string  `thrift:"type,1,required" json:"type"`
	Text    *string `thrift:"text,2,optional" json:"text,omitempty"`
	FileURL *string `thrift:"file_url,3,optional" json:"file_url,omitempty"`
	FileID  *int64  `thrift:"file_id,4,optional" json:"file_id,omitempty"`
}

func NewAdditionalContent() *AdditionalContent {
	return &AdditionalContent{}
}

func (p *AdditionalContent) InitDefault() {
}

func (p *AdditionalContent) GetType() (v string) {
	return p.Type
}

var AdditionalContent_Text_DEFAULT string

func (p *AdditionalContent) GetText() (v string) {
	if !p.IsSetText() {
		return AdditionalContent_Text_DEFAULT
	}
	return *p.Text
}

var AdditionalContent_FileURL_DEFAULT string

func (p *AdditionalContent) GetFileURL() (v string) {
	if !p.IsSetFileURL() {
		return AdditionalContent_FileURL_DEFAULT
	}
	return *p.FileURL
}

var AdditionalContent_FileID_DEFAULT int64

func (p *AdditionalContent) GetFileID() (v int64) {
	if !p.IsSetFileID() {
		return AdditionalContent_FileID_DEFAULT
	}
	return *p.FileID
}
func (p *AdditionalContent) SetType(val string) {
	p.Type = val
}
func (p *AdditionalContent) SetText(val *string) {
	p.Text = val
}
func (p *AdditionalContent) SetFileURL(val *string) {
	p.FileURL = val
}
func (p *AdditionalContent) SetFileID(val *int64) {
	p.FileID = val
}

func (p *AdditionalContent) IsSetText() bool {
	return p.Text != nil
}

func (p *AdditionalContent) IsSetFileURL() bool {
	return p.FileURL != nil
}

func (p *AdditionalContent) IsSetFileID() bool {
	return p.FileID != nil
}

func (p *AdditionalContent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdditionalContent(%+v)", *p)
}

type AgentRunRequest struct {
	BotID                    int64                         `thrift:"bot_id,1" form:"bot_id" json:"bot_id,string" query:"bot_id"`
	ConversationID           int64                         `thrift:"conversation_id,2,required" form:"conversation_id" json:"conversation_id,string" query:"conversation_id"`
	Query                    string                        `thrift:"query,5,required" json:"query"`
	Extra                    map[string]string             `thrift:"extra,7" json:"extra"`
	CustomVariables          map[string]string             `thrift:"custom_variables,9" json:"custom_variables"`
	DraftMode                *bool                         `thrift:"draft_mode,10,optional" json:"draft_mode,omitempty"`
	Scene                    *common.Scene                 `thrift:"scene,11,optional,Scene" json:"scene,omitempty"`
	ContentType              *string                       `thrift:"content_type,12,optional" json:"content_type,omitempty"`
	RegenMessageID           *int64                        `thrift:"regen_message_id,13,optional" json:"regen_message_id,omitempty"`
	LocalMessageID           *string                       `thrift:"local_message_id,14,optional" json:"local_message_id,omitempty"`
	PresetBot                *string                       `thrift:"preset_bot,15,optional" json:"preset_bot,omitempty"`
	InsertHistoryMessageList []string                      `thrift:"insert_history_message_list,16,optional,list<string>" json:"insert_history_message_list,omitempty"`
	DeviceID                 *string                       `thrift:"device_id,17,optional" json:"device_id,omitempty"`
	MentionList              []*message.MsgParticipantInfo `thrift:"mention_list,18,optional,list<message.MsgParticipantInfo>" json:"mention_list,omitempty"`
	ToolList                 []*Tool                       `thrift:"toolList,19,optional,list<Tool>" json:"toolList,omitempty"`
	CommitVersion            *string                       `thrift:"commit_version,20,optional" json:"commit_version,omitempty"`
	SubScene                 *string                       `thrift:"sub_scene,21,optional" json:"sub_scene,omitempty"`
	DiffModeIdentifier       *DiffModeIdentifier           `thrift:"diff_mode_identifier,22,optional,DiffModeIdentifier" json:"diff_mode_identifier,omitempty"`
	ShortcutCmdID            *int64                        `thrift:"shortcut_cmd_id,23,optional" json:"shortcut_cmd_id,omitempty"`
}

func NewAgentRunRequest() *AgentRunRequest {
	return &AgentRunRequest{}
}

func (p *AgentRunRequest) InitDefault() {
}

func (p *AgentRunRequest) GetBotID() (v int64) {
	return p.BotID
}

func (p *AgentRunRequest) GetConversationID() (v int64) {
	return p.ConversationID
}

func (p *AgentRunRequest) GetQuery() (v string) {
	return p.Query
}

func (p *AgentRunRequest) GetExtra() (v map[string]string) {
	return p.Extra
}

func (p *AgentRunRequest) GetCustomVariables() (v map[string]string) {
	return p.CustomVariables
}

var AgentRunRequest_DraftMode_DEFAULT bool

func (p *AgentRunRequest) GetDraftMode() (v bool) {
	if !p.IsSetDraftMode() {
		return AgentRunRequest_DraftMode_DEFAULT
	}
	return *p.DraftMode
}

var AgentRunRequest_Scene_DEFAULT common.Scene

func (p *AgentRunRequest) GetScene() (v common.Scene) {
	if !p.IsSetScene() {
		return AgentRunRequest_Scene_DEFAULT
	}
	return *p.Scene
}

var AgentRunRequest_ContentType_DEFAULT string

func (p *AgentRunRequest) GetContentType() (v string) {
	if !p.IsSetContentType() {
		return AgentRunRequest_ContentType_DEFAULT
	}
	return *p.ContentType
}

var AgentRunRequest_RegenMessageID_DEFAULT int64

func (p *AgentRunRequest) GetRegenMessageID() (v int64) {
	if !p.IsSetRegenMessageID() {
		return AgentRunRequest_RegenMessageID_DEFAULT
	}
	return *p.RegenMessageID
}

var AgentRunRequest_LocalMessageID_DEFAULT string

func (p *AgentRunRequest) GetLocalMessageID() (v string) {
	if !p.IsSetLocalMessageID() {
		return AgentRunRequest_LocalMessageID_DEFAULT
	}
	return *p.LocalMessageID
}

var AgentRunRequest_PresetBot_DEFAULT string

func (p *AgentRunRequest) GetPresetBot() (v string) {
	if !p.IsSetPresetBot() {
		return AgentRunRequest_PresetBot_DEFAULT
	}
	return *p.PresetBot
}

var AgentRunRequest_InsertHistoryMessageList_DEFAULT []string

func (p *AgentRunRequest) GetInsertHistoryMessageList() (v []string) {
	if !p.IsSetInsertHistoryMessageList() {
		return AgentRunRequest_InsertHistoryMessageList_DEFAULT
	}
	return p.InsertHistoryMessageList
}

var AgentRunRequest_DeviceID_DEFAULT string

func (p *AgentRunRequest) GetDeviceID() (v string) {
	if !p.IsSetDeviceID() {
		return AgentRunRequest_DeviceID_DEFAULT
	}
	return *p.DeviceID
}

var AgentRunRequest_MentionList_DEFAULT []*message.MsgParticipantInfo

func (p *AgentRunRequest) GetMentionList() (v []*message.MsgParticipantInfo) {
	if !p.IsSetMentionList() {
		return AgentRunRequest_MentionList_DEFAULT
	}
	return p.MentionList
}

var AgentRunRequest_ToolList_DEFAULT []*Tool

func (p *AgentRunRequest) GetToolList() (v []*Tool) {
	if !p.IsSetToolList() {
		return AgentRunRequest_ToolList_DEFAULT
	}
	return p.ToolList
}

var AgentRunRequest_CommitVersion_DEFAULT string

func (p *AgentRunRequest) GetCommitVersion() (v string) {
	if !p.IsSetCommitVersion() {
		return AgentRunRequest_CommitVersion_DEFAULT
	}
	return *p.CommitVersion
}

var AgentRunRequest_SubScene_DEFAULT string

func (p *AgentRunRequest) GetSubScene() (v string) {
	if !p.IsSetSubScene() {
		return AgentRunRequest_SubScene_DEFAULT
	}
	return *p.SubScene
}

var AgentRunRequest_DiffModeIdentifier_DEFAULT DiffModeIdentifier

func (p *AgentRunRequest) GetDiffModeIdentifier() (v DiffModeIdentifier) {
	if !p.IsSetDiffModeIdentifier() {
		return AgentRunRequest_DiffModeIdentifier_DEFAULT
	}
	return *p.DiffModeIdentifier
}

var AgentRunRequest_ShortcutCmdID_DEFAULT int64

func (p *AgentRunRequest) GetShortcutCmdID() (v int64) {
	if !p.IsSetShortcutCmdID() {
		return AgentRunRequest_ShortcutCmdID_DEFAULT
	}
	return *p.ShortcutCmdID
}
func (p *AgentRunRequest) SetBotID(val int64) {
	p.BotID = val
}
func (p *AgentRunRequest) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *AgentRunRequest) SetQuery(val string) {
	p.Query = val
}
func (p *AgentRunRequest) SetExtra(val map[string]string) {
	p.Extra = val
}
func (p *AgentRunRequest) SetCustomVariables(val map[string]string) {
	p.CustomVariables = val
}
func (p *AgentRunRequest) SetDraftMode(val *bool) {
	p.DraftMode = val
}
func (p *AgentRunRequest) SetScene(val *common.Scene) {
	p.Scene = val
}
func (p *AgentRunRequest) SetContentType(val *string) {
	p.ContentType = val
}
func (p *AgentRunRequest) SetRegenMessageID(val *int64) {
	p.RegenMessageID = val
}
func (p *AgentRunRequest) SetLocalMessageID(val *string) {
	p.LocalMessageID = val
}
func (p *AgentRunRequest) SetPresetBot(val *string) {
	p.PresetBot = val
}
func (p *AgentRunRequest) SetInsertHistoryMessageList(val []string) {
	p.InsertHistoryMessageList = val
}
func (p *AgentRunRequest) SetDeviceID(val *string) {
	p.DeviceID = val
}
func (p *AgentRunRequest) SetMentionList(val []*message.MsgParticipantInfo) {
	p.MentionList = val
}
func (p *AgentRunRequest) SetToolList(val []*Tool) {
	p.ToolList = val
}
func (p *AgentRunRequest) SetCommitVersion(val *string) {
	p.CommitVersion = val
}
func (p *AgentRunRequest) SetSubScene(val *string) {
	p.SubScene = val
}
func (p *AgentRunRequest) SetDiffModeIdentifier(val *DiffModeIdentifier) {
	p.DiffModeIdentifier = val
}
func (p *AgentRunRequest) SetShortcutCmdID(val *int64) {
	p.ShortcutCmdID = val
}

func (p *AgentRunRequest) IsSetDraftMode() bool {
	return p.DraftMode != nil
}

func (p *AgentRunRequest) IsSetScene() bool {
	return p.Scene != nil
}

func (p *AgentRunRequest) IsSetContentType() bool {
	return p.ContentType != nil
}

func (p *AgentRunRequest) IsSetRegenMessageID() bool {
	return p.RegenMessageID != nil
}

func (p *AgentRunRequest) IsSetLocalMessageID() bool {
	return p.LocalMessageID != nil
}

func (p *AgentRunRequest) IsSetPresetBot() bool {
	return p.PresetBot != nil
}

func (p *AgentRunRequest) IsSetInsertHistoryMessageList() bool {
	return p.InsertHistoryMessageList != nil
}

func (p *AgentRunRequest) IsSetDeviceID() bool {
	return p.DeviceID != nil
}

func (p *AgentRunRequest) IsSetMentionList() bool {
	return p.MentionList != nil
}

func (p *AgentRunRequest) IsSetToolList() bool {
	return p.ToolList != nil
}

func (p *AgentRunRequest) IsSetCommitVersion() bool {
	return p.CommitVersion != nil
}

func (p *AgentRunRequest) IsSetSubScene() bool {
	return p.SubScene != nil
}

func (p *AgentRunRequest) IsSetDiffModeIdentifier() bool {
	return p.DiffModeIdentifier != nil
}

func (p *AgentRunRequest) IsSetShortcutCmdID() bool {
	return p.ShortcutCmdID != nil
}

func (p *AgentRunRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentRunRequest(%+v)", *p)
}

type RunStreamResponse struct {
	Message        *message.ChatMessage `thrift:"message,1,required" json:"message"`
	IsFinish       *bool                `thrift:"is_finish,2,optional" json:"is_finish,omitempty"`
	Index          int32                `thrift:"index,3,required" json:"index"`
	ConversationID string               `thrift:"conversation_id,4,required" json:"conversation_id"`
	SeqID          int32                `thrift:"seq_id,5,required" json:"seq_id"`
}

func NewRunStreamResponse() *RunStreamResponse {
	return &RunStreamResponse{}
}

func (p *RunStreamResponse) InitDefault() {
}

var RunStreamResponse_Message_DEFAULT *message.ChatMessage

func (p *RunStreamResponse) GetMessage() (v *message.ChatMessage) {
	if !p.IsSetMessage() {
		return RunStreamResponse_Message_DEFAULT
	}
	return p.Message
}

var RunStreamResponse_IsFinish_DEFAULT bool

func (p *RunStreamResponse) GetIsFinish() (v bool) {
	if !p.IsSetIsFinish() {
		return RunStreamResponse_IsFinish_DEFAULT
	}
	return *p.IsFinish
}

func (p *RunStreamResponse) GetIndex() (v int32) {
	return p.Index
}

func (p *RunStreamResponse) GetConversationID() (v string) {
	return p.ConversationID
}

func (p *RunStreamResponse) GetSeqID() (v int32) {
	return p.SeqID
}
func (p *RunStreamResponse) SetMessage(val *message.ChatMessage) {
	p.Message = val
}
func (p *RunStreamResponse) SetIsFinish(val *bool) {
	p.IsFinish = val
}
func (p *RunStreamResponse) SetIndex(val int32) {
	p.Index = val
}
func (p *RunStreamResponse) SetConversationID(val string) {
	p.ConversationID = val
}
func (p *RunStreamResponse) SetSeqID(val int32) {
	p.SeqID = val
}

func (p *RunStreamResponse) IsSetMessage() bool {
	return p.Message != nil
}

func (p *RunStreamResponse) IsSetIsFinish() bool {
	return p.IsFinish != nil
}

func (p *RunStreamResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RunStreamResponse(%+v)", *p)
}

type AgentRunResponse struct {
	Code int64  `thrift:"code,1" json:"code"`
	Msg  string `thrift:"msg,2" json:"msg"`
}

func NewAgentRunResponse() *AgentRunResponse {
	return &AgentRunResponse{}
}

func (p *AgentRunResponse) InitDefault() {
}

func (p *AgentRunResponse) GetCode() (v int64) {
	return p.Code
}

func (p *AgentRunResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *AgentRunResponse) SetCode(val int64) {
	p.Code = val
}
func (p *AgentRunResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *AgentRunResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentRunResponse(%+v)", *p)
}

type ErrorData struct {
	Code int64  `thrift:"code,1" json:"code"`
	Msg  string `thrift:"msg,2" json:"msg"`
}

func NewErrorData() *ErrorData {
	return &ErrorData{}
}

func (p *ErrorData) InitDefault() {
}

func (p *ErrorData) GetCode() (v int64) {
	return p.Code
}

func (p *ErrorData) GetMsg() (v string) {
	return p.Msg
}
func (p *ErrorData) SetCode(val int64) {
	p.Code = val
}
func (p *ErrorData) SetMsg(val string) {
	p.Msg = val
}

func (p *ErrorData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ErrorData(%+v)", *p)
}

type CustomConfig struct {
	ModelConfig *ModelConfig `thrift:"ModelConfig,1,optional" json:"ModelConfig,omitempty"`
	BotConfig   *BotConfig   `thrift:"BotConfig,2,optional" json:"BotConfig,omitempty"`
}

func NewCustomConfig() *CustomConfig {
	return &CustomConfig{}
}

func (p *CustomConfig) InitDefault() {
}

var CustomConfig_ModelConfig_DEFAULT *ModelConfig

func (p *CustomConfig) GetModelConfig() (v *ModelConfig) {
	if !p.IsSetModelConfig() {
		return CustomConfig_ModelConfig_DEFAULT
	}
	return p.ModelConfig
}

var CustomConfig_BotConfig_DEFAULT *BotConfig

func (p *CustomConfig) GetBotConfig() (v *BotConfig) {
	if !p.IsSetBotConfig() {
		return CustomConfig_BotConfig_DEFAULT
	}
	return p.BotConfig
}
func (p *CustomConfig) SetModelConfig(val *ModelConfig) {
	p.ModelConfig = val
}
func (p *CustomConfig) SetBotConfig(val *BotConfig) {
	p.BotConfig = val
}

func (p *CustomConfig) IsSetModelConfig() bool {
	return p.ModelConfig != nil
}

func (p *CustomConfig) IsSetBotConfig() bool {
	return p.BotConfig != nil
}

func (p *CustomConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CustomConfig(%+v)", *p)
}

type ModelConfig struct {
	ModelID *string `thrift:"ModelID,1,optional" json:"ModelID,omitempty"`
}

func NewModelConfig() *ModelConfig {
	return &ModelConfig{}
}

func (p *ModelConfig) InitDefault() {
}

var ModelConfig_ModelID_DEFAULT string

func (p *ModelConfig) GetModelID() (v string) {
	if !p.IsSetModelID() {
		return ModelConfig_ModelID_DEFAULT
	}
	return *p.ModelID
}
func (p *ModelConfig) SetModelID(val *string) {
	p.ModelID = val
}

func (p *ModelConfig) IsSetModelID() bool {
	return p.ModelID != nil
}

func (p *ModelConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelConfig(%+v)", *p)
}

type BotConfig struct {
	CharacterName *string `thrift:"CharacterName,1,optional" json:"CharacterName,omitempty"`
	Prompt        *string `thrift:"Prompt,2,optional" json:"Prompt,omitempty"`
}

func NewBotConfig() *BotConfig {
	return &BotConfig{}
}

func (p *BotConfig) InitDefault() {
}

var BotConfig_CharacterName_DEFAULT string

func (p *BotConfig) GetCharacterName() (v string) {
	if !p.IsSetCharacterName() {
		return BotConfig_CharacterName_DEFAULT
	}
	return *p.CharacterName
}

var BotConfig_Prompt_DEFAULT string

func (p *BotConfig) GetPrompt() (v string) {
	if !p.IsSetPrompt() {
		return BotConfig_Prompt_DEFAULT
	}
	return *p.Prompt
}
func (p *BotConfig) SetCharacterName(val *string) {
	p.CharacterName = val
}
func (p *BotConfig) SetPrompt(val *string) {
	p.Prompt = val
}

func (p *BotConfig) IsSetCharacterName() bool {
	return p.CharacterName != nil
}

func (p *BotConfig) IsSetPrompt() bool {
	return p.Prompt != nil
}

func (p *BotConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BotConfig(%+v)", *p)
}

type ShortcutCommandDetail struct {
	CommandID  int64             `thrift:"command_id,1,required" json:"command_id"`
	Parameters map[string]string `thrift:"parameters,2" json:"parameters"`
}

func NewShortcutCommandDetail() *ShortcutCommandDetail {
	return &ShortcutCommandDetail{}
}

func (p *ShortcutCommandDetail) InitDefault() {
}

func (p *ShortcutCommandDetail) GetCommandID() (v int64) {
	return p.CommandID
}

func (p *ShortcutCommandDetail) GetParameters() (v map[string]string) {
	return p.Parameters
}
func (p *ShortcutCommandDetail) SetCommandID(val int64) {
	p.CommandID = val
}
func (p *ShortcutCommandDetail) SetParameters(val map[string]string) {
	p.Parameters = val
}

func (p *ShortcutCommandDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShortcutCommandDetail(%+v)", *p)
}

type ChatV3Request struct {
	BotID              int64                  `thrift:"BotID,1,required" json:"BotID"`
	ConversationID     *int64                 `thrift:"ConversationID,2,optional" json:"ConversationID,omitempty"`
	User               string                 `thrift:"User,3,required" json:"User"`
	Stream             *bool                  `thrift:"Stream,4,optional" json:"Stream,omitempty"`
	AdditionalMessages []*EnterMessage        `thrift:"AdditionalMessages,5,optional,list<EnterMessage>" json:"AdditionalMessages,omitempty"`
	CustomVariables    map[string]string      `thrift:"CustomVariables,6,optional" json:"CustomVariables,omitempty"`
	MetaData           map[string]string      `thrift:"MetaData,8,optional" json:"MetaData,omitempty"`
	CustomConfig       *CustomConfig          `thrift:"CustomConfig,10,optional" json:"CustomConfig,omitempty"`
	ExtraParams        map[string]string      `thrift:"ExtraParams,11,optional" json:"ExtraParams,omitempty"`
	ConnectorID        *int64                 `thrift:"ConnectorID,12,optional" json:"ConnectorID,omitempty"`
	ShortcutCommand    *ShortcutCommandDetail `thrift:"ShortcutCommand,13,optional" json:"ShortcutCommand,omitempty"`
}

func NewChatV3Request() *ChatV3Request {
	return &ChatV3Request{}
}

func (p *ChatV3Request) InitDefault() {
}

func (p *ChatV3Request) GetBotID() (v int64) {
	return p.BotID
}

var ChatV3Request_ConversationID_DEFAULT int64

func (p *ChatV3Request) GetConversationID() (v int64) {
	if !p.IsSetConversationID() {
		return ChatV3Request_ConversationID_DEFAULT
	}
	return *p.ConversationID
}

func (p *ChatV3Request) GetUser() (v string) {
	return p.User
}

var ChatV3Request_Stream_DEFAULT bool

func (p *ChatV3Request) GetStream() (v bool) {
	if !p.IsSetStream() {
		return ChatV3Request_Stream_DEFAULT
	}
	return *p.Stream
}

var ChatV3Request_AdditionalMessages_DEFAULT []*EnterMessage

func (p *ChatV3Request) GetAdditionalMessages() (v []*EnterMessage) {
	if !p.IsSetAdditionalMessages() {
		return ChatV3Request_AdditionalMessages_DEFAULT
	}
	return p.AdditionalMessages
}

var ChatV3Request_CustomVariables_DEFAULT map[string]string

func (p *ChatV3Request) GetCustomVariables() (v map[string]string) {
	if !p.IsSetCustomVariables() {
		return ChatV3Request_CustomVariables_DEFAULT
	}
	return p.CustomVariables
}

var ChatV3Request_MetaData_DEFAULT map[string]string

func (p *ChatV3Request) GetMetaData() (v map[string]string) {
	if !p.IsSetMetaData() {
		return ChatV3Request_MetaData_DEFAULT
	}
	return p.MetaData
}

var ChatV3Request_CustomConfig_DEFAULT *CustomConfig

func (p *ChatV3Request) GetCustomConfig() (v *CustomConfig) {
	if !p.IsSetCustomConfig() {
		return ChatV3Request_CustomConfig_DEFAULT
	}
	return p.CustomConfig
}

var ChatV3Request_ExtraParams_DEFAULT map[string]string

func (p *ChatV3Request) GetExtraParams() (v map[string]string) {
	if !p.IsSetExtraParams() {
		return ChatV3Request_ExtraParams_DEFAULT
	}
	return p.ExtraParams
}

var ChatV3Request_ConnectorID_DEFAULT int64

func (p *ChatV3Request) GetConnectorID() (v int64) {
	if !p.IsSetConnectorID() {
		return ChatV3Request_ConnectorID_DEFAULT
	}
	return *p.ConnectorID
}

var ChatV3Request_ShortcutCommand_DEFAULT *ShortcutCommandDetail

func (p *ChatV3Request) GetShortcutCommand() (v *ShortcutCommandDetail) {
	if !p.IsSetShortcutCommand() {
		return ChatV3Request_ShortcutCommand_DEFAULT
	}
	return p.ShortcutCommand
}
func (p *ChatV3Request) SetBotID(val int64) {
	p.BotID = val
}
func (p *ChatV3Request) SetConversationID(val *int64) {
	p.ConversationID = val
}
func (p *ChatV3Request) SetUser(val string) {
	p.User = val
}
func (p *ChatV3Request) SetStream(val *bool) {
	p.Stream = val
}
func (p *ChatV3Request) SetAdditionalMessages(val []*EnterMessage) {
	p.AdditionalMessages = val
}
func (p *ChatV3Request) SetCustomVariables(val map[string]string) {
	p.CustomVariables = val
}
func (p *ChatV3Request) SetMetaData(val map[string]string) {
	p.MetaData = val
}
func (p *ChatV3Request) SetCustomConfig(val *CustomConfig) {
	p.CustomConfig = val
}
func (p *ChatV3Request) SetExtraParams(val map[string]string) {
	p.ExtraParams = val
}
func (p *ChatV3Request) SetConnectorID(val *int64) {
	p.ConnectorID = val
}
func (p *ChatV3Request) SetShortcutCommand(val *ShortcutCommandDetail) {
	p.ShortcutCommand = val
}

func (p *ChatV3Request) IsSetConversationID() bool {
	return p.ConversationID != nil
}

func (p *ChatV3Request) IsSetStream() bool {
	return p.Stream != nil
}

func (p *ChatV3Request) IsSetAdditionalMessages() bool {
	return p.AdditionalMessages != nil
}

func (p *ChatV3Request) IsSetCustomVariables() bool {
	return p.CustomVariables != nil
}

func (p *ChatV3Request) IsSetMetaData() bool {
	return p.MetaData != nil
}

func (p *ChatV3Request) IsSetCustomConfig() bool {
	return p.CustomConfig != nil
}

func (p *ChatV3Request) IsSetExtraParams() bool {
	return p.ExtraParams != nil
}

func (p *ChatV3Request) IsSetConnectorID() bool {
	return p.ConnectorID != nil
}

func (p *ChatV3Request) IsSetShortcutCommand() bool {
	return p.ShortcutCommand != nil
}

func (p *ChatV3Request) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatV3Request(%+v)", *p)
}

type ChatV3MessageDetail struct {
	ID               string            `thrift:"ID,1,required" json:"ID"`
	ConversationID   string            `thrift:"ConversationID,2,required" json:"ConversationID"`
	BotID            string            `thrift:"BotID,3,required" json:"BotID"`
	Role             string            `thrift:"Role,4,required" json:"Role"`
	Type             string            `thrift:"Type,5,required" json:"Type"`
	Content          string            `thrift:"Content,6,required" json:"Content"`
	ContentType      string            `thrift:"ContentType,7,required" json:"ContentType"`
	MetaData         map[string]string `thrift:"MetaData,8,optional" json:"MetaData,omitempty"`
	ChatID           string            `thrift:"ChatID,9,required" json:"ChatID"`
	SectionID        *string           `thrift:"SectionID,10,optional" json:"SectionID,omitempty"`
	CreatedAt        *int64            `thrift:"CreatedAt,11,optional" json:"CreatedAt,omitempty"`
	UpdatedAt        *int64            `thrift:"UpdatedAt,12,optional" json:"UpdatedAt,omitempty"`
	ReasoningContent *string           `thrift:"ReasoningContent,13,optional" json:"ReasoningContent,omitempty"`
}

func NewChatV3MessageDetail() *ChatV3MessageDetail {
	return &ChatV3MessageDetail{}
}

func (p *ChatV3MessageDetail) InitDefault() {
}

func (p *ChatV3MessageDetail) GetID() (v string) {
	return p.ID
}

func (p *ChatV3MessageDetail) GetConversationID() (v string) {
	return p.ConversationID
}

func (p *ChatV3MessageDetail) GetBotID() (v string) {
	return p.BotID
}

func (p *ChatV3MessageDetail) GetRole() (v string) {
	return p.Role
}

func (p *ChatV3MessageDetail) GetType() (v string) {
	return p.Type
}

func (p *ChatV3MessageDetail) GetContent() (v string) {
	return p.Content
}

func (p *ChatV3MessageDetail) GetContentType() (v string) {
	return p.ContentType
}

var ChatV3MessageDetail_MetaData_DEFAULT map[string]string

func (p *ChatV3MessageDetail) GetMetaData() (v map[string]string) {
	if !p.IsSetMetaData() {
		return ChatV3MessageDetail_MetaData_DEFAULT
	}
	return p.MetaData
}

func (p *ChatV3MessageDetail) GetChatID() (v string) {
	return p.ChatID
}

var ChatV3MessageDetail_SectionID_DEFAULT string

func (p *ChatV3MessageDetail) GetSectionID() (v string) {
	if !p.IsSetSectionID() {
		return ChatV3MessageDetail_SectionID_DEFAULT
	}
	return *p.SectionID
}

var ChatV3MessageDetail_CreatedAt_DEFAULT int64

func (p *ChatV3MessageDetail) GetCreatedAt() (v int64) {
	if !p.IsSetCreatedAt() {
		return ChatV3MessageDetail_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var ChatV3MessageDetail_UpdatedAt_DEFAULT int64

func (p *ChatV3MessageDetail) GetUpdatedAt() (v int64) {
	if !p.IsSetUpdatedAt() {
		return ChatV3MessageDetail_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}

var ChatV3MessageDetail_ReasoningContent_DEFAULT string

func (p *ChatV3MessageDetail) GetReasoningContent() (v string) {
	if !p.IsSetReasoningContent() {
		return ChatV3MessageDetail_ReasoningContent_DEFAULT
	}
	return *p.ReasoningContent
}
func (p *ChatV3MessageDetail) SetID(val string) {
	p.ID = val
}
func (p *ChatV3MessageDetail) SetConversationID(val string) {
	p.ConversationID = val
}
func (p *ChatV3MessageDetail) SetBotID(val string) {
	p.BotID = val
}
func (p *ChatV3MessageDetail) SetRole(val string) {
	p.Role = val
}
func (p *ChatV3MessageDetail) SetType(val string) {
	p.Type = val
}
func (p *ChatV3MessageDetail) SetContent(val string) {
	p.Content = val
}
func (p *ChatV3MessageDetail) SetContentType(val string) {
	p.ContentType = val
}
func (p *ChatV3MessageDetail) SetMetaData(val map[string]string) {
	p.MetaData = val
}
func (p *ChatV3MessageDetail) SetChatID(val string) {
	p.ChatID = val
}
func (p *ChatV3MessageDetail) SetSectionID(val *string) {
	p.SectionID = val
}
func (p *ChatV3MessageDetail) SetCreatedAt(val *int64) {
	p.CreatedAt = val
}
func (p *ChatV3MessageDetail) SetUpdatedAt(val *int64) {
	p.UpdatedAt = val
}
func (p *ChatV3MessageDetail) SetReasoningContent(val *string) {
	p.ReasoningContent = val
}

func (p *ChatV3MessageDetail) IsSetMetaData() bool {
	return p.MetaData != nil
}

func (p *ChatV3MessageDetail) IsSetSectionID() bool {
	return p.SectionID != nil
}

func (p *ChatV3MessageDetail) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *ChatV3MessageDetail) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *ChatV3MessageDetail) IsSetReasoningContent() bool {
	return p.ReasoningContent != nil
}

func (p *ChatV3MessageDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatV3MessageDetail(%+v)", *p)
}

type EnterMessage struct {
	Role        string            `thrift:"Role,1" json:"Role"`
	Content     string            `thrift:"Content,2" json:"Content"`
	MetaData    map[string]string `thrift:"MetaData,3" json:"MetaData"`
	ContentType string            `thrift:"ContentType,4" json:"ContentType"`
	Type        *string           `thrift:"Type,5,optional" json:"Type,omitempty"`
	Name        *string           `thrift:"Name,6,optional" json:"Name,omitempty"`
}

func NewEnterMessage() *EnterMessage {
	return &EnterMessage{}
}

func (p *EnterMessage) InitDefault() {
}

func (p *EnterMessage) GetRole() (v string) {
	return p.Role
}

func (p *EnterMessage) GetContent() (v string) {
	return p.Content
}

func (p *EnterMessage) GetMetaData() (v map[string]string) {
	return p.MetaData
}

func (p *EnterMessage) GetContentType() (v string) {
	return p.ContentType
}

var EnterMessage_Type_DEFAULT string

func (p *EnterMessage) GetType() (v string) {
	if !p.IsSetType() {
		return EnterMessage_Type_DEFAULT
	}
	return *p.Type
}

var EnterMessage_Name_DEFAULT string

func (p *EnterMessage) GetName() (v string) {
	if !p.IsSetName() {
		return EnterMessage_Name_DEFAULT
	}
	return *p.Name
}
func (p *EnterMessage) SetRole(val string) {
	p.Role = val
}
func (p *EnterMessage) SetContent(val string) {
	p.Content = val
}
func (p *EnterMessage) SetMetaData(val map[string]string) {
	p.MetaData = val
}
func (p *EnterMessage) SetContentType(val string) {
	p.ContentType = val
}
func (p *EnterMessage) SetType(val *string) {
	p.Type = val
}
func (p *EnterMessage) SetName(val *string) {
	p.Name = val
}

func (p *EnterMessage) IsSetType() bool {
	return p.Type != nil
}

func (p *EnterMessage) IsSetName() bool {
	return p.Name != nil
}

func (p *EnterMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EnterMessage(%+v)", *p)
}

type LastError struct {
	Code int32  `thrift:"Code,1,required" json:"Code"`
	Msg  string `thrift:"Msg,2,required" json:"Msg"`
}

func NewLastError() *LastError {
	return &LastError{}
}

func (p *LastError) InitDefault() {
}

func (p *LastError) GetCode() (v int32) {
	return p.Code
}

func (p *LastError) GetMsg() (v string) {
	return p.Msg
}
func (p *LastError) SetCode(val int32) {
	p.Code = val
}
func (p *LastError) SetMsg(val string) {
	p.Msg = val
}

func (p *LastError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LastError(%+v)", *p)
}

type Usage struct {
	TokenCount   *int32 `thrift:"TokenCount,1,optional" json:"TokenCount,omitempty"`
	OutputTokens *int32 `thrift:"OutputTokens,2,optional" json:"OutputTokens,omitempty"`
	InputTokens  *int32 `thrift:"InputTokens,3,optional" json:"InputTokens,omitempty"`
}

func NewUsage() *Usage {
	return &Usage{}
}

func (p *Usage) InitDefault() {
}

var Usage_TokenCount_DEFAULT int32

func (p *Usage) GetTokenCount() (v int32) {
	if !p.IsSetTokenCount() {
		return Usage_TokenCount_DEFAULT
	}
	return *p.TokenCount
}

var Usage_OutputTokens_DEFAULT int32

func (p *Usage) GetOutputTokens() (v int32) {
	if !p.IsSetOutputTokens() {
		return Usage_OutputTokens_DEFAULT
	}
	return *p.OutputTokens
}

var Usage_InputTokens_DEFAULT int32

func (p *Usage) GetInputTokens() (v int32) {
	if !p.IsSetInputTokens() {
		return Usage_InputTokens_DEFAULT
	}
	return *p.InputTokens
}
func (p *Usage) SetTokenCount(val *int32) {
	p.TokenCount = val
}
func (p *Usage) SetOutputTokens(val *int32) {
	p.OutputTokens = val
}
func (p *Usage) SetInputTokens(val *int32) {
	p.InputTokens = val
}

func (p *Usage) IsSetTokenCount() bool {
	return p.TokenCount != nil
}

func (p *Usage) IsSetOutputTokens() bool {
	return p.OutputTokens != nil
}

func (p *Usage) IsSetInputTokens() bool {
	return p.InputTokens != nil
}

func (p *Usage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Usage(%+v)", *p)
}

type RequiredAction struct {
	Type              string             `thrift:"Type,1" json:"Type"`
	SubmitToolOutputs *SubmitToolOutputs `thrift:"SubmitToolOutputs,2" json:"SubmitToolOutputs"`
}

func NewRequiredAction() *RequiredAction {
	return &RequiredAction{}
}

func (p *RequiredAction) InitDefault() {
}

func (p *RequiredAction) GetType() (v string) {
	return p.Type
}

var RequiredAction_SubmitToolOutputs_DEFAULT *SubmitToolOutputs

func (p *RequiredAction) GetSubmitToolOutputs() (v *SubmitToolOutputs) {
	if !p.IsSetSubmitToolOutputs() {
		return RequiredAction_SubmitToolOutputs_DEFAULT
	}
	return p.SubmitToolOutputs
}
func (p *RequiredAction) SetType(val string) {
	p.Type = val
}
func (p *RequiredAction) SetSubmitToolOutputs(val *SubmitToolOutputs) {
	p.SubmitToolOutputs = val
}

func (p *RequiredAction) IsSetSubmitToolOutputs() bool {
	return p.SubmitToolOutputs != nil
}

func (p *RequiredAction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequiredAction(%+v)", *p)
}

type SubmitToolOutputs struct {
	ToolCalls []*InterruptPlugin `thrift:"ToolCalls,1,default,list<InterruptPlugin>" json:"ToolCalls"`
}

func NewSubmitToolOutputs() *SubmitToolOutputs {
	return &SubmitToolOutputs{}
}

func (p *SubmitToolOutputs) InitDefault() {
}

func (p *SubmitToolOutputs) GetToolCalls() (v []*InterruptPlugin) {
	return p.ToolCalls
}
func (p *SubmitToolOutputs) SetToolCalls(val []*InterruptPlugin) {
	p.ToolCalls = val
}

func (p *SubmitToolOutputs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubmitToolOutputs(%+v)", *p)
}

type InterruptPlugin struct {
	ID          string                `thrift:"id,1" json:"id"`
	Type        string                `thrift:"type,2" json:"type"`
	Function    *InterruptFunction    `thrift:"function,3" json:"function"`
	RequireInfo *InterruptRequireInfo `thrift:"require_info,4" json:"require_info"`
}

func NewInterruptPlugin() *InterruptPlugin {
	return &InterruptPlugin{}
}

func (p *InterruptPlugin) InitDefault() {
}

func (p *InterruptPlugin) GetID() (v string) {
	return p.ID
}

func (p *InterruptPlugin) GetType() (v string) {
	return p.Type
}

var InterruptPlugin_Function_DEFAULT *InterruptFunction

func (p *InterruptPlugin) GetFunction() (v *InterruptFunction) {
	if !p.IsSetFunction() {
		return InterruptPlugin_Function_DEFAULT
	}
	return p.Function
}

var InterruptPlugin_RequireInfo_DEFAULT *InterruptRequireInfo

func (p *InterruptPlugin) GetRequireInfo() (v *InterruptRequireInfo) {
	if !p.IsSetRequireInfo() {
		return InterruptPlugin_RequireInfo_DEFAULT
	}
	return p.RequireInfo
}
func (p *InterruptPlugin) SetID(val string) {
	p.ID = val
}
func (p *InterruptPlugin) SetType(val string) {
	p.Type = val
}
func (p *InterruptPlugin) SetFunction(val *InterruptFunction) {
	p.Function = val
}
func (p *InterruptPlugin) SetRequireInfo(val *InterruptRequireInfo) {
	p.RequireInfo = val
}

func (p *InterruptPlugin) IsSetFunction() bool {
	return p.Function != nil
}

func (p *InterruptPlugin) IsSetRequireInfo() bool {
	return p.RequireInfo != nil
}

func (p *InterruptPlugin) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterruptPlugin(%+v)", *p)
}

type InterruptFunction struct {
	Name      string `thrift:"name,1" json:"name"`
	Arguments string `thrift:"arguments,2" json:"arguments"`
}

func NewInterruptFunction() *InterruptFunction {
	return &InterruptFunction{}
}

func (p *InterruptFunction) InitDefault() {
}

func (p *InterruptFunction) GetName() (v string) {
	return p.Name
}

func (p *InterruptFunction) GetArguments() (v string) {
	return p.Arguments
}
func (p *InterruptFunction) SetName(val string) {
	p.Name = val
}
func (p *InterruptFunction) SetArguments(val string) {
	p.Arguments = val
}

func (p *InterruptFunction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterruptFunction(%+v)", *p)
}

type InterruptRequireInfo struct {
	Infos []string `thrift:"infos,1,default,list<string>" json:"infos"`
}

func NewInterruptRequireInfo() *InterruptRequireInfo {
	return &InterruptRequireInfo{}
}

func (p *InterruptRequireInfo) InitDefault() {
}

func (p *InterruptRequireInfo) GetInfos() (v []string) {
	return p.Infos
}
func (p *InterruptRequireInfo) SetInfos(val []string) {
	p.Infos = val
}

func (p *InterruptRequireInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterruptRequireInfo(%+v)", *p)
}

type ChatV3ChatDetail struct {
	ID             int64             `thrift:"ID,1,required" json:"ID"`
	ConversationID int64             `thrift:"ConversationID,2,required" json:"ConversationID"`
	BotID          int64             `thrift:"BotID,3,required" json:"BotID"`
	CreatedAt      *int32            `thrift:"CreatedAt,4,optional" json:"CreatedAt,omitempty"`
	CompletedAt    *int32            `thrift:"CompletedAt,5,optional" json:"CompletedAt,omitempty"`
	FailedAt       *int32            `thrift:"FailedAt,6,optional" json:"FailedAt,omitempty"`
	MetaData       map[string]string `thrift:"MetaData,7,optional" json:"MetaData,omitempty"`
	LastError      *LastError        `thrift:"LastError,8,optional" json:"LastError,omitempty"`
	Status         string            `thrift:"Status,9,required" json:"Status"`
	Usage          *Usage            `thrift:"Usage,10,optional" json:"Usage,omitempty"`
	RequiredAction *RequiredAction   `thrift:"RequiredAction,11,optional" json:"RequiredAction,omitempty"`
	SectionID      *int64            `thrift:"SectionID,12,optional" json:"SectionID,omitempty"`
}

func NewChatV3ChatDetail() *ChatV3ChatDetail {
	return &ChatV3ChatDetail{}
}

func (p *ChatV3ChatDetail) InitDefault() {
}

func (p *ChatV3ChatDetail) GetID() (v int64) {
	return p.ID
}

func (p *ChatV3ChatDetail) GetConversationID() (v int64) {
	return p.ConversationID
}

func (p *ChatV3ChatDetail) GetBotID() (v int64) {
	return p.BotID
}

var ChatV3ChatDetail_CreatedAt_DEFAULT int32

func (p *ChatV3ChatDetail) GetCreatedAt() (v int32) {
	if !p.IsSetCreatedAt() {
		return ChatV3ChatDetail_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var ChatV3ChatDetail_CompletedAt_DEFAULT int32

func (p *ChatV3ChatDetail) GetCompletedAt() (v int32) {
	if !p.IsSetCompletedAt() {
		return ChatV3ChatDetail_CompletedAt_DEFAULT
	}
	return *p.CompletedAt
}

var ChatV3ChatDetail_FailedAt_DEFAULT int32

func (p *ChatV3ChatDetail) GetFailedAt() (v int32) {
	if !p.IsSetFailedAt() {
		return ChatV3ChatDetail_FailedAt_DEFAULT
	}
	return *p.FailedAt
}

var ChatV3ChatDetail_MetaData_DEFAULT map[string]string

func (p *ChatV3ChatDetail) GetMetaData() (v map[string]string) {
	if !p.IsSetMetaData() {
		return ChatV3ChatDetail_MetaData_DEFAULT
	}
	return p.MetaData
}

var ChatV3ChatDetail_LastError_DEFAULT *LastError

func (p *ChatV3ChatDetail) GetLastError() (v *LastError) {
	if !p.IsSetLastError() {
		return ChatV3ChatDetail_LastError_DEFAULT
	}
	return p.LastError
}

func (p *ChatV3ChatDetail) GetStatus() (v string) {
	return p.Status
}

var ChatV3ChatDetail_Usage_DEFAULT *Usage

func (p *ChatV3ChatDetail) GetUsage() (v *Usage) {
	if !p.IsSetUsage() {
		return ChatV3ChatDetail_Usage_DEFAULT
	}
	return p.Usage
}

var ChatV3ChatDetail_RequiredAction_DEFAULT *RequiredAction

func (p *ChatV3ChatDetail) GetRequiredAction() (v *RequiredAction) {
	if !p.IsSetRequiredAction() {
		return ChatV3ChatDetail_RequiredAction_DEFAULT
	}
	return p.RequiredAction
}

var ChatV3ChatDetail_SectionID_DEFAULT int64

func (p *ChatV3ChatDetail) GetSectionID() (v int64) {
	if !p.IsSetSectionID() {
		return ChatV3ChatDetail_SectionID_DEFAULT
	}
	return *p.SectionID
}
func (p *ChatV3ChatDetail) SetID(val int64) {
	p.ID = val
}
func (p *ChatV3ChatDetail) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *ChatV3ChatDetail) SetBotID(val int64) {
	p.BotID = val
}
func (p *ChatV3ChatDetail) SetCreatedAt(val *int32) {
	p.CreatedAt = val
}
func (p *ChatV3ChatDetail) SetCompletedAt(val *int32) {
	p.CompletedAt = val
}
func (p *ChatV3ChatDetail) SetFailedAt(val *int32) {
	p.FailedAt = val
}
func (p *ChatV3ChatDetail) SetMetaData(val map[string]string) {
	p.MetaData = val
}
func (p *ChatV3ChatDetail) SetLastError(val *LastError) {
	p.LastError = val
}
func (p *ChatV3ChatDetail) SetStatus(val string) {
	p.Status = val
}
func (p *ChatV3ChatDetail) SetUsage(val *Usage) {
	p.Usage = val
}
func (p *ChatV3ChatDetail) SetRequiredAction(val *RequiredAction) {
	p.RequiredAction = val
}
func (p *ChatV3ChatDetail) SetSectionID(val *int64) {
	p.SectionID = val
}

func (p *ChatV3ChatDetail) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *ChatV3ChatDetail) IsSetCompletedAt() bool {
	return p.CompletedAt != nil
}

func (p *ChatV3ChatDetail) IsSetFailedAt() bool {
	return p.FailedAt != nil
}

func (p *ChatV3ChatDetail) IsSetMetaData() bool {
	return p.MetaData != nil
}

func (p *ChatV3ChatDetail) IsSetLastError() bool {
	return p.LastError != nil
}

func (p *ChatV3ChatDetail) IsSetUsage() bool {
	return p.Usage != nil
}

func (p *ChatV3ChatDetail) IsSetRequiredAction() bool {
	return p.RequiredAction != nil
}

func (p *ChatV3ChatDetail) IsSetSectionID() bool {
	return p.SectionID != nil
}

func (p *ChatV3ChatDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatV3ChatDetail(%+v)", *p)
}

type ChatV3Response struct {
	ChatDetail *ChatV3ChatDetail `thrift:"ChatDetail,1,optional" json:"ChatDetail,omitempty"`
	Code       int32             `thrift:"Code,2,required" json:"Code"`
	Msg        string            `thrift:"Msg,3,required" json:"Msg"`
}

func NewChatV3Response() *ChatV3Response {
	return &ChatV3Response{}
}

func (p *ChatV3Response) InitDefault() {
}

var ChatV3Response_ChatDetail_DEFAULT *ChatV3ChatDetail

func (p *ChatV3Response) GetChatDetail() (v *ChatV3ChatDetail) {
	if !p.IsSetChatDetail() {
		return ChatV3Response_ChatDetail_DEFAULT
	}
	return p.ChatDetail
}

func (p *ChatV3Response) GetCode() (v int32) {
	return p.Code
}

func (p *ChatV3Response) GetMsg() (v string) {
	return p.Msg
}
func (p *ChatV3Response) SetChatDetail(val *ChatV3ChatDetail) {
	p.ChatDetail = val
}
func (p *ChatV3Response) SetCode(val int32) {
	p.Code = val
}
func (p *ChatV3Response) SetMsg(val string) {
	p.Msg = val
}

func (p *ChatV3Response) IsSetChatDetail() bool {
	return p.ChatDetail != nil
}

func (p *ChatV3Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatV3Response(%+v)", *p)
}

type CancelChatApiRequest struct {
	ChatID         int64      `thrift:"ChatID,1,required" json:"ChatID"`
	ConversationID int64      `thrift:"ConversationID,2,required" json:"ConversationID"`
	Base           *base.Base `thrift:"Base,255" json:"Base"`
}

func NewCancelChatApiRequest() *CancelChatApiRequest {
	return &CancelChatApiRequest{}
}

func (p *CancelChatApiRequest) InitDefault() {
}

func (p *CancelChatApiRequest) GetChatID() (v int64) {
	return p.ChatID
}

func (p *CancelChatApiRequest) GetConversationID() (v int64) {
	return p.ConversationID
}

var CancelChatApiRequest_Base_DEFAULT *base.Base

func (p *CancelChatApiRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return CancelChatApiRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *CancelChatApiRequest) SetChatID(val int64) {
	p.ChatID = val
}
func (p *CancelChatApiRequest) SetConversationID(val int64) {
	p.ConversationID = val
}
func (p *CancelChatApiRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *CancelChatApiRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *CancelChatApiRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelChatApiRequest(%+v)", *p)
}

type CancelChatApiResponse struct {
	ChatV3ChatDetail *ChatV3ChatDetail `thrift:"ChatV3ChatDetail,1" json:"ChatV3ChatDetail"`
	BaseResp         *base.BaseResp    `thrift:"BaseResp,255" json:"BaseResp"`
}

func NewCancelChatApiResponse() *CancelChatApiResponse {
	return &CancelChatApiResponse{}
}

func (p *CancelChatApiResponse) InitDefault() {
}

var CancelChatApiResponse_ChatV3ChatDetail_DEFAULT *ChatV3ChatDetail

func (p *CancelChatApiResponse) GetChatV3ChatDetail() (v *ChatV3ChatDetail) {
	if !p.IsSetChatV3ChatDetail() {
		return CancelChatApiResponse_ChatV3ChatDetail_DEFAULT
	}
	return p.ChatV3ChatDetail
}

var CancelChatApiResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CancelChatApiResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CancelChatApiResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CancelChatApiResponse) SetChatV3ChatDetail(val *ChatV3ChatDetail) {
	p.ChatV3ChatDetail = val
}
func (p *CancelChatApiResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CancelChatApiResponse) IsSetChatV3ChatDetail() bool {
	return p.ChatV3ChatDetail != nil
}

func (p *CancelChatApiResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CancelChatApiResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelChatApiResponse(%+v)", *p)
}
