// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package airi

import (
	"github.com/kiosk404/airi-go/backend/api/model/app/bot_open_api"
	"github.com/kiosk404/airi-go/backend/api/model/llm/manage"
	"github.com/kiosk404/airi-go/backend/api/model/llm/runtime"
	"github.com/kiosk404/airi-go/backend/api/model/passport"
	"github.com/kiosk404/airi-go/backend/api/model/permission/openapiauth"
)

type BotOpenApiService interface {
	bot_open_api.BotOpenApiService
}

type OpenAPIAuthService interface {
	openapiauth.OpenAPIAuthService
}

type PassportService interface {
	passport.PassportService
}

type LLMManageService interface {
	manage.LLMManageService
}

type LLMRuntimeService interface {
	runtime.LLMRuntimeService
}
