// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package airi

import (
	"github.com/kiosk404/airi-go/backend/api/model/app/bot_open_api"
	"github.com/kiosk404/airi-go/backend/api/model/app/developer_api"
	"github.com/kiosk404/airi-go/backend/api/model/component/plugin_develop"
	"github.com/kiosk404/airi-go/backend/api/model/conversation/agentrun"
	"github.com/kiosk404/airi-go/backend/api/model/conversation/conversation"
	"github.com/kiosk404/airi-go/backend/api/model/conversation/message"
	"github.com/kiosk404/airi-go/backend/api/model/foundation/openapiauth"
	"github.com/kiosk404/airi-go/backend/api/model/foundation/user"
	"github.com/kiosk404/airi-go/backend/api/model/llm/manage"
	"github.com/kiosk404/airi-go/backend/api/model/llm/runtime"
	"github.com/kiosk404/airi-go/backend/api/model/playground"
)

type BotOpenApiService interface {
	bot_open_api.BotOpenApiService
}

type DeveloperApiService interface {
	developer_api.DeveloperApiService
}

type OpenAPIAuthService interface {
	openapiauth.OpenAPIAuthService
}

type UserService interface {
	user.UserService
}

type LLMManageService interface {
	manage.LLMManageService
}

type LLMRuntimeService interface {
	runtime.LLMRuntimeService
}

type PluginDevelopService interface {
	plugin_develop.PluginDevelopService
}

type AgentRunService interface {
	agentrun.AgentRunService
}

type MessageService interface {
	message.MessageService
}

type ConversationService interface {
	conversation.ConversationService
}

type PlaygroundService interface {
	playground.PlaygroundService
}
