// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package intelligence

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/kiosk404/airi-go/backend/api/model/app/intelligence/common"
	"github.com/kiosk404/airi-go/backend/api/model/base"
)

type OrderBy int64

const (
	OrderBy_UpdateTime  OrderBy = 0
	OrderBy_CreateTime  OrderBy = 1
	OrderBy_PublishTime OrderBy = 2
)

func (p OrderBy) String() string {
	switch p {
	case OrderBy_UpdateTime:
		return "UpdateTime"
	case OrderBy_CreateTime:
		return "CreateTime"
	case OrderBy_PublishTime:
		return "PublishTime"
	}
	return "<UNSET>"
}

func OrderByFromString(s string) (OrderBy, error) {
	switch s {
	case "UpdateTime":
		return OrderBy_UpdateTime, nil
	case "CreateTime":
		return OrderBy_CreateTime, nil
	case "PublishTime":
		return OrderBy_PublishTime, nil
	}
	return OrderBy(0), fmt.Errorf("not a valid OrderBy string")
}

func OrderByPtr(v OrderBy) *OrderBy { return &v }
func (p *OrderBy) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OrderBy(result.Int64)
	return
}

func (p *OrderBy) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OceanProjectOrderBy int64

const (
	OceanProjectOrderBy_UpdateTime OceanProjectOrderBy = 0
	OceanProjectOrderBy_CreateTime OceanProjectOrderBy = 1
)

func (p OceanProjectOrderBy) String() string {
	switch p {
	case OceanProjectOrderBy_UpdateTime:
		return "UpdateTime"
	case OceanProjectOrderBy_CreateTime:
		return "CreateTime"
	}
	return "<UNSET>"
}

func OceanProjectOrderByFromString(s string) (OceanProjectOrderBy, error) {
	switch s {
	case "UpdateTime":
		return OceanProjectOrderBy_UpdateTime, nil
	case "CreateTime":
		return OceanProjectOrderBy_CreateTime, nil
	}
	return OceanProjectOrderBy(0), fmt.Errorf("not a valid OceanProjectOrderBy string")
}

func OceanProjectOrderByPtr(v OceanProjectOrderBy) *OceanProjectOrderBy { return &v }
func (p *OceanProjectOrderBy) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OceanProjectOrderBy(result.Int64)
	return
}

func (p *OceanProjectOrderBy) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type SearchScope int64

const (
	SearchScope_All        SearchScope = 0
	SearchScope_CreateByMe SearchScope = 1
)

func (p SearchScope) String() string {
	switch p {
	case SearchScope_All:
		return "All"
	case SearchScope_CreateByMe:
		return "CreateByMe"
	}
	return "<UNSET>"
}

func SearchScopeFromString(s string) (SearchScope, error) {
	switch s {
	case "All":
		return SearchScope_All, nil
	case "CreateByMe":
		return SearchScope_CreateByMe, nil
	}
	return SearchScope(0), fmt.Errorf("not a valid SearchScope string")
}

func SearchScopePtr(v SearchScope) *SearchScope { return &v }
func (p *SearchScope) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = SearchScope(result.Int64)
	return
}

func (p *SearchScope) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type BotMode int64

const (
	BotMode_SingleMode   BotMode = 0
	BotMode_MultiMode    BotMode = 1
	BotMode_WorkflowMode BotMode = 2
)

func (p BotMode) String() string {
	switch p {
	case BotMode_SingleMode:
		return "SingleMode"
	case BotMode_MultiMode:
		return "MultiMode"
	case BotMode_WorkflowMode:
		return "WorkflowMode"
	}
	return "<UNSET>"
}

func BotModeFromString(s string) (BotMode, error) {
	switch s {
	case "SingleMode":
		return BotMode_SingleMode, nil
	case "MultiMode":
		return BotMode_MultiMode, nil
	case "WorkflowMode":
		return BotMode_WorkflowMode, nil
	}
	return BotMode(0), fmt.Errorf("not a valid BotMode string")
}

func BotModePtr(v BotMode) *BotMode { return &v }
func (p *BotMode) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = BotMode(result.Int64)
	return
}

func (p *BotMode) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type GetDraftIntelligenceListOption struct {
	NeedReplica bool `thrift:"need_replica,1" json:"need_replica"`
}

func NewGetDraftIntelligenceListOption() *GetDraftIntelligenceListOption {
	return &GetDraftIntelligenceListOption{}
}

func (p *GetDraftIntelligenceListOption) InitDefault() {
}

func (p *GetDraftIntelligenceListOption) GetNeedReplica() (v bool) {
	return p.NeedReplica
}
func (p *GetDraftIntelligenceListOption) SetNeedReplica(val bool) {
	p.NeedReplica = val
}

func (p *GetDraftIntelligenceListOption) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDraftIntelligenceListOption(%+v)", *p)
}

type GetDraftIntelligenceListRequest struct {
	SpaceID      int64                           `thrift:"space_id,1,required" json:"space_id"`
	Name         *string                         `thrift:"name,2,optional" json:"name,omitempty"`
	HasPublished *bool                           `thrift:"has_published,3,optional" json:"has_published,omitempty"`
	Status       []common.IntelligenceStatus     `thrift:"status,4,optional,list<IntelligenceStatus>" json:"status,omitempty"`
	Types        []common.IntelligenceType       `thrift:"types,5,optional,list<IntelligenceType>" json:"types,omitempty"`
	SearchScope  *SearchScope                    `thrift:"search_scope,6,optional,SearchScope" json:"search_scope,omitempty"`
	IsFav        *bool                           `thrift:"is_fav,51,optional" json:"is_fav,omitempty"`
	RecentlyOpen *bool                           `thrift:"recently_open,52,optional" json:"recently_open,omitempty"`
	Option       *GetDraftIntelligenceListOption `thrift:"option,99,optional" json:"option,omitempty"`
	OrderBy      *OrderBy                        `thrift:"order_by,100,optional,OrderBy" json:"order_by,omitempty"`
	CursorID     *string                         `thrift:"cursor_id,101,optional" json:"cursor_id,omitempty"`
	Size         *int32                          `thrift:"size,102,optional" json:"size,omitempty"`
	Base         *base.Base                      `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewGetDraftIntelligenceListRequest() *GetDraftIntelligenceListRequest {
	return &GetDraftIntelligenceListRequest{}
}

func (p *GetDraftIntelligenceListRequest) InitDefault() {
}

func (p *GetDraftIntelligenceListRequest) GetSpaceID() (v int64) {
	return p.SpaceID
}

var GetDraftIntelligenceListRequest_Name_DEFAULT string

func (p *GetDraftIntelligenceListRequest) GetName() (v string) {
	if !p.IsSetName() {
		return GetDraftIntelligenceListRequest_Name_DEFAULT
	}
	return *p.Name
}

var GetDraftIntelligenceListRequest_HasPublished_DEFAULT bool

func (p *GetDraftIntelligenceListRequest) GetHasPublished() (v bool) {
	if !p.IsSetHasPublished() {
		return GetDraftIntelligenceListRequest_HasPublished_DEFAULT
	}
	return *p.HasPublished
}

var GetDraftIntelligenceListRequest_Status_DEFAULT []common.IntelligenceStatus

func (p *GetDraftIntelligenceListRequest) GetStatus() (v []common.IntelligenceStatus) {
	if !p.IsSetStatus() {
		return GetDraftIntelligenceListRequest_Status_DEFAULT
	}
	return p.Status
}

var GetDraftIntelligenceListRequest_Types_DEFAULT []common.IntelligenceType

func (p *GetDraftIntelligenceListRequest) GetTypes() (v []common.IntelligenceType) {
	if !p.IsSetTypes() {
		return GetDraftIntelligenceListRequest_Types_DEFAULT
	}
	return p.Types
}

var GetDraftIntelligenceListRequest_SearchScope_DEFAULT SearchScope

func (p *GetDraftIntelligenceListRequest) GetSearchScope() (v SearchScope) {
	if !p.IsSetSearchScope() {
		return GetDraftIntelligenceListRequest_SearchScope_DEFAULT
	}
	return *p.SearchScope
}

var GetDraftIntelligenceListRequest_IsFav_DEFAULT bool

func (p *GetDraftIntelligenceListRequest) GetIsFav() (v bool) {
	if !p.IsSetIsFav() {
		return GetDraftIntelligenceListRequest_IsFav_DEFAULT
	}
	return *p.IsFav
}

var GetDraftIntelligenceListRequest_RecentlyOpen_DEFAULT bool

func (p *GetDraftIntelligenceListRequest) GetRecentlyOpen() (v bool) {
	if !p.IsSetRecentlyOpen() {
		return GetDraftIntelligenceListRequest_RecentlyOpen_DEFAULT
	}
	return *p.RecentlyOpen
}

var GetDraftIntelligenceListRequest_Option_DEFAULT *GetDraftIntelligenceListOption

func (p *GetDraftIntelligenceListRequest) GetOption() (v *GetDraftIntelligenceListOption) {
	if !p.IsSetOption() {
		return GetDraftIntelligenceListRequest_Option_DEFAULT
	}
	return p.Option
}

var GetDraftIntelligenceListRequest_OrderBy_DEFAULT OrderBy

func (p *GetDraftIntelligenceListRequest) GetOrderBy() (v OrderBy) {
	if !p.IsSetOrderBy() {
		return GetDraftIntelligenceListRequest_OrderBy_DEFAULT
	}
	return *p.OrderBy
}

var GetDraftIntelligenceListRequest_CursorID_DEFAULT string

func (p *GetDraftIntelligenceListRequest) GetCursorID() (v string) {
	if !p.IsSetCursorID() {
		return GetDraftIntelligenceListRequest_CursorID_DEFAULT
	}
	return *p.CursorID
}

var GetDraftIntelligenceListRequest_Size_DEFAULT int32

func (p *GetDraftIntelligenceListRequest) GetSize() (v int32) {
	if !p.IsSetSize() {
		return GetDraftIntelligenceListRequest_Size_DEFAULT
	}
	return *p.Size
}

var GetDraftIntelligenceListRequest_Base_DEFAULT *base.Base

func (p *GetDraftIntelligenceListRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetDraftIntelligenceListRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *GetDraftIntelligenceListRequest) SetSpaceID(val int64) {
	p.SpaceID = val
}
func (p *GetDraftIntelligenceListRequest) SetName(val *string) {
	p.Name = val
}
func (p *GetDraftIntelligenceListRequest) SetHasPublished(val *bool) {
	p.HasPublished = val
}
func (p *GetDraftIntelligenceListRequest) SetStatus(val []common.IntelligenceStatus) {
	p.Status = val
}
func (p *GetDraftIntelligenceListRequest) SetTypes(val []common.IntelligenceType) {
	p.Types = val
}
func (p *GetDraftIntelligenceListRequest) SetSearchScope(val *SearchScope) {
	p.SearchScope = val
}
func (p *GetDraftIntelligenceListRequest) SetIsFav(val *bool) {
	p.IsFav = val
}
func (p *GetDraftIntelligenceListRequest) SetRecentlyOpen(val *bool) {
	p.RecentlyOpen = val
}
func (p *GetDraftIntelligenceListRequest) SetOption(val *GetDraftIntelligenceListOption) {
	p.Option = val
}
func (p *GetDraftIntelligenceListRequest) SetOrderBy(val *OrderBy) {
	p.OrderBy = val
}
func (p *GetDraftIntelligenceListRequest) SetCursorID(val *string) {
	p.CursorID = val
}
func (p *GetDraftIntelligenceListRequest) SetSize(val *int32) {
	p.Size = val
}
func (p *GetDraftIntelligenceListRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetDraftIntelligenceListRequest) IsSetName() bool {
	return p.Name != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetHasPublished() bool {
	return p.HasPublished != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetTypes() bool {
	return p.Types != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetSearchScope() bool {
	return p.SearchScope != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetIsFav() bool {
	return p.IsFav != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetRecentlyOpen() bool {
	return p.RecentlyOpen != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetOption() bool {
	return p.Option != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetOrderBy() bool {
	return p.OrderBy != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetCursorID() bool {
	return p.CursorID != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetSize() bool {
	return p.Size != nil
}

func (p *GetDraftIntelligenceListRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetDraftIntelligenceListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDraftIntelligenceListRequest(%+v)", *p)
}

type IntelligencePublishInfo struct {
	PublishTime  string                  `thrift:"publish_time,1" json:"publish_time"`
	HasPublished bool                    `thrift:"has_published,2" json:"has_published"`
	Connectors   []*common.ConnectorInfo `thrift:"connectors,3,default,list<common.ConnectorInfo>" json:"connectors"`
}

func NewIntelligencePublishInfo() *IntelligencePublishInfo {
	return &IntelligencePublishInfo{}
}

func (p *IntelligencePublishInfo) InitDefault() {
}

func (p *IntelligencePublishInfo) GetPublishTime() (v string) {
	return p.PublishTime
}

func (p *IntelligencePublishInfo) GetHasPublished() (v bool) {
	return p.HasPublished
}

func (p *IntelligencePublishInfo) GetConnectors() (v []*common.ConnectorInfo) {
	return p.Connectors
}
func (p *IntelligencePublishInfo) SetPublishTime(val string) {
	p.PublishTime = val
}
func (p *IntelligencePublishInfo) SetHasPublished(val bool) {
	p.HasPublished = val
}
func (p *IntelligencePublishInfo) SetConnectors(val []*common.ConnectorInfo) {
	p.Connectors = val
}

func (p *IntelligencePublishInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IntelligencePublishInfo(%+v)", *p)
}

type IntelligencePermissionInfo struct {
	InCollaboration bool `thrift:"in_collaboration,1" json:"in_collaboration"`
	CanDelete       bool `thrift:"can_delete,2" json:"can_delete"`
	CanView         bool `thrift:"can_view,3" json:"can_view"`
}

func NewIntelligencePermissionInfo() *IntelligencePermissionInfo {
	return &IntelligencePermissionInfo{}
}

func (p *IntelligencePermissionInfo) InitDefault() {
}

func (p *IntelligencePermissionInfo) GetInCollaboration() (v bool) {
	return p.InCollaboration
}

func (p *IntelligencePermissionInfo) GetCanDelete() (v bool) {
	return p.CanDelete
}

func (p *IntelligencePermissionInfo) GetCanView() (v bool) {
	return p.CanView
}
func (p *IntelligencePermissionInfo) SetInCollaboration(val bool) {
	p.InCollaboration = val
}
func (p *IntelligencePermissionInfo) SetCanDelete(val bool) {
	p.CanDelete = val
}
func (p *IntelligencePermissionInfo) SetCanView(val bool) {
	p.CanView = val
}

func (p *IntelligencePermissionInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IntelligencePermissionInfo(%+v)", *p)
}

type FavoriteInfo struct {
	IsFav   bool   `thrift:"is_fav,1" json:"is_fav"`
	FavTime string `thrift:"fav_time,2" json:"fav_time"`
}

func NewFavoriteInfo() *FavoriteInfo {
	return &FavoriteInfo{}
}

func (p *FavoriteInfo) InitDefault() {
}

func (p *FavoriteInfo) GetIsFav() (v bool) {
	return p.IsFav
}

func (p *FavoriteInfo) GetFavTime() (v string) {
	return p.FavTime
}
func (p *FavoriteInfo) SetIsFav(val bool) {
	p.IsFav = val
}
func (p *FavoriteInfo) SetFavTime(val string) {
	p.FavTime = val
}

func (p *FavoriteInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FavoriteInfo(%+v)", *p)
}

type OtherInfo struct {
	RecentlyOpenTime string  `thrift:"recently_open_time,1" json:"recently_open_time"`
	BotMode          BotMode `thrift:"bot_mode,2,default,BotMode" json:"bot_mode"`
}

func NewOtherInfo() *OtherInfo {
	return &OtherInfo{}
}

func (p *OtherInfo) InitDefault() {
}

func (p *OtherInfo) GetRecentlyOpenTime() (v string) {
	return p.RecentlyOpenTime
}

func (p *OtherInfo) GetBotMode() (v BotMode) {
	return p.BotMode
}
func (p *OtherInfo) SetRecentlyOpenTime(val string) {
	p.RecentlyOpenTime = val
}
func (p *OtherInfo) SetBotMode(val BotMode) {
	p.BotMode = val
}

func (p *OtherInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OtherInfo(%+v)", *p)
}

type Intelligence struct {
	BasicInfo      *common.IntelligenceBasicInfo `thrift:"basic_info,1" json:"basic_info"`
	Type           common.IntelligenceType       `thrift:"type,2,default,IntelligenceType" json:"type"`
	PublishInfo    *IntelligencePublishInfo      `thrift:"publish_info,3" json:"publish_info"`
	OwnerInfo      *common.User                  `thrift:"owner_info,4" json:"owner_info"`
	PermissionInfo *IntelligencePermissionInfo   `thrift:"permission_info,5" json:"permission_info"`
}

func NewIntelligence() *Intelligence {
	return &Intelligence{}
}

func (p *Intelligence) InitDefault() {
}

var Intelligence_BasicInfo_DEFAULT *common.IntelligenceBasicInfo

func (p *Intelligence) GetBasicInfo() (v *common.IntelligenceBasicInfo) {
	if !p.IsSetBasicInfo() {
		return Intelligence_BasicInfo_DEFAULT
	}
	return p.BasicInfo
}

func (p *Intelligence) GetType() (v common.IntelligenceType) {
	return p.Type
}

var Intelligence_PublishInfo_DEFAULT *IntelligencePublishInfo

func (p *Intelligence) GetPublishInfo() (v *IntelligencePublishInfo) {
	if !p.IsSetPublishInfo() {
		return Intelligence_PublishInfo_DEFAULT
	}
	return p.PublishInfo
}

var Intelligence_OwnerInfo_DEFAULT *common.User

func (p *Intelligence) GetOwnerInfo() (v *common.User) {
	if !p.IsSetOwnerInfo() {
		return Intelligence_OwnerInfo_DEFAULT
	}
	return p.OwnerInfo
}

var Intelligence_PermissionInfo_DEFAULT *IntelligencePermissionInfo

func (p *Intelligence) GetPermissionInfo() (v *IntelligencePermissionInfo) {
	if !p.IsSetPermissionInfo() {
		return Intelligence_PermissionInfo_DEFAULT
	}
	return p.PermissionInfo
}
func (p *Intelligence) SetBasicInfo(val *common.IntelligenceBasicInfo) {
	p.BasicInfo = val
}
func (p *Intelligence) SetType(val common.IntelligenceType) {
	p.Type = val
}
func (p *Intelligence) SetPublishInfo(val *IntelligencePublishInfo) {
	p.PublishInfo = val
}
func (p *Intelligence) SetOwnerInfo(val *common.User) {
	p.OwnerInfo = val
}
func (p *Intelligence) SetPermissionInfo(val *IntelligencePermissionInfo) {
	p.PermissionInfo = val
}

func (p *Intelligence) IsSetBasicInfo() bool {
	return p.BasicInfo != nil
}

func (p *Intelligence) IsSetPublishInfo() bool {
	return p.PublishInfo != nil
}

func (p *Intelligence) IsSetOwnerInfo() bool {
	return p.OwnerInfo != nil
}

func (p *Intelligence) IsSetPermissionInfo() bool {
	return p.PermissionInfo != nil
}

func (p *Intelligence) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Intelligence(%+v)", *p)
}

type IntelligenceData struct {
	BasicInfo       *common.IntelligenceBasicInfo `thrift:"basic_info,1" json:"basic_info"`
	Type            common.IntelligenceType       `thrift:"type,2,default,IntelligenceType" json:"type"`
	PublishInfo     *IntelligencePublishInfo      `thrift:"publish_info,3" json:"publish_info"`
	PermissionInfo  *IntelligencePermissionInfo   `thrift:"permission_info,4" json:"permission_info"`
	OwnerInfo       *common.User                  `thrift:"owner_info,5" json:"owner_info"`
	LatestAuditInfo *common.AuditInfo             `thrift:"latest_audit_info,6" json:"latest_audit_info"`
	FavoriteInfo    *FavoriteInfo                 `thrift:"favorite_info,7" json:"favorite_info"`
	OtherInfo       *OtherInfo                    `thrift:"other_info,50" json:"other_info"`
}

func NewIntelligenceData() *IntelligenceData {
	return &IntelligenceData{}
}

func (p *IntelligenceData) InitDefault() {
}

var IntelligenceData_BasicInfo_DEFAULT *common.IntelligenceBasicInfo

func (p *IntelligenceData) GetBasicInfo() (v *common.IntelligenceBasicInfo) {
	if !p.IsSetBasicInfo() {
		return IntelligenceData_BasicInfo_DEFAULT
	}
	return p.BasicInfo
}

func (p *IntelligenceData) GetType() (v common.IntelligenceType) {
	return p.Type
}

var IntelligenceData_PublishInfo_DEFAULT *IntelligencePublishInfo

func (p *IntelligenceData) GetPublishInfo() (v *IntelligencePublishInfo) {
	if !p.IsSetPublishInfo() {
		return IntelligenceData_PublishInfo_DEFAULT
	}
	return p.PublishInfo
}

var IntelligenceData_PermissionInfo_DEFAULT *IntelligencePermissionInfo

func (p *IntelligenceData) GetPermissionInfo() (v *IntelligencePermissionInfo) {
	if !p.IsSetPermissionInfo() {
		return IntelligenceData_PermissionInfo_DEFAULT
	}
	return p.PermissionInfo
}

var IntelligenceData_OwnerInfo_DEFAULT *common.User

func (p *IntelligenceData) GetOwnerInfo() (v *common.User) {
	if !p.IsSetOwnerInfo() {
		return IntelligenceData_OwnerInfo_DEFAULT
	}
	return p.OwnerInfo
}

var IntelligenceData_LatestAuditInfo_DEFAULT *common.AuditInfo

func (p *IntelligenceData) GetLatestAuditInfo() (v *common.AuditInfo) {
	if !p.IsSetLatestAuditInfo() {
		return IntelligenceData_LatestAuditInfo_DEFAULT
	}
	return p.LatestAuditInfo
}

var IntelligenceData_FavoriteInfo_DEFAULT *FavoriteInfo

func (p *IntelligenceData) GetFavoriteInfo() (v *FavoriteInfo) {
	if !p.IsSetFavoriteInfo() {
		return IntelligenceData_FavoriteInfo_DEFAULT
	}
	return p.FavoriteInfo
}

var IntelligenceData_OtherInfo_DEFAULT *OtherInfo

func (p *IntelligenceData) GetOtherInfo() (v *OtherInfo) {
	if !p.IsSetOtherInfo() {
		return IntelligenceData_OtherInfo_DEFAULT
	}
	return p.OtherInfo
}
func (p *IntelligenceData) SetBasicInfo(val *common.IntelligenceBasicInfo) {
	p.BasicInfo = val
}
func (p *IntelligenceData) SetType(val common.IntelligenceType) {
	p.Type = val
}
func (p *IntelligenceData) SetPublishInfo(val *IntelligencePublishInfo) {
	p.PublishInfo = val
}
func (p *IntelligenceData) SetPermissionInfo(val *IntelligencePermissionInfo) {
	p.PermissionInfo = val
}
func (p *IntelligenceData) SetOwnerInfo(val *common.User) {
	p.OwnerInfo = val
}
func (p *IntelligenceData) SetLatestAuditInfo(val *common.AuditInfo) {
	p.LatestAuditInfo = val
}
func (p *IntelligenceData) SetFavoriteInfo(val *FavoriteInfo) {
	p.FavoriteInfo = val
}
func (p *IntelligenceData) SetOtherInfo(val *OtherInfo) {
	p.OtherInfo = val
}

func (p *IntelligenceData) IsSetBasicInfo() bool {
	return p.BasicInfo != nil
}

func (p *IntelligenceData) IsSetPublishInfo() bool {
	return p.PublishInfo != nil
}

func (p *IntelligenceData) IsSetPermissionInfo() bool {
	return p.PermissionInfo != nil
}

func (p *IntelligenceData) IsSetOwnerInfo() bool {
	return p.OwnerInfo != nil
}

func (p *IntelligenceData) IsSetLatestAuditInfo() bool {
	return p.LatestAuditInfo != nil
}

func (p *IntelligenceData) IsSetFavoriteInfo() bool {
	return p.FavoriteInfo != nil
}

func (p *IntelligenceData) IsSetOtherInfo() bool {
	return p.OtherInfo != nil
}

func (p *IntelligenceData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IntelligenceData(%+v)", *p)
}

type DraftIntelligenceListData struct {
	Intelligences []*IntelligenceData `thrift:"intelligences,1,default,list<IntelligenceData>" json:"intelligences"`
	Total         int32               `thrift:"total,2" json:"total"`
	HasMore       bool                `thrift:"has_more,3" json:"has_more"`
	NextCursorID  string              `thrift:"next_cursor_id,4" json:"next_cursor_id"`
}

func NewDraftIntelligenceListData() *DraftIntelligenceListData {
	return &DraftIntelligenceListData{}
}

func (p *DraftIntelligenceListData) InitDefault() {
}

func (p *DraftIntelligenceListData) GetIntelligences() (v []*IntelligenceData) {
	return p.Intelligences
}

func (p *DraftIntelligenceListData) GetTotal() (v int32) {
	return p.Total
}

func (p *DraftIntelligenceListData) GetHasMore() (v bool) {
	return p.HasMore
}

func (p *DraftIntelligenceListData) GetNextCursorID() (v string) {
	return p.NextCursorID
}
func (p *DraftIntelligenceListData) SetIntelligences(val []*IntelligenceData) {
	p.Intelligences = val
}
func (p *DraftIntelligenceListData) SetTotal(val int32) {
	p.Total = val
}
func (p *DraftIntelligenceListData) SetHasMore(val bool) {
	p.HasMore = val
}
func (p *DraftIntelligenceListData) SetNextCursorID(val string) {
	p.NextCursorID = val
}

func (p *DraftIntelligenceListData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DraftIntelligenceListData(%+v)", *p)
}

type GetDraftIntelligenceListResponse struct {
	Data     *DraftIntelligenceListData `thrift:"data,1" json:"data"`
	Code     int32                      `thrift:"code,253" json:"code"`
	Msg      string                     `thrift:"msg,254" json:"msg"`
	BaseResp *base.BaseResp             `thrift:"BaseResp,255,optional" json:"BaseResp,omitempty"`
}

func NewGetDraftIntelligenceListResponse() *GetDraftIntelligenceListResponse {
	return &GetDraftIntelligenceListResponse{}
}

func (p *GetDraftIntelligenceListResponse) InitDefault() {
}

var GetDraftIntelligenceListResponse_Data_DEFAULT *DraftIntelligenceListData

func (p *GetDraftIntelligenceListResponse) GetData() (v *DraftIntelligenceListData) {
	if !p.IsSetData() {
		return GetDraftIntelligenceListResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *GetDraftIntelligenceListResponse) GetCode() (v int32) {
	return p.Code
}

func (p *GetDraftIntelligenceListResponse) GetMsg() (v string) {
	return p.Msg
}

var GetDraftIntelligenceListResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetDraftIntelligenceListResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetDraftIntelligenceListResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetDraftIntelligenceListResponse) SetData(val *DraftIntelligenceListData) {
	p.Data = val
}
func (p *GetDraftIntelligenceListResponse) SetCode(val int32) {
	p.Code = val
}
func (p *GetDraftIntelligenceListResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *GetDraftIntelligenceListResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetDraftIntelligenceListResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetDraftIntelligenceListResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetDraftIntelligenceListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDraftIntelligenceListResponse(%+v)", *p)
}

type GetDraftIntelligenceInfoRequest struct {
	IntelligenceID   int64                   `thrift:"intelligence_id,1" json:"intelligence_id"`
	IntelligenceType common.IntelligenceType `thrift:"intelligence_type,2,default,IntelligenceType" json:"intelligence_type"`
	Version          *int64                  `thrift:"version,3,optional" json:"version,omitempty"`
	Base             *base.Base              `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewGetDraftIntelligenceInfoRequest() *GetDraftIntelligenceInfoRequest {
	return &GetDraftIntelligenceInfoRequest{}
}

func (p *GetDraftIntelligenceInfoRequest) InitDefault() {
}

func (p *GetDraftIntelligenceInfoRequest) GetIntelligenceID() (v int64) {
	return p.IntelligenceID
}

func (p *GetDraftIntelligenceInfoRequest) GetIntelligenceType() (v common.IntelligenceType) {
	return p.IntelligenceType
}

var GetDraftIntelligenceInfoRequest_Version_DEFAULT int64

func (p *GetDraftIntelligenceInfoRequest) GetVersion() (v int64) {
	if !p.IsSetVersion() {
		return GetDraftIntelligenceInfoRequest_Version_DEFAULT
	}
	return *p.Version
}

var GetDraftIntelligenceInfoRequest_Base_DEFAULT *base.Base

func (p *GetDraftIntelligenceInfoRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetDraftIntelligenceInfoRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *GetDraftIntelligenceInfoRequest) SetIntelligenceID(val int64) {
	p.IntelligenceID = val
}
func (p *GetDraftIntelligenceInfoRequest) SetIntelligenceType(val common.IntelligenceType) {
	p.IntelligenceType = val
}
func (p *GetDraftIntelligenceInfoRequest) SetVersion(val *int64) {
	p.Version = val
}
func (p *GetDraftIntelligenceInfoRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetDraftIntelligenceInfoRequest) IsSetVersion() bool {
	return p.Version != nil
}

func (p *GetDraftIntelligenceInfoRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetDraftIntelligenceInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDraftIntelligenceInfoRequest(%+v)", *p)
}

type GetDraftIntelligenceInfoData struct {
	IntelligenceType common.IntelligenceType       `thrift:"intelligence_type,1,default,IntelligenceType" json:"intelligence_type"`
	BasicInfo        *common.IntelligenceBasicInfo `thrift:"basic_info,2" json:"basic_info"`
	PublishInfo      *IntelligencePublishInfo      `thrift:"publish_info,3,optional" json:"publish_info,omitempty"`
	OwnerInfo        *common.User                  `thrift:"owner_info,4,optional" json:"owner_info,omitempty"`
}

func NewGetDraftIntelligenceInfoData() *GetDraftIntelligenceInfoData {
	return &GetDraftIntelligenceInfoData{}
}

func (p *GetDraftIntelligenceInfoData) InitDefault() {
}

func (p *GetDraftIntelligenceInfoData) GetIntelligenceType() (v common.IntelligenceType) {
	return p.IntelligenceType
}

var GetDraftIntelligenceInfoData_BasicInfo_DEFAULT *common.IntelligenceBasicInfo

func (p *GetDraftIntelligenceInfoData) GetBasicInfo() (v *common.IntelligenceBasicInfo) {
	if !p.IsSetBasicInfo() {
		return GetDraftIntelligenceInfoData_BasicInfo_DEFAULT
	}
	return p.BasicInfo
}

var GetDraftIntelligenceInfoData_PublishInfo_DEFAULT *IntelligencePublishInfo

func (p *GetDraftIntelligenceInfoData) GetPublishInfo() (v *IntelligencePublishInfo) {
	if !p.IsSetPublishInfo() {
		return GetDraftIntelligenceInfoData_PublishInfo_DEFAULT
	}
	return p.PublishInfo
}

var GetDraftIntelligenceInfoData_OwnerInfo_DEFAULT *common.User

func (p *GetDraftIntelligenceInfoData) GetOwnerInfo() (v *common.User) {
	if !p.IsSetOwnerInfo() {
		return GetDraftIntelligenceInfoData_OwnerInfo_DEFAULT
	}
	return p.OwnerInfo
}
func (p *GetDraftIntelligenceInfoData) SetIntelligenceType(val common.IntelligenceType) {
	p.IntelligenceType = val
}
func (p *GetDraftIntelligenceInfoData) SetBasicInfo(val *common.IntelligenceBasicInfo) {
	p.BasicInfo = val
}
func (p *GetDraftIntelligenceInfoData) SetPublishInfo(val *IntelligencePublishInfo) {
	p.PublishInfo = val
}
func (p *GetDraftIntelligenceInfoData) SetOwnerInfo(val *common.User) {
	p.OwnerInfo = val
}

func (p *GetDraftIntelligenceInfoData) IsSetBasicInfo() bool {
	return p.BasicInfo != nil
}

func (p *GetDraftIntelligenceInfoData) IsSetPublishInfo() bool {
	return p.PublishInfo != nil
}

func (p *GetDraftIntelligenceInfoData) IsSetOwnerInfo() bool {
	return p.OwnerInfo != nil
}

func (p *GetDraftIntelligenceInfoData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDraftIntelligenceInfoData(%+v)", *p)
}

type GetDraftIntelligenceInfoResponse struct {
	Data     *GetDraftIntelligenceInfoData `thrift:"data,1" json:"data"`
	Code     int32                         `thrift:"code,253" json:"code"`
	Msg      string                        `thrift:"msg,254" json:"msg"`
	BaseResp *base.BaseResp                `thrift:"BaseResp,255,optional" json:"BaseResp,omitempty"`
}

func NewGetDraftIntelligenceInfoResponse() *GetDraftIntelligenceInfoResponse {
	return &GetDraftIntelligenceInfoResponse{}
}

func (p *GetDraftIntelligenceInfoResponse) InitDefault() {
}

var GetDraftIntelligenceInfoResponse_Data_DEFAULT *GetDraftIntelligenceInfoData

func (p *GetDraftIntelligenceInfoResponse) GetData() (v *GetDraftIntelligenceInfoData) {
	if !p.IsSetData() {
		return GetDraftIntelligenceInfoResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *GetDraftIntelligenceInfoResponse) GetCode() (v int32) {
	return p.Code
}

func (p *GetDraftIntelligenceInfoResponse) GetMsg() (v string) {
	return p.Msg
}

var GetDraftIntelligenceInfoResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetDraftIntelligenceInfoResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetDraftIntelligenceInfoResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetDraftIntelligenceInfoResponse) SetData(val *GetDraftIntelligenceInfoData) {
	p.Data = val
}
func (p *GetDraftIntelligenceInfoResponse) SetCode(val int32) {
	p.Code = val
}
func (p *GetDraftIntelligenceInfoResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *GetDraftIntelligenceInfoResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetDraftIntelligenceInfoResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetDraftIntelligenceInfoResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetDraftIntelligenceInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDraftIntelligenceInfoResponse(%+v)", *p)
}

type GetUserRecentlyEditIntelligenceRequest struct {
	Size           int32                     `thrift:"size,1" json:"size"`
	Types          []common.IntelligenceType `thrift:"types,2,optional,list<IntelligenceType>" json:"types,omitempty"`
	EnterpriseID   *string                   `thrift:"enterprise_id,3,optional" json:"enterprise_id,omitempty"`
	OrganizationID *string                   `thrift:"organization_id,4,optional" json:"organization_id,omitempty"`
	Base           *base.Base                `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewGetUserRecentlyEditIntelligenceRequest() *GetUserRecentlyEditIntelligenceRequest {
	return &GetUserRecentlyEditIntelligenceRequest{}
}

func (p *GetUserRecentlyEditIntelligenceRequest) InitDefault() {
}

func (p *GetUserRecentlyEditIntelligenceRequest) GetSize() (v int32) {
	return p.Size
}

var GetUserRecentlyEditIntelligenceRequest_Types_DEFAULT []common.IntelligenceType

func (p *GetUserRecentlyEditIntelligenceRequest) GetTypes() (v []common.IntelligenceType) {
	if !p.IsSetTypes() {
		return GetUserRecentlyEditIntelligenceRequest_Types_DEFAULT
	}
	return p.Types
}

var GetUserRecentlyEditIntelligenceRequest_EnterpriseID_DEFAULT string

func (p *GetUserRecentlyEditIntelligenceRequest) GetEnterpriseID() (v string) {
	if !p.IsSetEnterpriseID() {
		return GetUserRecentlyEditIntelligenceRequest_EnterpriseID_DEFAULT
	}
	return *p.EnterpriseID
}

var GetUserRecentlyEditIntelligenceRequest_OrganizationID_DEFAULT string

func (p *GetUserRecentlyEditIntelligenceRequest) GetOrganizationID() (v string) {
	if !p.IsSetOrganizationID() {
		return GetUserRecentlyEditIntelligenceRequest_OrganizationID_DEFAULT
	}
	return *p.OrganizationID
}

var GetUserRecentlyEditIntelligenceRequest_Base_DEFAULT *base.Base

func (p *GetUserRecentlyEditIntelligenceRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetUserRecentlyEditIntelligenceRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *GetUserRecentlyEditIntelligenceRequest) SetSize(val int32) {
	p.Size = val
}
func (p *GetUserRecentlyEditIntelligenceRequest) SetTypes(val []common.IntelligenceType) {
	p.Types = val
}
func (p *GetUserRecentlyEditIntelligenceRequest) SetEnterpriseID(val *string) {
	p.EnterpriseID = val
}
func (p *GetUserRecentlyEditIntelligenceRequest) SetOrganizationID(val *string) {
	p.OrganizationID = val
}
func (p *GetUserRecentlyEditIntelligenceRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetUserRecentlyEditIntelligenceRequest) IsSetTypes() bool {
	return p.Types != nil
}

func (p *GetUserRecentlyEditIntelligenceRequest) IsSetEnterpriseID() bool {
	return p.EnterpriseID != nil
}

func (p *GetUserRecentlyEditIntelligenceRequest) IsSetOrganizationID() bool {
	return p.OrganizationID != nil
}

func (p *GetUserRecentlyEditIntelligenceRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetUserRecentlyEditIntelligenceRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRecentlyEditIntelligenceRequest(%+v)", *p)
}

type GetUserRecentlyEditIntelligenceData struct {
	IntelligenceInfoList []*IntelligenceData `thrift:"intelligence_info_list,1,default,list<IntelligenceData>" json:"intelligence_info_list"`
}

func NewGetUserRecentlyEditIntelligenceData() *GetUserRecentlyEditIntelligenceData {
	return &GetUserRecentlyEditIntelligenceData{}
}

func (p *GetUserRecentlyEditIntelligenceData) InitDefault() {
}

func (p *GetUserRecentlyEditIntelligenceData) GetIntelligenceInfoList() (v []*IntelligenceData) {
	return p.IntelligenceInfoList
}
func (p *GetUserRecentlyEditIntelligenceData) SetIntelligenceInfoList(val []*IntelligenceData) {
	p.IntelligenceInfoList = val
}

func (p *GetUserRecentlyEditIntelligenceData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRecentlyEditIntelligenceData(%+v)", *p)
}

type GetUserRecentlyEditIntelligenceResponse struct {
	Data     *GetUserRecentlyEditIntelligenceData `thrift:"data,1" json:"data"`
	Code     int32                                `thrift:"code,253" json:"code"`
	Msg      string                               `thrift:"msg,254" json:"msg"`
	BaseResp *base.BaseResp                       `thrift:"BaseResp,255,optional" json:"BaseResp,omitempty"`
}

func NewGetUserRecentlyEditIntelligenceResponse() *GetUserRecentlyEditIntelligenceResponse {
	return &GetUserRecentlyEditIntelligenceResponse{}
}

func (p *GetUserRecentlyEditIntelligenceResponse) InitDefault() {
}

var GetUserRecentlyEditIntelligenceResponse_Data_DEFAULT *GetUserRecentlyEditIntelligenceData

func (p *GetUserRecentlyEditIntelligenceResponse) GetData() (v *GetUserRecentlyEditIntelligenceData) {
	if !p.IsSetData() {
		return GetUserRecentlyEditIntelligenceResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *GetUserRecentlyEditIntelligenceResponse) GetCode() (v int32) {
	return p.Code
}

func (p *GetUserRecentlyEditIntelligenceResponse) GetMsg() (v string) {
	return p.Msg
}

var GetUserRecentlyEditIntelligenceResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetUserRecentlyEditIntelligenceResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetUserRecentlyEditIntelligenceResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetUserRecentlyEditIntelligenceResponse) SetData(val *GetUserRecentlyEditIntelligenceData) {
	p.Data = val
}
func (p *GetUserRecentlyEditIntelligenceResponse) SetCode(val int32) {
	p.Code = val
}
func (p *GetUserRecentlyEditIntelligenceResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *GetUserRecentlyEditIntelligenceResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetUserRecentlyEditIntelligenceResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetUserRecentlyEditIntelligenceResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserRecentlyEditIntelligenceResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRecentlyEditIntelligenceResponse(%+v)", *p)
}
