// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package upload

import (
	"context"
	"fmt"
)

type CommonUploadRequest struct {
	ByteData   []byte  `thrift:"ByteData,1,optional" json:"ByteData,omitempty"`
	UploadID   *string `thrift:"uploadID,2,optional" json:"uploadID,omitempty"`
	PartNumber *string `thrift:"partNumber,3,optional" json:"partNumber,omitempty"`
}

func NewCommonUploadRequest() *CommonUploadRequest {
	return &CommonUploadRequest{}
}

func (p *CommonUploadRequest) InitDefault() {
}

var CommonUploadRequest_ByteData_DEFAULT []byte

func (p *CommonUploadRequest) GetByteData() (v []byte) {
	if !p.IsSetByteData() {
		return CommonUploadRequest_ByteData_DEFAULT
	}
	return p.ByteData
}

var CommonUploadRequest_UploadID_DEFAULT string

func (p *CommonUploadRequest) GetUploadID() (v string) {
	if !p.IsSetUploadID() {
		return CommonUploadRequest_UploadID_DEFAULT
	}
	return *p.UploadID
}

var CommonUploadRequest_PartNumber_DEFAULT string

func (p *CommonUploadRequest) GetPartNumber() (v string) {
	if !p.IsSetPartNumber() {
		return CommonUploadRequest_PartNumber_DEFAULT
	}
	return *p.PartNumber
}
func (p *CommonUploadRequest) SetByteData(val []byte) {
	p.ByteData = val
}
func (p *CommonUploadRequest) SetUploadID(val *string) {
	p.UploadID = val
}
func (p *CommonUploadRequest) SetPartNumber(val *string) {
	p.PartNumber = val
}

func (p *CommonUploadRequest) IsSetByteData() bool {
	return p.ByteData != nil
}

func (p *CommonUploadRequest) IsSetUploadID() bool {
	return p.UploadID != nil
}

func (p *CommonUploadRequest) IsSetPartNumber() bool {
	return p.PartNumber != nil
}

func (p *CommonUploadRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonUploadRequest(%+v)", *p)
}

type Error struct {
	Code      int32  `thrift:"code,1" json:"code"`
	Error     string `thrift:"error,2" json:"error"`
	ErrorCode int32  `thrift:"error_code,3" json:"error_code"`
	Message   string `thrift:"message,4" json:"message"`
}

func NewError() *Error {
	return &Error{}
}

func (p *Error) InitDefault() {
}

func (p *Error) GetCode() (v int32) {
	return p.Code
}

func (p *Error) GetError() (v string) {
	return p.Error
}

func (p *Error) GetErrorCode() (v int32) {
	return p.ErrorCode
}

func (p *Error) GetMessage() (v string) {
	return p.Message
}
func (p *Error) SetCode(val int32) {
	p.Code = val
}
func (p *Error) SetError(val string) {
	p.Error = val
}
func (p *Error) SetErrorCode(val int32) {
	p.ErrorCode = val
}
func (p *Error) SetMessage(val string) {
	p.Message = val
}

func (p *Error) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Error(%+v)", *p)
}

type Payload struct {
	Hash     string `thrift:"hash,1" json:"hash"`
	Key      string `thrift:"key,2" json:"key"`
	UploadID string `thrift:"uploadID,3" json:"uploadID"`
}

func NewPayload() *Payload {
	return &Payload{}
}

func (p *Payload) InitDefault() {
}

func (p *Payload) GetHash() (v string) {
	return p.Hash
}

func (p *Payload) GetKey() (v string) {
	return p.Key
}

func (p *Payload) GetUploadID() (v string) {
	return p.UploadID
}
func (p *Payload) SetHash(val string) {
	p.Hash = val
}
func (p *Payload) SetKey(val string) {
	p.Key = val
}
func (p *Payload) SetUploadID(val string) {
	p.UploadID = val
}

func (p *Payload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Payload(%+v)", *p)
}

type CommonUploadResponse struct {
	Version string   `thrift:"Version,1" json:"Version"`
	Success int32    `thrift:"success,2" json:"success"`
	Error   *Error   `thrift:"error,3" json:"error"`
	Payload *Payload `thrift:"payload,4" json:"payload"`
}

func NewCommonUploadResponse() *CommonUploadResponse {
	return &CommonUploadResponse{}
}

func (p *CommonUploadResponse) InitDefault() {
}

func (p *CommonUploadResponse) GetVersion() (v string) {
	return p.Version
}

func (p *CommonUploadResponse) GetSuccess() (v int32) {
	return p.Success
}

var CommonUploadResponse_Error_DEFAULT *Error

func (p *CommonUploadResponse) GetError() (v *Error) {
	if !p.IsSetError() {
		return CommonUploadResponse_Error_DEFAULT
	}
	return p.Error
}

var CommonUploadResponse_Payload_DEFAULT *Payload

func (p *CommonUploadResponse) GetPayload() (v *Payload) {
	if !p.IsSetPayload() {
		return CommonUploadResponse_Payload_DEFAULT
	}
	return p.Payload
}
func (p *CommonUploadResponse) SetVersion(val string) {
	p.Version = val
}
func (p *CommonUploadResponse) SetSuccess(val int32) {
	p.Success = val
}
func (p *CommonUploadResponse) SetError(val *Error) {
	p.Error = val
}
func (p *CommonUploadResponse) SetPayload(val *Payload) {
	p.Payload = val
}

func (p *CommonUploadResponse) IsSetError() bool {
	return p.Error != nil
}

func (p *CommonUploadResponse) IsSetPayload() bool {
	return p.Payload != nil
}

func (p *CommonUploadResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonUploadResponse(%+v)", *p)
}

type ApplyUploadActionRequest struct {
	Action        *string `thrift:"Action,1,optional" json:"Action,omitempty"`
	Version       *string `thrift:"Version,2,optional" json:"Version,omitempty"`
	ServiceId     *string `thrift:"ServiceId,3,optional" json:"ServiceId,omitempty"`
	FileExtension *string `thrift:"FileExtension,4,optional" json:"FileExtension,omitempty"`
	FileSize      *string `thrift:"FileSize,5,optional" json:"FileSize,omitempty"`
	S             *string `thrift:"s,6,optional" json:"s,omitempty"`
	ByteData      []byte  `thrift:"ByteData,7,optional" json:"ByteData,omitempty"`
}

func NewApplyUploadActionRequest() *ApplyUploadActionRequest {
	return &ApplyUploadActionRequest{}
}

func (p *ApplyUploadActionRequest) InitDefault() {
}

var ApplyUploadActionRequest_Action_DEFAULT string

func (p *ApplyUploadActionRequest) GetAction() (v string) {
	if !p.IsSetAction() {
		return ApplyUploadActionRequest_Action_DEFAULT
	}
	return *p.Action
}

var ApplyUploadActionRequest_Version_DEFAULT string

func (p *ApplyUploadActionRequest) GetVersion() (v string) {
	if !p.IsSetVersion() {
		return ApplyUploadActionRequest_Version_DEFAULT
	}
	return *p.Version
}

var ApplyUploadActionRequest_ServiceId_DEFAULT string

func (p *ApplyUploadActionRequest) GetServiceId() (v string) {
	if !p.IsSetServiceId() {
		return ApplyUploadActionRequest_ServiceId_DEFAULT
	}
	return *p.ServiceId
}

var ApplyUploadActionRequest_FileExtension_DEFAULT string

func (p *ApplyUploadActionRequest) GetFileExtension() (v string) {
	if !p.IsSetFileExtension() {
		return ApplyUploadActionRequest_FileExtension_DEFAULT
	}
	return *p.FileExtension
}

var ApplyUploadActionRequest_FileSize_DEFAULT string

func (p *ApplyUploadActionRequest) GetFileSize() (v string) {
	if !p.IsSetFileSize() {
		return ApplyUploadActionRequest_FileSize_DEFAULT
	}
	return *p.FileSize
}

var ApplyUploadActionRequest_S_DEFAULT string

func (p *ApplyUploadActionRequest) GetS() (v string) {
	if !p.IsSetS() {
		return ApplyUploadActionRequest_S_DEFAULT
	}
	return *p.S
}

var ApplyUploadActionRequest_ByteData_DEFAULT []byte

func (p *ApplyUploadActionRequest) GetByteData() (v []byte) {
	if !p.IsSetByteData() {
		return ApplyUploadActionRequest_ByteData_DEFAULT
	}
	return p.ByteData
}
func (p *ApplyUploadActionRequest) SetAction(val *string) {
	p.Action = val
}
func (p *ApplyUploadActionRequest) SetVersion(val *string) {
	p.Version = val
}
func (p *ApplyUploadActionRequest) SetServiceId(val *string) {
	p.ServiceId = val
}
func (p *ApplyUploadActionRequest) SetFileExtension(val *string) {
	p.FileExtension = val
}
func (p *ApplyUploadActionRequest) SetFileSize(val *string) {
	p.FileSize = val
}
func (p *ApplyUploadActionRequest) SetS(val *string) {
	p.S = val
}
func (p *ApplyUploadActionRequest) SetByteData(val []byte) {
	p.ByteData = val
}

func (p *ApplyUploadActionRequest) IsSetAction() bool {
	return p.Action != nil
}

func (p *ApplyUploadActionRequest) IsSetVersion() bool {
	return p.Version != nil
}

func (p *ApplyUploadActionRequest) IsSetServiceId() bool {
	return p.ServiceId != nil
}

func (p *ApplyUploadActionRequest) IsSetFileExtension() bool {
	return p.FileExtension != nil
}

func (p *ApplyUploadActionRequest) IsSetFileSize() bool {
	return p.FileSize != nil
}

func (p *ApplyUploadActionRequest) IsSetS() bool {
	return p.S != nil
}

func (p *ApplyUploadActionRequest) IsSetByteData() bool {
	return p.ByteData != nil
}

func (p *ApplyUploadActionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApplyUploadActionRequest(%+v)", *p)
}

type ResponseMetadata struct {
	RequestId string `thrift:"RequestId,1,required" json:"RequestId"`
	Action    string `thrift:"Action,2,required" json:"Action"`
	Version   string `thrift:"Version,3,required" json:"Version"`
	Service   string `thrift:"Service,4,required" json:"Service"`
	Region    string `thrift:"Region,5,required" json:"Region"`
}

func NewResponseMetadata() *ResponseMetadata {
	return &ResponseMetadata{}
}

func (p *ResponseMetadata) InitDefault() {
}

func (p *ResponseMetadata) GetRequestId() (v string) {
	return p.RequestId
}

func (p *ResponseMetadata) GetAction() (v string) {
	return p.Action
}

func (p *ResponseMetadata) GetVersion() (v string) {
	return p.Version
}

func (p *ResponseMetadata) GetService() (v string) {
	return p.Service
}

func (p *ResponseMetadata) GetRegion() (v string) {
	return p.Region
}
func (p *ResponseMetadata) SetRequestId(val string) {
	p.RequestId = val
}
func (p *ResponseMetadata) SetAction(val string) {
	p.Action = val
}
func (p *ResponseMetadata) SetVersion(val string) {
	p.Version = val
}
func (p *ResponseMetadata) SetService(val string) {
	p.Service = val
}
func (p *ResponseMetadata) SetRegion(val string) {
	p.Region = val
}

func (p *ResponseMetadata) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResponseMetadata(%+v)", *p)
}

type StoreInfo struct {
	StoreUri string `thrift:"StoreUri,1,required" json:"StoreUri"`
	Auth     string `thrift:"Auth,2,required" json:"Auth"`
	UploadID string `thrift:"UploadID,3,required" json:"UploadID"`
}

func NewStoreInfo() *StoreInfo {
	return &StoreInfo{}
}

func (p *StoreInfo) InitDefault() {
}

func (p *StoreInfo) GetStoreUri() (v string) {
	return p.StoreUri
}

func (p *StoreInfo) GetAuth() (v string) {
	return p.Auth
}

func (p *StoreInfo) GetUploadID() (v string) {
	return p.UploadID
}
func (p *StoreInfo) SetStoreUri(val string) {
	p.StoreUri = val
}
func (p *StoreInfo) SetAuth(val string) {
	p.Auth = val
}
func (p *StoreInfo) SetUploadID(val string) {
	p.UploadID = val
}

func (p *StoreInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StoreInfo(%+v)", *p)
}

type UploadAddress struct {
	StoreInfos   []*StoreInfo      `thrift:"StoreInfos,1,required,list<StoreInfo>" json:"StoreInfos"`
	UploadHosts  []string          `thrift:"UploadHosts,2,required,list<string>" json:"UploadHosts"`
	UploadHeader map[string]string `thrift:"UploadHeader,3,optional" json:"UploadHeader,omitempty"`
	SessionKey   string            `thrift:"SessionKey,4,required" json:"SessionKey"`
	Cloud        string            `thrift:"Cloud,5,required" json:"Cloud"`
}

func NewUploadAddress() *UploadAddress {
	return &UploadAddress{}
}

func (p *UploadAddress) InitDefault() {
}

func (p *UploadAddress) GetStoreInfos() (v []*StoreInfo) {
	return p.StoreInfos
}

func (p *UploadAddress) GetUploadHosts() (v []string) {
	return p.UploadHosts
}

var UploadAddress_UploadHeader_DEFAULT map[string]string

func (p *UploadAddress) GetUploadHeader() (v map[string]string) {
	if !p.IsSetUploadHeader() {
		return UploadAddress_UploadHeader_DEFAULT
	}
	return p.UploadHeader
}

func (p *UploadAddress) GetSessionKey() (v string) {
	return p.SessionKey
}

func (p *UploadAddress) GetCloud() (v string) {
	return p.Cloud
}
func (p *UploadAddress) SetStoreInfos(val []*StoreInfo) {
	p.StoreInfos = val
}
func (p *UploadAddress) SetUploadHosts(val []string) {
	p.UploadHosts = val
}
func (p *UploadAddress) SetUploadHeader(val map[string]string) {
	p.UploadHeader = val
}
func (p *UploadAddress) SetSessionKey(val string) {
	p.SessionKey = val
}
func (p *UploadAddress) SetCloud(val string) {
	p.Cloud = val
}

func (p *UploadAddress) IsSetUploadHeader() bool {
	return p.UploadHeader != nil
}

func (p *UploadAddress) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAddress(%+v)", *p)
}

type UploadNode struct {
	StoreInfos   []*StoreInfo      `thrift:"StoreInfos,1,required,list<StoreInfo>" json:"StoreInfos"`
	UploadHost   string            `thrift:"UploadHost,2,required" json:"UploadHost"`
	UploadHeader map[string]string `thrift:"UploadHeader,3,optional" json:"UploadHeader,omitempty"`
	SessionKey   string            `thrift:"SessionKey,4,required" json:"SessionKey"`
}

func NewUploadNode() *UploadNode {
	return &UploadNode{}
}

func (p *UploadNode) InitDefault() {
}

func (p *UploadNode) GetStoreInfos() (v []*StoreInfo) {
	return p.StoreInfos
}

func (p *UploadNode) GetUploadHost() (v string) {
	return p.UploadHost
}

var UploadNode_UploadHeader_DEFAULT map[string]string

func (p *UploadNode) GetUploadHeader() (v map[string]string) {
	if !p.IsSetUploadHeader() {
		return UploadNode_UploadHeader_DEFAULT
	}
	return p.UploadHeader
}

func (p *UploadNode) GetSessionKey() (v string) {
	return p.SessionKey
}
func (p *UploadNode) SetStoreInfos(val []*StoreInfo) {
	p.StoreInfos = val
}
func (p *UploadNode) SetUploadHost(val string) {
	p.UploadHost = val
}
func (p *UploadNode) SetUploadHeader(val map[string]string) {
	p.UploadHeader = val
}
func (p *UploadNode) SetSessionKey(val string) {
	p.SessionKey = val
}

func (p *UploadNode) IsSetUploadHeader() bool {
	return p.UploadHeader != nil
}

func (p *UploadNode) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadNode(%+v)", *p)
}

type InnerUploadAddress struct {
	UploadNodes []*UploadNode `thrift:"UploadNodes,1,required,list<UploadNode>" json:"UploadNodes"`
}

func NewInnerUploadAddress() *InnerUploadAddress {
	return &InnerUploadAddress{}
}

func (p *InnerUploadAddress) InitDefault() {
}

func (p *InnerUploadAddress) GetUploadNodes() (v []*UploadNode) {
	return p.UploadNodes
}
func (p *InnerUploadAddress) SetUploadNodes(val []*UploadNode) {
	p.UploadNodes = val
}

func (p *InnerUploadAddress) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InnerUploadAddress(%+v)", *p)
}

type UploadResult struct {
	Uri       string `thrift:"Uri,1,required" json:"Uri"`
	UriStatus int32  `thrift:"UriStatus,2,required" json:"UriStatus"`
}

func NewUploadResult() *UploadResult {
	return &UploadResult{}
}

func (p *UploadResult) InitDefault() {
}

func (p *UploadResult) GetUri() (v string) {
	return p.Uri
}

func (p *UploadResult) GetUriStatus() (v int32) {
	return p.UriStatus
}
func (p *UploadResult) SetUri(val string) {
	p.Uri = val
}
func (p *UploadResult) SetUriStatus(val int32) {
	p.UriStatus = val
}

func (p *UploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadResult(%+v)", *p)
}

type PluginResult struct {
	FileName    string `thrift:"FileName,1,required" json:"FileName"`
	SourceUri   string `thrift:"SourceUri,2,required" json:"SourceUri"`
	ImageUri    string `thrift:"ImageUri,3,required" json:"ImageUri"`
	ImageWidth  int32  `thrift:"ImageWidth,4,required" json:"ImageWidth"`
	ImageHeight int32  `thrift:"ImageHeight,5,required" json:"ImageHeight"`
	ImageMd5    string `thrift:"ImageMd5,6,required" json:"ImageMd5"`
	ImageFormat string `thrift:"ImageFormat,7,required" json:"ImageFormat"`
	ImageSize   int32  `thrift:"ImageSize,8,required" json:"ImageSize"`
	FrameCnt    int32  `thrift:"FrameCnt,9,required" json:"FrameCnt"`
}

func NewPluginResult() *PluginResult {
	return &PluginResult{}
}

func (p *PluginResult) InitDefault() {
}

func (p *PluginResult) GetFileName() (v string) {
	return p.FileName
}

func (p *PluginResult) GetSourceUri() (v string) {
	return p.SourceUri
}

func (p *PluginResult) GetImageUri() (v string) {
	return p.ImageUri
}

func (p *PluginResult) GetImageWidth() (v int32) {
	return p.ImageWidth
}

func (p *PluginResult) GetImageHeight() (v int32) {
	return p.ImageHeight
}

func (p *PluginResult) GetImageMd5() (v string) {
	return p.ImageMd5
}

func (p *PluginResult) GetImageFormat() (v string) {
	return p.ImageFormat
}

func (p *PluginResult) GetImageSize() (v int32) {
	return p.ImageSize
}

func (p *PluginResult) GetFrameCnt() (v int32) {
	return p.FrameCnt
}
func (p *PluginResult) SetFileName(val string) {
	p.FileName = val
}
func (p *PluginResult) SetSourceUri(val string) {
	p.SourceUri = val
}
func (p *PluginResult) SetImageUri(val string) {
	p.ImageUri = val
}
func (p *PluginResult) SetImageWidth(val int32) {
	p.ImageWidth = val
}
func (p *PluginResult) SetImageHeight(val int32) {
	p.ImageHeight = val
}
func (p *PluginResult) SetImageMd5(val string) {
	p.ImageMd5 = val
}
func (p *PluginResult) SetImageFormat(val string) {
	p.ImageFormat = val
}
func (p *PluginResult) SetImageSize(val int32) {
	p.ImageSize = val
}
func (p *PluginResult) SetFrameCnt(val int32) {
	p.FrameCnt = val
}

func (p *PluginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginResult(%+v)", *p)
}

type ApplyUploadActionResult struct {
	UploadAddress         *UploadAddress      `thrift:"UploadAddress,1,optional" json:"UploadAddress,omitempty"`
	FallbackUploadAddress *UploadAddress      `thrift:"FallbackUploadAddress,2,optional" json:"FallbackUploadAddress,omitempty"`
	InnerUploadAddress    *InnerUploadAddress `thrift:"InnerUploadAddress,3,optional" json:"InnerUploadAddress,omitempty"`
	RequestId             *string             `thrift:"RequestId,4,optional" json:"RequestId,omitempty"`
	SDKParam              *string             `thrift:"SDKParam,5,optional" json:"SDKParam,omitempty"`
	Results               []*UploadResult     `thrift:"Results,6,optional,list<UploadResult>" json:"Results,omitempty"`
	PluginResult          []*PluginResult     `thrift:"PluginResult,7,optional,list<PluginResult>" json:"PluginResult,omitempty"`
}

func NewApplyUploadActionResult() *ApplyUploadActionResult {
	return &ApplyUploadActionResult{}
}

func (p *ApplyUploadActionResult) InitDefault() {
}

var ApplyUploadActionResult_UploadAddress_DEFAULT *UploadAddress

func (p *ApplyUploadActionResult) GetUploadAddress() (v *UploadAddress) {
	if !p.IsSetUploadAddress() {
		return ApplyUploadActionResult_UploadAddress_DEFAULT
	}
	return p.UploadAddress
}

var ApplyUploadActionResult_FallbackUploadAddress_DEFAULT *UploadAddress

func (p *ApplyUploadActionResult) GetFallbackUploadAddress() (v *UploadAddress) {
	if !p.IsSetFallbackUploadAddress() {
		return ApplyUploadActionResult_FallbackUploadAddress_DEFAULT
	}
	return p.FallbackUploadAddress
}

var ApplyUploadActionResult_InnerUploadAddress_DEFAULT *InnerUploadAddress

func (p *ApplyUploadActionResult) GetInnerUploadAddress() (v *InnerUploadAddress) {
	if !p.IsSetInnerUploadAddress() {
		return ApplyUploadActionResult_InnerUploadAddress_DEFAULT
	}
	return p.InnerUploadAddress
}

var ApplyUploadActionResult_RequestId_DEFAULT string

func (p *ApplyUploadActionResult) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return ApplyUploadActionResult_RequestId_DEFAULT
	}
	return *p.RequestId
}

var ApplyUploadActionResult_SDKParam_DEFAULT string

func (p *ApplyUploadActionResult) GetSDKParam() (v string) {
	if !p.IsSetSDKParam() {
		return ApplyUploadActionResult_SDKParam_DEFAULT
	}
	return *p.SDKParam
}

var ApplyUploadActionResult_Results_DEFAULT []*UploadResult

func (p *ApplyUploadActionResult) GetResults() (v []*UploadResult) {
	if !p.IsSetResults() {
		return ApplyUploadActionResult_Results_DEFAULT
	}
	return p.Results
}

var ApplyUploadActionResult_PluginResult_DEFAULT []*PluginResult

func (p *ApplyUploadActionResult) GetPluginResult() (v []*PluginResult) {
	if !p.IsSetPluginResult() {
		return ApplyUploadActionResult_PluginResult_DEFAULT
	}
	return p.PluginResult
}
func (p *ApplyUploadActionResult) SetUploadAddress(val *UploadAddress) {
	p.UploadAddress = val
}
func (p *ApplyUploadActionResult) SetFallbackUploadAddress(val *UploadAddress) {
	p.FallbackUploadAddress = val
}
func (p *ApplyUploadActionResult) SetInnerUploadAddress(val *InnerUploadAddress) {
	p.InnerUploadAddress = val
}
func (p *ApplyUploadActionResult) SetRequestId(val *string) {
	p.RequestId = val
}
func (p *ApplyUploadActionResult) SetSDKParam(val *string) {
	p.SDKParam = val
}
func (p *ApplyUploadActionResult) SetResults(val []*UploadResult) {
	p.Results = val
}
func (p *ApplyUploadActionResult) SetPluginResult(val []*PluginResult) {
	p.PluginResult = val
}

func (p *ApplyUploadActionResult) IsSetUploadAddress() bool {
	return p.UploadAddress != nil
}

func (p *ApplyUploadActionResult) IsSetFallbackUploadAddress() bool {
	return p.FallbackUploadAddress != nil
}

func (p *ApplyUploadActionResult) IsSetInnerUploadAddress() bool {
	return p.InnerUploadAddress != nil
}

func (p *ApplyUploadActionResult) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *ApplyUploadActionResult) IsSetSDKParam() bool {
	return p.SDKParam != nil
}

func (p *ApplyUploadActionResult) IsSetResults() bool {
	return p.Results != nil
}

func (p *ApplyUploadActionResult) IsSetPluginResult() bool {
	return p.PluginResult != nil
}

func (p *ApplyUploadActionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApplyUploadActionResult(%+v)", *p)
}

type ApplyUploadActionResponse struct {
	ResponseMetadata *ResponseMetadata        `thrift:"ResponseMetadata,1,required" json:"ResponseMetadata"`
	Result           *ApplyUploadActionResult `thrift:"Result,2,required" json:"Result"`
}

func NewApplyUploadActionResponse() *ApplyUploadActionResponse {
	return &ApplyUploadActionResponse{}
}

func (p *ApplyUploadActionResponse) InitDefault() {
}

var ApplyUploadActionResponse_ResponseMetadata_DEFAULT *ResponseMetadata

func (p *ApplyUploadActionResponse) GetResponseMetadata() (v *ResponseMetadata) {
	if !p.IsSetResponseMetadata() {
		return ApplyUploadActionResponse_ResponseMetadata_DEFAULT
	}
	return p.ResponseMetadata
}

var ApplyUploadActionResponse_Result_DEFAULT *ApplyUploadActionResult

func (p *ApplyUploadActionResponse) GetResult() (v *ApplyUploadActionResult) {
	if !p.IsSetResult() {
		return ApplyUploadActionResponse_Result_DEFAULT
	}
	return p.Result
}
func (p *ApplyUploadActionResponse) SetResponseMetadata(val *ResponseMetadata) {
	p.ResponseMetadata = val
}
func (p *ApplyUploadActionResponse) SetResult(val *ApplyUploadActionResult) {
	p.Result = val
}

func (p *ApplyUploadActionResponse) IsSetResponseMetadata() bool {
	return p.ResponseMetadata != nil
}

func (p *ApplyUploadActionResponse) IsSetResult() bool {
	return p.Result != nil
}

func (p *ApplyUploadActionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApplyUploadActionResponse(%+v)", *p)
}

type UploadService interface {
	CommonUpload(ctx context.Context, request *CommonUploadRequest) (r *CommonUploadResponse, err error)

	ApplyUploadAction(ctx context.Context, request *ApplyUploadActionRequest) (r *ApplyUploadActionResponse, err error)
}
