// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package passport

import (
	"context"
	"fmt"
)

type AppUserInfo struct {
	UserUniqueName string `thrift:"user_unique_name,1,required" json:"user_unique_name"`
}

func NewAppUserInfo() *AppUserInfo {
	return &AppUserInfo{}
}

func (p *AppUserInfo) InitDefault() {
}

func (p *AppUserInfo) GetUserUniqueName() (v string) {
	return p.UserUniqueName
}
func (p *AppUserInfo) SetUserUniqueName(val string) {
	p.UserUniqueName = val
}

func (p *AppUserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppUserInfo(%+v)", *p)
}

type User struct {
	UserIDStr      int64        `thrift:"user_id_str,1,required" json:"user_id_str"`
	Name           string       `thrift:"name,2,required" json:"name"`
	UserUniqueName string       `thrift:"user_unique_name,3,required" json:"user_unique_name"`
	Account        string       `thrift:"account,4,required" json:"account"`
	Description    string       `thrift:"description,5,required" json:"description"`
	AvatarURL      string       `thrift:"avatar_url,6,required" json:"avatar_url"`
	ScreenName     *string      `thrift:"screen_name,7,optional" json:"screen_name,omitempty"`
	AppUserInfo    *AppUserInfo `thrift:"app_user_info,8,optional" json:"app_user_info,omitempty"`
	Locale         *string      `thrift:"locale,9,optional" json:"locale,omitempty"`
	UserCreateTime int64        `thrift:"user_create_time,10" json:"user_create_time"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetUserIDStr() (v int64) {
	return p.UserIDStr
}

func (p *User) GetName() (v string) {
	return p.Name
}

func (p *User) GetUserUniqueName() (v string) {
	return p.UserUniqueName
}

func (p *User) GetAccount() (v string) {
	return p.Account
}

func (p *User) GetDescription() (v string) {
	return p.Description
}

func (p *User) GetAvatarURL() (v string) {
	return p.AvatarURL
}

var User_ScreenName_DEFAULT string

func (p *User) GetScreenName() (v string) {
	if !p.IsSetScreenName() {
		return User_ScreenName_DEFAULT
	}
	return *p.ScreenName
}

var User_AppUserInfo_DEFAULT *AppUserInfo

func (p *User) GetAppUserInfo() (v *AppUserInfo) {
	if !p.IsSetAppUserInfo() {
		return User_AppUserInfo_DEFAULT
	}
	return p.AppUserInfo
}

var User_Locale_DEFAULT string

func (p *User) GetLocale() (v string) {
	if !p.IsSetLocale() {
		return User_Locale_DEFAULT
	}
	return *p.Locale
}

func (p *User) GetUserCreateTime() (v int64) {
	return p.UserCreateTime
}
func (p *User) SetUserIDStr(val int64) {
	p.UserIDStr = val
}
func (p *User) SetName(val string) {
	p.Name = val
}
func (p *User) SetUserUniqueName(val string) {
	p.UserUniqueName = val
}
func (p *User) SetAccount(val string) {
	p.Account = val
}
func (p *User) SetDescription(val string) {
	p.Description = val
}
func (p *User) SetAvatarURL(val string) {
	p.AvatarURL = val
}
func (p *User) SetScreenName(val *string) {
	p.ScreenName = val
}
func (p *User) SetAppUserInfo(val *AppUserInfo) {
	p.AppUserInfo = val
}
func (p *User) SetLocale(val *string) {
	p.Locale = val
}
func (p *User) SetUserCreateTime(val int64) {
	p.UserCreateTime = val
}

func (p *User) IsSetScreenName() bool {
	return p.ScreenName != nil
}

func (p *User) IsSetAppUserInfo() bool {
	return p.AppUserInfo != nil
}

func (p *User) IsSetLocale() bool {
	return p.Locale != nil
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

type PassportWebAccountRegisterPostRequest struct {
	Password string `thrift:"password,11,required" json:"password"`
	Account  string `thrift:"account,23" json:"account"`
}

func NewPassportWebAccountRegisterPostRequest() *PassportWebAccountRegisterPostRequest {
	return &PassportWebAccountRegisterPostRequest{}
}

func (p *PassportWebAccountRegisterPostRequest) InitDefault() {
}

func (p *PassportWebAccountRegisterPostRequest) GetPassword() (v string) {
	return p.Password
}

func (p *PassportWebAccountRegisterPostRequest) GetAccount() (v string) {
	return p.Account
}
func (p *PassportWebAccountRegisterPostRequest) SetPassword(val string) {
	p.Password = val
}
func (p *PassportWebAccountRegisterPostRequest) SetAccount(val string) {
	p.Account = val
}

func (p *PassportWebAccountRegisterPostRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportWebAccountRegisterPostRequest(%+v)", *p)
}

type PassportWebAccountRegisterPostResponse struct {
	Data *User  `thrift:"data,1,required" json:"data"`
	Code int32  `thrift:"code,253,required" json:"code"`
	Msg  string `thrift:"msg,254,required" json:"msg"`
}

func NewPassportWebAccountRegisterPostResponse() *PassportWebAccountRegisterPostResponse {
	return &PassportWebAccountRegisterPostResponse{}
}

func (p *PassportWebAccountRegisterPostResponse) InitDefault() {
}

var PassportWebAccountRegisterPostResponse_Data_DEFAULT *User

func (p *PassportWebAccountRegisterPostResponse) GetData() (v *User) {
	if !p.IsSetData() {
		return PassportWebAccountRegisterPostResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *PassportWebAccountRegisterPostResponse) GetCode() (v int32) {
	return p.Code
}

func (p *PassportWebAccountRegisterPostResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *PassportWebAccountRegisterPostResponse) SetData(val *User) {
	p.Data = val
}
func (p *PassportWebAccountRegisterPostResponse) SetCode(val int32) {
	p.Code = val
}
func (p *PassportWebAccountRegisterPostResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *PassportWebAccountRegisterPostResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *PassportWebAccountRegisterPostResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportWebAccountRegisterPostResponse(%+v)", *p)
}

type PassportWebLogoutGetRequest struct {
}

func NewPassportWebLogoutGetRequest() *PassportWebLogoutGetRequest {
	return &PassportWebLogoutGetRequest{}
}

func (p *PassportWebLogoutGetRequest) InitDefault() {
}

func (p *PassportWebLogoutGetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportWebLogoutGetRequest(%+v)", *p)
}

type PassportWebLogoutGetResponse struct {
	RedirectURL string `thrift:"redirect_url,1,required" json:"redirect_url"`
	Code        int32  `thrift:"code,253,required" json:"code"`
	Msg         string `thrift:"msg,254,required" json:"msg"`
}

func NewPassportWebLogoutGetResponse() *PassportWebLogoutGetResponse {
	return &PassportWebLogoutGetResponse{}
}

func (p *PassportWebLogoutGetResponse) InitDefault() {
}

func (p *PassportWebLogoutGetResponse) GetRedirectURL() (v string) {
	return p.RedirectURL
}

func (p *PassportWebLogoutGetResponse) GetCode() (v int32) {
	return p.Code
}

func (p *PassportWebLogoutGetResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *PassportWebLogoutGetResponse) SetRedirectURL(val string) {
	p.RedirectURL = val
}
func (p *PassportWebLogoutGetResponse) SetCode(val int32) {
	p.Code = val
}
func (p *PassportWebLogoutGetResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *PassportWebLogoutGetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportWebLogoutGetResponse(%+v)", *p)
}

type PassportWebAccountLoginPostRequest struct {
	Account  string `thrift:"account,6,required" json:"account"`
	Password string `thrift:"password,7,required" json:"password"`
}

func NewPassportWebAccountLoginPostRequest() *PassportWebAccountLoginPostRequest {
	return &PassportWebAccountLoginPostRequest{}
}

func (p *PassportWebAccountLoginPostRequest) InitDefault() {
}

func (p *PassportWebAccountLoginPostRequest) GetAccount() (v string) {
	return p.Account
}

func (p *PassportWebAccountLoginPostRequest) GetPassword() (v string) {
	return p.Password
}
func (p *PassportWebAccountLoginPostRequest) SetAccount(val string) {
	p.Account = val
}
func (p *PassportWebAccountLoginPostRequest) SetPassword(val string) {
	p.Password = val
}

func (p *PassportWebAccountLoginPostRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportWebAccountLoginPostRequest(%+v)", *p)
}

type PassportWebAccountLoginPostResponse struct {
	Data *User  `thrift:"data,1,required" json:"data"`
	Code int32  `thrift:"code,253,required" json:"code"`
	Msg  string `thrift:"msg,254,required" json:"msg"`
}

func NewPassportWebAccountLoginPostResponse() *PassportWebAccountLoginPostResponse {
	return &PassportWebAccountLoginPostResponse{}
}

func (p *PassportWebAccountLoginPostResponse) InitDefault() {
}

var PassportWebAccountLoginPostResponse_Data_DEFAULT *User

func (p *PassportWebAccountLoginPostResponse) GetData() (v *User) {
	if !p.IsSetData() {
		return PassportWebAccountLoginPostResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *PassportWebAccountLoginPostResponse) GetCode() (v int32) {
	return p.Code
}

func (p *PassportWebAccountLoginPostResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *PassportWebAccountLoginPostResponse) SetData(val *User) {
	p.Data = val
}
func (p *PassportWebAccountLoginPostResponse) SetCode(val int32) {
	p.Code = val
}
func (p *PassportWebAccountLoginPostResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *PassportWebAccountLoginPostResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *PassportWebAccountLoginPostResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportWebAccountLoginPostResponse(%+v)", *p)
}

type PassportWebAccountPasswordResetGetRequest struct {
	Password string `thrift:"password,1" json:"password"`
	Code     string `thrift:"code,2" json:"code"`
	Account  string `thrift:"account,3" json:"account"`
}

func NewPassportWebAccountPasswordResetGetRequest() *PassportWebAccountPasswordResetGetRequest {
	return &PassportWebAccountPasswordResetGetRequest{}
}

func (p *PassportWebAccountPasswordResetGetRequest) InitDefault() {
}

func (p *PassportWebAccountPasswordResetGetRequest) GetPassword() (v string) {
	return p.Password
}

func (p *PassportWebAccountPasswordResetGetRequest) GetCode() (v string) {
	return p.Code
}

func (p *PassportWebAccountPasswordResetGetRequest) GetAccount() (v string) {
	return p.Account
}
func (p *PassportWebAccountPasswordResetGetRequest) SetPassword(val string) {
	p.Password = val
}
func (p *PassportWebAccountPasswordResetGetRequest) SetCode(val string) {
	p.Code = val
}
func (p *PassportWebAccountPasswordResetGetRequest) SetAccount(val string) {
	p.Account = val
}

func (p *PassportWebAccountPasswordResetGetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportWebAccountPasswordResetGetRequest(%+v)", *p)
}

type PassportWebAccountPasswordResetGetResponse struct {
	Code int32  `thrift:"code,253,required" json:"code"`
	Msg  string `thrift:"msg,254,required" json:"msg"`
}

func NewPassportWebAccountPasswordResetGetResponse() *PassportWebAccountPasswordResetGetResponse {
	return &PassportWebAccountPasswordResetGetResponse{}
}

func (p *PassportWebAccountPasswordResetGetResponse) InitDefault() {
}

func (p *PassportWebAccountPasswordResetGetResponse) GetCode() (v int32) {
	return p.Code
}

func (p *PassportWebAccountPasswordResetGetResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *PassportWebAccountPasswordResetGetResponse) SetCode(val int32) {
	p.Code = val
}
func (p *PassportWebAccountPasswordResetGetResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *PassportWebAccountPasswordResetGetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportWebAccountPasswordResetGetResponse(%+v)", *p)
}

type PassportAccountInfoRequest struct {
}

func NewPassportAccountInfoRequest() *PassportAccountInfoRequest {
	return &PassportAccountInfoRequest{}
}

func (p *PassportAccountInfoRequest) InitDefault() {
}

func (p *PassportAccountInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportAccountInfoRequest(%+v)", *p)
}

type PassportAccountInfoResponse struct {
	Data *User  `thrift:"data,1,required" json:"data"`
	Code int32  `thrift:"code,253,required" json:"code"`
	Msg  string `thrift:"msg,254,required" json:"msg"`
}

func NewPassportAccountInfoResponse() *PassportAccountInfoResponse {
	return &PassportAccountInfoResponse{}
}

func (p *PassportAccountInfoResponse) InitDefault() {
}

var PassportAccountInfoResponse_Data_DEFAULT *User

func (p *PassportAccountInfoResponse) GetData() (v *User) {
	if !p.IsSetData() {
		return PassportAccountInfoResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *PassportAccountInfoResponse) GetCode() (v int32) {
	return p.Code
}

func (p *PassportAccountInfoResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *PassportAccountInfoResponse) SetData(val *User) {
	p.Data = val
}
func (p *PassportAccountInfoResponse) SetCode(val int32) {
	p.Code = val
}
func (p *PassportAccountInfoResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *PassportAccountInfoResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *PassportAccountInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassportAccountInfoResponse(%+v)", *p)
}

type UserUpdateAvatarRequest struct {
	Avatar []byte `thrift:"avatar,3,required" json:"avatar"`
}

func NewUserUpdateAvatarRequest() *UserUpdateAvatarRequest {
	return &UserUpdateAvatarRequest{}
}

func (p *UserUpdateAvatarRequest) InitDefault() {
}

func (p *UserUpdateAvatarRequest) GetAvatar() (v []byte) {
	return p.Avatar
}
func (p *UserUpdateAvatarRequest) SetAvatar(val []byte) {
	p.Avatar = val
}

func (p *UserUpdateAvatarRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserUpdateAvatarRequest(%+v)", *p)
}

type UserUpdateAvatarResponseData struct {
	WebURI string `thrift:"web_uri,1,required" json:"web_uri"`
}

func NewUserUpdateAvatarResponseData() *UserUpdateAvatarResponseData {
	return &UserUpdateAvatarResponseData{}
}

func (p *UserUpdateAvatarResponseData) InitDefault() {
}

func (p *UserUpdateAvatarResponseData) GetWebURI() (v string) {
	return p.WebURI
}
func (p *UserUpdateAvatarResponseData) SetWebURI(val string) {
	p.WebURI = val
}

func (p *UserUpdateAvatarResponseData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserUpdateAvatarResponseData(%+v)", *p)
}

type UserUpdateAvatarResponse struct {
	Data *UserUpdateAvatarResponseData `thrift:"data,1,required" json:"data"`
	Code int32                         `thrift:"code,253,required" json:"code"`
	Msg  string                        `thrift:"msg,254,required" json:"msg"`
}

func NewUserUpdateAvatarResponse() *UserUpdateAvatarResponse {
	return &UserUpdateAvatarResponse{}
}

func (p *UserUpdateAvatarResponse) InitDefault() {
}

var UserUpdateAvatarResponse_Data_DEFAULT *UserUpdateAvatarResponseData

func (p *UserUpdateAvatarResponse) GetData() (v *UserUpdateAvatarResponseData) {
	if !p.IsSetData() {
		return UserUpdateAvatarResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *UserUpdateAvatarResponse) GetCode() (v int32) {
	return p.Code
}

func (p *UserUpdateAvatarResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *UserUpdateAvatarResponse) SetData(val *UserUpdateAvatarResponseData) {
	p.Data = val
}
func (p *UserUpdateAvatarResponse) SetCode(val int32) {
	p.Code = val
}
func (p *UserUpdateAvatarResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *UserUpdateAvatarResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *UserUpdateAvatarResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserUpdateAvatarResponse(%+v)", *p)
}

type UserUpdateProfileRequest struct {
	Name           *string `thrift:"name,2,optional" json:"name,omitempty"`
	UserUniqueName *string `thrift:"user_unique_name,3,optional" json:"user_unique_name,omitempty"`
	Description    *string `thrift:"description,5,optional" json:"description,omitempty"`
	Locale         *string `thrift:"locale,6,optional" json:"locale,omitempty"`
}

func NewUserUpdateProfileRequest() *UserUpdateProfileRequest {
	return &UserUpdateProfileRequest{}
}

func (p *UserUpdateProfileRequest) InitDefault() {
}

var UserUpdateProfileRequest_Name_DEFAULT string

func (p *UserUpdateProfileRequest) GetName() (v string) {
	if !p.IsSetName() {
		return UserUpdateProfileRequest_Name_DEFAULT
	}
	return *p.Name
}

var UserUpdateProfileRequest_UserUniqueName_DEFAULT string

func (p *UserUpdateProfileRequest) GetUserUniqueName() (v string) {
	if !p.IsSetUserUniqueName() {
		return UserUpdateProfileRequest_UserUniqueName_DEFAULT
	}
	return *p.UserUniqueName
}

var UserUpdateProfileRequest_Description_DEFAULT string

func (p *UserUpdateProfileRequest) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UserUpdateProfileRequest_Description_DEFAULT
	}
	return *p.Description
}

var UserUpdateProfileRequest_Locale_DEFAULT string

func (p *UserUpdateProfileRequest) GetLocale() (v string) {
	if !p.IsSetLocale() {
		return UserUpdateProfileRequest_Locale_DEFAULT
	}
	return *p.Locale
}
func (p *UserUpdateProfileRequest) SetName(val *string) {
	p.Name = val
}
func (p *UserUpdateProfileRequest) SetUserUniqueName(val *string) {
	p.UserUniqueName = val
}
func (p *UserUpdateProfileRequest) SetDescription(val *string) {
	p.Description = val
}
func (p *UserUpdateProfileRequest) SetLocale(val *string) {
	p.Locale = val
}

func (p *UserUpdateProfileRequest) IsSetName() bool {
	return p.Name != nil
}

func (p *UserUpdateProfileRequest) IsSetUserUniqueName() bool {
	return p.UserUniqueName != nil
}

func (p *UserUpdateProfileRequest) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UserUpdateProfileRequest) IsSetLocale() bool {
	return p.Locale != nil
}

func (p *UserUpdateProfileRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserUpdateProfileRequest(%+v)", *p)
}

type UserUpdateProfileResponse struct {
	Code int32  `thrift:"code,253,required" json:"code"`
	Msg  string `thrift:"msg,254,required" json:"msg"`
}

func NewUserUpdateProfileResponse() *UserUpdateProfileResponse {
	return &UserUpdateProfileResponse{}
}

func (p *UserUpdateProfileResponse) InitDefault() {
}

func (p *UserUpdateProfileResponse) GetCode() (v int32) {
	return p.Code
}

func (p *UserUpdateProfileResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *UserUpdateProfileResponse) SetCode(val int32) {
	p.Code = val
}
func (p *UserUpdateProfileResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *UserUpdateProfileResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserUpdateProfileResponse(%+v)", *p)
}

type PassportService interface {
	PassportWebAccountRegisterPost(ctx context.Context, req *PassportWebAccountRegisterPostRequest) (r *PassportWebAccountRegisterPostResponse, err error)

	PassportWebLogoutGet(ctx context.Context, req *PassportWebLogoutGetRequest) (r *PassportWebLogoutGetResponse, err error)

	PassportWebAccountLoginPost(ctx context.Context, req *PassportWebAccountLoginPostRequest) (r *PassportWebAccountLoginPostResponse, err error)

	PassportWebAccountPasswordResetGet(ctx context.Context, req *PassportWebAccountPasswordResetGetRequest) (r *PassportWebAccountPasswordResetGetResponse, err error)

	PassportAccountInfo(ctx context.Context, req *PassportAccountInfoRequest) (r *PassportAccountInfoResponse, err error)

	UserUpdateAvatar(ctx context.Context, req *UserUpdateAvatarRequest) (r *UserUpdateAvatarResponse, err error)

	UserUpdateProfile(ctx context.Context, req *UserUpdateProfileRequest) (r *UserUpdateProfileResponse, err error)
}
