// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package manage

import (
	"context"
	"fmt"
	"github.com/kiosk404/airi-go/backend/api/model/base"
	"github.com/kiosk404/airi-go/backend/api/model/llm/domain/common"
	"github.com/kiosk404/airi-go/backend/api/model/llm/domain/manage"
)

type ListModelsRequest struct {
	Scenario  *common.Scenario `thrift:"scenario,1,optional" json:"scenario,omitempty"`
	PageSize  *int32           `thrift:"page_size,127,optional" json:"page_size,omitempty"`
	PageToken *string          `thrift:"page_token,128,optional" json:"page_token,omitempty"`
	Base      *base.Base       `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewListModelsRequest() *ListModelsRequest {
	return &ListModelsRequest{}
}

func (p *ListModelsRequest) InitDefault() {
}

var ListModelsRequest_Scenario_DEFAULT common.Scenario

func (p *ListModelsRequest) GetScenario() (v common.Scenario) {
	if !p.IsSetScenario() {
		return ListModelsRequest_Scenario_DEFAULT
	}
	return *p.Scenario
}

var ListModelsRequest_PageSize_DEFAULT int32

func (p *ListModelsRequest) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return ListModelsRequest_PageSize_DEFAULT
	}
	return *p.PageSize
}

var ListModelsRequest_PageToken_DEFAULT string

func (p *ListModelsRequest) GetPageToken() (v string) {
	if !p.IsSetPageToken() {
		return ListModelsRequest_PageToken_DEFAULT
	}
	return *p.PageToken
}

var ListModelsRequest_Base_DEFAULT *base.Base

func (p *ListModelsRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ListModelsRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *ListModelsRequest) SetScenario(val *common.Scenario) {
	p.Scenario = val
}
func (p *ListModelsRequest) SetPageSize(val *int32) {
	p.PageSize = val
}
func (p *ListModelsRequest) SetPageToken(val *string) {
	p.PageToken = val
}
func (p *ListModelsRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *ListModelsRequest) IsSetScenario() bool {
	return p.Scenario != nil
}

func (p *ListModelsRequest) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *ListModelsRequest) IsSetPageToken() bool {
	return p.PageToken != nil
}

func (p *ListModelsRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListModelsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListModelsRequest(%+v)", *p)
}

type ListModelsResponse struct {
	Models        []*manage.AdminModel `thrift:"models,1,optional,list<manage.AdminModel>" json:"models,omitempty"`
	HasMore       *bool                `thrift:"has_more,127,optional" json:"has_more,omitempty"`
	NextPageToken *string              `thrift:"next_page_token,128,optional" json:"next_page_token,omitempty"`
	Total         *int32               `thrift:"total,129,optional" json:"total,omitempty"`
	BaseResp      *base.BaseResp       `thrift:"BaseResp,255" json:"BaseResp"`
}

func NewListModelsResponse() *ListModelsResponse {
	return &ListModelsResponse{}
}

func (p *ListModelsResponse) InitDefault() {
}

var ListModelsResponse_Models_DEFAULT []*manage.AdminModel

func (p *ListModelsResponse) GetModels() (v []*manage.AdminModel) {
	if !p.IsSetModels() {
		return ListModelsResponse_Models_DEFAULT
	}
	return p.Models
}

var ListModelsResponse_HasMore_DEFAULT bool

func (p *ListModelsResponse) GetHasMore() (v bool) {
	if !p.IsSetHasMore() {
		return ListModelsResponse_HasMore_DEFAULT
	}
	return *p.HasMore
}

var ListModelsResponse_NextPageToken_DEFAULT string

func (p *ListModelsResponse) GetNextPageToken() (v string) {
	if !p.IsSetNextPageToken() {
		return ListModelsResponse_NextPageToken_DEFAULT
	}
	return *p.NextPageToken
}

var ListModelsResponse_Total_DEFAULT int32

func (p *ListModelsResponse) GetTotal() (v int32) {
	if !p.IsSetTotal() {
		return ListModelsResponse_Total_DEFAULT
	}
	return *p.Total
}

var ListModelsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ListModelsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListModelsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListModelsResponse) SetModels(val []*manage.AdminModel) {
	p.Models = val
}
func (p *ListModelsResponse) SetHasMore(val *bool) {
	p.HasMore = val
}
func (p *ListModelsResponse) SetNextPageToken(val *string) {
	p.NextPageToken = val
}
func (p *ListModelsResponse) SetTotal(val *int32) {
	p.Total = val
}
func (p *ListModelsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListModelsResponse) IsSetModels() bool {
	return p.Models != nil
}

func (p *ListModelsResponse) IsSetHasMore() bool {
	return p.HasMore != nil
}

func (p *ListModelsResponse) IsSetNextPageToken() bool {
	return p.NextPageToken != nil
}

func (p *ListModelsResponse) IsSetTotal() bool {
	return p.Total != nil
}

func (p *ListModelsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListModelsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListModelsResponse(%+v)", *p)
}

type GetModelRequest struct {
	ModelID *int64     `thrift:"model_id,1,optional" json:"model_id"`
	Base    *base.Base `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewGetModelRequest() *GetModelRequest {
	return &GetModelRequest{}
}

func (p *GetModelRequest) InitDefault() {
}

var GetModelRequest_ModelID_DEFAULT int64

func (p *GetModelRequest) GetModelID() (v int64) {
	if !p.IsSetModelID() {
		return GetModelRequest_ModelID_DEFAULT
	}
	return *p.ModelID
}

var GetModelRequest_Base_DEFAULT *base.Base

func (p *GetModelRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetModelRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *GetModelRequest) SetModelID(val *int64) {
	p.ModelID = val
}
func (p *GetModelRequest) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetModelRequest) IsSetModelID() bool {
	return p.ModelID != nil
}

func (p *GetModelRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetModelRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetModelRequest(%+v)", *p)
}

type GetModelResponse struct {
	Model    *manage.AdminModel `thrift:"model,1,optional" json:"model,omitempty"`
	BaseResp *base.BaseResp     `thrift:"BaseResp,255" json:"BaseResp"`
}

func NewGetModelResponse() *GetModelResponse {
	return &GetModelResponse{}
}

func (p *GetModelResponse) InitDefault() {
}

var GetModelResponse_Model_DEFAULT *manage.AdminModel

func (p *GetModelResponse) GetModel() (v *manage.AdminModel) {
	if !p.IsSetModel() {
		return GetModelResponse_Model_DEFAULT
	}
	return p.Model
}

var GetModelResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetModelResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetModelResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetModelResponse) SetModel(val *manage.AdminModel) {
	p.Model = val
}
func (p *GetModelResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetModelResponse) IsSetModel() bool {
	return p.Model != nil
}

func (p *GetModelResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetModelResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetModelResponse(%+v)", *p)
}

type LLMManageService interface {
	ListModels(ctx context.Context, req *ListModelsRequest) (r *ListModelsResponse, err error)

	GetModel(ctx context.Context, req *GetModelRequest) (r *GetModelResponse, err error)
}
