// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConversation = "conversation"

// Conversation 会话信息表
type Conversation struct {
	ID        int64   `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                    // 主键ID
	AgentID   int64   `gorm:"column:agent_id;type:bigint(20);not null;index:idx_bot_status,priority:1;comment:agent_id" json:"agent_id"`  // agent_id
	Scene     int32   `gorm:"column:scene;type:tinyint(4);not null;comment:会话场景" json:"scene"`                                            // 会话场景
	SectionID int64   `gorm:"column:section_id;type:bigint(20) unsigned;not null;comment:最新section_id" json:"section_id"`                 // 最新section_id
	CreatorID *int64  `gorm:"column:creator_id;type:bigint(20) unsigned;index:idx_bot_status,priority:2;comment:创建者id" json:"creator_id"` // 创建者id
	Ext       *string `gorm:"column:ext;type:text;comment:扩展字段" json:"ext"`                                                               // 扩展字段
	Name      string  `gorm:"column:name;type:varchar(255);not null;comment:conversation name" json:"name"`                               // conversation name
	Status    int32   `gorm:"column:status;type:tinyint(4);not null;default:1;comment:status: 1-normal 2-deleted" json:"status"`          // status: 1-normal 2-deleted
	CreatedAt int64   `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:创建时间" json:"created_at"`                         // 创建时间
	UpdatedAt int64   `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:更新时间" json:"updated_at"`                         // 更新时间
}

// TableName Conversation's table name
func (*Conversation) TableName() string {
	return TableNameConversation
}
