// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/kiosk404/airi-go/backend/modules/llm/infra/repo/gorm_gen/model"
)

func newModelMetum(db *gorm.DB, opts ...gen.DOOption) modelMetum {
	_modelMetum := modelMetum{}

	_modelMetum.modelMetumDo.UseDB(db, opts...)
	_modelMetum.modelMetumDo.UseModel(&model.ModelMetum{})

	tableName := _modelMetum.modelMetumDo.TableName()
	_modelMetum.ALL = field.NewAsterisk(tableName)
	_modelMetum.ID = field.NewInt64(tableName, "id")
	_modelMetum.ModelName = field.NewString(tableName, "model_name")
	_modelMetum.Protocol = field.NewString(tableName, "protocol")
	_modelMetum.IconURI = field.NewString(tableName, "icon_uri")
	_modelMetum.IconURL = field.NewString(tableName, "icon_url")
	_modelMetum.Capability = field.NewString(tableName, "capability")
	_modelMetum.ConnConfig = field.NewString(tableName, "conn_config")
	_modelMetum.Status = field.NewInt32(tableName, "status")
	_modelMetum.Description = field.NewString(tableName, "description")
	_modelMetum.CreatedAt = field.NewInt64(tableName, "created_at")
	_modelMetum.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_modelMetum.DeletedAt = field.NewInt64(tableName, "deleted_at")

	_modelMetum.fillFieldMap()

	return _modelMetum
}

// modelMetum 模型元信息
type modelMetum struct {
	modelMetumDo modelMetumDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键ID
	ModelName   field.String // 模型名称
	Protocol    field.String // 模型协议
	IconURI     field.String // Icon URI
	IconURL     field.String // Icon URL
	Capability  field.String // 模型能力
	ConnConfig  field.String // 模型连接配置
	Status      field.Int32  // 模型状态
	Description field.String // 模型描述
	CreatedAt   field.Int64  // Create Time in Milliseconds
	UpdatedAt   field.Int64  // Update Time in Milliseconds
	DeletedAt   field.Int64  // Delete Time in Milliseconds

	fieldMap map[string]field.Expr
}

func (m modelMetum) Table(newTableName string) *modelMetum {
	m.modelMetumDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m modelMetum) As(alias string) *modelMetum {
	m.modelMetumDo.DO = *(m.modelMetumDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *modelMetum) updateTableName(table string) *modelMetum {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.ModelName = field.NewString(table, "model_name")
	m.Protocol = field.NewString(table, "protocol")
	m.IconURI = field.NewString(table, "icon_uri")
	m.IconURL = field.NewString(table, "icon_url")
	m.Capability = field.NewString(table, "capability")
	m.ConnConfig = field.NewString(table, "conn_config")
	m.Status = field.NewInt32(table, "status")
	m.Description = field.NewString(table, "description")
	m.CreatedAt = field.NewInt64(table, "created_at")
	m.UpdatedAt = field.NewInt64(table, "updated_at")
	m.DeletedAt = field.NewInt64(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *modelMetum) WithContext(ctx context.Context) *modelMetumDo {
	return m.modelMetumDo.WithContext(ctx)
}

func (m modelMetum) TableName() string { return m.modelMetumDo.TableName() }

func (m modelMetum) Alias() string { return m.modelMetumDo.Alias() }

func (m modelMetum) Columns(cols ...field.Expr) gen.Columns { return m.modelMetumDo.Columns(cols...) }

func (m *modelMetum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *modelMetum) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["model_name"] = m.ModelName
	m.fieldMap["protocol"] = m.Protocol
	m.fieldMap["icon_uri"] = m.IconURI
	m.fieldMap["icon_url"] = m.IconURL
	m.fieldMap["capability"] = m.Capability
	m.fieldMap["conn_config"] = m.ConnConfig
	m.fieldMap["status"] = m.Status
	m.fieldMap["description"] = m.Description
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
}

func (m modelMetum) clone(db *gorm.DB) modelMetum {
	m.modelMetumDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m modelMetum) replaceDB(db *gorm.DB) modelMetum {
	m.modelMetumDo.ReplaceDB(db)
	return m
}

type modelMetumDo struct{ gen.DO }

func (m modelMetumDo) Debug() *modelMetumDo {
	return m.withDO(m.DO.Debug())
}

func (m modelMetumDo) WithContext(ctx context.Context) *modelMetumDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m modelMetumDo) ReadDB() *modelMetumDo {
	return m.Clauses(dbresolver.Read)
}

func (m modelMetumDo) WriteDB() *modelMetumDo {
	return m.Clauses(dbresolver.Write)
}

func (m modelMetumDo) Session(config *gorm.Session) *modelMetumDo {
	return m.withDO(m.DO.Session(config))
}

func (m modelMetumDo) Clauses(conds ...clause.Expression) *modelMetumDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m modelMetumDo) Returning(value interface{}, columns ...string) *modelMetumDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m modelMetumDo) Not(conds ...gen.Condition) *modelMetumDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m modelMetumDo) Or(conds ...gen.Condition) *modelMetumDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m modelMetumDo) Select(conds ...field.Expr) *modelMetumDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m modelMetumDo) Where(conds ...gen.Condition) *modelMetumDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m modelMetumDo) Order(conds ...field.Expr) *modelMetumDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m modelMetumDo) Distinct(cols ...field.Expr) *modelMetumDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m modelMetumDo) Omit(cols ...field.Expr) *modelMetumDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m modelMetumDo) Join(table schema.Tabler, on ...field.Expr) *modelMetumDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m modelMetumDo) LeftJoin(table schema.Tabler, on ...field.Expr) *modelMetumDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m modelMetumDo) RightJoin(table schema.Tabler, on ...field.Expr) *modelMetumDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m modelMetumDo) Group(cols ...field.Expr) *modelMetumDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m modelMetumDo) Having(conds ...gen.Condition) *modelMetumDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m modelMetumDo) Limit(limit int) *modelMetumDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m modelMetumDo) Offset(offset int) *modelMetumDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m modelMetumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *modelMetumDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m modelMetumDo) Unscoped() *modelMetumDo {
	return m.withDO(m.DO.Unscoped())
}

func (m modelMetumDo) Create(values ...*model.ModelMetum) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m modelMetumDo) CreateInBatches(values []*model.ModelMetum, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m modelMetumDo) Save(values ...*model.ModelMetum) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m modelMetumDo) First() (*model.ModelMetum, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelMetum), nil
	}
}

func (m modelMetumDo) Take() (*model.ModelMetum, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelMetum), nil
	}
}

func (m modelMetumDo) Last() (*model.ModelMetum, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelMetum), nil
	}
}

func (m modelMetumDo) Find() ([]*model.ModelMetum, error) {
	result, err := m.DO.Find()
	return result.([]*model.ModelMetum), err
}

func (m modelMetumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModelMetum, err error) {
	buf := make([]*model.ModelMetum, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m modelMetumDo) FindInBatches(result *[]*model.ModelMetum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m modelMetumDo) Attrs(attrs ...field.AssignExpr) *modelMetumDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m modelMetumDo) Assign(attrs ...field.AssignExpr) *modelMetumDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m modelMetumDo) Joins(fields ...field.RelationField) *modelMetumDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m modelMetumDo) Preload(fields ...field.RelationField) *modelMetumDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m modelMetumDo) FirstOrInit() (*model.ModelMetum, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelMetum), nil
	}
}

func (m modelMetumDo) FirstOrCreate() (*model.ModelMetum, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelMetum), nil
	}
}

func (m modelMetumDo) FindByPage(offset int, limit int) (result []*model.ModelMetum, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m modelMetumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m modelMetumDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m modelMetumDo) Delete(models ...*model.ModelMetum) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *modelMetumDo) withDO(do gen.Dao) *modelMetumDo {
	m.DO = *do.(*gen.DO)
	return m
}
