// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAPIKey = "api_key"

// APIKey mapped from table <api_key>
type APIKey struct {
	ID          int64  `gorm:"column:id;primaryKey" json:"id"`
	Name        string `gorm:"column:name" json:"name"`
	APIKey      string `gorm:"column:api_key" json:"api_key"`
	ConnectorID int64  `gorm:"column:connector_id" json:"connector_id"`
	UserID      int64  `gorm:"column:user_id" json:"user_id"`
	AkType      int32  `gorm:"column:ak_type" json:"ak_type"`
	LastUsedAt  int64  `gorm:"column:last_used_at" json:"last_used_at"`
	ExpiredAt   int64  `gorm:"column:expired_at" json:"expired_at"`
	CreatedAt   int64  `gorm:"column:created_at;autoCreateTime:milli" json:"created_at"`
	UpdatedAt   int64  `gorm:"column:updated_at;autoUpdateTime:milli" json:"updated_at"`
}

// TableName APIKey's table name
func (*APIKey) TableName() string {
	return TableNameAPIKey
}
