// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kiosk404/airi-go/backend/modules/foundation/user/domain/repo (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/user.go -package=mocks . UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/kiosk404/airi-go/backend/modules/foundation/user/infra/repo/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CheckAccountExist mocks base method.
func (m *MockUserRepository) CheckAccountExist(ctx context.Context, account string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccountExist", ctx, account)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccountExist indicates an expected call of CheckAccountExist.
func (mr *MockUserRepositoryMockRecorder) CheckAccountExist(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccountExist", reflect.TypeOf((*MockUserRepository)(nil).CheckAccountExist), ctx, account)
}

// CheckUniqueNameExist mocks base method.
func (m *MockUserRepository) CheckUniqueNameExist(ctx context.Context, uniqueName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUniqueNameExist", ctx, uniqueName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUniqueNameExist indicates an expected call of CheckUniqueNameExist.
func (mr *MockUserRepositoryMockRecorder) CheckUniqueNameExist(ctx, uniqueName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUniqueNameExist", reflect.TypeOf((*MockUserRepository)(nil).CheckUniqueNameExist), ctx, uniqueName)
}

// ClearSessionKey mocks base method.
func (m *MockUserRepository) ClearSessionKey(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSessionKey", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSessionKey indicates an expected call of ClearSessionKey.
func (mr *MockUserRepositoryMockRecorder) ClearSessionKey(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSessionKey", reflect.TypeOf((*MockUserRepository)(nil).ClearSessionKey), ctx, userID)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, user)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// GetUserBySessionKey mocks base method.
func (m *MockUserRepository) GetUserBySessionKey(ctx context.Context, sessionKey string) (*model.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBySessionKey", ctx, sessionKey)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserBySessionKey indicates an expected call of GetUserBySessionKey.
func (mr *MockUserRepositoryMockRecorder) GetUserBySessionKey(ctx, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBySessionKey", reflect.TypeOf((*MockUserRepository)(nil).GetUserBySessionKey), ctx, sessionKey)
}

// GetUsersByAccount mocks base method.
func (m *MockUserRepository) GetUsersByAccount(ctx context.Context, account string) (*model.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByAccount", ctx, account)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUsersByAccount indicates an expected call of GetUsersByAccount.
func (mr *MockUserRepositoryMockRecorder) GetUsersByAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByAccount", reflect.TypeOf((*MockUserRepository)(nil).GetUsersByAccount), ctx, account)
}

// GetUsersByIDs mocks base method.
func (m *MockUserRepository) GetUsersByIDs(ctx context.Context, userIDs []int64) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ctx, userIDs)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MockUserRepositoryMockRecorder) GetUsersByIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MockUserRepository)(nil).GetUsersByIDs), ctx, userIDs)
}

// UpdateAvatar mocks base method.
func (m *MockUserRepository) UpdateAvatar(ctx context.Context, userID int64, iconURI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, userID, iconURI)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockUserRepositoryMockRecorder) UpdateAvatar(ctx, userID, iconURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockUserRepository)(nil).UpdateAvatar), ctx, userID, iconURI)
}

// UpdatePassword mocks base method.
func (m *MockUserRepository) UpdatePassword(ctx context.Context, account, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, account, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepositoryMockRecorder) UpdatePassword(ctx, account, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepository)(nil).UpdatePassword), ctx, account, password)
}

// UpdateProfile mocks base method.
func (m *MockUserRepository) UpdateProfile(ctx context.Context, userID int64, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserRepositoryMockRecorder) UpdateProfile(ctx, userID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserRepository)(nil).UpdateProfile), ctx, userID, updates)
}

// UpdateSessionKey mocks base method.
func (m *MockUserRepository) UpdateSessionKey(ctx context.Context, userID int64, sessionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionKey", ctx, userID, sessionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionKey indicates an expected call of UpdateSessionKey.
func (mr *MockUserRepositoryMockRecorder) UpdateSessionKey(ctx, userID, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionKey", reflect.TypeOf((*MockUserRepository)(nil).UpdateSessionKey), ctx, userID, sessionKey)
}
