// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package modelapi

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/kiosk404/airi-go/backend/api/model/app/developer_api"
	"github.com/kiosk404/airi-go/backend/api/model/base"
)

type ModelType int64

const (
	ModelType_LLM           ModelType = 0
	ModelType_TextEmbedding ModelType = 1
	ModelType_Rerank        ModelType = 2
)

func (p ModelType) String() string {
	switch p {
	case ModelType_LLM:
		return "LLM"
	case ModelType_TextEmbedding:
		return "TextEmbedding"
	case ModelType_Rerank:
		return "Rerank"
	}
	return "<UNSET>"
}

func ModelTypeFromString(s string) (ModelType, error) {
	switch s {
	case "LLM":
		return ModelType_LLM, nil
	case "TextEmbedding":
		return ModelType_TextEmbedding, nil
	case "Rerank":
		return ModelType_Rerank, nil
	}
	return ModelType(0), fmt.Errorf("not a valid ModelType string")
}

func ModelTypePtr(v ModelType) *ModelType { return &v }
func (p *ModelType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ModelType(result.Int64)
	return
}

func (p *ModelType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ThinkingType int64

const (
	ThinkingType_Default ThinkingType = 0
	ThinkingType_Enable  ThinkingType = 1
	ThinkingType_Disable ThinkingType = 2
	ThinkingType_Auto    ThinkingType = 3
)

func (p ThinkingType) String() string {
	switch p {
	case ThinkingType_Default:
		return "Default"
	case ThinkingType_Enable:
		return "Enable"
	case ThinkingType_Disable:
		return "Disable"
	case ThinkingType_Auto:
		return "Auto"
	}
	return "<UNSET>"
}

func ThinkingTypeFromString(s string) (ThinkingType, error) {
	switch s {
	case "Default":
		return ThinkingType_Default, nil
	case "Enable":
		return ThinkingType_Enable, nil
	case "Disable":
		return ThinkingType_Disable, nil
	case "Auto":
		return ThinkingType_Auto, nil
	}
	return ThinkingType(0), fmt.Errorf("not a valid ThinkingType string")
}

func ThinkingTypePtr(v ThinkingType) *ThinkingType { return &v }
func (p *ThinkingType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ThinkingType(result.Int64)
	return
}

func (p *ThinkingType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ModelStatus int64

const (
	ModelStatus_StatusDefault ModelStatus = 0
	ModelStatus_StatusInUse   ModelStatus = 1
	ModelStatus_StatusDeleted ModelStatus = 2
)

func (p ModelStatus) String() string {
	switch p {
	case ModelStatus_StatusDefault:
		return "StatusDefault"
	case ModelStatus_StatusInUse:
		return "StatusInUse"
	case ModelStatus_StatusDeleted:
		return "StatusDeleted"
	}
	return "<UNSET>"
}

func ModelStatusFromString(s string) (ModelStatus, error) {
	switch s {
	case "StatusDefault":
		return ModelStatus_StatusDefault, nil
	case "StatusInUse":
		return ModelStatus_StatusInUse, nil
	case "StatusDeleted":
		return ModelStatus_StatusDeleted, nil
	}
	return ModelStatus(0), fmt.Errorf("not a valid ModelStatus string")
}

func ModelStatusPtr(v ModelStatus) *ModelStatus { return &v }
func (p *ModelStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ModelStatus(result.Int64)
	return
}

func (p *ModelStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type CodeRunnerType int64

const (
	CodeRunnerType_Local   CodeRunnerType = 0
	CodeRunnerType_Sandbox CodeRunnerType = 1
)

func (p CodeRunnerType) String() string {
	switch p {
	case CodeRunnerType_Local:
		return "Local"
	case CodeRunnerType_Sandbox:
		return "Sandbox"
	}
	return "<UNSET>"
}

func CodeRunnerTypeFromString(s string) (CodeRunnerType, error) {
	switch s {
	case "Local":
		return CodeRunnerType_Local, nil
	case "Sandbox":
		return CodeRunnerType_Sandbox, nil
	}
	return CodeRunnerType(0), fmt.Errorf("not a valid CodeRunnerType string")
}

func CodeRunnerTypePtr(v CodeRunnerType) *CodeRunnerType { return &v }
func (p *CodeRunnerType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = CodeRunnerType(result.Int64)
	return
}

func (p *CodeRunnerType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type EmbeddingType int64

const (
	EmbeddingType_Ark    EmbeddingType = 0
	EmbeddingType_OpenAI EmbeddingType = 1
	EmbeddingType_Ollama EmbeddingType = 2
	EmbeddingType_Gemini EmbeddingType = 3
	EmbeddingType_HTTP   EmbeddingType = 4
)

func (p EmbeddingType) String() string {
	switch p {
	case EmbeddingType_Ark:
		return "Ark"
	case EmbeddingType_OpenAI:
		return "OpenAI"
	case EmbeddingType_Ollama:
		return "Ollama"
	case EmbeddingType_Gemini:
		return "Gemini"
	case EmbeddingType_HTTP:
		return "HTTP"
	}
	return "<UNSET>"
}

func EmbeddingTypeFromString(s string) (EmbeddingType, error) {
	switch s {
	case "Ark":
		return EmbeddingType_Ark, nil
	case "OpenAI":
		return EmbeddingType_OpenAI, nil
	case "Ollama":
		return EmbeddingType_Ollama, nil
	case "Gemini":
		return EmbeddingType_Gemini, nil
	case "HTTP":
		return EmbeddingType_HTTP, nil
	}
	return EmbeddingType(0), fmt.Errorf("not a valid EmbeddingType string")
}

func EmbeddingTypePtr(v EmbeddingType) *EmbeddingType { return &v }
func (p *EmbeddingType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = EmbeddingType(result.Int64)
	return
}

func (p *EmbeddingType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RerankType int64

const (
	RerankType_VikingDB RerankType = 0
	RerankType_RRF      RerankType = 1
)

func (p RerankType) String() string {
	switch p {
	case RerankType_VikingDB:
		return "VikingDB"
	case RerankType_RRF:
		return "RRF"
	}
	return "<UNSET>"
}

func RerankTypeFromString(s string) (RerankType, error) {
	switch s {
	case "VikingDB":
		return RerankType_VikingDB, nil
	case "RRF":
		return RerankType_RRF, nil
	}
	return RerankType(0), fmt.Errorf("not a valid RerankType string")
}

func RerankTypePtr(v RerankType) *RerankType { return &v }
func (p *RerankType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RerankType(result.Int64)
	return
}

func (p *RerankType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OCRType int64

const (
	OCRType_Volcengine OCRType = 0
	OCRType_Paddleocr  OCRType = 1
)

func (p OCRType) String() string {
	switch p {
	case OCRType_Volcengine:
		return "Volcengine"
	case OCRType_Paddleocr:
		return "Paddleocr"
	}
	return "<UNSET>"
}

func OCRTypeFromString(s string) (OCRType, error) {
	switch s {
	case "Volcengine":
		return OCRType_Volcengine, nil
	case "Paddleocr":
		return OCRType_Paddleocr, nil
	}
	return OCRType(0), fmt.Errorf("not a valid OCRType string")
}

func OCRTypePtr(v OCRType) *OCRType { return &v }
func (p *OCRType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OCRType(result.Int64)
	return
}

func (p *OCRType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ParserType int64

const (
	ParserType_builtin   ParserType = 0
	ParserType_Paddleocr ParserType = 1
)

func (p ParserType) String() string {
	switch p {
	case ParserType_builtin:
		return "builtin"
	case ParserType_Paddleocr:
		return "Paddleocr"
	}
	return "<UNSET>"
}

func ParserTypeFromString(s string) (ParserType, error) {
	switch s {
	case "builtin":
		return ParserType_builtin, nil
	case "Paddleocr":
		return ParserType_Paddleocr, nil
	}
	return ParserType(0), fmt.Errorf("not a valid ParserType string")
}

func ParserTypePtr(v ParserType) *ParserType { return &v }
func (p *ParserType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ParserType(result.Int64)
	return
}

func (p *ParserType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type I18nText struct {
	ZhCn string `thrift:"zh_cn,1" json:"zh_cn"`
	EnUs string `thrift:"en_us,2" json:"en_us"`
}

func NewI18nText() *I18nText {
	return &I18nText{}
}

func (p *I18nText) InitDefault() {
}

func (p *I18nText) GetZhCn() (v string) {
	return p.ZhCn
}

func (p *I18nText) GetEnUs() (v string) {
	return p.EnUs
}
func (p *I18nText) SetZhCn(val string) {
	p.ZhCn = val
}
func (p *I18nText) SetEnUs(val string) {
	p.EnUs = val
}

func (p *I18nText) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("I18nText(%+v)", *p)
}

type ModelProvider struct {
	Name        *I18nText                `thrift:"name,1" json:"name"`
	IconURI     string                   `thrift:"icon_uri,2" json:"icon_uri"`
	IconURL     string                   `thrift:"icon_url,3" json:"icon_url"`
	Description *I18nText                `thrift:"description,4" json:"description"`
	ModelClass  developer_api.ModelClass `thrift:"model_class,5,default,ModelClass" json:"model_class"`
}

func NewModelProvider() *ModelProvider {
	return &ModelProvider{}
}

func (p *ModelProvider) InitDefault() {
}

var ModelProvider_Name_DEFAULT *I18nText

func (p *ModelProvider) GetName() (v *I18nText) {
	if !p.IsSetName() {
		return ModelProvider_Name_DEFAULT
	}
	return p.Name
}

func (p *ModelProvider) GetIconURI() (v string) {
	return p.IconURI
}

func (p *ModelProvider) GetIconURL() (v string) {
	return p.IconURL
}

var ModelProvider_Description_DEFAULT *I18nText

func (p *ModelProvider) GetDescription() (v *I18nText) {
	if !p.IsSetDescription() {
		return ModelProvider_Description_DEFAULT
	}
	return p.Description
}

func (p *ModelProvider) GetModelClass() (v developer_api.ModelClass) {
	return p.ModelClass
}
func (p *ModelProvider) SetName(val *I18nText) {
	p.Name = val
}
func (p *ModelProvider) SetIconURI(val string) {
	p.IconURI = val
}
func (p *ModelProvider) SetIconURL(val string) {
	p.IconURL = val
}
func (p *ModelProvider) SetDescription(val *I18nText) {
	p.Description = val
}
func (p *ModelProvider) SetModelClass(val developer_api.ModelClass) {
	p.ModelClass = val
}

func (p *ModelProvider) IsSetName() bool {
	return p.Name != nil
}

func (p *ModelProvider) IsSetDescription() bool {
	return p.Description != nil
}

func (p *ModelProvider) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelProvider(%+v)", *p)
}

type DisplayInfo struct {
	Name         string    `thrift:"name,1" json:"name"`
	Description  *I18nText `thrift:"description,3" json:"description"`
	OutputTokens int64     `thrift:"output_tokens,4" json:"output_tokens"`
	MaxTokens    int64     `thrift:"max_tokens,5" json:"max_tokens"`
}

func NewDisplayInfo() *DisplayInfo {
	return &DisplayInfo{}
}

func (p *DisplayInfo) InitDefault() {
}

func (p *DisplayInfo) GetName() (v string) {
	return p.Name
}

var DisplayInfo_Description_DEFAULT *I18nText

func (p *DisplayInfo) GetDescription() (v *I18nText) {
	if !p.IsSetDescription() {
		return DisplayInfo_Description_DEFAULT
	}
	return p.Description
}

func (p *DisplayInfo) GetOutputTokens() (v int64) {
	return p.OutputTokens
}

func (p *DisplayInfo) GetMaxTokens() (v int64) {
	return p.MaxTokens
}
func (p *DisplayInfo) SetName(val string) {
	p.Name = val
}
func (p *DisplayInfo) SetDescription(val *I18nText) {
	p.Description = val
}
func (p *DisplayInfo) SetOutputTokens(val int64) {
	p.OutputTokens = val
}
func (p *DisplayInfo) SetMaxTokens(val int64) {
	p.MaxTokens = val
}

func (p *DisplayInfo) IsSetDescription() bool {
	return p.Description != nil
}

func (p *DisplayInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DisplayInfo(%+v)", *p)
}

type Connection struct {
	BaseConnInfo *BaseConnectionInfo `thrift:"base_conn_info,1" json:"base_conn_info"`
	Openai       *OpenAIConnInfo     `thrift:"openai,2,optional" json:"openai,omitempty"`
	Deepseek     *DeepseekConnInfo   `thrift:"deepseek,3,optional" json:"deepseek,omitempty"`
	Gemini       *GeminiConnInfo     `thrift:"gemini,4,optional" json:"gemini,omitempty"`
	Qwen         *QwenConnInfo       `thrift:"qwen,5,optional" json:"qwen,omitempty"`
	Ollama       *OllamaConnInfo     `thrift:"ollama,6,optional" json:"ollama,omitempty"`
	Claude       *ClaudeConnInfo     `thrift:"claude,7,optional" json:"claude,omitempty"`
}

func NewConnection() *Connection {
	return &Connection{}
}

func (p *Connection) InitDefault() {
}

var Connection_BaseConnInfo_DEFAULT *BaseConnectionInfo

func (p *Connection) GetBaseConnInfo() (v *BaseConnectionInfo) {
	if !p.IsSetBaseConnInfo() {
		return Connection_BaseConnInfo_DEFAULT
	}
	return p.BaseConnInfo
}

var Connection_Openai_DEFAULT *OpenAIConnInfo

func (p *Connection) GetOpenai() (v *OpenAIConnInfo) {
	if !p.IsSetOpenai() {
		return Connection_Openai_DEFAULT
	}
	return p.Openai
}

var Connection_Deepseek_DEFAULT *DeepseekConnInfo

func (p *Connection) GetDeepseek() (v *DeepseekConnInfo) {
	if !p.IsSetDeepseek() {
		return Connection_Deepseek_DEFAULT
	}
	return p.Deepseek
}

var Connection_Gemini_DEFAULT *GeminiConnInfo

func (p *Connection) GetGemini() (v *GeminiConnInfo) {
	if !p.IsSetGemini() {
		return Connection_Gemini_DEFAULT
	}
	return p.Gemini
}

var Connection_Qwen_DEFAULT *QwenConnInfo

func (p *Connection) GetQwen() (v *QwenConnInfo) {
	if !p.IsSetQwen() {
		return Connection_Qwen_DEFAULT
	}
	return p.Qwen
}

var Connection_Ollama_DEFAULT *OllamaConnInfo

func (p *Connection) GetOllama() (v *OllamaConnInfo) {
	if !p.IsSetOllama() {
		return Connection_Ollama_DEFAULT
	}
	return p.Ollama
}

var Connection_Claude_DEFAULT *ClaudeConnInfo

func (p *Connection) GetClaude() (v *ClaudeConnInfo) {
	if !p.IsSetClaude() {
		return Connection_Claude_DEFAULT
	}
	return p.Claude
}
func (p *Connection) SetBaseConnInfo(val *BaseConnectionInfo) {
	p.BaseConnInfo = val
}
func (p *Connection) SetOpenai(val *OpenAIConnInfo) {
	p.Openai = val
}
func (p *Connection) SetDeepseek(val *DeepseekConnInfo) {
	p.Deepseek = val
}
func (p *Connection) SetGemini(val *GeminiConnInfo) {
	p.Gemini = val
}
func (p *Connection) SetQwen(val *QwenConnInfo) {
	p.Qwen = val
}
func (p *Connection) SetOllama(val *OllamaConnInfo) {
	p.Ollama = val
}
func (p *Connection) SetClaude(val *ClaudeConnInfo) {
	p.Claude = val
}

func (p *Connection) IsSetBaseConnInfo() bool {
	return p.BaseConnInfo != nil
}

func (p *Connection) IsSetOpenai() bool {
	return p.Openai != nil
}

func (p *Connection) IsSetDeepseek() bool {
	return p.Deepseek != nil
}

func (p *Connection) IsSetGemini() bool {
	return p.Gemini != nil
}

func (p *Connection) IsSetQwen() bool {
	return p.Qwen != nil
}

func (p *Connection) IsSetOllama() bool {
	return p.Ollama != nil
}

func (p *Connection) IsSetClaude() bool {
	return p.Claude != nil
}

func (p *Connection) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Connection(%+v)", *p)
}

type BaseConnectionInfo struct {
	BaseURL      string       `thrift:"base_url,1" json:"base_url"`
	APIKey       string       `thrift:"api_key,2" json:"api_key"`
	Model        string       `thrift:"model,3" json:"model"`
	ThinkingType ThinkingType `thrift:"thinking_type,4,default,ThinkingType" json:"thinking_type"`
}

func NewBaseConnectionInfo() *BaseConnectionInfo {
	return &BaseConnectionInfo{}
}

func (p *BaseConnectionInfo) InitDefault() {
}

func (p *BaseConnectionInfo) GetBaseURL() (v string) {
	return p.BaseURL
}

func (p *BaseConnectionInfo) GetAPIKey() (v string) {
	return p.APIKey
}

func (p *BaseConnectionInfo) GetModel() (v string) {
	return p.Model
}

func (p *BaseConnectionInfo) GetThinkingType() (v ThinkingType) {
	return p.ThinkingType
}
func (p *BaseConnectionInfo) SetBaseURL(val string) {
	p.BaseURL = val
}
func (p *BaseConnectionInfo) SetAPIKey(val string) {
	p.APIKey = val
}
func (p *BaseConnectionInfo) SetModel(val string) {
	p.Model = val
}
func (p *BaseConnectionInfo) SetThinkingType(val ThinkingType) {
	p.ThinkingType = val
}

func (p *BaseConnectionInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseConnectionInfo(%+v)", *p)
}

type EmbeddingInfo struct {
	Dims int32 `thrift:"dims,1" json:"dims"`
}

func NewEmbeddingInfo() *EmbeddingInfo {
	return &EmbeddingInfo{}
}

func (p *EmbeddingInfo) InitDefault() {
}

func (p *EmbeddingInfo) GetDims() (v int32) {
	return p.Dims
}
func (p *EmbeddingInfo) SetDims(val int32) {
	p.Dims = val
}

func (p *EmbeddingInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmbeddingInfo(%+v)", *p)
}

type ArkConnInfo struct {
	Region  string `thrift:"region,1" json:"region"`
	APIType string `thrift:"api_type,3" json:"api_type"`
}

func NewArkConnInfo() *ArkConnInfo {
	return &ArkConnInfo{}
}

func (p *ArkConnInfo) InitDefault() {
}

func (p *ArkConnInfo) GetRegion() (v string) {
	return p.Region
}

func (p *ArkConnInfo) GetAPIType() (v string) {
	return p.APIType
}
func (p *ArkConnInfo) SetRegion(val string) {
	p.Region = val
}
func (p *ArkConnInfo) SetAPIType(val string) {
	p.APIType = val
}

func (p *ArkConnInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArkConnInfo(%+v)", *p)
}

type OpenAIConnInfo struct {
	ByAzure    bool   `thrift:"by_azure,6" json:"by_azure"`
	APIVersion string `thrift:"api_version,7" json:"api_version"`
}

func NewOpenAIConnInfo() *OpenAIConnInfo {
	return &OpenAIConnInfo{}
}

func (p *OpenAIConnInfo) InitDefault() {
}

func (p *OpenAIConnInfo) GetByAzure() (v bool) {
	return p.ByAzure
}

func (p *OpenAIConnInfo) GetAPIVersion() (v string) {
	return p.APIVersion
}
func (p *OpenAIConnInfo) SetByAzure(val bool) {
	p.ByAzure = val
}
func (p *OpenAIConnInfo) SetAPIVersion(val string) {
	p.APIVersion = val
}

func (p *OpenAIConnInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OpenAIConnInfo(%+v)", *p)
}

type GeminiConnInfo struct {
	Backend  int32  `thrift:"backend,1" json:"backend"`
	Project  string `thrift:"project,2" json:"project"`
	Location string `thrift:"location,3" json:"location"`
}

func NewGeminiConnInfo() *GeminiConnInfo {
	return &GeminiConnInfo{}
}

func (p *GeminiConnInfo) InitDefault() {
}

func (p *GeminiConnInfo) GetBackend() (v int32) {
	return p.Backend
}

func (p *GeminiConnInfo) GetProject() (v string) {
	return p.Project
}

func (p *GeminiConnInfo) GetLocation() (v string) {
	return p.Location
}
func (p *GeminiConnInfo) SetBackend(val int32) {
	p.Backend = val
}
func (p *GeminiConnInfo) SetProject(val string) {
	p.Project = val
}
func (p *GeminiConnInfo) SetLocation(val string) {
	p.Location = val
}

func (p *GeminiConnInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GeminiConnInfo(%+v)", *p)
}

type DeepseekConnInfo struct {
}

func NewDeepseekConnInfo() *DeepseekConnInfo {
	return &DeepseekConnInfo{}
}

func (p *DeepseekConnInfo) InitDefault() {
}

func (p *DeepseekConnInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeepseekConnInfo(%+v)", *p)
}

type QwenConnInfo struct {
}

func NewQwenConnInfo() *QwenConnInfo {
	return &QwenConnInfo{}
}

func (p *QwenConnInfo) InitDefault() {
}

func (p *QwenConnInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QwenConnInfo(%+v)", *p)
}

type OllamaConnInfo struct {
}

func NewOllamaConnInfo() *OllamaConnInfo {
	return &OllamaConnInfo{}
}

func (p *OllamaConnInfo) InitDefault() {
}

func (p *OllamaConnInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OllamaConnInfo(%+v)", *p)
}

type ClaudeConnInfo struct {
}

func NewClaudeConnInfo() *ClaudeConnInfo {
	return &ClaudeConnInfo{}
}

func (p *ClaudeConnInfo) InitDefault() {
}

func (p *ClaudeConnInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClaudeConnInfo(%+v)", *p)
}

type CreateModelReq struct {
	ModelClass      developer_api.ModelClass `thrift:"model_class,1,default,ModelClass" json:"model_class"`
	ModelName       string                   `thrift:"model_name,2" json:"model_name"`
	Connection      *Connection              `thrift:"connection,3" json:"connection"`
	EnableBase64URL bool                     `thrift:"enable_base64_url,4" json:"enable_base64_url"`
	Base            *base.Base               `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewCreateModelReq() *CreateModelReq {
	return &CreateModelReq{}
}

func (p *CreateModelReq) InitDefault() {
}

func (p *CreateModelReq) GetModelClass() (v developer_api.ModelClass) {
	return p.ModelClass
}

func (p *CreateModelReq) GetModelName() (v string) {
	return p.ModelName
}

var CreateModelReq_Connection_DEFAULT *Connection

func (p *CreateModelReq) GetConnection() (v *Connection) {
	if !p.IsSetConnection() {
		return CreateModelReq_Connection_DEFAULT
	}
	return p.Connection
}

func (p *CreateModelReq) GetEnableBase64URL() (v bool) {
	return p.EnableBase64URL
}

var CreateModelReq_Base_DEFAULT *base.Base

func (p *CreateModelReq) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return CreateModelReq_Base_DEFAULT
	}
	return p.Base
}
func (p *CreateModelReq) SetModelClass(val developer_api.ModelClass) {
	p.ModelClass = val
}
func (p *CreateModelReq) SetModelName(val string) {
	p.ModelName = val
}
func (p *CreateModelReq) SetConnection(val *Connection) {
	p.Connection = val
}
func (p *CreateModelReq) SetEnableBase64URL(val bool) {
	p.EnableBase64URL = val
}
func (p *CreateModelReq) SetBase(val *base.Base) {
	p.Base = val
}

func (p *CreateModelReq) IsSetConnection() bool {
	return p.Connection != nil
}

func (p *CreateModelReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateModelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateModelReq(%+v)", *p)
}

type CreateModelResp struct {
	ID       int64          `thrift:"id,1" json:"id"`
	Code     int64          `thrift:"code,253,required" json:"code"`
	Msg      string         `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewCreateModelResp() *CreateModelResp {
	return &CreateModelResp{}
}

func (p *CreateModelResp) InitDefault() {
}

func (p *CreateModelResp) GetID() (v int64) {
	return p.ID
}

func (p *CreateModelResp) GetCode() (v int64) {
	return p.Code
}

func (p *CreateModelResp) GetMsg() (v string) {
	return p.Msg
}

var CreateModelResp_BaseResp_DEFAULT *base.BaseResp

func (p *CreateModelResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateModelResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreateModelResp) SetID(val int64) {
	p.ID = val
}
func (p *CreateModelResp) SetCode(val int64) {
	p.Code = val
}
func (p *CreateModelResp) SetMsg(val string) {
	p.Msg = val
}
func (p *CreateModelResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CreateModelResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateModelResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateModelResp(%+v)", *p)
}

type DeleteModelReq struct {
	ID   int64      `thrift:"id,1" json:"id"`
	Base *base.Base `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewDeleteModelReq() *DeleteModelReq {
	return &DeleteModelReq{}
}

func (p *DeleteModelReq) InitDefault() {
}

func (p *DeleteModelReq) GetID() (v int64) {
	return p.ID
}

var DeleteModelReq_Base_DEFAULT *base.Base

func (p *DeleteModelReq) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return DeleteModelReq_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteModelReq) SetID(val int64) {
	p.ID = val
}
func (p *DeleteModelReq) SetBase(val *base.Base) {
	p.Base = val
}

func (p *DeleteModelReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteModelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteModelReq(%+v)", *p)
}

type DeleteModelResp struct {
	Code     int64          `thrift:"code,253,required" json:"code"`
	Msg      string         `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewDeleteModelResp() *DeleteModelResp {
	return &DeleteModelResp{}
}

func (p *DeleteModelResp) InitDefault() {
}

func (p *DeleteModelResp) GetCode() (v int64) {
	return p.Code
}

func (p *DeleteModelResp) GetMsg() (v string) {
	return p.Msg
}

var DeleteModelResp_BaseResp_DEFAULT *base.BaseResp

func (p *DeleteModelResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeleteModelResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteModelResp) SetCode(val int64) {
	p.Code = val
}
func (p *DeleteModelResp) SetMsg(val string) {
	p.Msg = val
}
func (p *DeleteModelResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeleteModelResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteModelResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteModelResp(%+v)", *p)
}

type UpdateModelResp struct {
	Code     int64          `thrift:"code,253,required" json:"code"`
	Msg      string         `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewUpdateModelResp() *UpdateModelResp {
	return &UpdateModelResp{}
}

func (p *UpdateModelResp) InitDefault() {
}

func (p *UpdateModelResp) GetCode() (v int64) {
	return p.Code
}

func (p *UpdateModelResp) GetMsg() (v string) {
	return p.Msg
}

var UpdateModelResp_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateModelResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateModelResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateModelResp) SetCode(val int64) {
	p.Code = val
}
func (p *UpdateModelResp) SetMsg(val string) {
	p.Msg = val
}
func (p *UpdateModelResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateModelResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateModelResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateModelResp(%+v)", *p)
}

type SaveBasicConfigurationReq struct {
	Configuration *BasicConfiguration `thrift:"configuration,1" json:"configuration"`
	Base          *base.Base          `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewSaveBasicConfigurationReq() *SaveBasicConfigurationReq {
	return &SaveBasicConfigurationReq{}
}

func (p *SaveBasicConfigurationReq) InitDefault() {
}

var SaveBasicConfigurationReq_Configuration_DEFAULT *BasicConfiguration

func (p *SaveBasicConfigurationReq) GetConfiguration() (v *BasicConfiguration) {
	if !p.IsSetConfiguration() {
		return SaveBasicConfigurationReq_Configuration_DEFAULT
	}
	return p.Configuration
}

var SaveBasicConfigurationReq_Base_DEFAULT *base.Base

func (p *SaveBasicConfigurationReq) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return SaveBasicConfigurationReq_Base_DEFAULT
	}
	return p.Base
}
func (p *SaveBasicConfigurationReq) SetConfiguration(val *BasicConfiguration) {
	p.Configuration = val
}
func (p *SaveBasicConfigurationReq) SetBase(val *base.Base) {
	p.Base = val
}

func (p *SaveBasicConfigurationReq) IsSetConfiguration() bool {
	return p.Configuration != nil
}

func (p *SaveBasicConfigurationReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *SaveBasicConfigurationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SaveBasicConfigurationReq(%+v)", *p)
}

type SaveBasicConfigurationResp struct {
	Code     int64          `thrift:"code,253,required" json:"code"`
	Msg      string         `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewSaveBasicConfigurationResp() *SaveBasicConfigurationResp {
	return &SaveBasicConfigurationResp{}
}

func (p *SaveBasicConfigurationResp) InitDefault() {
}

func (p *SaveBasicConfigurationResp) GetCode() (v int64) {
	return p.Code
}

func (p *SaveBasicConfigurationResp) GetMsg() (v string) {
	return p.Msg
}

var SaveBasicConfigurationResp_BaseResp_DEFAULT *base.BaseResp

func (p *SaveBasicConfigurationResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return SaveBasicConfigurationResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SaveBasicConfigurationResp) SetCode(val int64) {
	p.Code = val
}
func (p *SaveBasicConfigurationResp) SetMsg(val string) {
	p.Msg = val
}
func (p *SaveBasicConfigurationResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *SaveBasicConfigurationResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SaveBasicConfigurationResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SaveBasicConfigurationResp(%+v)", *p)
}

type GetBasicConfigurationReq struct {
	Base *base.Base `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewGetBasicConfigurationReq() *GetBasicConfigurationReq {
	return &GetBasicConfigurationReq{}
}

func (p *GetBasicConfigurationReq) InitDefault() {
}

var GetBasicConfigurationReq_Base_DEFAULT *base.Base

func (p *GetBasicConfigurationReq) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetBasicConfigurationReq_Base_DEFAULT
	}
	return p.Base
}
func (p *GetBasicConfigurationReq) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetBasicConfigurationReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetBasicConfigurationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBasicConfigurationReq(%+v)", *p)
}

type GetBasicConfigurationResp struct {
	Configuration *BasicConfiguration `thrift:"configuration,1" json:"configuration"`
	Code          int64               `thrift:"code,253,required" json:"code"`
	Msg           string              `thrift:"msg,254,required" json:"msg"`
	BaseResp      *base.BaseResp      `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewGetBasicConfigurationResp() *GetBasicConfigurationResp {
	return &GetBasicConfigurationResp{}
}

func (p *GetBasicConfigurationResp) InitDefault() {
}

var GetBasicConfigurationResp_Configuration_DEFAULT *BasicConfiguration

func (p *GetBasicConfigurationResp) GetConfiguration() (v *BasicConfiguration) {
	if !p.IsSetConfiguration() {
		return GetBasicConfigurationResp_Configuration_DEFAULT
	}
	return p.Configuration
}

func (p *GetBasicConfigurationResp) GetCode() (v int64) {
	return p.Code
}

func (p *GetBasicConfigurationResp) GetMsg() (v string) {
	return p.Msg
}

var GetBasicConfigurationResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetBasicConfigurationResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetBasicConfigurationResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetBasicConfigurationResp) SetConfiguration(val *BasicConfiguration) {
	p.Configuration = val
}
func (p *GetBasicConfigurationResp) SetCode(val int64) {
	p.Code = val
}
func (p *GetBasicConfigurationResp) SetMsg(val string) {
	p.Msg = val
}
func (p *GetBasicConfigurationResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetBasicConfigurationResp) IsSetConfiguration() bool {
	return p.Configuration != nil
}

func (p *GetBasicConfigurationResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetBasicConfigurationResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBasicConfigurationResp(%+v)", *p)
}

type SandboxConfig struct {
	AllowEnv       string  `thrift:"allow_env,1" json:"allow_env"`
	AllowRead      string  `thrift:"allow_read,2" json:"allow_read"`
	AllowWrite     string  `thrift:"allow_write,3" json:"allow_write"`
	AllowRun       string  `thrift:"allow_run,4" json:"allow_run"`
	AllowNet       string  `thrift:"allow_net,5" json:"allow_net"`
	AllowFfi       string  `thrift:"allow_ffi,6" json:"allow_ffi"`
	NodeModulesDir string  `thrift:"node_modules_dir,7" json:"node_modules_dir"`
	TimeoutSeconds float64 `thrift:"timeout_seconds,8" json:"timeout_seconds"`
	MemoryLimitMb  int64   `thrift:"memory_limit_mb,9" json:"memory_limit_mb"`
}

func NewSandboxConfig() *SandboxConfig {
	return &SandboxConfig{}
}

func (p *SandboxConfig) InitDefault() {
}

func (p *SandboxConfig) GetAllowEnv() (v string) {
	return p.AllowEnv
}

func (p *SandboxConfig) GetAllowRead() (v string) {
	return p.AllowRead
}

func (p *SandboxConfig) GetAllowWrite() (v string) {
	return p.AllowWrite
}

func (p *SandboxConfig) GetAllowRun() (v string) {
	return p.AllowRun
}

func (p *SandboxConfig) GetAllowNet() (v string) {
	return p.AllowNet
}

func (p *SandboxConfig) GetAllowFfi() (v string) {
	return p.AllowFfi
}

func (p *SandboxConfig) GetNodeModulesDir() (v string) {
	return p.NodeModulesDir
}

func (p *SandboxConfig) GetTimeoutSeconds() (v float64) {
	return p.TimeoutSeconds
}

func (p *SandboxConfig) GetMemoryLimitMb() (v int64) {
	return p.MemoryLimitMb
}
func (p *SandboxConfig) SetAllowEnv(val string) {
	p.AllowEnv = val
}
func (p *SandboxConfig) SetAllowRead(val string) {
	p.AllowRead = val
}
func (p *SandboxConfig) SetAllowWrite(val string) {
	p.AllowWrite = val
}
func (p *SandboxConfig) SetAllowRun(val string) {
	p.AllowRun = val
}
func (p *SandboxConfig) SetAllowNet(val string) {
	p.AllowNet = val
}
func (p *SandboxConfig) SetAllowFfi(val string) {
	p.AllowFfi = val
}
func (p *SandboxConfig) SetNodeModulesDir(val string) {
	p.NodeModulesDir = val
}
func (p *SandboxConfig) SetTimeoutSeconds(val float64) {
	p.TimeoutSeconds = val
}
func (p *SandboxConfig) SetMemoryLimitMb(val int64) {
	p.MemoryLimitMb = val
}

func (p *SandboxConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SandboxConfig(%+v)", *p)
}

type BasicConfiguration struct {
	AdminEmails             string               `thrift:"admin_emails,1" json:"admin_emails"`
	DisableUserRegistration bool                 `thrift:"disable_user_registration,2" json:"disable_user_registration"`
	AllowRegistrationEmail  string               `thrift:"allow_registration_email,3" json:"allow_registration_email"`
	PluginConfiguration     *PluginConfiguration `thrift:"plugin_configuration,4" json:"plugin_configuration"`
	CodeRunnerType          CodeRunnerType       `thrift:"code_runner_type,5,default,CodeRunnerType" json:"code_runner_type"`
	SandboxConfig           *SandboxConfig       `thrift:"sandbox_config,6,optional" json:"sandbox_config,omitempty"`
	ServerHost              string               `thrift:"server_host,7" json:"server_host"`
}

func NewBasicConfiguration() *BasicConfiguration {
	return &BasicConfiguration{}
}

func (p *BasicConfiguration) InitDefault() {
}

func (p *BasicConfiguration) GetAdminEmails() (v string) {
	return p.AdminEmails
}

func (p *BasicConfiguration) GetDisableUserRegistration() (v bool) {
	return p.DisableUserRegistration
}

func (p *BasicConfiguration) GetAllowRegistrationEmail() (v string) {
	return p.AllowRegistrationEmail
}

var BasicConfiguration_PluginConfiguration_DEFAULT *PluginConfiguration

func (p *BasicConfiguration) GetPluginConfiguration() (v *PluginConfiguration) {
	if !p.IsSetPluginConfiguration() {
		return BasicConfiguration_PluginConfiguration_DEFAULT
	}
	return p.PluginConfiguration
}

func (p *BasicConfiguration) GetCodeRunnerType() (v CodeRunnerType) {
	return p.CodeRunnerType
}

var BasicConfiguration_SandboxConfig_DEFAULT *SandboxConfig

func (p *BasicConfiguration) GetSandboxConfig() (v *SandboxConfig) {
	if !p.IsSetSandboxConfig() {
		return BasicConfiguration_SandboxConfig_DEFAULT
	}
	return p.SandboxConfig
}

func (p *BasicConfiguration) GetServerHost() (v string) {
	return p.ServerHost
}
func (p *BasicConfiguration) SetAdminEmails(val string) {
	p.AdminEmails = val
}
func (p *BasicConfiguration) SetDisableUserRegistration(val bool) {
	p.DisableUserRegistration = val
}
func (p *BasicConfiguration) SetAllowRegistrationEmail(val string) {
	p.AllowRegistrationEmail = val
}
func (p *BasicConfiguration) SetPluginConfiguration(val *PluginConfiguration) {
	p.PluginConfiguration = val
}
func (p *BasicConfiguration) SetCodeRunnerType(val CodeRunnerType) {
	p.CodeRunnerType = val
}
func (p *BasicConfiguration) SetSandboxConfig(val *SandboxConfig) {
	p.SandboxConfig = val
}
func (p *BasicConfiguration) SetServerHost(val string) {
	p.ServerHost = val
}

func (p *BasicConfiguration) IsSetPluginConfiguration() bool {
	return p.PluginConfiguration != nil
}

func (p *BasicConfiguration) IsSetSandboxConfig() bool {
	return p.SandboxConfig != nil
}

func (p *BasicConfiguration) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BasicConfiguration(%+v)", *p)
}

type PluginConfiguration struct {
	SaasPluginEnabled bool   `thrift:"saas_plugin_enabled,1" json:"saas_plugin_enabled"`
	APIToken          string `thrift:"api_token,2" json:"api_token"`
	SaasAPIBaseURL    string `thrift:"saas_api_base_url,3" json:"saas_api_base_url"`
}

func NewPluginConfiguration() *PluginConfiguration {
	return &PluginConfiguration{}
}

func (p *PluginConfiguration) InitDefault() {
}

func (p *PluginConfiguration) GetSaasPluginEnabled() (v bool) {
	return p.SaasPluginEnabled
}

func (p *PluginConfiguration) GetAPIToken() (v string) {
	return p.APIToken
}

func (p *PluginConfiguration) GetSaasAPIBaseURL() (v string) {
	return p.SaasAPIBaseURL
}
func (p *PluginConfiguration) SetSaasPluginEnabled(val bool) {
	p.SaasPluginEnabled = val
}
func (p *PluginConfiguration) SetAPIToken(val string) {
	p.APIToken = val
}
func (p *PluginConfiguration) SetSaasAPIBaseURL(val string) {
	p.SaasAPIBaseURL = val
}

func (p *PluginConfiguration) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginConfiguration(%+v)", *p)
}

type UpdateKnowledgeConfigReq struct {
	KnowledgeConfig *KnowledgeConfig `thrift:"knowledge_config,1" json:"knowledge_config"`
	Base            *base.Base       `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewUpdateKnowledgeConfigReq() *UpdateKnowledgeConfigReq {
	return &UpdateKnowledgeConfigReq{}
}

func (p *UpdateKnowledgeConfigReq) InitDefault() {
}

var UpdateKnowledgeConfigReq_KnowledgeConfig_DEFAULT *KnowledgeConfig

func (p *UpdateKnowledgeConfigReq) GetKnowledgeConfig() (v *KnowledgeConfig) {
	if !p.IsSetKnowledgeConfig() {
		return UpdateKnowledgeConfigReq_KnowledgeConfig_DEFAULT
	}
	return p.KnowledgeConfig
}

var UpdateKnowledgeConfigReq_Base_DEFAULT *base.Base

func (p *UpdateKnowledgeConfigReq) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return UpdateKnowledgeConfigReq_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateKnowledgeConfigReq) SetKnowledgeConfig(val *KnowledgeConfig) {
	p.KnowledgeConfig = val
}
func (p *UpdateKnowledgeConfigReq) SetBase(val *base.Base) {
	p.Base = val
}

func (p *UpdateKnowledgeConfigReq) IsSetKnowledgeConfig() bool {
	return p.KnowledgeConfig != nil
}

func (p *UpdateKnowledgeConfigReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateKnowledgeConfigReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateKnowledgeConfigReq(%+v)", *p)
}

type UpdateKnowledgeConfigResp struct {
	Code     int64          `thrift:"code,253,required" json:"code"`
	Msg      string         `thrift:"msg,254,required" json:"msg"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewUpdateKnowledgeConfigResp() *UpdateKnowledgeConfigResp {
	return &UpdateKnowledgeConfigResp{}
}

func (p *UpdateKnowledgeConfigResp) InitDefault() {
}

func (p *UpdateKnowledgeConfigResp) GetCode() (v int64) {
	return p.Code
}

func (p *UpdateKnowledgeConfigResp) GetMsg() (v string) {
	return p.Msg
}

var UpdateKnowledgeConfigResp_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateKnowledgeConfigResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateKnowledgeConfigResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateKnowledgeConfigResp) SetCode(val int64) {
	p.Code = val
}
func (p *UpdateKnowledgeConfigResp) SetMsg(val string) {
	p.Msg = val
}
func (p *UpdateKnowledgeConfigResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateKnowledgeConfigResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateKnowledgeConfigResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateKnowledgeConfigResp(%+v)", *p)
}

type GetKnowledgeConfigReq struct {
	Base *base.Base `thrift:"Base,255,optional" json:"Base,omitempty"`
}

func NewGetKnowledgeConfigReq() *GetKnowledgeConfigReq {
	return &GetKnowledgeConfigReq{}
}

func (p *GetKnowledgeConfigReq) InitDefault() {
}

var GetKnowledgeConfigReq_Base_DEFAULT *base.Base

func (p *GetKnowledgeConfigReq) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return GetKnowledgeConfigReq_Base_DEFAULT
	}
	return p.Base
}
func (p *GetKnowledgeConfigReq) SetBase(val *base.Base) {
	p.Base = val
}

func (p *GetKnowledgeConfigReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetKnowledgeConfigReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetKnowledgeConfigReq(%+v)", *p)
}

type GetKnowledgeConfigResp struct {
	KnowledgeConfig *KnowledgeConfig `thrift:"knowledge_config,1" json:"knowledge_config"`
	Code            int64            `thrift:"code,253,required" json:"code"`
	Msg             string           `thrift:"msg,254,required" json:"msg"`
	BaseResp        *base.BaseResp   `thrift:"BaseResp,255,required" json:"BaseResp"`
}

func NewGetKnowledgeConfigResp() *GetKnowledgeConfigResp {
	return &GetKnowledgeConfigResp{}
}

func (p *GetKnowledgeConfigResp) InitDefault() {
}

var GetKnowledgeConfigResp_KnowledgeConfig_DEFAULT *KnowledgeConfig

func (p *GetKnowledgeConfigResp) GetKnowledgeConfig() (v *KnowledgeConfig) {
	if !p.IsSetKnowledgeConfig() {
		return GetKnowledgeConfigResp_KnowledgeConfig_DEFAULT
	}
	return p.KnowledgeConfig
}

func (p *GetKnowledgeConfigResp) GetCode() (v int64) {
	return p.Code
}

func (p *GetKnowledgeConfigResp) GetMsg() (v string) {
	return p.Msg
}

var GetKnowledgeConfigResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetKnowledgeConfigResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetKnowledgeConfigResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetKnowledgeConfigResp) SetKnowledgeConfig(val *KnowledgeConfig) {
	p.KnowledgeConfig = val
}
func (p *GetKnowledgeConfigResp) SetCode(val int64) {
	p.Code = val
}
func (p *GetKnowledgeConfigResp) SetMsg(val string) {
	p.Msg = val
}
func (p *GetKnowledgeConfigResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetKnowledgeConfigResp) IsSetKnowledgeConfig() bool {
	return p.KnowledgeConfig != nil
}

func (p *GetKnowledgeConfigResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetKnowledgeConfigResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetKnowledgeConfigResp(%+v)", *p)
}

type KnowledgeConfig struct {
	EmbeddingConfig *EmbeddingConfig `thrift:"embedding_config,1" json:"embedding_config"`
	RerankConfig    *RerankConfig    `thrift:"rerank_config,2" json:"rerank_config"`
	OcrConfig       *OCRConfig       `thrift:"ocr_config,3" json:"ocr_config"`
	ParserConfig    *ParserConfig    `thrift:"parser_config,4" json:"parser_config"`
	BuiltinModelID  int64            `thrift:"builtin_model_id,5" json:"builtin_model_id"`
}

func NewKnowledgeConfig() *KnowledgeConfig {
	return &KnowledgeConfig{}
}

func (p *KnowledgeConfig) InitDefault() {
}

var KnowledgeConfig_EmbeddingConfig_DEFAULT *EmbeddingConfig

func (p *KnowledgeConfig) GetEmbeddingConfig() (v *EmbeddingConfig) {
	if !p.IsSetEmbeddingConfig() {
		return KnowledgeConfig_EmbeddingConfig_DEFAULT
	}
	return p.EmbeddingConfig
}

var KnowledgeConfig_RerankConfig_DEFAULT *RerankConfig

func (p *KnowledgeConfig) GetRerankConfig() (v *RerankConfig) {
	if !p.IsSetRerankConfig() {
		return KnowledgeConfig_RerankConfig_DEFAULT
	}
	return p.RerankConfig
}

var KnowledgeConfig_OcrConfig_DEFAULT *OCRConfig

func (p *KnowledgeConfig) GetOcrConfig() (v *OCRConfig) {
	if !p.IsSetOcrConfig() {
		return KnowledgeConfig_OcrConfig_DEFAULT
	}
	return p.OcrConfig
}

var KnowledgeConfig_ParserConfig_DEFAULT *ParserConfig

func (p *KnowledgeConfig) GetParserConfig() (v *ParserConfig) {
	if !p.IsSetParserConfig() {
		return KnowledgeConfig_ParserConfig_DEFAULT
	}
	return p.ParserConfig
}

func (p *KnowledgeConfig) GetBuiltinModelID() (v int64) {
	return p.BuiltinModelID
}
func (p *KnowledgeConfig) SetEmbeddingConfig(val *EmbeddingConfig) {
	p.EmbeddingConfig = val
}
func (p *KnowledgeConfig) SetRerankConfig(val *RerankConfig) {
	p.RerankConfig = val
}
func (p *KnowledgeConfig) SetOcrConfig(val *OCRConfig) {
	p.OcrConfig = val
}
func (p *KnowledgeConfig) SetParserConfig(val *ParserConfig) {
	p.ParserConfig = val
}
func (p *KnowledgeConfig) SetBuiltinModelID(val int64) {
	p.BuiltinModelID = val
}

func (p *KnowledgeConfig) IsSetEmbeddingConfig() bool {
	return p.EmbeddingConfig != nil
}

func (p *KnowledgeConfig) IsSetRerankConfig() bool {
	return p.RerankConfig != nil
}

func (p *KnowledgeConfig) IsSetOcrConfig() bool {
	return p.OcrConfig != nil
}

func (p *KnowledgeConfig) IsSetParserConfig() bool {
	return p.ParserConfig != nil
}

func (p *KnowledgeConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeConfig(%+v)", *p)
}

type EmbeddingConfig struct {
	Type         EmbeddingType        `thrift:"type,1,default,EmbeddingType" json:"type"`
	MaxBatchSize int32                `thrift:"max_batch_size,2" json:"max_batch_size"`
	Connection   *EmbeddingConnection `thrift:"connection,3" json:"connection"`
}

func NewEmbeddingConfig() *EmbeddingConfig {
	return &EmbeddingConfig{}
}

func (p *EmbeddingConfig) InitDefault() {
}

func (p *EmbeddingConfig) GetType() (v EmbeddingType) {
	return p.Type
}

func (p *EmbeddingConfig) GetMaxBatchSize() (v int32) {
	return p.MaxBatchSize
}

var EmbeddingConfig_Connection_DEFAULT *EmbeddingConnection

func (p *EmbeddingConfig) GetConnection() (v *EmbeddingConnection) {
	if !p.IsSetConnection() {
		return EmbeddingConfig_Connection_DEFAULT
	}
	return p.Connection
}
func (p *EmbeddingConfig) SetType(val EmbeddingType) {
	p.Type = val
}
func (p *EmbeddingConfig) SetMaxBatchSize(val int32) {
	p.MaxBatchSize = val
}
func (p *EmbeddingConfig) SetConnection(val *EmbeddingConnection) {
	p.Connection = val
}

func (p *EmbeddingConfig) IsSetConnection() bool {
	return p.Connection != nil
}

func (p *EmbeddingConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmbeddingConfig(%+v)", *p)
}

type EmbeddingConnection struct {
	BaseConnInfo  *BaseConnectionInfo `thrift:"base_conn_info,1" json:"base_conn_info"`
	EmbeddingInfo *EmbeddingInfo      `thrift:"embedding_info,2" json:"embedding_info"`
	Openai        *OpenAIConnInfo     `thrift:"openai,3,optional" json:"openai,omitempty"`
	Ollama        *OllamaConnInfo     `thrift:"ollama,4,optional" json:"ollama,omitempty"`
	Gemini        *GeminiConnInfo     `thrift:"gemini,5,optional" json:"gemini,omitempty"`
	HTTP          *HttpConnection     `thrift:"http,6,optional" json:"http,omitempty"`
}

func NewEmbeddingConnection() *EmbeddingConnection {
	return &EmbeddingConnection{}
}

func (p *EmbeddingConnection) InitDefault() {
}

var EmbeddingConnection_BaseConnInfo_DEFAULT *BaseConnectionInfo

func (p *EmbeddingConnection) GetBaseConnInfo() (v *BaseConnectionInfo) {
	if !p.IsSetBaseConnInfo() {
		return EmbeddingConnection_BaseConnInfo_DEFAULT
	}
	return p.BaseConnInfo
}

var EmbeddingConnection_EmbeddingInfo_DEFAULT *EmbeddingInfo

func (p *EmbeddingConnection) GetEmbeddingInfo() (v *EmbeddingInfo) {
	if !p.IsSetEmbeddingInfo() {
		return EmbeddingConnection_EmbeddingInfo_DEFAULT
	}
	return p.EmbeddingInfo
}

var EmbeddingConnection_Openai_DEFAULT *OpenAIConnInfo

func (p *EmbeddingConnection) GetOpenai() (v *OpenAIConnInfo) {
	if !p.IsSetOpenai() {
		return EmbeddingConnection_Openai_DEFAULT
	}
	return p.Openai
}

var EmbeddingConnection_Ollama_DEFAULT *OllamaConnInfo

func (p *EmbeddingConnection) GetOllama() (v *OllamaConnInfo) {
	if !p.IsSetOllama() {
		return EmbeddingConnection_Ollama_DEFAULT
	}
	return p.Ollama
}

var EmbeddingConnection_Gemini_DEFAULT *GeminiConnInfo

func (p *EmbeddingConnection) GetGemini() (v *GeminiConnInfo) {
	if !p.IsSetGemini() {
		return EmbeddingConnection_Gemini_DEFAULT
	}
	return p.Gemini
}

var EmbeddingConnection_HTTP_DEFAULT *HttpConnection

func (p *EmbeddingConnection) GetHTTP() (v *HttpConnection) {
	if !p.IsSetHTTP() {
		return EmbeddingConnection_HTTP_DEFAULT
	}
	return p.HTTP
}
func (p *EmbeddingConnection) SetBaseConnInfo(val *BaseConnectionInfo) {
	p.BaseConnInfo = val
}
func (p *EmbeddingConnection) SetEmbeddingInfo(val *EmbeddingInfo) {
	p.EmbeddingInfo = val
}
func (p *EmbeddingConnection) SetOpenai(val *OpenAIConnInfo) {
	p.Openai = val
}
func (p *EmbeddingConnection) SetOllama(val *OllamaConnInfo) {
	p.Ollama = val
}
func (p *EmbeddingConnection) SetGemini(val *GeminiConnInfo) {
	p.Gemini = val
}
func (p *EmbeddingConnection) SetHTTP(val *HttpConnection) {
	p.HTTP = val
}

func (p *EmbeddingConnection) IsSetBaseConnInfo() bool {
	return p.BaseConnInfo != nil
}

func (p *EmbeddingConnection) IsSetEmbeddingInfo() bool {
	return p.EmbeddingInfo != nil
}

func (p *EmbeddingConnection) IsSetOpenai() bool {
	return p.Openai != nil
}

func (p *EmbeddingConnection) IsSetOllama() bool {
	return p.Ollama != nil
}

func (p *EmbeddingConnection) IsSetGemini() bool {
	return p.Gemini != nil
}

func (p *EmbeddingConnection) IsSetHTTP() bool {
	return p.HTTP != nil
}

func (p *EmbeddingConnection) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmbeddingConnection(%+v)", *p)
}

type HttpConnection struct {
	Address string `thrift:"address,1" json:"address"`
}

func NewHttpConnection() *HttpConnection {
	return &HttpConnection{}
}

func (p *HttpConnection) InitDefault() {
}

func (p *HttpConnection) GetAddress() (v string) {
	return p.Address
}
func (p *HttpConnection) SetAddress(val string) {
	p.Address = val
}

func (p *HttpConnection) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HttpConnection(%+v)", *p)
}

type RerankConfig struct {
	Type           RerankType      `thrift:"type,1,default,RerankType" json:"type"`
	VikingdbConfig *VikingDBConfig `thrift:"vikingdb_config,2" json:"vikingdb_config"`
}

func NewRerankConfig() *RerankConfig {
	return &RerankConfig{}
}

func (p *RerankConfig) InitDefault() {
}

func (p *RerankConfig) GetType() (v RerankType) {
	return p.Type
}

var RerankConfig_VikingdbConfig_DEFAULT *VikingDBConfig

func (p *RerankConfig) GetVikingdbConfig() (v *VikingDBConfig) {
	if !p.IsSetVikingdbConfig() {
		return RerankConfig_VikingdbConfig_DEFAULT
	}
	return p.VikingdbConfig
}
func (p *RerankConfig) SetType(val RerankType) {
	p.Type = val
}
func (p *RerankConfig) SetVikingdbConfig(val *VikingDBConfig) {
	p.VikingdbConfig = val
}

func (p *RerankConfig) IsSetVikingdbConfig() bool {
	return p.VikingdbConfig != nil
}

func (p *RerankConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RerankConfig(%+v)", *p)
}

type VikingDBConfig struct {
	Ak     string `thrift:"ak,1" json:"ak"`
	Sk     string `thrift:"sk,2" json:"sk"`
	Host   string `thrift:"host,3" json:"host"`
	Region string `thrift:"region,4" json:"region"`
	Model  string `thrift:"model,5" json:"model"`
}

func NewVikingDBConfig() *VikingDBConfig {
	return &VikingDBConfig{}
}

func (p *VikingDBConfig) InitDefault() {
}

func (p *VikingDBConfig) GetAk() (v string) {
	return p.Ak
}

func (p *VikingDBConfig) GetSk() (v string) {
	return p.Sk
}

func (p *VikingDBConfig) GetHost() (v string) {
	return p.Host
}

func (p *VikingDBConfig) GetRegion() (v string) {
	return p.Region
}

func (p *VikingDBConfig) GetModel() (v string) {
	return p.Model
}
func (p *VikingDBConfig) SetAk(val string) {
	p.Ak = val
}
func (p *VikingDBConfig) SetSk(val string) {
	p.Sk = val
}
func (p *VikingDBConfig) SetHost(val string) {
	p.Host = val
}
func (p *VikingDBConfig) SetRegion(val string) {
	p.Region = val
}
func (p *VikingDBConfig) SetModel(val string) {
	p.Model = val
}

func (p *VikingDBConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VikingDBConfig(%+v)", *p)
}

type OCRConfig struct {
	Type            OCRType `thrift:"type,1,default,OCRType" json:"type"`
	VolcengineAk    string  `thrift:"volcengine_ak,2" json:"volcengine_ak"`
	VolcengineSk    string  `thrift:"volcengine_sk,3" json:"volcengine_sk"`
	PaddleocrAPIURL string  `thrift:"paddleocr_api_url,4" json:"paddleocr_api_url"`
}

func NewOCRConfig() *OCRConfig {
	return &OCRConfig{}
}

func (p *OCRConfig) InitDefault() {
}

func (p *OCRConfig) GetType() (v OCRType) {
	return p.Type
}

func (p *OCRConfig) GetVolcengineAk() (v string) {
	return p.VolcengineAk
}

func (p *OCRConfig) GetVolcengineSk() (v string) {
	return p.VolcengineSk
}

func (p *OCRConfig) GetPaddleocrAPIURL() (v string) {
	return p.PaddleocrAPIURL
}
func (p *OCRConfig) SetType(val OCRType) {
	p.Type = val
}
func (p *OCRConfig) SetVolcengineAk(val string) {
	p.VolcengineAk = val
}
func (p *OCRConfig) SetVolcengineSk(val string) {
	p.VolcengineSk = val
}
func (p *OCRConfig) SetPaddleocrAPIURL(val string) {
	p.PaddleocrAPIURL = val
}

func (p *OCRConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OCRConfig(%+v)", *p)
}

type ParserConfig struct {
	Type                     ParserType `thrift:"type,1,default,ParserType" json:"type"`
	PaddleocrStructureAPIURL string     `thrift:"paddleocr_structure_api_url,2" json:"paddleocr_structure_api_url"`
}

func NewParserConfig() *ParserConfig {
	return &ParserConfig{}
}

func (p *ParserConfig) InitDefault() {
}

func (p *ParserConfig) GetType() (v ParserType) {
	return p.Type
}

func (p *ParserConfig) GetPaddleocrStructureAPIURL() (v string) {
	return p.PaddleocrStructureAPIURL
}
func (p *ParserConfig) SetType(val ParserType) {
	p.Type = val
}
func (p *ParserConfig) SetPaddleocrStructureAPIURL(val string) {
	p.PaddleocrStructureAPIURL = val
}

func (p *ParserConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ParserConfig(%+v)", *p)
}

type ModelConfigService interface {
	GetBasicConfiguration(ctx context.Context, req *GetBasicConfigurationReq) (r *GetBasicConfigurationResp, err error)

	SaveBasicConfiguration(ctx context.Context, req *SaveBasicConfigurationReq) (r *SaveBasicConfigurationResp, err error)

	GetKnowledgeConfig(ctx context.Context, req *GetKnowledgeConfigReq) (r *GetKnowledgeConfigResp, err error)

	UpdateKnowledgeConfig(ctx context.Context, req *UpdateKnowledgeConfigReq) (r *UpdateKnowledgeConfigResp, err error)

	CreateModel(ctx context.Context, req *CreateModelReq) (r *CreateModelResp, err error)

	DeleteModel(ctx context.Context, req *DeleteModelReq) (r *DeleteModelResp, err error)
}
