// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameFile = "files"

// File file resource table
type File struct {
	ID          int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:id" json:"id"`                                                // id
	Name        string         `gorm:"column:name;type:varchar(255);not null;comment:file name" json:"name"`                                              // file name
	FileSize    int64          `gorm:"column:file_size;type:bigint(20) unsigned;not null;comment:file size" json:"file_size"`                             // file size
	TosURI      string         `gorm:"column:tos_uri;type:varchar(1024);not null;comment:TOS URI" json:"tos_uri"`                                         // TOS URI
	Status      int32          `gorm:"column:status;type:tinyint(4) unsigned;not null;comment:status，0invalid，1valid" json:"status"`                      // status，0invalid，1valid
	Comment     string         `gorm:"column:comment;type:varchar(1024);not null;comment:file comment" json:"comment"`                                    // file comment
	Source      int32          `gorm:"column:source;type:tinyint(4) unsigned;not null;comment:source：1 from API," json:"source"`                          // source：1 from API,
	CreatorID   string         `gorm:"column:creator_id;type:varchar(512);not null;index:idx_creator_id,priority:1;comment:creator id" json:"creator_id"` // creator id
	ContentType string         `gorm:"column:content_type;type:varchar(255);not null;comment:content type" json:"content_type"`                           // content type
	CreatedAt   int64          `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:Create Time in Milliseconds" json:"created_at"`         // Create Time in Milliseconds
	UpdatedAt   int64          `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:Update Time in Milliseconds" json:"updated_at"`         // Update Time in Milliseconds
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:Delete Time" json:"deleted_at"`                                          // Delete Time
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
