// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kiosk404/airi-go/backend/modules/component/plugin/infra/repo/gorm_gen/model"
)

const TableNameAgentToolVersion = "agent_tool_version"

// AgentToolVersion Agent Tool Version
type AgentToolVersion struct {
	ID           int64                    `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:Primary Key ID" json:"id"`                                                                                                                                                                                                                             // Primary Key ID
	AgentID      int64                    `gorm:"column:agent_id;type:bigint(20) unsigned;not null;uniqueIndex:uniq_idx_agent_tool_id_agent_version,priority:1;uniqueIndex:uniq_idx_agent_tool_name_agent_version,priority:1;index:idx_agent_tool_id_created_at,priority:1;index:idx_agent_tool_name_created_at,priority:1;comment:Agent ID" json:"agent_id"` // Agent ID
	PluginID     int64                    `gorm:"column:plugin_id;type:bigint(20) unsigned;not null;comment:Plugin ID" json:"plugin_id"`                                                                                                                                                                                                                      // Plugin ID
	ToolID       int64                    `gorm:"column:tool_id;type:bigint(20) unsigned;not null;uniqueIndex:uniq_idx_agent_tool_id_agent_version,priority:2;index:idx_agent_tool_id_created_at,priority:2;comment:Tool ID" json:"tool_id"`                                                                                                                  // Tool ID
	AgentVersion string                   `gorm:"column:agent_version;type:varchar(255);not null;uniqueIndex:uniq_idx_agent_tool_id_agent_version,priority:3;uniqueIndex:uniq_idx_agent_tool_name_agent_version,priority:3;comment:Agent Tool Version" json:"agent_version"`                                                                                  // Agent Tool Version
	ToolName     string                   `gorm:"column:tool_name;type:varchar(255);not null;uniqueIndex:uniq_idx_agent_tool_name_agent_version,priority:2;index:idx_agent_tool_name_created_at,priority:2;comment:Tool Name" json:"tool_name"`                                                                                                               // Tool Name
	ToolVersion  string                   `gorm:"column:tool_version;type:varchar(255);not null;comment:Tool Version, e.g. v1.0.0" json:"tool_version"`                                                                                                                                                                                                       // Tool Version, e.g. v1.0.0
	SubURL       string                   `gorm:"column:sub_url;type:varchar(512);not null;comment:Sub URL Path" json:"sub_url"`                                                                                                                                                                                                                              // Sub URL Path
	Method       string                   `gorm:"column:method;type:varchar(64);not null;comment:HTTP Request Method" json:"method"`                                                                                                                                                                                                                          // HTTP Request Method
	Operation    *model.Openapi3Operation `gorm:"column:operation;type:json;comment:Tool Openapi Operation Schema;serializer:json" json:"operation"`                                                                                                                                                                                                          // Tool Openapi Operation Schema
	CreatedAt    int64                    `gorm:"column:created_at;type:bigint(20) unsigned;not null;index:idx_agent_tool_id_created_at,priority:3;index:idx_agent_tool_name_created_at,priority:3;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"`                                                                               // Create Time in Milliseconds
}

// TableName AgentToolVersion's table name
func (*AgentToolVersion) TableName() string {
	return TableNameAgentToolVersion
}
