// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/kiosk404/airi-go/backend/modules/component/crossdomain/plugin/model"

const TableNameTool = "tool"

// Tool Latest Tool
type Tool struct {
	ID              int64                    `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:Tool ID" json:"id"`                                                                                                                  // Tool ID
	PluginID        int64                    `gorm:"column:plugin_id;type:bigint(20) unsigned;not null;uniqueIndex:uniq_idx_plugin_sub_url_method,priority:1;index:idx_plugin_activated_status,priority:1;comment:Plugin ID" json:"plugin_id"` // Plugin ID
	CreatedAt       int64                    `gorm:"column:created_at;type:bigint(20) unsigned;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"`                                                           // Create Time in Milliseconds
	UpdatedAt       int64                    `gorm:"column:updated_at;type:bigint(20) unsigned;not null;autoUpdateTime:milli;comment:Update Time in Milliseconds" json:"updated_at"`                                                           // Update Time in Milliseconds
	Version         string                   `gorm:"column:version;type:varchar(255);not null;comment:Tool Version, e.g. v1.0.0" json:"version"`                                                                                               // Tool Version, e.g. v1.0.0
	SubURL          string                   `gorm:"column:sub_url;type:varchar(512);not null;uniqueIndex:uniq_idx_plugin_sub_url_method,priority:2;comment:Sub URL Path" json:"sub_url"`                                                      // Sub URL Path
	Method          string                   `gorm:"column:method;type:varchar(64);not null;uniqueIndex:uniq_idx_plugin_sub_url_method,priority:3;comment:HTTP Request Method" json:"method"`                                                  // HTTP Request Method
	Operation       *model.Openapi3Operation `gorm:"column:operation;type:json;comment:Tool Openapi Operation Schema;serializer:json" json:"operation"`                                                                                        // Tool Openapi Operation Schema
	ActivatedStatus int32                    `gorm:"column:activated_status;type:tinyint(4) unsigned;not null;index:idx_plugin_activated_status,priority:2;comment:0:activated; 1:deactivated" json:"activated_status"`                        // 0:activated; 1:deactivated
}

// TableName Tool's table name
func (*Tool) TableName() string {
	return TableNameTool
}
